### ISSUE TITLE
compiler.{JSExportsTest, JSDynamicLiteralTest} crash DirectTest in 2.11.5

### ISSUE THREAD

**Issue by sjrd** [scala-js/scala-js#1443]

**Comment by sjrd** [comment]
Since testing "manually" on the side, without `DirectTest` in the way, worked, I'll differ the fix to this one to a later release.

**Comment by gzm0** [comment]
Testing has shown that this is "caused" by reusing the same compiler multiple times in `DirectTest`. A typical stacktrace looks like this (always ends in `compileLate`):

```
[error] Test org.scalajs.core.compiler.test.JSDynamicLiteralTest.noNonLiteralMethodName failed: null
[error]     at scala.tools.nsc.Global$Run.compileLate(Global.scala:1595)
[error]     at scala.tools.nsc.GlobalSymbolLoaders.compileLate(GlobalSymbolLoaders.scala:29)
[error]     at scala.tools.nsc.symtab.SymbolLoaders$SourcefileLoader.doComplete(SymbolLoaders.scala:369)
[error]     at scala.tools.nsc.symtab.SymbolLoaders$SymbolLoader.complete(SymbolLoaders.scala:212)
[error]     at scala.reflect.internal.Symbols$Symbol.info(Symbols.scala:1488)
[error]     at scala.tools.nsc.transform.SpecializeTypes.scala$tools$nsc$transform$SpecializeTypes$$specializedClass$1(SpecializeTypes.scala:538)
[error]     at scala.tools.nsc.transform.SpecializeTypes.specializeClass(SpecializeTypes.scala:787)
[error]     at scala.tools.nsc.transform.SpecializeTypes.transformInfo(SpecializeTypes.scala:1181)
[error]     at scala.tools.nsc.transform.InfoTransform$Phase$$anon$1.transform(InfoTransform.scala:38)
[error]     at scala.reflect.internal.Symbols$Symbol.rawInfo(Symbols.scala:1578)
[error]     at scala.reflect.internal.Symbols$Symbol.info(Symbols.scala:1498)
[error]     at scala.reflect.internal.Types$TypeRef.baseTypeSeqImpl(Types.scala:2227)
[error]     at scala.reflect.internal.Types$class.defineBaseTypeSeqOfTypeRef(Types.scala:2372)
[error]     at scala.reflect.internal.SymbolTable.defineBaseTypeSeqOfTypeRef(SymbolTable.scala:16)
[error]     at scala.reflect.internal.Types$TypeRef.baseTypeSeq(Types.scala:2240)
[error]     at scala.reflect.internal.BaseTypeSeqs$class.compoundBaseTypeSeq(BaseTypeSeqs.scala:168)
[error]     at scala.reflect.internal.SymbolTable.compoundBaseTypeSeq(SymbolTable.scala:16)
[error]     at scala.reflect.internal.Types$class.defineBaseTypeSeqOfCompoundType(Types.scala:1488)
[error]     at scala.reflect.internal.SymbolTable.defineBaseTypeSeqOfCompoundType(SymbolTable.scala:16)
[error]     at scala.reflect.internal.Types$CompoundType.baseTypeSeq(Types.scala:1356)
[error]     at scala.reflect.internal.Types$TypeRef.baseTypeSeqImpl(Types.scala:2227)
[error]     at scala.reflect.internal.Types$class.defineBaseTypeSeqOfTypeRef(Types.scala:2372)
[error]     at scala.reflect.internal.SymbolTable.defineBaseTypeSeqOfTypeRef(SymbolTable.scala:16)
[error]     at scala.reflect.internal.Types$TypeRef.baseTypeSeq(Types.scala:2240)
[error]     at scala.reflect.internal.BaseTypeSeqs$class.compoundBaseTypeSeq(BaseTypeSeqs.scala:168)
[error]     at scala.reflect.internal.SymbolTable.compoundBaseTypeSeq(SymbolTable.scala:16)
[error]     at scala.reflect.internal.Types$class.defineBaseTypeSeqOfCompoundType(Types.scala:1488)
[error]     at scala.reflect.internal.SymbolTable.defineBaseTypeSeqOfCompoundType(SymbolTable.scala:16)
[error]     at scala.reflect.internal.Types$CompoundType.baseTypeSeq(Types.scala:1356)
[error]     at scala.reflect.internal.Types$Type.baseTypeIndex(Types.scala:891)
[error]     at scala.reflect.internal.Types$CompoundType.baseType(Types.scala:1401)
[error]     at scala.reflect.internal.Types$ClassTypeRef$class.baseType(Types.scala:1968)
[error]     at scala.reflect.internal.Types$ClassNoArgsTypeRef.baseType(Types.scala:2331)
[error]     at scala.reflect.internal.Types$class.elementExtract(Types.scala:3689)
[error]     at scala.reflect.internal.SymbolTable.elementExtract(SymbolTable.scala:16)
[error]     at scala.reflect.internal.Definitions$DefinitionsClass.dropByName(Definitions.scala:407)
[error]     at scala.tools.nsc.typechecker.Infer$$anonfun$3.apply(Infer.scala:39)
[error]     at scala.tools.nsc.typechecker.Infer$$anonfun$3.apply(Infer.scala:39)
[error]     at scala.collection.immutable.List.loop$1(List.scala:173)
[error]     at scala.collection.immutable.List.mapConserve(List.scala:189)
[error]     at scala.tools.nsc.typechecker.Infer$class.formalTypes(Infer.scala:39)
[error]     at scala.tools.nsc.transform.Erasure.formalTypes(Erasure.scala:15)
[error]     at scala.tools.nsc.typechecker.Typers$Typer.doTypedApply(Typers.scala:3322)
[error]     at scala.tools.nsc.typechecker.Typers$Typer.normalTypedApply$1(Typers.scala:4544)
[error]     at scala.tools.nsc.typechecker.Typers$Typer.typedApply$1(Typers.scala:4578)
[error]     at scala.tools.nsc.typechecker.Typers$Typer.typedInAnyMode$1(Typers.scala:5343)
[error]     at scala.tools.nsc.typechecker.Typers$Typer.typed1(Typers.scala:5360)
[error]     at scala.tools.nsc.transform.Erasure$Eraser.typed1(Erasure.scala:696)
[error]     at scala.tools.nsc.typechecker.Typers$Typer.runTyper$1(Typers.scala:5396)
[error]     at scala.tools.nsc.typechecker.Typers$Typer.scala$tools$nsc$typechecker$Typers$Typer$$typedInternal(Typers.scala:5423)
[error]     at scala.tools.nsc.typechecker.Typers$Typer.body$2(Typers.scala:5370)
[error]     at scala.tools.nsc.typechecker.Typers$Typer.typed(Typers.scala:5374)
[error]     at scala.tools.nsc.typechecker.Typers$Typer.transformedOrTyped(Typers.scala:5605)
[error]     at scala.tools.nsc.typechecker.Typers$Typer.typedDefDef(Typers.scala:2208)
[error]     at scala.tools.nsc.typechecker.Typers$Typer.typedMemberDef$1(Typers.scala:5308)
[error]     at scala.tools.nsc.typechecker.Typers$Typer.typed1(Typers.scala:5359)
[error]     at scala.tools.nsc.transform.Erasure$Eraser.typed1(Erasure.scala:696)
[error]     at scala.tools.nsc.typechecker.Typers$Typer.runTyper$1(Typers.scala:5396)
[error]     at scala.tools.nsc.typechecker.Typers$Typer.scala$tools$nsc$typechecker$Typers$Typer$$typedInternal(Typers.scala:5423)
[error]     at scala.tools.nsc.typechecker.Typers$Typer.body$2(Typers.scala:5370)
[error]     at scala.tools.nsc.typechecker.Typers$Typer.typed(Typers.scala:5374)
[error]     at scala.tools.nsc.typechecker.Typers$Typer.typedByValueExpr(Typers.scala:5452)
[error]     at scala.tools.nsc.typechecker.Typers$Typer.scala$tools$nsc$typechecker$Typers$Typer$$typedStat$1(Typers.scala:3046)
[error]     at scala.tools.nsc.typechecker.Typers$Typer$$anonfun$62.apply(Typers.scala:3150)
[error]     at scala.tools.nsc.typechecker.Typers$Typer$$anonfun$62.apply(Typers.scala:3150)
[error]     at scala.collection.immutable.List.loop$1(List.scala:173)
[error]     at scala.collection.immutable.List.mapConserve(List.scala:189)
[error]     at scala.tools.nsc.typechecker.Typers$Typer.typedStats(Typers.scala:3150)
[error]     at scala.tools.nsc.typechecker.Typers$Typer.typedTemplate(Typers.scala:1921)
[error]     at scala.tools.nsc.typechecker.Typers$Typer.typedClassDef(Typers.scala:1762)
[error]     at scala.tools.nsc.typechecker.Typers$Typer.typedMemberDef$1(Typers.scala:5309)
[error]     at scala.tools.nsc.typechecker.Typers$Typer.typed1(Typers.scala:5359)
[error]     at scala.tools.nsc.transform.Erasure$Eraser.typed1(Erasure.scala:696)
[error]     at scala.tools.nsc.typechecker.Typers$Typer.runTyper$1(Typers.scala:5396)
[error]     at scala.tools.nsc.typechecker.Typers$Typer.scala$tools$nsc$typechecker$Typers$Typer$$typedInternal(Typers.scala:5423)
[error]     at scala.tools.nsc.typechecker.Typers$Typer.body$2(Typers.scala:5370)
[error]     at scala.tools.nsc.typechecker.Typers$Typer.typed(Typers.scala:5374)
[error]     at scala.tools.nsc.typechecker.Typers$Typer.typedByValueExpr(Typers.scala:5452)
[error]     at scala.tools.nsc.typechecker.Typers$Typer.scala$tools$nsc$typechecker$Typers$Typer$$typedStat$1(Typers.scala:3046)
[error]     at scala.tools.nsc.typechecker.Typers$Typer$$anonfun$62.apply(Typers.scala:3150)
[error]     at scala.tools.nsc.typechecker.Typers$Typer$$anonfun$62.apply(Typers.scala:3150)
[error]     at scala.collection.immutable.List.loop$1(List.scala:173)
[error]     at scala.collection.immutable.List.mapConserve(List.scala:189)
[error]     at scala.tools.nsc.typechecker.Typers$Typer.typedStats(Typers.scala:3150)
[error]     at scala.tools.nsc.typechecker.Typers$Typer.typedPackageDef$1(Typers.scala:5012)
[error]     at scala.tools.nsc.typechecker.Typers$Typer.typedMemberDef$1(Typers.scala:5312)
[error]     at scala.tools.nsc.typechecker.Typers$Typer.typed1(Typers.scala:5359)
[error]     at scala.tools.nsc.transform.Erasure$Eraser.typed1(Erasure.scala:696)
[error]     at scala.tools.nsc.typechecker.Typers$Typer.runTyper$1(Typers.scala:5396)
[error]     at scala.tools.nsc.typechecker.Typers$Typer.scala$tools$nsc$typechecker$Typers$Typer$$typedInternal(Typers.scala:5423)
[error]     at scala.tools.nsc.typechecker.Typers$Typer.body$2(Typers.scala:5370)
[error]     at scala.tools.nsc.typechecker.Typers$Typer.typed(Typers.scala:5374)
[error]     at scala.tools.nsc.typechecker.Typers$Typer.typed(Typers.scala:5448)
[error]     at scala.tools.nsc.transform.Erasure$ErasureTransformer$$anonfun$transform$2.apply(Erasure.scala:1166)
[error]     at scala.tools.nsc.transform.Erasure$ErasureTransformer$$anonfun$transform$2.apply(Erasure.scala:1162)
[error]     at scala.reflect.internal.SymbolTable.enteringPhase(SymbolTable.scala:235)
[error]     at scala.reflect.internal.SymbolTable.exitingPhase(SymbolTable.scala:256)
[error]     at scala.tools.nsc.transform.Erasure$ErasureTransformer.transform(Erasure.scala:1162)
[error]     at scala.tools.nsc.transform.Erasure$ErasureTransformer.transform(Erasure.scala:743)
[error]     at scala.tools.nsc.ast.Trees$Transformer.transformUnit(Trees.scala:147)
[error]     at scala.tools.nsc.transform.Transform$Phase.apply(Transform.scala:30)
[error]     at scala.tools.nsc.Global$GlobalPhase$$anonfun$applyPhase$1.apply$mcV$sp(Global.scala:441)
[error]     at scala.tools.nsc.Global$GlobalPhase.withCurrentUnit(Global.scala:432)
[error]     at scala.tools.nsc.Global$GlobalPhase.applyPhase(Global.scala:441)
[error]     at scala.tools.nsc.Global$GlobalPhase$$anonfun$run$1.apply(Global.scala:399)
[error]     at scala.tools.nsc.Global$GlobalPhase$$anonfun$run$1.apply(Global.scala:399)
[error]     at scala.collection.Iterator$class.foreach(Iterator.scala:750)
[error]     at scala.collection.AbstractIterator.foreach(Iterator.scala:1202)
[error]     at scala.tools.nsc.Global$GlobalPhase.run(Global.scala:399)
[error]     at scala.tools.nsc.Global$Run.compileUnitsInternal(Global.scala:1500)
[error]     at scala.tools.nsc.Global$Run.compileUnits(Global.scala:1487)
[error]     at scala.tools.nsc.Global$Run.compileSources(Global.scala:1482)
[error]     at org.scalajs.core.compiler.test.util.DirectTest$$anonfun$compileSources$1.apply(DirectTest.scala:54)
[error]     at org.scalajs.core.compiler.test.util.DirectTest$$anonfun$compileSources$1.apply(DirectTest.scala:54)
[error]     at org.scalajs.core.compiler.test.util.DirectTest.withRun(DirectTest.scala:50)
[error]     at org.scalajs.core.compiler.test.util.DirectTest.compileSources(DirectTest.scala:54)
[error]     at org.scalajs.core.compiler.test.util.DirectTest.compileString(DirectTest.scala:59)
[error]     at org.scalajs.core.compiler.test.util.DirectTest.compileString(DirectTest.scala:62)
[error]     at org.scalajs.core.compiler.test.util.TestHelpers$CompileTests$$anonfun$1.apply$mcV$sp(TestHelpers.scala:30)
[error]     at org.scalajs.core.compiler.test.util.TestHelpers$CompileTests.repResult(TestHelpers.scala:59)
[error]     at org.scalajs.core.compiler.test.util.TestHelpers$CompileTests.hasErrors(TestHelpers.scala:29)
[error]     at org.scalajs.core.compiler.test.JSDynamicLiteralTest.noNonLiteralMethodName(JSDynamicLiteralTest.scala:93)
```

**Comment by gzm0** [comment]
@adriaanm have there been any changes in 2.11.5 that could cause this?

**Comment by sjrd** [comment]
@gzm0 Do we still want to investigate this? i.e., return to the old style that reused the `Global` instance? IMO if it's stable like it is now, we can keep it that way forever.

**Comment by gzm0** [comment]
Yeah, let's close it. People don't seem to encounter issues with how the compiler is reused in sbt, so we shouldn't bother.
