### ISSUE TITLE
ScalaDoc run crashes with property @JSExports

### ISSUE THREAD

**Issue by jokade** [scala-js/scala-js#1451]
Why does the following snippet compile, but results in an assertion error during publishing:
```scala
trait Foo {
  @JSExport
  var bar: js.Any = null
}
```
I've checked it with `0.6.0-RC1`, `0.5.6` and `0.5.2` - same result. Here's the stack trace (for `0.6.0-RC1`:

        java.lang.AssertionError: assertion failed: <no phase>
	at scala.reflect.internal.SymbolTable.phase_$eq(SymbolTable.scala:192)
	at scala.reflect.internal.SymbolTable.pushPhase(SymbolTable.scala:198)
	at scala.reflect.internal.SymbolTable.enteringPhase(SymbolTable.scala:234)
	at org.scalajs.core.compiler.Compat210Component$class.enteringPhase(Compat210Component.scala:33)
	at org.scalajs.core.compiler.ScalaJSPlugin$jsAddons$.enteringPhase(ScalaJSPlugin.scala:38)
	at org.scalajs.core.compiler.JSGlobalAddons$jsInterop$.isJSSetter(JSGlobalAddons.scala:230)
	at org.scalajs.core.compiler.JSGlobalAddons$jsInterop$$anonfun$directExportsOf$1.apply(JSGlobalAddons.scala:109)
	at org.scalajs.core.compiler.JSGlobalAddons$jsInterop$$anonfun$directExportsOf$1.apply(JSGlobalAddons.scala:90)
	at scala.collection.immutable.List.map(List.scala:272)
	at org.scalajs.core.compiler.JSGlobalAddons$jsInterop$.directExportsOf(JSGlobalAddons.scala:90)
	at org.scalajs.core.compiler.JSGlobalAddons$jsInterop$.exportsOf(JSGlobalAddons.scala:48)
	at org.scalajs.core.compiler.PrepJSExports$class.genExportMember(PrepJSExports.scala:34)
	at org.scalajs.core.compiler.PrepJSInterop.genExportMember(PrepJSInterop.scala:26)
	at org.scalajs.core.compiler.PrepJSInterop$JSInteropTransformer.transform(PrepJSInterop.scala:202)
	at org.scalajs.core.compiler.PrepJSInterop$JSInteropTransformer.transform(PrepJSInterop.scala:70)
	at scala.reflect.api.Trees$Transformer$$anonfun$transformStats$1.apply(Trees.scala:2589)
	at scala.reflect.api.Trees$Transformer$$anonfun$transformStats$1.apply(Trees.scala:2587)
	at scala.collection.immutable.List.loop$1(List.scala:172)
	at scala.collection.immutable.List.mapConserve(List.scala:188)
	at scala.reflect.api.Trees$Transformer.transformStats(Trees.scala:2587)
	at scala.reflect.internal.Trees$class.itransform(Trees.scala:1397)
	at scala.reflect.internal.SymbolTable.itransform(SymbolTable.scala:16)
	at scala.reflect.internal.SymbolTable.itransform(SymbolTable.scala:16)
	at scala.reflect.api.Trees$Transformer.transform(Trees.scala:2555)
	at org.scalajs.core.compiler.PrepJSInterop$JSInteropTransformer.transform(PrepJSInterop.scala:248)
	at org.scalajs.core.compiler.PrepJSInterop$JSInteropTransformer.transform(PrepJSInterop.scala:70)
	at scala.reflect.api.Trees$Transformer.transformTemplate(Trees.scala:2563)
	at scala.reflect.internal.Trees$$anonfun$itransform$4.apply(Trees.scala:1401)
	at scala.reflect.internal.Trees$$anonfun$itransform$4.apply(Trees.scala:1400)
	at scala.reflect.api.Trees$Transformer.atOwner(Trees.scala:2600)
	at scala.reflect.internal.Trees$class.itransform(Trees.scala:1399)
	at scala.reflect.internal.SymbolTable.itransform(SymbolTable.scala:16)
	at scala.reflect.internal.SymbolTable.itransform(SymbolTable.scala:16)
	at scala.reflect.api.Trees$Transformer.transform(Trees.scala:2555)
	at org.scalajs.core.compiler.PrepJSInterop$JSInteropTransformer.org$scalajs$core$compiler$PrepJSInterop$JSInteropTransformer$$super$transform(PrepJSInterop.scala:111)
	at org.scalajs.core.compiler.PrepJSInterop$JSInteropTransformer$$anonfun$transform$4.apply(PrepJSInterop.scala:125)
	at org.scalajs.core.compiler.PrepJSInterop$JSInteropTransformer$$anonfun$transform$4.apply(PrepJSInterop.scala:125)
	at org.scalajs.core.compiler.PrepJSInterop$JSInteropTransformer.enterScalaCls(PrepJSInterop.scala:464)
	at org.scalajs.core.compiler.PrepJSInterop$JSInteropTransformer.transform(PrepJSInterop.scala:125)
	at org.scalajs.core.compiler.PrepJSInterop$JSInteropTransformer.transform(PrepJSInterop.scala:70)
	at scala.reflect.api.Trees$Transformer$$anonfun$transformStats$1.apply(Trees.scala:2589)
	at scala.reflect.api.Trees$Transformer$$anonfun$transformStats$1.apply(Trees.scala:2587)
	at scala.collection.immutable.List.loop$1(List.scala:172)
	at scala.collection.immutable.List.mapConserve(List.scala:188)
	at scala.reflect.api.Trees$Transformer.transformStats(Trees.scala:2587)
	at scala.reflect.internal.Trees$$anonfun$itransform$7.apply(Trees.scala:1419)
	at scala.reflect.internal.Trees$$anonfun$itransform$7.apply(Trees.scala:1419)
	at scala.reflect.api.Trees$Transformer.atOwner(Trees.scala:2600)
	at scala.reflect.internal.Trees$class.itransform(Trees.scala:1418)
	at scala.reflect.internal.SymbolTable.itransform(SymbolTable.scala:16)
	at scala.reflect.internal.SymbolTable.itransform(SymbolTable.scala:16)
	at scala.reflect.api.Trees$Transformer.transform(Trees.scala:2555)
	at org.scalajs.core.compiler.PrepJSInterop$JSInteropTransformer.transform(PrepJSInterop.scala:248)
	at org.scalajs.core.compiler.PrepJSInterop$JSInteropTransformer.transform(PrepJSInterop.scala:70)
	at scala.tools.nsc.ast.Trees$Transformer.transformUnit(Trees.scala:147)
	at scala.tools.nsc.transform.Transform$Phase.apply(Transform.scala:30)
	at scala.tools.nsc.Global$GlobalPhase.applyPhase(Global.scala:410)
	at scala.tools.nsc.Global$GlobalPhase$$anonfun$run$1.apply(Global.scala:377)
	at scala.tools.nsc.Global$GlobalPhase$$anonfun$run$1.apply(Global.scala:377)
	at scala.collection.Iterator$class.foreach(Iterator.scala:743)
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1177)
	at scala.tools.nsc.Global$GlobalPhase.run(Global.scala:377)
	at org.scalajs.core.compiler.PrepJSInterop$JSInteropPhase.run(PrepJSInterop.scala:50)
	at scala.tools.nsc.Global$Run.compileUnitsInternal(Global.scala:1557)
	at scala.tools.nsc.Global$Run.compileUnits(Global.scala:1542)
	at scala.tools.nsc.Global$Run.compileSources(Global.scala:1537)
	at scala.tools.nsc.Global$Run.compile(Global.scala:1644)
	at scala.tools.nsc.doc.DocFactory.makeUniverse(DocFactory.scala:44)
	at scala.tools.nsc.doc.DocFactory.generate$1(DocFactory.scala:112)
	at scala.tools.nsc.doc.DocFactory.document(DocFactory.scala:124)
	at xsbt.Runner.run(ScaladocInterface.scala:26)
	at xsbt.ScaladocInterface.run(ScaladocInterface.scala:10)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at sbt.compiler.AnalyzingCompiler.call(AnalyzingCompiler.scala:101)
	at sbt.compiler.AnalyzingCompiler.doc(AnalyzingCompiler.scala:67)
	at sbt.compiler.AnalyzingCompiler.doc(AnalyzingCompiler.scala:62)
	at sbt.Doc$$anonfun$scaladoc$1.apply(Doc.scala:23)
	at sbt.Doc$$anonfun$scaladoc$1.apply(Doc.scala:23)
	at sbt.RawCompileLike$$anonfun$prepare$1.apply(RawCompileLike.scala:64)
	at sbt.RawCompileLike$$anonfun$prepare$1.apply(RawCompileLike.scala:56)
	at sbt.RawCompileLike$$anonfun$cached$1$$anonfun$2$$anonfun$apply$1.apply(RawCompileLike.scala:49)
	at sbt.RawCompileLike$$anonfun$cached$1$$anonfun$2$$anonfun$apply$1.apply(RawCompileLike.scala:47)
	at sbt.Tracked$$anonfun$outputChanged$1.apply(Tracked.scala:57)
	at sbt.Tracked$$anonfun$outputChanged$1.apply(Tracked.scala:52)
	at sbt.RawCompileLike$$anonfun$cached$1.apply(RawCompileLike.scala:54)
	at sbt.RawCompileLike$$anonfun$cached$1.apply(RawCompileLike.scala:39)
	at sbt.Defaults$$anonfun$docTaskSettings$3.apply(Defaults.scala:733)
	at sbt.Defaults$$anonfun$docTaskSettings$3.apply(Defaults.scala:711)
	at scala.Function1$$anonfun$compose$1.apply(Function1.scala:47)
	at sbt.$tilde$greater$$anonfun$$u2219$1.apply(TypeFunctions.scala:40)
	at sbt.std.Transform$$anon$4.work(System.scala:63)
	at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:226)
	at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:226)
	at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:17)
	at sbt.Execute.work(Execute.scala:235)
	at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:226)
	at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:226)
	at sbt.ConcurrentRestrictions$$anon$4$$anonfun$1.apply(ConcurrentRestrictions.scala:159)
	at sbt.CompletionService$$anon$2.call(CompletionService.scala:28)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

**Comment by sjrd** [comment]
Well, that's a bug ... Kind of really annoying, too. It happens when generating the ScalaDoc of your library, and it is triggered by the `@JSExport` on a `val`, `var`, or `def` without `()`.

You can work around the bug with the following sbt setting:
```scala
scalacOptions in (Compile, doc) ~= { _.filterNot(_.contains("scalajs-compiler_")) }
```
which deactivates the Scala.js compiler when calling ScalaDoc. It's not needed anyway to generate the doc, so that's OK.

It the work around works for you, I'll fix this in 0.6.1. If it doesn't work, I'll consider this a blocker and fix it in 0.6.0.

**Comment by jokade** [comment]
Yes, the sbt setting works fine. Thanks.

**Comment by sjrd** [comment]
OK, assigning to 0.6.1, then. Thanks for the feedback :-)
