### ISSUE TITLE
Critical incorrect constant folding of * (-1) in the optimizer

### ISSUE THREAD

**Issue by japgolly** [scala-js/scala-js#1453]
I'm seeing a new issue with 0.6.0-RC1 and Scala 2.10 (only; 2.11.5 is fine).
Ideas?

##### Reproduction
1. Checkout https://github.com/japgolly/nyaya
2. `git co scalajs-0.6`
3. `./sbt-210 T`

##### Problem
Tests crash like this:
```
[info] 1/4     japgolly.nyaya.util.MultimapTest.list		Success
[info] 2/4     japgolly.nyaya.util.MultimapTest.set		Success
[info] 3/4     japgolly.nyaya.util.MultimapTest.vector		Success
[info] 4/4     japgolly.nyaya.util.MultimapTest		Success
[error] FATAL ERROR: JS Allocation failed - process out of memory
java.net.SocketException: Connection reset
	at java.net.SocketInputStream.read(SocketInputStream.java:189)
	at java.net.SocketInputStream.read(SocketInputStream.java:121)
	at java.io.BufferedInputStream.fill(BufferedInputStream.java:246)
	at java.io.BufferedInputStream.read(BufferedInputStream.java:265)
	at java.io.DataInputStream.readInt(DataInputStream.java:387)
	at org.scalajs.jsenv.nodejs.NodeJSEnv$ComNodeRunner.receive(NodeJSEnv.scala:181)
	at org.scalajs.testadapter.ComUtils$.receiveResponse(ComUtils.scala:23)
	at org.scalajs.testadapter.ComUtils$.receiveLoop(ComUtils.scala:15)
	at org.scalajs.testadapter.ScalaJSTask.execute(ScalaJSTask.scala:62)
	at sbt.TestRunner.runTest$1(TestFramework.scala:76)
	at sbt.TestRunner.run(TestFramework.scala:85)
	at sbt.TestFramework$$anon$2$$anonfun$$init$$1$$anonfun$apply$8.apply(TestFramework.scala:202)
	at sbt.TestFramework$$anon$2$$anonfun$$init$$1$$anonfun$apply$8.apply(TestFramework.scala:202)
	at sbt.TestFramework$.sbt$TestFramework$$withContextLoader(TestFramework.scala:185)
	at sbt.TestFramework$$anon$2$$anonfun$$init$$1.apply(TestFramework.scala:202)
	at sbt.TestFramework$$anon$2$$anonfun$$init$$1.apply(TestFramework.scala:202)
	at sbt.TestFunction.apply(TestFramework.scala:207)
	at sbt.Tests$$anonfun$9.apply(Tests.scala:216)
	at sbt.Tests$$anonfun$9.apply(Tests.scala:216)
	at sbt.std.Transform$$anon$3$$anonfun$apply$2.apply(System.scala:44)
	at sbt.std.Transform$$anon$3$$anonfun$apply$2.apply(System.scala:44)
	at sbt.std.Transform$$anon$4.work(System.scala:63)
	at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:226)
	at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:226)
	at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:17)
	at sbt.Execute.work(Execute.scala:235)
	at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:226)
	at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:226)
	at sbt.ConcurrentRestrictions$$anon$4$$anonfun$1.apply(ConcurrentRestrictions.scala:159)
	at sbt.CompletionService$$anon$2.call(CompletionService.scala:28)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
[error] Could not run test japgolly.nyaya.test.GenTest: java.net.SocketException: Connection reset
java.net.SocketException: Broken pipe
	at java.net.SocketOutputStream.socketWrite0(Native Method)
	at java.net.SocketOutputStream.socketWrite(SocketOutputStream.java:109)
	at java.net.SocketOutputStream.write(SocketOutputStream.java:153)
	at java.io.BufferedOutputStream.flushBuffer(BufferedOutputStream.java:82)
	at java.io.BufferedOutputStream.flush(BufferedOutputStream.java:140)
	at java.io.DataOutputStream.flush(DataOutputStream.java:123)
	at org.scalajs.jsenv.nodejs.NodeJSEnv$ComNodeRunner.send(NodeJSEnv.scala:173)
	at org.scalajs.testadapter.ScalaJSRunner$$anonfun$stopSlaves$1.apply(ScalaJSRunner.scala:128)
	at org.scalajs.testadapter.ScalaJSRunner$$anonfun$stopSlaves$1.apply(ScalaJSRunner.scala:128)
	at scala.collection.Iterator$class.foreach(Iterator.scala:727)
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1157)
	at scala.collection.MapLike$DefaultValuesIterable.foreach(MapLike.scala:206)
	at org.scalajs.testadapter.ScalaJSRunner.stopSlaves(ScalaJSRunner.scala:128)
	at org.scalajs.testadapter.ScalaJSRunner.done(ScalaJSRunner.scala:67)
	at sbt.Defaults$$anonfun$allTestGroupsTask$1$$anonfun$16.apply(Defaults.scala:547)
	at sbt.Defaults$$anonfun$allTestGroupsTask$1$$anonfun$16.apply(Defaults.scala:545)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:244)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:244)
	at scala.collection.immutable.Map$Map1.foreach(Map.scala:109)
	at scala.collection.TraversableLike$class.map(TraversableLike.scala:244)
	at scala.collection.AbstractTraversable.map(Traversable.scala:105)
	at sbt.Defaults$$anonfun$allTestGroupsTask$1.apply(Defaults.scala:545)
	at sbt.Defaults$$anonfun$allTestGroupsTask$1.apply(Defaults.scala:543)
	at scala.Function1$$anonfun$compose$1.apply(Function1.scala:47)
	at sbt.$tilde$greater$$anonfun$$u2219$1.apply(TypeFunctions.scala:40)
	at sbt.std.Transform$$anon$4.work(System.scala:63)
	at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:226)
	at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:226)
	at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:17)
	at sbt.Execute.work(Execute.scala:235)
	at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:226)
	at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:226)
	at sbt.ConcurrentRestrictions$$anon$4$$anonfun$1.apply(ConcurrentRestrictions.scala:159)
	at sbt.CompletionService$$anon$2.call(CompletionService.scala:28)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
[error] (nyaya-test-js/test:executeTests) java.net.SocketException: Broken pipe
```

**Comment by japgolly** [comment]
There's this warning that persists with `scalac.patmat.analysisBudget` set to 512, 1024, 2048.
It can't be a coincidence but I don't see how that would cause a crash _after_ compilation...

```
[warn] /home/golly/projects/nyaya/nyaya-core/src/main/scala/japgolly/nyaya/Logic.scala:70: Cannot check match for unreachability.
[warn] (The analysis required more space than allowed. Please try with scalac -Dscalac.patmat.analysisBudget=1024 or -Dscalac.patmat.analysisBudget=off.)
[warn]   final def ∨(q: Logic[P, A]): Logic[P, A] = this match {
[warn]                                              ^
[warn] /home/golly/projects/nyaya/nyaya-core/src/main/scala/japgolly/nyaya/Logic.scala:82: Cannot check match for unreachability.
[warn] (The analysis required more space than allowed. Please try with scalac -Dscalac.patmat.analysisBudget=1024 or -Dscalac.patmat.analysisBudget=off.)
[warn]   final def ∧(q: Logic[P, A]): Logic[P, A] = this match {
[warn]                                              ^
[warn] /home/golly/projects/nyaya/nyaya-core/src/main/scala/japgolly/nyaya/Logic.scala:70: Cannot check match for unreachability.
[warn] (The analysis required more space than allowed. Please try with scalac -Dscalac.patmat.analysisBudget=1024 or -Dscalac.patmat.analysisBudget=off.)
[warn]   final def ∨(q: Logic[P, A]): Logic[P, A] = this match {
[warn]                                              ^
[warn] /home/golly/projects/nyaya/nyaya-core/src/main/scala/japgolly/nyaya/Logic.scala:82: Cannot check match for unreachability.
[warn] (The analysis required more space than allowed. Please try with scalac -Dscalac.patmat.analysisBudget=1024 or -Dscalac.patmat.analysisBudget=off.)
[warn]   final def ∧(q: Logic[P, A]): Logic[P, A] = this match {
[warn]                                              ^
[warn] /home/golly/projects/nyaya/nyaya-core/src/main/scala/japgolly/nyaya/Logic.scala:120: Cannot check match for unreachability.
[warn] (The analysis required more space than allowed. Please try with scalac -Dscalac.patmat.analysisBudget=1024 or -Dscalac.patmat.analysisBudget=off.)
[warn]   final def rename(n: => String): Logic[P, A] = this match {
[warn]                                                 ^
[warn] /home/golly/projects/nyaya/nyaya-core/src/main/scala/japgolly/nyaya/Logic.scala:120: Cannot check match for unreachability.
[warn] (The analysis required more space than allowed. Please try with scalac -Dscalac.patmat.analysisBudget=1024 or -Dscalac.patmat.analysisBudget=off.)
[warn]   final def rename(n: => String): Logic[P, A] = this match {
```

**Comment by sjrd** [comment]
The `analysisBudget` has nothing to do with this ;)

**Comment by sjrd** [comment]
It seems there is a major memory leak somewhere. Strange thing, with Rhino, it runs ^^ And with PhantomJS, it's much worse because it doesn't detect the memory blowup, and hence the RAM of my entire system when berserk (and I got 16 GB) ...

**Comment by sjrd** [comment]
OK that's a bug in the optimizer with constant folding ^^ (which is why it works in Rhino)

Can you see the obvious mistake here:
https://github.com/scala-js/scala-js/blob/v0.6.0-RC1/tools/shared/src/main/scala/org/scalajs/core/tools/optimizer/OptimizerCore.scala#L1948
? :-p

It is revealed by this downward loop:
https://github.com/japgolly/nyaya/blob/scalajs-0.6/nyaya-test/src/main/scala/japgolly/nyaya/test/Gen.scala#L85
which, after inlining of the `Range` optimization of 2.10 (which is different than that of 2.11 - hence why it happens only in 2.10), and some crazy constant folding, wants to optimize this expression:
```scala
val len = buf.length
val numElems = len - 1
val lastElem = len + (numElems - 1) * (-1)
```
The `(numElems - 1) * (-1)` there is incorrectly "optimized" as just `- (-1)` instead of `- (numElems - 1)`.
This causes this loop to never terminate (well, it has 2^32 iterations due to wrapping), which in turns causes the OutOfMemory problem.

This is a critical bug. So we'll have an RC2 with a fix for this.
In the meantime, if you want to make progress on your libraries, you can deactive the optimizer with
```scala
scalaJSOptimizerOptions ~= { _.withDisableOptimizer(true) }
```
which should work around the problem for now.

**Comment by japgolly** [comment]
Nice work as always! Glad we hit it now it the RC phase. I'm only compiling
the 2.10 build for testing and completeness but thanks for the workaround.
Everything else was perfect. In fact now that this issue is understood I'll
report on the mailing list...
