### ISSUE TITLE
org.scalajs.jsenv.ComJSEnv$ComClosedException: Phantom.js isn't connected

### ISSUE THREAD

**Issue by benjaminjackman** [scala-js/scala-js#1457]
phantomjs version: 1.9.7
java version "1.7.0_67"
Java(TM) SE Runtime Environment (build 1.7.0_67-b01)
Java HotSpot(TM) 64-Bit Server VM (build 24.65-b04, mixed mode)

When building on developer boxes we are able to use phantom js just fine, however on our jenkins build server we get the following stack trace:

```
[error] (pint-sjs/test:loadedTestFrameworks) org.scalajs.jsenv.ComJSEnv$ComClosedException: Phantom.js isn't connected
[error] Total time: 11 s, completed Jan 14, 2015 5:40:07 PM
orange:pint-sjs:2.2.13-SNAPSHOT> last pint-sjs/test:loadedTestFrameworks
[debug] PhantomJS WS Jetty: INFO: jetty-8.1.16.v20140903 WrappedArray()
[debug] PhantomJS WS Jetty: INFO: Started {} WrappedArray(SelectChannelConnector@localhost:32847)
[debug] PhantomJS using webpage launcher at: /tmp/phantomjs-launcher-webpage3086986974158994472.html
[debug] PhantomJS using launcher at: /tmp/phantomjs-launcher1638445151149022404.js
org.scalajs.jsenv.ComJSEnv$ComClosedException: Phantom.js isn't connected
    at org.scalajs.jsenv.phantomjs.PhantomJSEnv$ComPhantomRunner.receive(PhantomJSEnv.scala:234)
    at org.scalajs.testadapter.ScalaJSFramework.fetchFrameworkInfo(ScalaJSFramework.scala:60)
    at org.scalajs.testadapter.ScalaJSFramework.<init>(ScalaJSFramework.scala:29)
    at org.scalajs.sbtplugin.ScalaJSPluginInternal$$anonfun$40$$anonfun$apply$29.apply(ScalaJSPluginInternal.scala:453)
    at org.scalajs.sbtplugin.ScalaJSPluginInternal$$anonfun$40$$anonfun$apply$29.apply(ScalaJSPluginInternal.scala:452)
    at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:244)
    at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:244)
    at scala.collection.immutable.Map$Map1.foreach(Map.scala:109)
    at scala.collection.TraversableLike$class.map(TraversableLike.scala:244)
    at scala.collection.AbstractTraversable.map(Traversable.scala:105)
    at org.scalajs.sbtplugin.ScalaJSPluginInternal$$anonfun$40.apply(ScalaJSPluginInternal.scala:452)
    at org.scalajs.sbtplugin.ScalaJSPluginInternal$$anonfun$40.apply(ScalaJSPluginInternal.scala:437)
    at scala.Function1$$anonfun$compose$1.apply(Function1.scala:47)
    at sbt.$tilde$greater$$anonfun$$u2219$1.apply(TypeFunctions.scala:40)
    at sbt.std.Transform$$anon$4.work(System.scala:63)
    at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:226)
    at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:226)
    at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:17)
    at sbt.Execute.work(Execute.scala:235)
    at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:226)
    at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:226)
    at sbt.ConcurrentRestrictions$$anon$4$$anonfun$1.apply(ConcurrentRestrictions.scala:159)
    at sbt.CompletionService$$anon$2.call(CompletionService.scala:28)
    at java.util.concurrent.FutureTask.run(FutureTask.java:262)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
    at java.util.concurrent.FutureTask.run(FutureTask.java:262)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
    at java.lang.Thread.run(Thread.java:745)
```

This is still on 0.6.0-M3, I will try RC1 next, but I suspect it will still be a problem because i don't know what would have changed on the scalajs/sbt side to fix this.

**Comment by benjaminjackman** [comment]
One thing to keep in mind is that our build server where we are seeing this issue is significantly slower than our dev boxes. So if there is a race to connect to the socket, that might be the source of the problem. I see that commit fdc8c5a42d4c408549101a01a0db9a1fa0876060 might help in that regard if I understand it correctly.

**Comment by matthughes** [comment]
Still getting these with 0.6.4 quite often.

**Comment by sjrd** [comment]
The workaround so far is to use this when running on your CI:
```scala
set inScope(ThisScope in theScalaJSProject)(
    postLinkJSEnv := new org.scalajs.jsenv.RetryingComJSEnv(PhantomJSEnv().value))
```
This is what do [here](https://github.com/scala-js/scala-js/blob/v0.6.4/ci/matrix.xml#L32).

We still don't have a clue what causes this, unfortunately :-(

**Comment by gzm0** [comment]
@benjaminjackman Is this still an issue, or can we close this?

**Comment by benjaminjackman** [comment]
Unfortunately I can't say I stopped using it.

**Comment by gzm0** [comment]
@benjaminjackman Is this still an issue, or can we close this?

**Comment by benjaminjackman** [comment]
Unfortunately I can't say I stopped using it. It's fine to close from my perspective.

**Comment by sjrd** [comment]
OK let's close this, then, thanks.
