### ISSUE TITLE
AssertionError when crossProject is used as a ProjectRef in another project

### ISSUE THREAD

**Issue by yelbota** [scala-js/scala-js#1569]
Hello everyone!

I encountered with a problem appeared when crossProject imports in other one as a ProjectRef.
This repo show how to reproduce this error https://github.com/yelbota/scalajs-crossProjectRef-error
Travis build log https://travis-ci.org/yelbota/scalajs-crossProjectRef-error

**Comment by sjrd** [comment]
The Travis URL you point to does not show anything.

**Comment by sjrd** [comment]
I get this error locally:
```
doeraene@lamppc37:~/projects/scalajs-crossProjectRef-error$ sbt
[info] Loading global plugins from /localhome/doeraene/.sbt/0.13/plugins
[info] Loading project definition from /localhome/doeraene/projects/scalajs-crossProjectRef-error/project
[info] Updating {file:/localhome/doeraene/projects/scalajs-crossProjectRef-error/project/}scalajs-crossprojectref-error-build...
[info] Resolving org.fusesource.jansi#jansi;1.4 ...
[info] Done updating.
[info] Loading project definition from /localhome/doeraene/projects/scalajs-crossProjectRef-error/crossProjectRef/project
[info] Updating {file:/localhome/doeraene/projects/scalajs-crossProjectRef-error/crossProjectRef/project/}crossprojectref-build...
[info] Resolving org.fusesource.jansi#jansi;1.4 ...
[info] Done updating.
java.lang.AssertionError: assertion failed: Directory /localhome/doeraene/projects/scalajs-crossProjectRef-error/.jvm is not contained in build root /localhome/doeraene/projects/scalajs-crossProjectRef-error/crossProjectRef
        at scala.Predef$.assert(Predef.scala:179)
        at sbt.Load$.checkProjectBase(Load.scala:345)
        at sbt.Load$.sbt$Load$$resolve$1(Load.scala:380)
        at sbt.Load$$anonfun$resolveBase$1.apply(Load.scala:383)
        at sbt.Load$$anonfun$resolveBase$1.apply(Load.scala:383)
        at scala.Function1$$anonfun$compose$1.apply(Function1.scala:47)
        at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:244)
        at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:244)
        at scala.collection.immutable.List.foreach(List.scala:318)
        at scala.collection.TraversableLike$class.map(TraversableLike.scala:244)
        at scala.collection.AbstractTraversable.map(Traversable.scala:105)
        at sbt.Load$.projects(Load.scala:407)
        at sbt.Load$.loaded(Load.scala:308)
        at sbt.Load$.loadAll(Load.scala:334)
        at sbt.Load$.loadURI(Load.scala:289)
        at sbt.Load$.load(Load.scala:285)
        at sbt.Load$.load(Load.scala:276)
        at sbt.Load$.apply(Load.scala:130)
        at sbt.Load$.defaultLoad(Load.scala:36)
        at sbt.BuiltinCommands$.doLoadProject(Main.scala:481)
        at sbt.BuiltinCommands$$anonfun$loadProjectImpl$2.apply(Main.scala:475)
        at sbt.BuiltinCommands$$anonfun$loadProjectImpl$2.apply(Main.scala:475)
        at sbt.Command$$anonfun$applyEffect$1$$anonfun$apply$2.apply(Command.scala:58)
        at sbt.Command$$anonfun$applyEffect$1$$anonfun$apply$2.apply(Command.scala:58)
        at sbt.Command$$anonfun$applyEffect$2$$anonfun$apply$3.apply(Command.scala:60)
        at sbt.Command$$anonfun$applyEffect$2$$anonfun$apply$3.apply(Command.scala:60)
        at sbt.Command$.process(Command.scala:92)
        at sbt.MainLoop$$anonfun$1$$anonfun$apply$1.apply(MainLoop.scala:98)
        at sbt.MainLoop$$anonfun$1$$anonfun$apply$1.apply(MainLoop.scala:98)
        at sbt.State$$anon$1.process(State.scala:184)
        at sbt.MainLoop$$anonfun$1.apply(MainLoop.scala:98)
        at sbt.MainLoop$$anonfun$1.apply(MainLoop.scala:98)
        at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:17)
        at sbt.MainLoop$.next(MainLoop.scala:98)
        at sbt.MainLoop$.run(MainLoop.scala:91)
        at sbt.MainLoop$$anonfun$runWithNewLog$1.apply(MainLoop.scala:70)
        at sbt.MainLoop$$anonfun$runWithNewLog$1.apply(MainLoop.scala:65)
        at sbt.Using.apply(Using.scala:24)
        at sbt.MainLoop$.runWithNewLog(MainLoop.scala:65)
        at sbt.MainLoop$.runAndClearLast(MainLoop.scala:48)
        at sbt.MainLoop$.runLoggedLoop(MainLoop.scala:32)
        at sbt.MainLoop$.runLogged(MainLoop.scala:24)
        at sbt.StandardMain$.runManaged(Main.scala:53)
        at sbt.xMain.run(Main.scala:28)
        at xsbt.boot.Launch$$anonfun$run$1.apply(Launch.scala:57)
        at xsbt.boot.Launch$.withContextLoader(Launch.scala:77)
        at xsbt.boot.Launch$.run(Launch.scala:57)
        at xsbt.boot.Launch$$anonfun$explicit$1.apply(Launch.scala:45)
        at xsbt.boot.Launch$.launch(Launch.scala:65)
        at xsbt.boot.Launch$.apply(Launch.scala:16)
        at xsbt.boot.Boot$.runImpl(Boot.scala:32)
        at xsbt.boot.Boot$.main(Boot.scala:21)
        at xsbt.boot.Boot.main(Boot.scala)
[error] java.lang.AssertionError: assertion failed: Directory /localhome/doeraene/projects/scalajs-crossProjectRef-error/.jvm is not contained in build root /localhome/doeraene/projects/scalajs-crossProjectRef-error/crossProjectRef
[error] Use 'last' for the full log.
Project loading failed: (r)etry, (q)uit, (l)ast, or (i)gnore?
```

**Comment by yelbota** [comment]
Check it now.

**Comment by yelbota** [comment]
I fix a travis. Error logs are matches

**Comment by gzm0** [comment]
Could we please have a minimal example in this ticket itself?

**Comment by yelbota** [comment]
> Could we please have a minimal example in this ticket itself?

    + /build.sbt
    + /crossProjectRef/build.sbt

`crossProjectRef/build.sbt` contains definition of crossProject: `crossProjectJS` and `crossProjectJVM`. `build.sbt` in root contains two `ProjectRef`s. Thats all. When we try to run a project an error occurs.

    Directory scalajs-crossProjectRef-error/.jvm is not contained in build root scalajs-crossProjectRef-error/crossProjectRef

**Comment by InTheNow** [comment]
I believe that the error is in the example (and hence the original build). Using this as the subproject file works:

```
lazy val crossProjectRef = crossProject.crossType(CrossType.Pure).in(file("crossProjectRef")).
  settings(scalaVersion := "2.11.6") 

lazy val crossProjectRefJS = crossProjectRef.js

lazy val crossProjectRefJVM = crossProjectRef.jvm

```

Why? see http://www.scala-sbt.org/0.13.5/docs/Getting-Started/Multi-Project.html#default-root-project

"Any .sbt files in foo, say foo/build.sbt, will be merged with the build definition for the entire build, but scoped to the hello-foo project."

so when the sub project sbt file is merged, the directory stays as is - "."

**Comment by yelbota** [comment]
> file("crossProjectRef")

Looks like absolute path. What if a referenced project placed outside of hierarchy? It could be project in other git repository.

See
http://www.scala-sbt.org/0.13.5/docs/Detailed-Topics/Paths.html#constructing-a-file
>Relative files should only be used when defining the base directory of a Project, where they will be resolved properly.

    val root = Project("root", file("."))

**Comment by InTheNow** [comment]
yes - ` only be used when defining the base directory of a Project` - But `lazy val crossProjectRef = crossProject.crossType(CrossType.Pure).in(file("."))` is not a Project - it is something else

**Comment by yelbota** [comment]
> is not a Project - it is something else

Semantically it is a project. `CrossProject` have similar API and used for define "real" projects.

**Comment by yelbota** [comment]
Look at this. ProjectRef can be anywhere
http://www.scala-sbt.org/0.12.4/docs/Dormant/Full-Configuration.html#project-relationships

**Comment by InTheNow** [comment]
I'm just saying that it's not a Project (a sealed trait), and can't be thought as such
