### ISSUE TITLE
AssertionError in FrameworkDetector when jsDependency log something in console on initialize

### ISSUE THREAD

**Issue by yelbota** [scala-js/scala-js#1571]
java.lang.AssertionError: assertion failed
      at scala.Predef$.assert(Predef.scala:165)
      at org.scalajs.sbtplugin.FrameworkDetector.detect(FrameworkDetector.scala:68)
      at org.scalajs.sbtplugin.ScalaJSPluginInternal$$anonfun$40.apply(ScalaJSPluginInternal.scala:455)
      at org.scalajs.sbtplugin.ScalaJSPluginInternal$$anonfun$40.apply(ScalaJSPluginInternal.scala:440)
      ...

I have asked @sjrd in gitter about this error. He recommended me check my `jsDependencies` for case of printing to console. So it turned out.

**Comment by yelbota** [comment]
I'm working on fix that will make `Framework Detector` resilient for such cases.
