### ISSUE TITLE
PermGen exception during tests execution in Travis-CI

### ISSUE THREAD

**Issue by yelbota** [scala-js/scala-js#1639]
I have an error when I use Rhino in Travis-CI
https://travis-ci.org/tenderowls/moorka/builds/61441060

    java.util.concurrent.ExecutionException: Boxed Error
      at scala.concurrent.impl.Promise$.resolver(Promise.scala:55)
      at scala.concurrent.impl.Promise$.scala$concurrent$impl$Promise$$resolveTry(Promise.scala:47)
      at scala.concurrent.impl.Promise$DefaultPromise.tryComplete(Promise.scala:244)
      at scala.concurrent.Promise$class.complete(Promise.scala:55)
      at scala.concurrent.impl.Promise$DefaultPromise.complete(Promise.scala:153)
      at scala.concurrent.Promise$class.failure(Promise.scala:107)
      at scala.concurrent.impl.Promise$DefaultPromise.failure(Promise.scala:153)
      at org.scalajs.jsenv.rhino.RhinoJSEnv$AsyncRunner$$anon$1.run(RhinoJSEnv.scala:80)
    Caused by: java.lang.OutOfMemoryError: PermGen space

My code is simple (~250 lines of JavaScript and ~200 of Scala) and works fine in JVM. Besides It runs well with Rhino on my Mac. Can you please say what kind of problem it could be?

**Comment by sjrd** [comment]
You have to [increase your PermGen space](http://stackoverflow.com/a/3003986/1829647).

**Comment by yelbota** [comment]
-Xms2048M
    -Xmx2048M
    -Xss6M
    -XX:MaxPermSize=512M

Unfortunately Travis-CI already has really huge limits.

**Comment by sjrd** [comment]
Well, then I guess you're simply hitting the limit of what Rhino can endure under the constraints of Travis. I suggest you don't use Rhino in your CI, and use Node.js or PhantomJS instead.

**Comment by yelbota** [comment]
Ok. I tried to use PhantomJS, but it turned out that jsDependencies don't embeds into *-test-fastopt.js. I will try reproduce it in pure environment to be sure that it is Scala.js bug.

**Comment by yelbota** [comment]
I increased MaxPermSize to 1024M (!) and it solves a problem. Amazingly that Travis-CI allowed me to do it.
