### ISSUE TITLE
Wrong exception stack trace

### ISSUE THREAD

**Issue by maruns** [scala-js/scala-js#1661]
Stack trace reported by exception is like this one:

    "Failure in async execution: TypeError: this$2 is null" scalajs-example-fastopt.js:57604:6
    $c_jl_JSConsoleBasedPrintStream.prototype.doWriteLine__p4__T__V() scalajs-example-fastopt.js:57604
    $c_jl_JSConsoleBasedPrintStream.prototype.printString__p4__T__V() scalajs-example-fastopt.js:57628
    $c_Ljava_io_PrintStream.prototype.println__T__V() scalajs-example-fastopt.js:53211
    $c_sjs_concurrent_RunNowExecutionContext$.prototype.reportFailure__jl_Throwable__V() scalajs-example-fastopt.js:46249
    $c_s_concurrent_impl_CallbackRunnable.prototype.run__V() scalajs-example-fastopt.js:24956
    $c_sjs_concurrent_RunNowExecutionContext$.prototype.execute__jl_Runnable__V() scalajs-example-fastopt.js:46253
    $c_s_concurrent_impl_CallbackRunnable.prototype.executeWithValue__s_util_Try__V() scalajs-example-fastopt.js:24976
    $c_s_concurrent_impl_Promise$DefaultPromise.prototype.tryComplete__s_util_Try__Z() scalajs-example-fastopt.js:53954
    $s_s_concurrent_Promise$class__complete__s_concurrent_Promise__s_util_Try__s_concurrent_Promise() scalajs-example-fastopt.js:7160
    $s_s_concurrent_Promise$class__success__s_concurrent_Promise__O__s_concurrent_Promise() scalajs-example-fastopt.js:7153
    $c_Lorg_scalajs_dom_ext_Ajax$.prototype.apply__T__T__T__I__sci_Map__Z__T__s_concurrent_Future/req.onreadystatechange</<()

But it should be something like this

    "TypeError: Cannot read property 'value$2' of null
    at $c_Lcom_advertine_web_data_Model.apply__s_Symbol__O (http://localhost:9000/assets/javascripts/scalajs-example-fastopt.js:46519:16)
    at $c_Lcom_advertine_web_ui_grid_TreeColumn$$anon$1.name__T (http://localhost:9000/assets/javascripts/scalajs-example-fastopt.js:60998:28)
    at $s_Lcom_advertine_web_view_table_TreeCell$class__template__Lcom_advertine_web_view_table_TreeCell__Lcom_advertine_web_html_Element (http://localhost:9000/assets/javascripts/scalajs-example-fastopt.js:4072:21)
    at $c_Lcom_advertine_web_ui_grid_TreeColumn$$anon$1.template__Lcom_advertine_web_html_Element (http://localhost:9000/assets/javascripts/scalajs-example-fastopt.js:60958:10)
    at $s_Lcom_advertine_web_view_util_Renderable$class__render__Lcom_advertine_web_view_util_Renderable__Lcom_advertine_web_html_Element (http://localhost:9000/assets/javascripts/scalajs-example-fastopt.js:4186:23)
    at $s_Lcom_advertine_web_view_View$class__render__Lcom_advertine_web_view_View__Lcom_advertine_web_html_Element (http://localhost:9000/assets/javascripts/scalajs-example-fastopt.js:2886:16)
    at $c_Lcom_advertine_web_ui_grid_TreeColumn$$anon$1.render__Lcom_advertine_web_html_Element (http://localhost:9000/assets/javascripts/scalajs-example-fastopt.js:60961:10)
    at $s_Lcom_advertine_web_view_View$class__getRoot__Lcom_advertine_web_view_View__Lcom_advertine_web_html_Element (http://localhost:9000/assets/javascripts/scalajs-example-fastopt.js:2917:12)
    at $s_Lcom_advertine_web_view_util_ViewEventSource$class__forward__Lcom_advertine_web_view_View__s_Symbol__T__s_Symbol__V (http://localhost:9000/assets/javascripts/scalajs-example-fastopt.js:4216:12)
    at $s_Lcom_advertine_web_view_table_TreeCell$class__$$init$__Lcom_advertine_web_view_table_TreeCell__V (http://localhost:9000/assets/javascripts/scalajs-example-fastopt.js:4009:3)"

Variable ``t`` passed as parameter of ``reportFailure`` contains property ``exception$4.stack`` which holds correct stack trace. (Mac, Opera 29.0.1795.47).

Can scala-js print second stack trace along the message about an exception?

**Comment by sjrd** [comment]
What version of Scala.js are you using? We supposedly fixed that in 0.6.3 already.

**Comment by maruns** [comment]
0.6.2. I have missed next release. :(. Sorry for inconvenience.
I'm upgrading now.

**Comment by gzm0** [comment]
Probably duplicate of #1608
