### ISSUE TITLE
ClassCastException: org.mozilla.javascript.UniqueTag running scala-js project

### ISSUE THREAD

**Issue by mkotsbak** [scala-js/scala-js#1774]
I tried to clone the repository at https://github.com/widok/todomvc and run "sbt run" and the run fails with this stacktrace:

[info] Running org.widok.todomvc.Application
java.lang.ClassCastException: org.mozilla.javascript.UniqueTag cannot be cast to org.mozilla.javascript.Scriptable
at org.scalajs.jsenv.rhino.ScalaJSCoreLib$$anonfun$lazifyScalaJSFields$2.apply(ScalaJSCoreLib.scala:154)
at org.scalajs.jsenv.rhino.ScalaJSCoreLib$$anonfun$lazifyScalaJSFields$2.apply(ScalaJSCoreLib.scala:153)
at scala.collection.TraversableLike$WithFilter$$anonfun$foreach$1.apply(TraversableLike.scala:772)
at scala.collection.immutable.List.foreach(List.scala:318)
at scala.collection.TraversableLike$WithFilter.foreach(TraversableLike.scala:771)
at org.scalajs.jsenv.rhino.ScalaJSCoreLib.lazifyScalaJSFields(ScalaJSCoreLib.scala:153)
at org.scalajs.jsenv.rhino.ScalaJSCoreLib.insertInto(ScalaJSCoreLib.scala:48)
at org.scalajs.jsenv.rhino.RhinoJSEnv$$anonfun$loadClasspath$2.apply(RhinoJSEnv.scala:329)
at org.scalajs.jsenv.rhino.RhinoJSEnv$$anonfun$loadClasspath$2.apply(RhinoJSEnv.scala:329)
at scala.Option.foreach(Option.scala:236)
at org.scalajs.jsenv.rhino.RhinoJSEnv.loadClasspath(RhinoJSEnv.scala:329)
at org.scalajs.jsenv.rhino.RhinoJSEnv.org$scalajs$jsenv$rhino$RhinoJSEnv$$internalRunJS(RhinoJSEnv.scala:149)
at org.scalajs.jsenv.rhino.RhinoJSEnv$Runner.run(RhinoJSEnv.scala:60)
at org.scalajs.sbtplugin.ScalaJSPluginInternal$.org$scalajs$sbtplugin$ScalaJSPluginInternal$$jsRun(ScalaJSPluginInternal.scala:373)
at org.scalajs.sbtplugin.ScalaJSPluginInternal$$anonfun$38$$anonfun$apply$24$$anonfun$apply$25.apply(ScalaJSPluginInternal.scala:433)
at org.scalajs.sbtplugin.ScalaJSPluginInternal$$anonfun$38$$anonfun$apply$24$$anonfun$apply$25.apply(ScalaJSPluginInternal.scala:427)
at scala.Function1$$anonfun$compose$1.apply(Function1.scala:47)

Originally reported at https://github.com/widok/todomvc/issues/3

**Comment by sjrd** [comment]
This is a bug in Rhino that we cannot really work around. You'll have to use Node.js or PhantomJS.

**Comment by mkotsbak** [comment]
Ok, is it a known bug in the Rhino project?

**Comment by sjrd** [comment]
I think so. I discovered that a long time ago. Anyhow, it won't get fixed, since rhino is basically dead.

**Comment by sjrd** [comment]
Ah no, this is not at all what I thought it was. This is a real bug. It is a bad interaction of running with Rhino + having `scalaJSSemantics ~= (_.withAsInstanceOfs(CheckedBehavior.Unchecked))` in the build file.

We never discovered this because I can't figure out why anyone would want to put that in their build file ^^ This is just a very good way of destroying debuggability in fastOpt mode. /cc @tindzk
