### ISSUE TITLE
NodeJSEnv + jsDependencies

### ISSUE THREAD

**Issue by japgolly** [scala-js/scala-js#1884]
I'm trying to get Node.JS to work but have hit a problem that suggests that `jsDependencies` might not work with Node.JS?

I have this:

``` scala
    def testjs(path: String) = ProvidedJS / s"testjs/$path"

// then in settings...
    jsDependencies in Test ++= Seq(
      testjs("react-with-addons.js"),
      testjs("jquery.min.js"),
      testjs("jquery.textcomplete.js") dependsOn "testjs/jquery.min.js",
      testjs("sizzle.min.js")),
```

Works fine with PhantomJS. Trying to get Node.JS working I've dumped this in:

``` scala
    scalaJSStage in Test := FastOptStage,
    jsEnv in Test := NodeJSEnv().value,
    postLinkJSEnv in Test := NodeJSEnv().value
```

Now I keep getting:

```
webapp-client> test
[trace] Stack trace suppressed: run last webapp-client/test:loadedTestFrameworks for the full output.
[error] (webapp-client/test:loadedTestFrameworks) org.scalajs.jsenv.ExternalJSEnv$NonZeroExitException: node.js exited with code 1
[error] Total time: 3 s, completed 28/08/2015 12:28:52 AM
webapp-client> last
[debug] Other repositories:
[debug] Default repositories:
[debug] Using inline dependencies specified in Scala.
[debug] Other repositories:
[debug] Default repositories:
[debug] Using inline dependencies specified in Scala.
[debug] Other repositories:
[debug] Default repositories:
[debug] Using inline dependencies specified in Scala.
[debug] Other repositories:
[debug] Default repositories:
[debug] Using inline dependencies specified in Scala.
[debug] Other repositories:
[debug] Default repositories:
[debug] Using inline dependencies specified in Scala.
[debug] 
[debug] Initial source changes: 
[debug]     removed:Set()
[debug]     added: Set()
[debug]     modified: Set()
[debug] Removed products: Set()
[debug] External API changes: API Changes: Set()
[debug] Modified binary dependencies: Set()
[debug] Initial directly invalidated sources: Set()
[debug] 
[debug] Sources indirectly invalidated by:
[debug]     product: Set()
[debug]     binary dep: Set()
[debug]     external source: Set()
[debug] All initially invalidated sources: Set()
[debug] Copy resource mappings: 
[debug]     
[debug] 
[debug] Initial source changes: 
[debug]     removed:Set()
[debug]     added: Set()
[debug]     modified: Set()
[debug] Removed products: Set()
[debug] External API changes: API Changes: Set()
[debug] Modified binary dependencies: Set()
[debug] Initial directly invalidated sources: Set()
[debug] 
[debug] Sources indirectly invalidated by:
[debug]     product: Set()
[debug]     binary dep: Set()
[debug]     external source: Set()
[debug] All initially invalidated sources: Set()
[debug] Copy resource mappings: 
[debug]     
[debug] 
[debug] Initial source changes: 
[debug]     removed:Set()
[debug]     added: Set()
[debug]     modified: Set()
[debug] Removed products: Set()
[debug] External API changes: API Changes: Set()
[debug] Modified binary dependencies: Set()
[debug] Initial directly invalidated sources: Set()
[debug] 
[debug] Sources indirectly invalidated by:
[debug]     product: Set()
[debug]     binary dep: Set()
[debug]     external source: Set()
[debug] All initially invalidated sources: Set()
[debug] Copy resource mappings: 
[debug]     
[debug] 
[debug] Initial source changes: 
[debug]     removed:Set()
[debug]     added: Set()
[debug]     modified: Set()
[debug] Removed products: Set()
[debug] External API changes: API Changes: Set()
[debug] Modified binary dependencies: Set()
[debug] Initial directly invalidated sources: Set()
[debug] 
[debug] Sources indirectly invalidated by:
[debug]     product: Set()
[debug]     binary dep: Set()
[debug]     external source: Set()
[debug] All initially invalidated sources: Set()
[debug] Copy resource mappings: 
[debug]     
[debug] 
[debug] Initial source changes: 
[debug]     removed:Set()
[debug]     added: Set()
[debug]     modified: Set()
[debug] Removed products: Set()
[debug] External API changes: API Changes: Set()
[debug] Modified binary dependencies: Set()
[debug] Initial directly invalidated sources: Set()
[debug] 
[debug] Sources indirectly invalidated by:
[debug]     product: Set()
[debug]     binary dep: Set()
[debug]     external source: Set()
[debug] All initially invalidated sources: Set()
[debug] Copy resource mappings: 
[debug]     
[debug] 
[debug] Initial source changes: 
[debug]     removed:Set()
[debug]     added: Set()
[debug]     modified: Set()
[debug] Removed products: Set()
[debug] External API changes: API Changes: Set()
[debug] Modified binary dependencies: Set()
[debug] Initial directly invalidated sources: Set()
[debug] 
[debug] Sources indirectly invalidated by:
[debug]     product: Set()
[debug]     binary dep: Set()
[debug]     external source: Set()
[debug] All initially invalidated sources: Set()
[debug] Copy resource mappings: 
[debug]     
[debug] 
[debug] Initial source changes: 
[debug]     removed:Set()
[debug]     added: Set()
[debug]     modified: Set()
[debug] Removed products: Set()
[debug] External API changes: API Changes: Set()
[debug] Modified binary dependencies: Set()
[debug] Initial directly invalidated sources: Set()
[debug] 
[debug] Sources indirectly invalidated by:
[debug]     product: Set()
[debug]     binary dep: Set()
[debug]     external source: Set()
[debug] All initially invalidated sources: Set()
[debug] Copy resource mappings: 
[debug]     (/home/golly/xxx/projects/xxx/Code/webapp-client/src/test/resources/testjs,/tmp/xxx.sbt/webapp-client/target/scala-2.11/test-classes/testjs)
[debug]     (/home/golly/xxx/projects/xxx/Code/webapp-client/src/test/resources/testjs/jquery.textcomplete.js,/tmp/xxx.sbt/webapp-client/target/scala-2.11/test-classes/testjs/jquery.textcomplete.js)
[debug]     (/home/golly/xxx/projects/xxx/Code/webapp-client/src/test/resources/testjs/react-with-addons.js,/tmp/xxx.sbt/webapp-client/target/scala-2.11/test-classes/testjs/react-with-addons.js)
[debug]     (/home/golly/xxx/projects/xxx/Code/webapp-client/src/test/resources/testjs/jquery.textcomplete.min.js,/tmp/xxx.sbt/webapp-client/target/scala-2.11/test-classes/testjs/jquery.textcomplete.min.js)
[debug]     (/home/golly/xxx/projects/xxx/Code/webapp-client/src/test/resources/testjs/jquery.min.js,/tmp/xxx.sbt/webapp-client/target/scala-2.11/test-classes/testjs/jquery.min.js)
[debug]     (/home/golly/xxx/projects/xxx/Code/webapp-client/src/test/resources/testjs/sizzle.min.js,/tmp/xxx.sbt/webapp-client/target/scala-2.11/test-classes/testjs/sizzle.min.js)
org.scalajs.jsenv.ExternalJSEnv$NonZeroExitException: node.js exited with code 1
    at org.scalajs.jsenv.ExternalJSEnv$AbstractExtRunner.waitForVM(ExternalJSEnv.scala:96)
    at org.scalajs.jsenv.ExternalJSEnv$ExtRunner.run(ExternalJSEnv.scala:143)
    at org.scalajs.sbtplugin.FrameworkDetector.detect(FrameworkDetector.scala:68)
    at org.scalajs.sbtplugin.ScalaJSPluginInternal$$anonfun$48.apply(ScalaJSPluginInternal.scala:574)
    at org.scalajs.sbtplugin.ScalaJSPluginInternal$$anonfun$48.apply(ScalaJSPluginInternal.scala:559)
    at scala.Function1$$anonfun$compose$1.apply(Function1.scala:47)
    at sbt.$tilde$greater$$anonfun$$u2219$1.apply(TypeFunctions.scala:40)
    at sbt.std.Transform$$anon$4.work(System.scala:63)
    at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:226)
    at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:226)
    at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:17)
    at sbt.Execute.work(Execute.scala:235)
    at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:226)
    at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:226)
    at sbt.ConcurrentRestrictions$$anon$4$$anonfun$1.apply(ConcurrentRestrictions.scala:159)
    at sbt.CompletionService$$anon$2.call(CompletionService.scala:28)
    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:745)
[error] (webapp-client/test:loadedTestFrameworks) org.scalajs.jsenv.ExternalJSEnv$NonZeroExitException: node.js exited with code 1
[error] Total time: 3 s, completed 28/08/2015 12:28:52 AM
[debug] > shell
```

If I remove the `jsDependencies` setting, the error goes away and tests execute.

**Comment by sjrd** [comment]
For Node.js, you typically need to make appropriate use of `commonJSName` in `jsDependencies`. http://stackoverflow.com/questions/31932340/sbt-and-scala-js-with-node-js-cant-run-with-a-local-js-dependency-due-to-ty/31954152#31954152

**Comment by japgolly** [comment]
Thanks but still not working. According to that answer, it's suggested to do

```js
modules.exports = function() {
  console.log("hello from js")
};
```
and add `commonJSName` to the dependency.

It works for React and JQuery, but not for jquery plugin "textcomplete". Looking at [the source](https://github.com/yuku-t/jquery-textcomplete/blob/master/dist/jquery.textcomplete.js), it begins with
```js
(function (factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['jquery'], factory);
  } else if (typeof module === "object" && module.exports) {
    var $ = require('jquery');
    module.exports = factory($);
```

which uses `modules.exports` like suggested above, yet in Scala.JS both with and without me adding `commonJSName`, it keeps crashing with

```
org.scalajs.jsenv.ExternalJSEnv$NonZeroExitException: node.js exited with code 1
	at org.scalajs.jsenv.ExternalJSEnv$AbstractExtRunner.waitForVM(ExternalJSEnv.scala:96)
	at org.scalajs.jsenv.ExternalJSEnv$ExtRunner.run(ExternalJSEnv.scala:143)
	at org.scalajs.sbtplugin.FrameworkDetector.detect(FrameworkDetector.scala:68)
	at org.scalajs.sbtplugin.ScalaJSPluginInternal$$anonfun$48.apply(ScalaJSPluginInternal.scala:574)
	at org.scalajs.sbtplugin.ScalaJSPluginInternal$$anonfun$48.apply(ScalaJSPluginInternal.scala:559)
	at scala.Function1$$anonfun$compose$1.apply(Function1.scala:47)
	at sbt.$tilde$greater$$anonfun$$u2219$1.apply(TypeFunctions.scala:40)
	at sbt.std.Transform$$anon$4.work(System.scala:63)
	at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:226)
	at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:226)
	at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:17)
	at sbt.Execute.work(Execute.scala:235)
	at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:226)
	at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:226)
	at sbt.ConcurrentRestrictions$$anon$4$$anonfun$1.apply(ConcurrentRestrictions.scala:159)
	at sbt.CompletionService$$anon$2.call(CompletionService.scala:28)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

and no useful information. Do you know what is needed to make this work?

(PS: It would be helpful if in this situation a dev could see the generated JS that it tried to run, and the output of the attempted run. Should I raise a ticket for something like that?)

**Comment by Enalmada** [comment]
In my play project, "activator test" always errors out with "org.scalajs.jsenv.ExternalJSEnv$NonZeroExitException: node.js exited with code 1" (activator run and production release "docker:stage" work fine).  I noticed that if I do the following then test seems to work again (I don't actually have any scalajs tests but "activator test" works):  
* In build.sbt client settings, add: jsDependencies += RuntimeDOM % "test"
* Remove all mention of scalaJSStage from build.sbt (ie: scalaJSStage in Global := FastOptStage).  My play 2.4.x project still does fastOpt in dev and fullOpt in prod without this line so for some reason all this line is doing is stopping my "activator test" from working.  

I am putting my results here with the hope it helps people finding this ticket because of similar error.

**Comment by sjrd** [comment]
This issue should be superseded by [scalajs-bundler](https://scalacenter.github.io/scalajs-bundler/).
