### ISSUE TITLE
Compiler crash: scala.reflect.internal.FatalError: Found unknown label apply

### ISSUE THREAD

**Issue by jeroentervoorde** [scala-js/scala-js#1955]
Hi,

The following code crashes the compiler when using scala 2.11.7 and scala-js 0.6.5:

```scala
case class Bug() {

  def doSomething(a: Int, b: Int) {}

  def bug(e: Boolean) {
    0 match {
      case 1 => (doSomething _).tupled( (123, 456) )
      case 2 if e =>
    }

    if (false) Unit
  }
}
```

The line at `case 1` seems to trigger the bug. It doesn't really matter what tupled method is called.
When removing either the `case 2`  or the `if (false)` line the code compiles.
  
The following exception is thrown:

```
[error] Found unknown label apply at source-/home/jeroen/dev/projects/scalajs-bug/src/main/scala/Bug.scala,line-6,offset=86: default4()
scala.reflect.internal.FatalError: Found unknown label apply at source-/home/jeroen/dev/projects/scalajs-bug/src/main/scala/Bug.scala,line-6,offset=86: default4()
	at scala.reflect.internal.SymbolTable.abort(SymbolTable.scala:58)
	at scala.tools.nsc.Global.abort(Global.scala:269)
	at org.scalajs.core.compiler.GenJSCode$JSCodePhase.genLabelApply(GenJSCode.scala:1848)
	at org.scalajs.core.compiler.GenJSCode$JSCodePhase.genApply(GenJSCode.scala:1650)
	at org.scalajs.core.compiler.GenJSCode$JSCodePhase.genStatOrExpr(GenJSCode.scala:1254)
	at org.scalajs.core.compiler.GenJSCode$JSCodePhase.genStatOrExpr(GenJSCode.scala:1229)
	at org.scalajs.core.compiler.GenJSCode$JSCodePhase.genStat(GenJSCode.scala:1163)
	at org.scalajs.core.compiler.GenJSCode$JSCodePhase$$anonfun$47.apply(GenJSCode.scala:2284)
	at org.scalajs.core.compiler.GenJSCode$JSCodePhase$$anonfun$47.apply(GenJSCode.scala:2284)
	at scala.collection.immutable.List.map(List.scala:274)
	at org.scalajs.core.compiler.GenJSCode$JSCodePhase.genBlock(GenJSCode.scala:2284)
	at org.scalajs.core.compiler.GenJSCode$JSCodePhase.genStatOrExpr(GenJSCode.scala:1335)
	at org.scalajs.core.compiler.GenJSCode$JSCodePhase$$anonfun$genMatch$2.genBody$2(GenJSCode.scala:2209)
	at org.scalajs.core.compiler.GenJSCode$JSCodePhase$$anonfun$genMatch$2.apply(GenJSCode.scala:2217)
	at org.scalajs.core.compiler.GenJSCode$JSCodePhase$$anonfun$genMatch$2.apply(GenJSCode.scala:2194)
	at scala.collection.TraversableLike$WithFilter$$anonfun$foreach$1.apply(TraversableLike.scala:778)
	at scala.collection.immutable.List.foreach(List.scala:383)
	at scala.collection.TraversableLike$WithFilter.foreach(TraversableLike.scala:777)
	at org.scalajs.core.compiler.GenJSCode$JSCodePhase.genMatch(GenJSCode.scala:2194)
	at org.scalajs.core.compiler.GenJSCode$JSCodePhase.genStatOrExpr(GenJSCode.scala:1387)
	at org.scalajs.core.compiler.GenJSCode$JSCodePhase.genBlock(GenJSCode.scala:2285)
	at org.scalajs.core.compiler.GenJSCode$JSCodePhase.genStatOrExpr(GenJSCode.scala:1335)
	at org.scalajs.core.compiler.GenJSCode$JSCodePhase.genStat(GenJSCode.scala:1163)
	at org.scalajs.core.compiler.GenJSCode$JSCodePhase$$anonfun$47.apply(GenJSCode.scala:2284)
	at org.scalajs.core.compiler.GenJSCode$JSCodePhase$$anonfun$47.apply(GenJSCode.scala:2284)
	at scala.collection.immutable.List.map(List.scala:274)
	at org.scalajs.core.compiler.GenJSCode$JSCodePhase.genBlock(GenJSCode.scala:2284)
	at org.scalajs.core.compiler.GenJSCode$JSCodePhase.genStatOrExpr(GenJSCode.scala:1335)
	at org.scalajs.core.compiler.GenJSCode$JSCodePhase.genStat(GenJSCode.scala:1163)
	at org.scalajs.core.compiler.GenJSCode$JSCodePhase.org$scalajs$core$compiler$GenJSCode$JSCodePhase$$genBody$1(GenJSCode.scala:1136)
	at org.scalajs.core.compiler.GenJSCode$JSCodePhase.genMethodDef(GenJSCode.scala:1141)
	at org.scalajs.core.compiler.GenJSCode$JSCodePhase$$anonfun$genMethodWithInfoBuilder$1$$anonfun$apply$9.apply(GenJSCode.scala:820)
	at org.scalajs.core.compiler.GenJSCode$JSCodePhase$$anonfun$genMethodWithInfoBuilder$1$$anonfun$apply$9.apply(GenJSCode.scala:781)
	at org.scalajs.core.compiler.util.ScopedVar$.withScopedVars(ScopedVar.scala:35)
	at org.scalajs.core.compiler.GenJSCode$JSCodePhase$$anonfun$genMethodWithInfoBuilder$1.apply(GenJSCode.scala:781)
	at org.scalajs.core.compiler.GenJSCode$JSCodePhase$$anonfun$genMethodWithInfoBuilder$1.apply(GenJSCode.scala:737)
	at org.scalajs.core.compiler.util.ScopedVar$.withScopedVars(ScopedVar.scala:35)
	at org.scalajs.core.compiler.GenJSCode$JSCodePhase.genMethodWithInfoBuilder(GenJSCode.scala:737)
	at org.scalajs.core.compiler.GenJSCode$JSCodePhase$$anonfun$genMethod$1.apply(GenJSCode.scala:698)
	at org.scalajs.core.compiler.GenJSCode$JSCodePhase$$anonfun$genMethod$1.apply(GenJSCode.scala:698)
	at org.scalajs.core.compiler.util.ScopedVar$.withScopedVars(ScopedVar.scala:35)
	at org.scalajs.core.compiler.JSEncoding$class.withNewLocalNameScope(JSEncoding.scala:54)
	at org.scalajs.core.compiler.GenJSCode.withNewLocalNameScope(GenJSCode.scala:31)
	at org.scalajs.core.compiler.GenJSCode$JSCodePhase.genMethod(GenJSCode.scala:697)
	at org.scalajs.core.compiler.GenJSCode$JSCodePhase.org$scalajs$core$compiler$GenJSCode$JSCodePhase$$gen$1(GenJSCode.scala:347)
	at org.scalajs.core.compiler.GenJSCode$JSCodePhase$$anonfun$org$scalajs$core$compiler$GenJSCode$JSCodePhase$$gen$1$1.apply(GenJSCode.scala:332)
	at org.scalajs.core.compiler.GenJSCode$JSCodePhase$$anonfun$org$scalajs$core$compiler$GenJSCode$JSCodePhase$$gen$1$1.apply(GenJSCode.scala:332)
	at scala.collection.immutable.List.foreach(List.scala:383)
	at org.scalajs.core.compiler.GenJSCode$JSCodePhase.org$scalajs$core$compiler$GenJSCode$JSCodePhase$$gen$1(GenJSCode.scala:332)
	at org.scalajs.core.compiler.GenJSCode$JSCodePhase.genClass(GenJSCode.scala:359)
	at org.scalajs.core.compiler.GenJSCode$JSCodePhase$$anonfun$apply$1$$anonfun$apply$2.apply(GenJSCode.scala:261)
	at org.scalajs.core.compiler.GenJSCode$JSCodePhase$$anonfun$apply$1$$anonfun$apply$2.apply(GenJSCode.scala:248)
	at org.scalajs.core.compiler.util.ScopedVar$.withScopedVars(ScopedVar.scala:35)
	at org.scalajs.core.compiler.GenJSCode$JSCodePhase$$anonfun$apply$1.apply(GenJSCode.scala:248)
	at org.scalajs.core.compiler.GenJSCode$JSCodePhase$$anonfun$apply$1.apply(GenJSCode.scala:230)
	at scala.collection.immutable.List.foreach(List.scala:383)
	at org.scalajs.core.compiler.GenJSCode$JSCodePhase.apply(GenJSCode.scala:230)
	at scala.tools.nsc.Global$GlobalPhase.applyPhase(Global.scala:430)
	at scala.tools.nsc.Global$GlobalPhase$$anonfun$run$1.apply(Global.scala:397)
	at scala.tools.nsc.Global$GlobalPhase$$anonfun$run$1.apply(Global.scala:397)
	at scala.collection.Iterator$class.foreach(Iterator.scala:743)
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1174)
	at scala.tools.nsc.Global$GlobalPhase.run(Global.scala:397)
	at org.scalajs.core.compiler.GenJSCode$JSCodePhase.run(GenJSCode.scala:168)
	at scala.tools.nsc.Global$Run.compileUnitsInternal(Global.scala:1625)
	at scala.tools.nsc.Global$Run.compileUnits(Global.scala:1610)
	at scala.tools.nsc.Global$Run.compileSources(Global.scala:1605)
	at scala.tools.nsc.Global$Run.compile(Global.scala:1703)
	at xsbt.CachedCompiler0.run(CompilerInterface.scala:116)
	at xsbt.CachedCompiler0.run(CompilerInterface.scala:95)
	at xsbt.CompilerInterface.run(CompilerInterface.scala:26)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at sbt.compiler.AnalyzingCompiler.call(AnalyzingCompiler.scala:101)
	at sbt.compiler.AnalyzingCompiler.compile(AnalyzingCompiler.scala:47)
	at sbt.compiler.AnalyzingCompiler.compile(AnalyzingCompiler.scala:41)
	at sbt.compiler.AggressiveCompile$$anonfun$3$$anonfun$compileScala$1$1.apply$mcV$sp(AggressiveCompile.scala:97)
	at sbt.compiler.AggressiveCompile$$anonfun$3$$anonfun$compileScala$1$1.apply(AggressiveCompile.scala:97)
	at sbt.compiler.AggressiveCompile$$anonfun$3$$anonfun$compileScala$1$1.apply(AggressiveCompile.scala:97)
	at sbt.compiler.AggressiveCompile.sbt$compiler$AggressiveCompile$$timed(AggressiveCompile.scala:162)
	at sbt.compiler.AggressiveCompile$$anonfun$3.compileScala$1(AggressiveCompile.scala:96)
	at sbt.compiler.AggressiveCompile$$anonfun$3.apply(AggressiveCompile.scala:139)
	at sbt.compiler.AggressiveCompile$$anonfun$3.apply(AggressiveCompile.scala:86)
	at sbt.inc.IncrementalCompile$$anonfun$doCompile$1.apply(Compile.scala:38)
	at sbt.inc.IncrementalCompile$$anonfun$doCompile$1.apply(Compile.scala:36)
	at sbt.inc.IncrementalCommon.cycle(IncrementalCommon.scala:31)
	at sbt.inc.Incremental$$anonfun$1.apply(Incremental.scala:39)
	at sbt.inc.Incremental$$anonfun$1.apply(Incremental.scala:38)
	at sbt.inc.Incremental$.manageClassfiles(Incremental.scala:66)
	at sbt.inc.Incremental$.compile(Incremental.scala:38)
	at sbt.inc.IncrementalCompile$.apply(Compile.scala:26)
	at sbt.compiler.AggressiveCompile.compile2(AggressiveCompile.scala:153)
	at sbt.compiler.AggressiveCompile.compile1(AggressiveCompile.scala:70)
	at sbt.compiler.AggressiveCompile.apply(AggressiveCompile.scala:45)
	at sbt.Compiler$.apply(Compiler.scala:74)
	at sbt.Compiler$.apply(Compiler.scala:65)
	at sbt.Defaults$.sbt$Defaults$$compileTaskImpl(Defaults.scala:777)
	at sbt.Defaults$$anonfun$compileTask$1.apply(Defaults.scala:769)
	at sbt.Defaults$$anonfun$compileTask$1.apply(Defaults.scala:769)
	at scala.Function1$$anonfun$compose$1.apply(Function1.scala:47)
	at sbt.$tilde$greater$$anonfun$$u2219$1.apply(TypeFunctions.scala:40)
	at sbt.std.Transform$$anon$4.work(System.scala:63)
	at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:226)
	at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:226)
	at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:17)
	at sbt.Execute.work(Execute.scala:235)
	at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:226)
	at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:226)
	at sbt.ConcurrentRestrictions$$anon$4$$anonfun$1.apply(ConcurrentRestrictions.scala:159)
	at sbt.CompletionService$$anon$2.call(CompletionService.scala:28)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by sjrd** [comment]
Confirmed, thanks for the report. Here is smaller minimization:
```scala
class Bug {
  def doSomething(a: Int, b: Int): Unit = ()

  def bug(e: Boolean): Unit = {
    0 match {
      case 1 => (doSomething _).tupled((123, 456))
      case 2 if e =>
    }

    if (false) ()
  }
}
```
Tree after `mixin`:
```scala
[[syntax trees at end of                     mixin]] // HelloWorld.scala
package helloworld {
  class Bug extends Object {
    def doSomething(a: Int, b: Int): Unit = ();
    def bug(e: Boolean): Unit = {
      {
        case <synthetic> val x1: Int = 0;
        (x1: Int) match {
          case 1 => {
            {
              (new <$anon: Function2>(Bug.this): Function2)
            }
          }.tupled().apply(new Tuple2$mcII$sp(123, 456))
          case 2 => {
            if (e)
              ()
            else
              default4();
            scala.runtime.BoxedUnit.UNIT
          }
          case _ => default4(){
            throw new MatchError(scala.Int.box(x1))
          }
        }
      };
      ()
    };
    def <init>(): helloworld.Bug = {
      Bug.super.<init>();
      ()
    }
  }
}
```
There is indeed a `BoxedUnit.UNIT` *after* the `if/else` that calls `default4()`, which is not a pattern we recognize. I have no idea why it appears for this code, but it does.
