### ISSUE TITLE
regression in 2.12 community build (OutOfMemoryError)

### ISSUE THREAD

**Issue by SethTisue** [scala-js/scala-js#2044]
at e.g. https://scala-ci.typesafe.com/view/scala-2.12.x/job/scala-2.12.x-integrate-community-build/224/consoleFull we're seeing a lot of

```scala
[scala-js] Caused by: java.lang.OutOfMemoryError: Java heap space
[scala-js] 	at org.mozilla.javascript.ObjToIntMap.rehashTable(ObjToIntMap.java:299)
[scala-js] 	at org.mozilla.javascript.ObjToIntMap.ensureIndex(ObjToIntMap.java:383)
[scala-js] 	at org.mozilla.javascript.ObjToIntMap.put(ObjToIntMap.java:150)
[scala-js] 	at org.mozilla.javascript.CodeGenerator.addStringPrefix(CodeGenerator.java:1369)
[scala-js] 	at org.mozilla.javascript.CodeGenerator.addStringOp(CodeGenerator.java:1346)
[scala-js] 	at org.mozilla.javascript.CodeGenerator.visitExpression(CodeGenerator.java:800)
...
```

I don't know whether it's because Scala changed or because Scala.js changed; the 2.12 community build actively tracks both projects. (fwiw, in Scala world, the biggest recent change is the merging of https://github.com/scala/scala/pull/4842)

**Comment by sjrd** [comment]
The OOMs happen during the executions of the tests by Rhino.

If it comes from Scala.js, that might be because we would suddenly have so much more in the test suite that Rhino dies. On our side, my obvious suspect would be #1959, but that was already 8 days ago. It was even before #2030, the fix for the previous regression.

How much RAM does sbt receive on the community build CI? We use `-J-Xmx3G -J-XX:MaxPermSize=512M` in ours, although the big number is mostly to deal with `fullOpt` which is not used on the community build. But maybe now the Rhino run takes a lot, too. I don't know at this point.

**Comment by SethTisue** [comment]
> How much RAM does sbt receive on the community build CI

dbuild defaults to `-Xmx1536m` (see https://github.com/typesafehub/dbuild/blob/master/support/src/main/scala/com/typesafe/dbuild/support/sbt/SbtRunner.scala#L121-L131) and I don't see anything in our config that overrides that.

note that the tests pass with (I believe) the same heap size in both the 2.11.x(-jdk6) and 2.11.x-jdk8 community builds, so that suggests some 2.12 specific problem. (though if we were already near running out of memory, just about anything might tip it over, of course)

> that was already 8 days ago

in itself that doesn't mean much, because we had frozen scala-js at a fixed SHA for a while I worked on https://github.com/scala/community-builds/issues/185, only just fixed yesterday

**Comment by sjrd** [comment]
Well, apparently it was already a regression in 2.12.0-M3. I could reproduce locally on a Windows 10, capping sbt's memory at 1G, on top of our commit f6542f6ff883bc6e8eaeafa9fbe3bff2fee3272d.

2.11.7 memory history over `testSuite/test`:
![mem2 11 7-max1024m](https://cloud.githubusercontent.com/assets/535934/11309666/6f09e362-8fc5-11e5-958e-b3d43e04e431.png)
and it succeeded.

2.12.0-M3 history:
![mem2 12 0-m3-max2014m](https://cloud.githubusercontent.com/assets/535934/11309831/730feb72-8fc6-11e5-9475-b6d9bb902f49.png)
and it crashed several times with OOMs in the process, just like on the community build.

Note that 2.11.7 took 1'30'' to execute, while 2.12.0-M3 took 18 minutes or so ^^ (of course, it was locked in GC most of the time).

Really sounds like it's Scala's fault, this time.

**Comment by sjrd** [comment]
On my machine, 1536M were enough, but we can see used heaps above 1G (even right after GC):
![mem2 12 0-m3-max1536m](https://cloud.githubusercontent.com/assets/535934/11309950/32a06bb0-8fc7-11e5-982e-1c7a3dec91cb.png)

**Comment by sjrd** [comment]
2.12.0-M2 already had a behavior similar to that of 2.12.0-M3. I killed it after a couple minutes, though:
![mem2 12 0-m2-max1024m](https://cloud.githubusercontent.com/assets/535934/11310229/b35d15d6-8fc8-11e5-84e6-e7ff4727d10f.png)

**Comment by sjrd** [comment]
I guess in the short term, the easiest way to fix the community build is to allocated more memory to sbt.

**Comment by lrytz** [comment]
what builds are you running and profiling, how can i reproduce it on my machine?

**Comment by sjrd** [comment]
Just `sbt testSuite/test`

**Comment by lrytz** [comment]
I can also reproduce it in YourKit (2.11.7 vs 2.12.0-M3). I took memory snapshots for each run at this moment in the build:

```
[...]
[info]   + work (test 89)
[info]   + work (test 90)
[info]   + work (test 91)
[info]   + work (test 92)
[info]   + work (test 93)
[info]   + work (test 94)
[info]   + work (test 95)
[info]
[info] Total for suite Source Maps
[info] 384 specs, 0 failure
[...]
```

The old gen is 728 MB vs 1011 MB.

2.11.7:
![image](https://cloud.githubusercontent.com/assets/119636/11334766/950cfc2a-91d7-11e5-8220-64809c6072bb.png)

2.12.0-M3:
![image](https://cloud.githubusercontent.com/assets/119636/11334760/8ad78fc2-91d7-11e5-9123-96f5668fca81.png)

I'm not sure how much we can read from comparing the memory snapshots because they were not captured at exactly the same moment – maybe one build was just in the middle of some test with live references to additional data, while the other was just between two tests. I didn't find a way to just compare objects in the old generation. So maybe the following is misleading.

The main difference I see between the two snapshots is instances of `org.mozilla.javascript.ScriptableObject$Slot`. Looking at "Objects reachable from GC roots via strong references"
  - 2.11.7: 939k instances, 350 MB retained size
  - 2.12.0-M3: 842k instances, 685 MB retained size

The main payload of these objects seems to be Strings (1'954k instances / 325 MB vs 2'246k instances / 565 MB reachable). I see larger such strings in the 2.12 snapshots (a few 1+ MB, many with hundreds of KB).

Example from 2.11 (first few lines, the entire string is 300 KB)
```
'ScalaJSl'cl'9Lorg_scalajs_testsuite_javalib_util_ArraysTest$$anonfun$1ZWmWXU'ScalaJSl'cl'sr_AbstractFunction0$mcV$spl'callW+XR+l'	$$outer$3Z*RV¤XR'ScalaJSl'cl'9Lorg_scalajs_testsuite_javalib_util_ArraysTest$$anonfun$1l'	prototypeZ'ScalaJSl'hl'sr_AbstractFunction0$mcV$spWXR'ScalaJSl'cl'9Lorg_scalajs_testsuite_javalib_util_ArraysTest$$anonfun$1l'	prototypeS)constructorTZ'ScalaJSl'cl'9Lorg_scalajs_testsuite_javalib_util_ArraysTest$$anonfun$1R'ScalaJSl'hl'9Lorg_scalajs_testsuite_javalib_util_ArraysTest$$anonfun$1ZWmWXUV¤XR'ScalaJSl'hl'9Lorg_scalajs_testsuite_javalib_util_ArraysTest$$anonfun$1l'	prototypeZ'ScalaJSl'cl'9Lorg_scalajs_testsuite_javalib_util_ArraysTest$$anonfun$1l'	prototypeR'ScalaJSl'cl'9Lorg_scalajs_testsuite_javalib_util_ArraysTest$$anonfun$1l'	prototypel'apply__VZWmWXU+l'apply$mcV$sp__VWXRV¤XR'ScalaJSl'cl'9Lorg_scalajs_testsuite_javalib_util_ArraysTest$$anonfun$1l'	prototypel'apply$mcV$sp__VZWmWXU+l'$testSort$1__p3__T__F1__F1__F1__F3__VW)IntY'ScalaJSl'cl'sjsr_AnonFunction1WXl'init___sjs_js_Function1WWmW'x$5$2XUz'x$5Z'ScalaJSl'uIW'x$5$2XR'x$5RV¤XXY'ScalaJSl'cl'sjsr_AnonFunction1WXl'init___sjs_js_Function1WWmW'x$6$2XUz'x$6Z'ScalaJSl'uIW'x$6$2XR'ScalaJSl'newArrayObjectW'ScalaJSl'dl'Il'
getArrayOfWXYS'x$6TXRV¤XXY'ScalaJSl'cl'sjsr_AnonFunction1WXl'init___sjs_js_Function1WWmW'x$7$2XUz'x$7Z'ScalaJSl'	asArrayOfl'IW'x$7$2Y(SXR'ScalaJSl'ml'
ju_Arrays$WXl'sort__AI__VW'x$7XRV¤XXY'ScalaJSl'cl'sjsr_AnonFunction3WXl'init___sjs_js_Function3WWmW'x$8$2Y'x$9$2Y'x$10$2XUz'x$8Z'ScalaJSl'	asArrayOfl'IW'x$8$2Y(SXRz'x$9Z'ScalaJSl'uIW'x$9$2XRz'x$10Z'ScalaJSl'uIW'x$10$2XR'ScalaJSl'ml'
ju_Arrays$WXl'sort__AI__I__I__VW'x$8Y'x$9Y'x$10XRV¤XXXR+l'$testSort$1__p3__T__F1__F1__F1__F3__VW)LongY'ScalaJSl'cl'sjsr_AnonFunction1WXl'init___sjs_js_Function1WWmW'x$11$2XUz'x$11Z'ScalaJSl'uIW'x$11$2XR'ScalaJSl'cl'sjsr_RuntimeLongWXl'init___IW'x$11XRV¤XXY'ScalaJSl'cl'sjsr_AnonFunction1WXl'init___sjs_js_Function1WWmW'x$12$2XUz'x$12Z'ScalaJSl'uIW'x$12$2XR'ScalaJSl'newArrayObjectW'ScalaJSl'dl'Jl'
getArrayOfWXYS'x$12TXRV¤XXY'ScalaJSl'cl'sjsr_AnonFunction1WXl'init___sjs_js_Function1WWmW'x$13$2XUz'x$13Z'ScalaJSl'	asArrayOfl'JW'x$13$2Y(SXR'ScalaJSl'ml'
ju_Arrays$WXl'sort__AJ__VW'x$13XRV¤XXY'ScalaJSl'cl'sjsr_AnonFunction3WXl'init___sjs_js_Function3WWmW'x$14$2Y'x$15$2Y'x$16$2XUz'x$14Z'ScalaJSl'	asArrayOfl'JW'x$14$2Y(SXRz'x$15Z'ScalaJSl'uIW'x$15$2XRz'x$16Z'ScalaJSl'uIW'x$16$2XR'ScalaJSl'ml'
```

From 2.12 (also a random 300 KB string):

```
'ScalaJSl'cl'1Lorg_scalajs_testsuite_javalib_time_DurationTest$ZWmWXU'ScalaJSl'cl'$Lorg_scalajs_jasminetest_JasmineTestl'callW+XR+l'dmin$2Z*R+l'dmax$2Z*RV¤XR'ScalaJSl'cl'1Lorg_scalajs_testsuite_javalib_time_DurationTest$l'	prototypeZ'ScalaJSl'hl'$Lorg_scalajs_jasminetest_JasmineTestWXR'ScalaJSl'cl'1Lorg_scalajs_testsuite_javalib_time_DurationTest$l'	prototypeS)constructorTZ'ScalaJSl'cl'1Lorg_scalajs_testsuite_javalib_time_DurationTest$R'ScalaJSl'hl'1Lorg_scalajs_testsuite_javalib_time_DurationTest$ZWmWXUV¤XR'ScalaJSl'hl'1Lorg_scalajs_testsuite_javalib_time_DurationTest$l'	prototypeZ'ScalaJSl'cl'1Lorg_scalajs_testsuite_javalib_time_DurationTest$l'	prototypeR'ScalaJSl'cl'1Lorg_scalajs_testsuite_javalib_time_DurationTest$l'	prototypel''expectThrows__F0__s_reflect_ClassTag__VZWmW'exprY'
evidence$1XU'ScalaJSl'sl'Lorg_scalajs_testsuite_utils_ExpectExceptions$class__expectThrows__Lorg_scalajs_testsuite_utils_ExpectExceptions__F0__s_reflect_ClassTag__VW+Y'exprY'
evidence$1XRV¤XR'ScalaJSl'cl'1Lorg_scalajs_testsuite_javalib_time_DurationTest$l'	prototypel'dmin__Ljava_time_DurationZWmWXU+l'dmin$2RV¤XR'ScalaJSl'cl'1Lorg_scalajs_testsuite_javalib_time_DurationTest$l'	prototypel'dmax__Ljava_time_DurationZWmWXU+l'dmax$2RV¤XR'ScalaJSl'cl'1Lorg_scalajs_testsuite_javalib_time_DurationTest$l'	prototypel''$$anonfun$4__p2__Ljava_time_Duration__JZWmW'd$1XU'd$1l'(get__Ljava_time_temporal_TemporalUnit__JW'ScalaJSl'ml'Ljava_time_temporal_ChronoUnit$WXl'&MICROS__Ljava_time_temporal_ChronoUnitWXXRV¤XR'ScalaJSl'cl'1Lorg_scalajs_testsuite_javalib_time_DurationTest$l'	prototypel''$$anonfun$5__p2__Ljava_time_Duration__JZWmW'd$1XU'd$1l'(get__Ljava_time_temporal_TemporalUnit__JW'ScalaJSl'ml'Ljava_time_temporal_ChronoUnit$WXl'&MILLIS__Ljava_time_temporal_ChronoUnitWXXRV¤XR'ScalaJSl'cl'1Lorg_scalajs_testsuite_javalib_time_DurationTest$l'	prototypel''$$anonfun$6__p2__Ljava_time_Duration__JZWmW'd$1XU'd$1l'(get__Ljava_time_temporal_TemporalUnit__JW'ScalaJSl'ml'Ljava_time_temporal_ChronoUnit$WXl''MINUTES__Ljava_time_temporal_ChronoUnitWXXRV¤XR'ScalaJSl'cl'1Lorg_scalajs_testsuite_javalib_time_DurationTest$l'	prototypel''$$anonfun$7__p2__Ljava_time_Duration__JZWmW'd$1XU'd$1l'(get__Ljava_time_temporal_TemporalUnit__JW'ScalaJSl'ml'Ljava_time_temporal_ChronoUnit$WXl'%HOURS__Ljava_time_temporal_ChronoUnitWXXRV¤XR'ScalaJSl'cl'1Lorg_scalajs_testsuite_javalib_time_DurationTest$l'	prototypel''$$anonfun$8__p2__Ljava_time_Duration__JZWmW'd$1XU'd$1l'(get__Ljava_time_temporal_TemporalUnit__JW'ScalaJSl'ml'Ljava_time_temporal_ChronoUnit$WXl',HALF$undDAYS__Ljava_time_temporal_ChronoUnitWXXRV¤XR'ScalaJSl'cl'1Lorg_scalajs_testsuite_javalib_time_DurationTest$l'	prototypel''$$anonfun$9__p2__Ljava_time_Duration__JZWmW'd$1XU'd$1l'(get__Ljava_time_temporal_TemporalUnit__JW'ScalaJSl'ml'Ljava_time_temporal_ChronoUnit$WXl'$DAYS__Ljava_time_temporal_ChronoUnitWXXRV¤XR'ScalaJSl'cl'1Lorg_scalajs_testsuite_javalib_time_DurationTest$l'	prototypel'($$anonfun$10__p2__Ljava_time_Duration__JZWmW'd$1XU'd$1l'(get__Ljava_time_temporal_TemporalUnit__JW'ScalaJSl'ml'Ljava_time_temporal_ChronoUnit$WXl'%WEEKS__Ljava_time_temporal_ChronoUnitWXXRV¤XR'ScalaJSl'cl'1Lorg_scalajs_testsuite_javalib_time_DurationTest$l'	prototypel'($$anonfun$11__p2__Ljava_time_Duration__JZWmW'd$1XU'd$1l'(get__Ljava_time_temporal_TemporalUnit__JW'ScalaJSl'ml'Ljava_time_temporal_ChronoUnit$WXl'&MONTHS__Ljava_time_temporal_ChronoUnitWXXRV¤XR'ScalaJSl'cl'1Lorg_scalajs_testsuite_javalib_time_DurationTest$l'	prototypel'($$anonfun$12__p2__Ljava_time_Duration__JZWmW'd$1XU'd$1l'(get__Ljava_time_temporal_TemporalUnit__JW'ScalaJSl'ml'Ljava_time_temporal_ChronoUnit$WXl'%YEARS__Ljava_time_temporal_ChronoUnitWXXRV¤XR'ScalaJSl'cl'1Lorg_scalajs_testsuite_javalib_time_DurationTest$l'	prototypel'($$anonfun$13__p2__Ljava_time_Duration__JZWmW'd$1XU'd$1l'(get__Ljava_time_temporal_TemporalUnit__JW'ScalaJSl'ml'Ljava_time_temporal_ChronoUnit$WXl''DECADES__Ljava_time_temporal_ChronoUnitWXXRV¤XR'ScalaJSl'cl'1Lorg_scalajs_testsuite_javalib_time_DurationTest$l'	prototypel'($$anonfun$14__p2__Ljava_time_Duration__JZWmW'd$1XU'd$1l'(get__Ljava_time_temporal_TemporalUnit__JW'ScalaJSl'ml'Ljava_time_temporal_ChronoUnit$WXl')CENTURIES__Ljava_time_temporal_ChronoUnitWXXRV¤XR'ScalaJSl'cl'1Lorg_scalajs_testsuite_javalib_time_DurationTest$l'	prototypel'($$anonfun$15__p2__Ljava_time_Duration__JZWmW'd$1XU'd$1l'(get__Ljava_time_temporal_TemporalUnit__JW'ScalaJSl'ml'Ljava_time_temporal_ChronoUnit$WXl')MILLENNIA__Ljava_time_temporal_ChronoUnitWXXRV¤XR'ScalaJSl'cl'1Lorg_scalajs_testsuite_javalib_time_DurationTest$l'	prototypel'($$anonfun$16__p2__Ljava_time_Duration__JZWmW'd$1XU'd$1l'(get__Ljava_time_temporal_TemporalUnit__JW'ScalaJSl'ml'Ljava_time_temporal_ChronoUnit$WXl'$ERAS__Ljava_time_temporal_ChronoUnitWXXRV¤XR'ScalaJSl'cl'1Lorg_scalajs_testsuite_javalib_time_DurationTest$l'	prototypel'($$anonfun$17__p2__Ljava_time_Duration__JZWmW'd$1XU'd$1l'(get__Ljava_time_temporal_TemporalUnit__JW'ScalaJSl'ml'Ljava_time_temporal_ChronoUnit$WXl''FOREVER__Ljava_time_temporal_ChronoUnitWXXRV¤XR'ScalaJSl'cl'1Lorg_scalajs_testsuite_javalib_time_DurationTest$l'	prototypel''$$anonfun$3__p2__Ljava_time_Duration__VZWmW'dXU+l''expectThrows__F0__s_reflect_ClassTag__VW'ScalaJSl'cl'sjsr_AnonFunction0WXl'init___sjs_js_Function0WWmW'$thisY'dXUWmWXU'$thisl''$$anonfun$4__p2__Ljava_time_Duration__JW'dXRV¤XRV¤XW+Y'dXXY'ScalaJSl'ml's_reflect_ClassTag$WXl'#apply__jl_Class__s_reflect_ClassTagW'ScalaJSl'dl'4Ljava_time_temporal_UnsupportedTemporalTypeExceptionl'
getClassOfWXXXR+l''expectThrows__F0__s_reflect_ClassTag__VW'ScalaJSl'cl'sjsr_AnonFunction0WXl'init___sjs_js_Function0WWmW'this$2Y'dXUWmWXU'this$2l''$$anonfun$5__p2__Ljava_time_Duration__JW'dXRV¤XRV¤XW+Y'dXXY'ScalaJSl'ml's_reflect_ClassTag$WXl'#apply__jl_Class__s_reflect_ClassTagW'ScalaJSl'dl'4Ljava_time_temporal_UnsupportedTemporalTypeExceptionl'
getClassOfWXXXR+l''expectThrows__F0__s_reflect_ClassTag__VW'ScalaJSl'cl'sjsr_AnonFunction0WXl'init___sjs_js_Function0WWmW'this$3Y'dXUWmWXU'this$3l''$$anonfun$6__p2__Ljava_time_Duration__JW'dXRV¤XRV¤XW+Y'dXXY'ScalaJSl'ml's_reflect_ClassTag$WXl'#apply__jl_Class__s_reflect_ClassTagW'ScalaJSl'dl'4Ljava_time_temporal_UnsupportedTemporalTypeExceptionl'
getClassOfWXXXR+l''expectThrows__F0__s_reflect_ClassTag__VW'ScalaJSl'cl'sjsr_AnonFunction0WXl'init___sjs_js_Function0WWmW'this$4Y'dXUWmWXU'this$4l''$$anonfun$7__p2__Ljava_time_Duration__JW'dXRV¤XRV¤XW+Y'dXXY'ScalaJSl'ml's_reflect_ClassTag$WXl'#apply__jl_Class__s_reflect_ClassTagW'ScalaJSl'dl'4Ljava_time_temporal_UnsupportedTemporalTypeExceptionl'
getClassOfWXXXR+l''expectThrows__F0__s_reflect_ClassTag__VW'ScalaJSl'cl'sjsr_AnonFunction0WXl'init___sjs_js_Function0WWmW'this$5Y'dXUWmWXU'this$5l''$$anonfun$8__p2__Ljava_time_Duration__JW'dXRV¤XRV¤XW+Y'dXXY'ScalaJSl'ml's_reflect_ClassTag$WXl'#apply__jl_Class__s_reflect_ClassTagW'ScalaJSl'dl'4Ljava_time_temporal_UnsupportedTemporalTypeExceptionl'
getClassOfWXXXR+l''expectThrows__F0__s_reflect_ClassTag__VW'ScalaJSl'cl'sjsr_AnonFunction0WXl'init___sjs_js_Function0WWmW'this$6Y'dXUWmWXU'this$6l''$$anonfun$9__p2__Ljava_time_Duration__JW'dXRV¤XRV¤XW+Y'dXXY'ScalaJSl'ml's_reflect_ClassTag$WXl'#apply__jl_Class__s_reflect_ClassTagW'ScalaJSl'dl'4Ljava_time_temporal_UnsupportedTemporalTypeExceptionl'
getClassOfWXXXR+l''expectThrows__F0__s_reflect_ClassTag__VW'ScalaJSl'cl'sjsr_AnonFunction0WXl'init___sjs_js_Function0WWmW'this$7Y'dXUWmWXU'this$7l'($$anonfun$10__p2__Ljava_time_Duration__JW'dXRV¤XRV¤XW+Y'dXXY'ScalaJSl'ml's_reflect_ClassTag$WXl'#apply__jl_Class__s_reflect_ClassTagW'ScalaJSl'dl'4Ljava_time_temporal_UnsupportedTemporalTypeExceptionl'
getClassOfWXXXR+l''expectThrows__F0__s_reflect_ClassTag__VW'ScalaJSl'cl'sjsr_AnonFunction0WXl'init___sjs_js_Function0WWmW'this$8Y'dXUWmWXU'this$8l'($$anonfun$11__p2__Ljava_time_Duration__JW'dXRV¤XRV¤XW+Y'dXXY'ScalaJSl'ml's_reflect_ClassTag$WXl'#apply__jl_Class__s_reflect_ClassTagW'ScalaJSl'dl'4Ljava_time_temporal_UnsupportedTemporalTypeExceptionl'
```

Let me know if any of that rings a bell.

**Comment by sjrd** [comment]
That does not ring any bell to me.

It looks like this is some sort of internal representation of Rhino for the scripts that we give it (readable bits are definitely identifiers in the JS code produced by Scala.js), but that's about all I can infer from that right now.

**Comment by lrytz** [comment]
To narrow the search space I tried to build with `-Ydelambdafy:method`, but that fails with lots of assertion errors like this one:

```
java.lang.AssertionError: assertion failed: ClassBType.info not yet assigned: Lorg/scalajs/testsuite/jsinterop/ExportsTest$;
	at scala.tools.nsc.backend.jvm.BTypes$ClassBType.info(BTypes.scala:844)
	at scala.tools.nsc.backend.jvm.BTypes$ClassBType.isNestedClass(BTypes.scala:907)
	at scala.tools.nsc.backend.jvm.BTypes$ClassBType.enclosingNestedClassesChain(BTypes.scala:910)
	at scala.tools.nsc.backend.jvm.BTypes$ClassBType.scala$tools$nsc$backend$jvm$BTypes$ClassBType$$$anonfun$32(BTypes.scala:912)
	at scala.tools.nsc.backend.jvm.BTypes$ClassBType.scala$tools$nsc$backend$jvm$BTypes$ClassBType$$$anonfun$32$adapted(BTypes.scala:910)
	at scala.tools.nsc.backend.jvm.BTypes$ClassBType.enclosingNestedClassesChain(BTypes.scala:910)
	at scala.tools.nsc.backend.jvm.BTypes$ClassBType.scala$tools$nsc$backend$jvm$BTypes$ClassBType$$$anonfun$32(BTypes.scala:912)
	at scala.tools.nsc.backend.jvm.BTypes$ClassBType.scala$tools$nsc$backend$jvm$BTypes$ClassBType$$$anonfun$32$adapted(BTypes.scala:910)
	at scala.tools.nsc.backend.jvm.BTypes$ClassBType.enclosingNestedClassesChain(BTypes.scala:910)
	at scala.tools.nsc.backend.jvm.BTypes$ClassBType.scala$tools$nsc$backend$jvm$BTypes$ClassBType$$$anonfun$32(BTypes.scala:912)
	at scala.tools.nsc.backend.jvm.BTypes$ClassBType.scala$tools$nsc$backend$jvm$BTypes$ClassBType$$$anonfun$32$adapted(BTypes.scala:910)
	at scala.tools.nsc.backend.jvm.BTypes$ClassBType.enclosingNestedClassesChain(BTypes.scala:910)
	at scala.tools.nsc.backend.jvm.BCodeHelpers.scala$tools$nsc$backend$jvm$BCodeHelpers$$$anonfun$13(BCodeHelpers.scala:209)
	at scala.tools.nsc.backend.jvm.BCodeHelpers.addInnerClassesASM(BCodeHelpers.scala:209)
	at scala.tools.nsc.backend.jvm.BCodeSkelBuilder$PlainSkelBuilder.genPlainClass(BCodeSkelBuilder.scala:133)
	at scala.tools.nsc.backend.jvm.GenBCode$BCodePhase$Worker1.visit(GenBCode.scala:189)
	at scala.tools.nsc.backend.jvm.GenBCode$BCodePhase$Worker1.scala$tools$nsc$backend$jvm$GenBCode$BCodePhase$Worker1$$$anonfun$1(GenBCode.scala:138)
	at scala.tools.nsc.backend.jvm.GenBCode$BCodePhase$Worker1.run(GenBCode.scala:138)
	at scala.tools.nsc.backend.jvm.GenBCode$BCodePhase.buildAndSendToDisk(GenBCode.scala:367)
	at scala.tools.nsc.backend.jvm.GenBCode$BCodePhase.run(GenBCode.scala:336)
	at scala.tools.nsc.Global$Run.compileUnitsInternal(Global.scala:1505)
	at scala.tools.nsc.Global$Run.compileUnits(Global.scala:1490)
	at scala.tools.nsc.Global$Run.compileSources(Global.scala:1485)
	at scala.tools.nsc.Global$Run.compile(Global.scala:1586)
	at xsbt.CachedCompiler0.run(CompilerInterface.scala:116)
```

**Comment by SethTisue** [comment]
> I guess in the short term, the easiest way to fix the community build is to allocated more memory to sbt

done in https://github.com/scala/community-builds/pull/190 . `-Xmx2048m` was enough.

**Comment by SethTisue** [comment]
we actually got an OutOfMemoryError yesterday in the 2.11.x-jdk8 community build too: https://scala-ci.typesafe.com/job/scala-2.11.x-jdk8-integrate-community-build/111/consoleFull

**Comment by gzm0** [comment]
@SethTisue how is the community build doing w.r.t. to memory? Can we close this?

**Comment by SethTisue** [comment]
I've been on leave for the last few months, but I'm back now and should be able to take a look soon.

**Comment by SethTisue** [comment]
I don't believe we've had any recent failures in this area.
