### ISSUE TITLE
Timeouts prevent long-running tests

### ISSUE THREAD

**Issue by japgolly** [scala-js/scala-js#2167]
I wanted to run a very thorough test that I expected to take a few hours. I came back to my PC later to find it died after 408 seconds (output below).

I don't see any settings in `PhantomJSEnv` or anywhere else that I can use to disable/extend these internal timeouts, hence this issue.

Output:
```
[trace] Stack trace suppressed: run last webapp-client/test:testOnly for the full output.
[error] Could not run test abc.webapp.client.app.abc.LogicPropTest: org.scalajs.jsenv.ComJSEnv$ComClosedException: JSCom has been closed
[trace] Stack trace suppressed: run last webapp-client/test:testOnly for the full output.
[error] (webapp-client/test:testOnly) org.scalajs.jsenv.ComJSEnv$ComClosedException: Phantom.js isn't connected
[error] Total time: 408 s, completed 12/01/2016 10:08:44 AM

webapp-client> last webapp-client/test:testOnly
[debug] Running TaskDef(abc.webapp.client.app.abc.LogicPropTest, org.scalajs.testadapter.FingerprintSerializers$DeserializedSubclassFingerprint@18cd756b, false, [SuiteSelector])
org.scalajs.jsenv.ComJSEnv$ComClosedException: JSCom has been closed
	at org.scalajs.jsenv.phantomjs.PhantomJSEnv$ComPhantomRunner.receiveFrag(PhantomJSEnv.scala:287)
	at org.scalajs.jsenv.phantomjs.PhantomJSEnv$ComPhantomRunner.loop$1(PhantomJSEnv.scala:258)
	at org.scalajs.jsenv.phantomjs.PhantomJSEnv$ComPhantomRunner.receive(PhantomJSEnv.scala:273)
	at org.scalajs.testadapter.ComUtils$.receiveResponse(ComUtils.scala:42)
	at org.scalajs.testadapter.ComUtils$.receiveLoop(ComUtils.scala:21)
	at org.scalajs.testadapter.ComUtils$.receiveLoop(ComUtils.scala:16)
	at org.scalajs.testadapter.ScalaJSTask.execute(ScalaJSTask.scala:62)
	at sbt.TestRunner.runTest$1(TestFramework.scala:76)
	at sbt.TestRunner.run(TestFramework.scala:85)
	at sbt.TestFramework$$anon$2$$anonfun$$init$$1$$anonfun$apply$8.apply(TestFramework.scala:202)
	at sbt.TestFramework$$anon$2$$anonfun$$init$$1$$anonfun$apply$8.apply(TestFramework.scala:202)
	at sbt.TestFramework$.sbt$TestFramework$$withContextLoader(TestFramework.scala:185)
	at sbt.TestFramework$$anon$2$$anonfun$$init$$1.apply(TestFramework.scala:202)
	at sbt.TestFramework$$anon$2$$anonfun$$init$$1.apply(TestFramework.scala:202)
	at sbt.TestFunction.apply(TestFramework.scala:207)
	at sbt.Tests$.sbt$Tests$$processRunnable$1(Tests.scala:239)
	at sbt.Tests$$anonfun$makeSerial$1.apply(Tests.scala:245)
	at sbt.Tests$$anonfun$makeSerial$1.apply(Tests.scala:245)
	at sbt.std.Transform$$anon$3$$anonfun$apply$2.apply(System.scala:44)
	at sbt.std.Transform$$anon$3$$anonfun$apply$2.apply(System.scala:44)
	at sbt.std.Transform$$anon$4.work(System.scala:63)
	at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:226)
	at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:226)
	at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:17)
	at sbt.Execute.work(Execute.scala:235)
	at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:226)
	at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:226)
	at sbt.ConcurrentRestrictions$$anon$4$$anonfun$1.apply(ConcurrentRestrictions.scala:159)
	at sbt.CompletionService$$anon$2.call(CompletionService.scala:28)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
[error] Could not run test abc.webapp.client.app.abc.LogicPropTest: org.scalajs.jsenv.ComJSEnv$ComClosedException: JSCom has been closed
org.scalajs.jsenv.ComJSEnv$ComClosedException: Phantom.js isn't connected
	at org.scalajs.jsenv.phantomjs.PhantomJSEnv$ComPhantomRunner.receive(PhantomJSEnv.scala:249)
	at org.scalajs.testadapter.ComUtils$.receiveResponse(ComUtils.scala:42)
	at org.scalajs.testadapter.ComUtils$.receiveLoop(ComUtils.scala:30)
	at org.scalajs.testadapter.ScalaJSRunner$$anonfun$8$$anonfun$apply$3.apply$mcV$sp(ScalaJSRunner.scala:165)
	at org.scalajs.testadapter.ScalaJSRunner$$anonfun$8$$anonfun$apply$3.apply(ScalaJSRunner.scala:164)
	at org.scalajs.testadapter.ScalaJSRunner$$anonfun$8$$anonfun$apply$3.apply(ScalaJSRunner.scala:164)
	at scala.util.Try$.apply(Try.scala:161)
	at org.scalajs.testadapter.ScalaJSRunner$$anonfun$8.apply(ScalaJSRunner.scala:164)
	at org.scalajs.testadapter.ScalaJSRunner$$anonfun$8.apply(ScalaJSRunner.scala:164)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:244)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:244)
	at scala.collection.immutable.List.foreach(List.scala:318)
	at scala.collection.TraversableLike$class.map(TraversableLike.scala:244)
	at scala.collection.AbstractTraversable.map(Traversable.scala:105)
	at org.scalajs.testadapter.ScalaJSRunner.stopSlaves(ScalaJSRunner.scala:164)
	at org.scalajs.testadapter.ScalaJSRunner.done(ScalaJSRunner.scala:77)
	at sbt.Defaults$$anonfun$allTestGroupsTask$1$$anonfun$16.apply(Defaults.scala:566)
	at sbt.Defaults$$anonfun$allTestGroupsTask$1$$anonfun$16.apply(Defaults.scala:564)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:244)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:244)
	at scala.collection.immutable.Map$Map1.foreach(Map.scala:109)
	at scala.collection.TraversableLike$class.map(TraversableLike.scala:244)
	at scala.collection.AbstractTraversable.map(Traversable.scala:105)
	at sbt.Defaults$$anonfun$allTestGroupsTask$1.apply(Defaults.scala:564)
	at sbt.Defaults$$anonfun$allTestGroupsTask$1.apply(Defaults.scala:562)
	at scala.Function1$$anonfun$compose$1.apply(Function1.scala:47)
	at sbt.$tilde$greater$$anonfun$$u2219$1.apply(TypeFunctions.scala:40)
	at sbt.std.Transform$$anon$4.work(System.scala:63)
	at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:226)
	at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:226)
	at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:17)
	at sbt.Execute.work(Execute.scala:235)
	at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:226)
	at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:226)
	at sbt.ConcurrentRestrictions$$anon$4$$anonfun$1.apply(ConcurrentRestrictions.scala:159)
	at sbt.CompletionService$$anon$2.call(CompletionService.scala:28)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by sjrd** [comment]
The timeout you're experiencing is happening when we wait for all spawned VMs to properly terminate. At this point, in theory all tests are already done :-s

As a workaround, you can use Java reflection to change the value of this `val`: https://github.com/scala-js/scala-js/blob/e51625a62faf464f5a68fdc97e6670757c3971c9/test-adapter/src/main/scala/org/scalajs/sbttestadapter/package.scala#L15

**Comment by japgolly** [comment]
Sorry I don't quite follow. My understanding (just through experience) is that SJS spawns VMs to run multiple tests, and each test gets a fixed amount of time or the whole VM is killed. That doesn't seem to align with what you're saying... did I misunderstand?

The `val` you referenced is only 5 seconds where as in my example it's killed after 400 sec. My intuition from usage is that tests exceeding 5min are normally killed.

**Comment by sjrd** [comment]
There is no timeout per-test. They're all `Duration.Infinity`.

The only timeouts we have are when launching the vm (before running any test, to make sure we could establish the connection with the vm) and when shutting the down  (after all the tests are done). In particular, I am pretty sure we don't have any timeout in the ballpark of 400 seconds.

**Comment by japgolly** [comment]
Oh I see. In that case, (unless there's something else killing the tests), it sounds like SJS might be spuriously thinking tests are finished when they're still running. That could be one of these probably: SJS JS envs, SJS's SBT test interface, μTest. I'll have to look into it further.

**Comment by japgolly** [comment]
I believe this should be resolved by #2226. Happy to close if you are.

**Comment by sjrd** [comment]
Possibly, indeed. I guess we can close. Can Cane reopened if it turns out not to be fixed.

**Comment by japgolly** [comment]
:+1:
