### ISSUE TITLE
Regression: fastOptJS fails with Illegal classpath entry: <non existent path> after upgrading from 0.6.5 to 0.6.6

### ISSUE THREAD

**Issue by ngbinh** [scala-js/scala-js#2198]
Here is the error message when I run `sbt clean fastOptJS`

```scala
java.lang.RuntimeException: Illegal classpath entry: /path-to-project/Web/
target/web/classes/main
        at scala.sys.package$.error(package.scala:27)
        at org.scalajs.sbtplugin.ScalaJSPluginInternal$$anonfun$org$scalajs$sbtplugin$ScalaJSPluginIntern
al$$collectFromClasspath$1.apply(ScalaJSPluginInternal.scala:322)
        at org.scalajs.sbtplugin.ScalaJSPluginInternal$$anonfun$org$scalajs$sbtplugin$ScalaJSPluginIntern
al$$collectFromClasspath$1.apply(ScalaJSPluginInternal.scala:309)
        at scala.collection.immutable.List.foreach(List.scala:318)
        at org.scalajs.sbtplugin.ScalaJSPluginInternal$.org$scalajs$sbtplugin$ScalaJSPluginInternal$$coll
ectFromClasspath(ScalaJSPluginInternal.scala:309)
        at org.scalajs.sbtplugin.ScalaJSPluginInternal$$anonfun$37.apply(ScalaJSPluginInternal.scala:464)
        at org.scalajs.sbtplugin.ScalaJSPluginInternal$$anonfun$37.apply(ScalaJSPluginInternal.scala:463)
        at scala.Function1$$anonfun$compose$1.apply(Function1.scala:47)
        at sbt.$tilde$greater$$anonfun$$u2219$1.apply(TypeFunctions.scala:40)
        at sbt.std.Transform$$anon$4.work(System.scala:63)
        at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:226)
        at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:226)
        at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:17)
        at sbt.Execute.work(Execute.scala:235)
        at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:226)
        at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:226)
        at sbt.ConcurrentRestrictions$$anon$4$$anonfun$1.apply(ConcurrentRestrictions.scala:159)
        at sbt.CompletionService$$anon$2.call(CompletionService.scala:28)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
```

note that `show Web/compile:fullClasspath` does contain non-existent `/path-to-project/Web/target/web/classes/main`

@sjrd suggest a fix by adding 
```scala
fullClasspath in (Web, Compile) ~= { _.filter(_.data.exists) }
```
works though.

**Comment by sjrd** [comment]
@gzm0 I guess we previously tolerated non-existent entries on the classpath, and ignored them. But now we don't and we crash.

**Comment by gzm0** [comment]
Yep... Indeed. The ever eternal "cannot determine if this is a directory if it doesn't exist" hit again.
