### ISSUE TITLE
Wrong compilation of the operation on shapeless HList

### ISSUE THREAD

**Issue by eugengarkusha** [scala-js/scala-js#2307]
The following(slightly simplified)snippet compiles and works as expected in scala but after compilation to scalaJs and launching I see the following exception:
```org.scalajs.jsenv.ExternalJSEnv$NonZeroExitException: Node.js exited with code 8```

```scala
import shapeless._, record._, syntax.singleton._

trait Crud[L <: HList, K, R] extends Serializable {
  type Out <: HList
  type V
  def apply(t: L, u: V=>R): (Out, V)
}

class UnsafeCrud(i: Int) extends Crud[HList, Any, Any] {
  type V = Any
  type Out = HList

  def unsafeUpdate(l: HList, i: Int, f: Any => Any): (HList, Any) = {
    def loop(l: HList, i: Int, prefix: List[Any]): (List[Any], HList, Any) =
      l match {
        case hd :: (tl: HList) => if (i == 0) (prefix, f(hd) :: tl, hd) else loop(tl, i - 1, hd :: prefix)
        case _ => throw new Exception("...")
      }

    val (prefix, suffix, v) = loop(l, i, Nil)
    prefix.foldLeft(suffix) { (tl, hd) => hd :: tl } -> v
  }

  def apply(l: HList, f: V => Any): (HList, Any) = unsafeUpdate(l, i, f)
}
type R = Record.`'i -> Int, 's -> String, 'c -> Char, 'j -> Int`.T
val r = 'i ->> 10 :: 's ->> "foo" :: 'c ->> 'x' :: 'j ->> 42 :: HNil

new UnsafeCrud(0).asInstanceOf[Crud[R,Witness.`'i`.T, String]].apply(r, _ => "newStr")
```

**Comment by sjrd** [comment]
What dependency do I need to compile the snippet and reproduce the issue?
Ideally, could you provide a minimal repo with an sbt build that reproduces the issue?

**Comment by eugengarkusha** [comment]
sjrd, sure, will provide the repo soon!
Also gzm0 advised me to  wrap the code with try catch and print the exception, so i will report the result of this action too.
Thanks!

**Comment by eugengarkusha** [comment]
@sjrd 
here it is (see readme for some details)
https://github.com/eugengarkusha/scalaJsIssue-2307

I have noticed that in the given setup this code causes the following exception:
java.lang.RuntimeException: There were linking errors

**Comment by sjrd** [comment]
The linking error is caused because you're not using a `%%%` dependency.

**Comment by eugengarkusha** [comment]
fixed this, thanks!
now I see the error I have told about.

Here is full listing:

```scala
[info] Loading project definition from /private/tmp/scalaJsIssue-2307/project
[info] Set current project to scjs (in build file:/private/tmp/scalaJsIssue-2307/)
[info] Updating {file:/private/tmp/scalaJsIssue-2307/}scalajsissue-2307...
[info] Resolving org.eclipse.jetty#jetty-continuation;8.1.16.v20140903 ...
[info] Done updating.
[info] Compiling 3 Scala sources to /private/tmp/scalaJsIssue-2307/target/scala-2.11/classes...
[info] Fast optimizing /private/tmp/scalaJsIssue-2307/target/scala-2.11/scjs-fastopt.js
[info] Running issue2307.JS
[error] /private/tmp/scalaJsIssue-2307/target/scala-2.11/scjs-fastopt.js:1203
[error]             break matchEnd5
[error]                   ^^^^^^^^^
[error] 
[error] SyntaxError: Undefined label 'matchEnd5'
[error]     at exports.runInThisContext (vm.js:53:16)
[error]     at Module._compile (module.js:387:25)
[error]     at Object.Module._extensions..js (module.js:422:10)
[error]     at Module.load (module.js:357:32)
[error]     at Function.Module._load (module.js:314:12)
[error]     at Module.require (module.js:367:17)
[error]     at require (internal/module.js:16:19)
[error]     at [stdin]:38:1
[error]     at Object.exports.runInThisContext (vm.js:54:17)
[error]     at Object.<anonymous> ([stdin]-wrapper:6:22)
org.scalajs.jsenv.ExternalJSEnv$NonZeroExitException: Node.js exited with code 1
        at org.scalajs.jsenv.ExternalJSEnv$AbstractExtRunner.waitForVM(ExternalJSEnv.scala:110)
        at org.scalajs.jsenv.ExternalJSEnv$ExtRunner.run(ExternalJSEnv.scala:159)
        at org.scalajs.sbtplugin.ScalaJSPluginInternal$.org$scalajs$sbtplugin$ScalaJSPluginInternal$$jsRun(ScalaJSPluginInternal.scala:639)
        at org.scalajs.sbtplugin.ScalaJSPluginInternal$$anonfun$56$$anonfun$apply$40$$anonfun$apply$41.apply(ScalaJSPluginInternal.scala:699)
        at org.scalajs.sbtplugin.ScalaJSPluginInternal$$anonfun$56$$anonfun$apply$40$$anonfun$apply$41.apply(ScalaJSPluginInternal.scala:693)
        at scala.Function1$$anonfun$compose$1.apply(Function1.scala:47)
[trace] Stack trace suppressed: run last compile:run for the full output.
[error] (compile:run) org.scalajs.jsenv.ExternalJSEnv$NonZeroExitException: Node.js exited with code 1

```

**Comment by gzm0** [comment]
Hahahaha, @sjrd do I remember a discussion we had about the IR checker checking labels? :P

**Comment by sjrd** [comment]
> Hahahaha, @sjrd do I remember a discussion we had about the IR checker checking labels? :P

Well it *did* catch it as a `SyntaxError`, as anticipated ^^

**Comment by sjrd** [comment]
It works fine if I disable the optimizer. So @gzm0 it wouldn't have been caught by the IR checker anyway.

**Comment by sjrd** [comment]
Note-to-self: here is a reproduction of the bug that does not depend on Shapeless:
```scala

class UnsafeCrud(i: Int) {
  def unsafeUpdate(l: List[Any], i: Int, f: Any => Any): (List[Any], Any) = {
    def loop(l: List[Any], i: Int, prefix: List[Any]): (List[Any], List[Any], Any) = {
      l match {
        case hd :: (tl: List[Any]) =>
          if (i == 0) (prefix, f(hd) :: tl, hd)
          else loop(tl, i - 1, hd :: prefix)
        case _ => throw new Exception("...")
      }
    }

    val (prefix, suffix, v) = loop(l, i, Nil)
    prefix.foldLeft(suffix) { (tl, hd) => hd :: tl } -> v
  }

  def apply(l: List[Any], f: Any => Any): (List[Any], Any) = unsafeUpdate(l, i, f)
}

object HelloWorld extends js.JSApp {
  def main() {
    val r = 10 :: "foo" :: 'x' :: 42 :: Nil
    println(new UnsafeCrud(0).apply(r, _ => "newStr"))
  }
}
```

**Comment by eugengarkusha** [comment]
@sjrd thanks much!
Looking forward for 0.69 to come out! ))

**Comment by sjrd** [comment]
> Looking forward for 0.69 to come out! ))

As a work around to immediately fix your issue, you can add `@noinline` on `def unsafeUpdate`

**Comment by eugengarkusha** [comment]
Great , it works!
Thanks again!
