### ISSUE TITLE
`test:loadedTestFrameworks` fails when a specific jsDependency is set via a "classic" dependency

### ISSUE THREAD

**Issue by olivierguerriat** [scala-js/scala-js#2322]
Hello,

I wanted to start testing our ScalaJS project but faced the following error:

```
[error] (fooJS/test:loadedTestFrameworks) java.lang.AssertionError: assertion failed
[error] Total time: 34 s, completed Apr 8, 2016 11:36:02 AM
> last fooJS/test:loadedTestFrameworks
java.lang.AssertionError: assertion failed
	at scala.Predef$.assert(Predef.scala:165)
	at org.scalajs.sbtplugin.FrameworkDetector.detect(FrameworkDetector.scala:74)
	at org.scalajs.sbtplugin.ScalaJSPluginInternal$$anonfun$59.apply(ScalaJSPluginInternal.scala:736)
	at org.scalajs.sbtplugin.ScalaJSPluginInternal$$anonfun$59.apply(ScalaJSPluginInternal.scala:719)
	at scala.Function1$$anonfun$compose$1.apply(Function1.scala:47)
	at sbt.$tilde$greater$$anonfun$$u2219$1.apply(TypeFunctions.scala:40)
	at sbt.std.Transform$$anon$4.work(System.scala:63)
	at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:226)
	at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:226)
	at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:17)
	at sbt.Execute.work(Execute.scala:235)
	at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:226)
	at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:226)
	at sbt.ConcurrentRestrictions$$anon$4$$anonfun$1.apply(ConcurrentRestrictions.scala:159)
	at sbt.CompletionService$$anon$2.call(CompletionService.scala:28)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
[error] (fooJS/test:loadedTestFrameworks) java.lang.AssertionError: assertion failed
```
After a lot of debugging, I still don't understand why it occurs but I managed to isolate the cause in a small project. Unfortunately, I was only able to reproduce it with [the professional version of Kendo UI](http://www.telerik.com/kendo-ui), which I can't freely distribute. You'll [find everything (except the faulty js file) in this archive](https://github.com/scala-js/scala-js/files/210376/js_dep_bug_stub.zip): a project where it works as expected (_ok_direct_) and a set of two projects (_main_ and _dep_) that trigger the above error (in _ko_via_dep_).

The error seems to occur when a specific js dependency (Kendo UI Pro) is added (with `ProvidedJS`) via a dependency of the cross project. The console buffer used to detect test frameworks is curiously empty in that precise case. I searched the (huge) JS file to see if it messed with the console but couldn't find anything weird.

Another thing I noticed: `foo-test-jsdeps.js` and `foo-test-fastopt.js` are exactly the same in both cases (direct or via a dependency).

Any ideas of why this might fail are welcome. If you are willing to investigate this further, please contact me directly so that we can arrange access to the problematic file.

Thank you very much,

Kind regards,

Olivier

**Comment by gzm0** [comment]
From what I can see so far, everything is indeed hinting that Kendo UI is messing with the console. (I guess you have seen that the assertion checks the number of returned lines from the `FrameworkDetector`).

I guess the next step would be to manually run a piece of JavaScript in the fully prepped `JSEnv` and see if `console.log` works.

Essentially, in your sbt project, try to redefine the run task:

```scala
run := {
  import org.scalajs.core.tools.io.MemVirtualJSFile
  val env = loadedJSEnv.value
  val code = new MemVirtualJSFile("code.js")
  code.content = """console.log("hello world")"""
  env.jsRunner(code).run(streams.value.log, scalaJSConsole.value)
}
```

then `run` in your sbt shell. If you see "hello world" in the output, there is a problem with how we invoke the `FrameworkDetector`. If you do not see "hello world" in the output (and removing the KendoUI dependency makes it appear), there is a problem with KendoUI.

Please let us know what this does.

**Comment by olivierguerriat** [comment]
Thank you for your help! I unfortunately can't get your redefined task to work. I added `import org.scalajs.sbtplugin.Implicits._` to fix a type mismatch for the `Logger`, but I have no idea how to fix the following error I get while loading sbt:

```
References to undefined settings: 

  root/*:scalaJSConsole from root/*:run (/…/ok_direct/build.sbt:38)

  root/*:loadedJSEnv from root/*:run (/…/ok_direct/build.sbt:38)
 
	at sbt.Init$class.Uninitialized(Settings.scala:270)
	at sbt.Def$.Uninitialized(Def.scala:10)
	at sbt.Init$class.delegate(Settings.scala:191)
	at sbt.Def$.delegate(Def.scala:10)
	at sbt.Init$class.compiled(Settings.scala:138)
	at sbt.Def$.compiled(Def.scala:10)
	at sbt.Init$class.make(Settings.scala:144)
	at sbt.Def$.make(Def.scala:10)
	at sbt.Load$.apply(Load.scala:135)
	at sbt.Load$.defaultLoad(Load.scala:36)
	at sbt.BuiltinCommands$.doLoadProject(Main.scala:481)
	at sbt.BuiltinCommands$$anonfun$loadProjectImpl$2.apply(Main.scala:475)
	at sbt.BuiltinCommands$$anonfun$loadProjectImpl$2.apply(Main.scala:475)
	at sbt.Command$$anonfun$applyEffect$1$$anonfun$apply$2.apply(Command.scala:59)
	at sbt.Command$$anonfun$applyEffect$1$$anonfun$apply$2.apply(Command.scala:59)
	at sbt.Command$$anonfun$applyEffect$2$$anonfun$apply$3.apply(Command.scala:61)
	at sbt.Command$$anonfun$applyEffect$2$$anonfun$apply$3.apply(Command.scala:61)
	at sbt.Command$.process(Command.scala:93)
	at sbt.MainLoop$$anonfun$1$$anonfun$apply$1.apply(MainLoop.scala:98)
	at sbt.MainLoop$$anonfun$1$$anonfun$apply$1.apply(MainLoop.scala:98)
	at sbt.State$$anon$1.process(State.scala:184)
	at sbt.MainLoop$$anonfun$1.apply(MainLoop.scala:98)
	at sbt.MainLoop$$anonfun$1.apply(MainLoop.scala:98)
	at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:17)
	at sbt.MainLoop$.next(MainLoop.scala:98)
	at sbt.MainLoop$.run(MainLoop.scala:91)
	at sbt.MainLoop$$anonfun$runWithNewLog$1.apply(MainLoop.scala:70)
	at sbt.MainLoop$$anonfun$runWithNewLog$1.apply(MainLoop.scala:65)
	at sbt.Using.apply(Using.scala:24)
	at sbt.MainLoop$.runWithNewLog(MainLoop.scala:65)
	at sbt.MainLoop$.runAndClearLast(MainLoop.scala:48)
	at sbt.MainLoop$.runLoggedLoop(MainLoop.scala:32)
	at sbt.MainLoop$.runLogged(MainLoop.scala:24)
	at sbt.StandardMain$.runManaged(Main.scala:53)
	at sbt.xMain.run(Main.scala:28)
	at xsbt.boot.Launch$$anonfun$run$1.apply(Launch.scala:109)
	at xsbt.boot.Launch$.withContextLoader(Launch.scala:128)
	at xsbt.boot.Launch$.run(Launch.scala:109)
	at xsbt.boot.Launch$$anonfun$apply$1.apply(Launch.scala:35)
	at xsbt.boot.Launch$.launch(Launch.scala:117)
	at xsbt.boot.Launch$.apply(Launch.scala:18)
	at xsbt.boot.Boot$.runImpl(Boot.scala:41)
	at xsbt.boot.Boot$.main(Boot.scala:17)
	at xsbt.boot.Boot.main(Boot.scala)
```

This probably is easy to fix, but I'm not that familiar with sbt inner working. `build.sbt:38` is the first line of your snippet: `run := {`. I have the feeling I don't put it at the correct place and thus executed too early. Where should it be? Maybe it's different since it's a cross project?

I also thought Kendo UI messing with the console was the culprit, but how to explain that the exact same JS file doesn't cause any trouble when imported directly?

**Comment by gzm0** [comment]
Ah, yes. The tasks were not scope properly. Do:

```scala
run := {
  import org.scalajs.core.tools.io.MemVirtualJSFile
  val env = (loadedJSEnv in Compile).value
  val code = new MemVirtualJSFile("code.js")
  code.content = """console.log("hello world")"""
  env.jsRunner(code).run(streams.value.log, (scalaJSConsole in Compile).value)
}
```

**Comment by gzm0** [comment]
Also, you should put it in the settings of `fooJS` not in the base settings.

**Comment by ngbinh** [comment]
We are seeing the same problem with Google ReCapcha JS files. @gzm0 is there a quick work around?

**Comment by olivierguerriat** [comment]
Thank you for the fix. It does display "hello world" when importing the JS file directly (in _ok_direct_) but doesn't display it when importing via a dependency (in _ko_via_dep/main_).

**Comment by gzm0** [comment]
Ok, I see the problem. This seems to have something to do with how we handle / cache JS files out of Jars: In one case, we actually have the JS file on disk (*ok_direct* case), in the other one, we only have it in the jar (I assume you `publishLocal`) and pull it in via an in-memory file.
I assume (from your build files) that you are running all this with Rhino.
This shouldn't make a difference, but it seems that somewhere it does. Could you quickly try and downgrade to `0.6.5`? (There was a major refactoring in how file caching happens in this version. If it works with `0.6.5`, this is likely the culprit).

**Comment by gzm0** [comment]
Can you also confirm, that this doesn't happen with your stub? (I can't reproduce the faulty behavior based on your Jar).

**Comment by gzm0** [comment]
Also @ngbinh, you mean you see the same exception, or the exact same issue with then you depend on the same file differently?
We currently do not have a workaround unfortunately.

**Comment by olivierguerriat** [comment]
It indeed seems to be linked to the refactor: I downgraded to `0.6.5` and confirm that I can't reproduce this problem (it works as expected).

A few additional notes:
- I can't reproduce the problem either with my stub (it is linked somehow to the Kendo UI file).
- I think all my tests are using PhantomJS as I need the dom and read that it was better all around.

**Comment by gzm0** [comment]
Ok, so it seems this is a bug in Scala.js. Just two quick questions:

- How large is the real Kendo UI file?
- Does it contain any non ASCII characters?

Sorry I'm so slow on this, don't have full-time resources to dedicate unfortunately...

**Comment by olivierguerriat** [comment]
The file is 7,1 MB (2,7 MB minified, and I can reproduce the bug with both versions) and it does contain those non ASCII characters (inside JavaScript strings): `ÂÁÚÏÎφ€`.

**Comment by gzm0** [comment]
Ok. So either of this could be the culprit. If you have time, you can try and test with a stub that:

- Is large (> 2.7 MB).
- Contains non-ASCII.

Otherwise I'm going to do it as soon as I find some time.

**Comment by olivierguerriat** [comment]
Unfortunately, in my limited testing, I couldn't reproduce this bug with a huge js file (20+ MB) nor a small one containing non-ASCII characters.

**Comment by olivierguerriat** [comment]
I tried to downgrade my projects but faced this bug once again, providing a new data point: it is reproducible with ScalaJS `0.6.5` when using PhantomJS: `jsEnv in Test := PhantomJSEnv().value` (you were right, my previous tests were using Rhino).

**Comment by gzm0** [comment]
Ok. It seems we won't get around testing the actual file. Can you ping me privately on gitter?

**Comment by gzm0** [comment]
Just as an update: I haven't forgotten about this but wasn't able to allocate the 2-3 hours it will surely take me to debug this.

If anyone else makes progress on this, any information would be greatly appreciated.

**Comment by gzm0** [comment]
Ok. I can confirm that this happens when the JS file is fetched through a JAR. I could split the working example into two sbt projects (in the same build) and would only get failures when setting `exportJars := true`.

However, I'm getting:

```
[error] (fooJS/test:loadedTestFrameworks) org.scalajs.jsenv.ExternalJSEnv$NonZeroExitException: PhantomJS exited with code 2
```

This is very likely due to different PhantomJS versions. @olivierguerriat what are you using? I'm using `1.9.0` (outdated).

**Comment by olivierguerriat** [comment]
Thank you for investigating. I'm using PhantomJS `2.0.0`.

**Comment by gzm0** [comment]
I can reproduce this with PhantomJS `2.1.1`. My suspicion is, that the difference between how we include dependencies that are stored in memory (i.e. in a Jar) and dependencies that are stored on disk matter (see [relevant code][1]).

[1]: https://github.com/scala-js/scala-js/blob/3a6562e81e129b43676e092078a9b01e41726a3e/js-envs/src/main/scala/org/scalajs/jsenv/phantomjs/PhantomJSEnv.scala#L330-342

**Comment by gzm0** [comment]
I suspect #2376 to be the culprit of this.

**Comment by gzm0** [comment]
Just a follow up on this (sorry for being so slow): The fix to #2376 is in, so if you feel adventurous, you could test against the snapshot version.

**Comment by olivierguerriat** [comment]
I did a few (limited) tests with the snapshot version and it does work :) Thank you for fixing this!

**Comment by gzm0** [comment]
No Problem. Thanks for bearing with us.
