### ISSUE TITLE
java.lang.IllegalStateException: Linker used concurrently

### ISSUE THREAD

**Issue by Atry** [scala-js/scala-js#2363]
I have a project that use Play and Scala.js together.

It throws a `java.lang.IllegalStateException: Linker used concurrently` when I run `sbt package`.

I guess the usage of `scalaJSLinkedFile` cause this problem (https://github.com/Atry/scalajs-linker-used-concurrently-bug/blob/master/build.sbt).

```
git clone https://github.com/Atry/scalajs-linker-used-concurrently-bug.git
cd scalajs-linker-used-concurrently-bug
sbt package
```

```
[info] Loading global plugins from /Users/twer/.sbt/0.13/plugins
[info] Loading project definition from /private/tmp/scalajs-linker-used-concurrently-bug/project
[info] Updating {file:/private/tmp/scalajs-linker-used-concurrently-bug/project/}scalajs-linker-used-concurrently-bug-build...
[info] Resolving org.fusesource.jansi#jansi;1.4 ...
[info] Done updating.
[info] Set current project to scalajs-linker-used-concurrently-bug (in build file:/private/tmp/scalajs-linker-used-concurrently-bug/)
[info] Updating {file:/private/tmp/scalajs-linker-used-concurrently-bug/}js...
[info] Resolving org.scala-lang#scala-compiler;2.11.8 ...
[info] Updating {file:/private/tmp/scalajs-linker-used-concurrently-bug/}scalajs-linker-used-concurrently-bug...
[info] Updating {file:/private/tmp/scalajs-linker-used-concurrently-bug/}js...
[info] Resolving org.eclipse.jetty#jetty-continuation;8.1.16.v20140903 ...
[info] Done updating.
[info] Resolving org.scala-lang#scala-reflect;2.11.8 ...
[info] Compiling 1 Scala source to /private/tmp/scalajs-linker-used-concurrently-bug/js/target/scala-2.11/classes...
[info] Resolving org.eclipse.jetty#jetty-continuation;8.1.16.v20140903 ...
[info] Done updating.
[info] Resolving com.typesafe.play#play_2.11;2.4.2 ...
[info] Compiling 1 Scala source to /private/tmp/scalajs-linker-used-concurrently-bug/js/target/scala-2.11/classes...
[info] Resolving jline#jline;2.12.1 ...
[info] Done updating.
[info] Packaging /private/tmp/scalajs-linker-used-concurrently-bug/js/target/scala-2.11/js_sjs0.6_2.11-0.1-SNAPSHOT.jar ...
[info] Done packaging.
[info] Fast optimizing /private/tmp/scalajs-linker-used-concurrently-bug/js/target/scala-2.11/js-fastopt.js
[info] Fast optimizing /private/tmp/scalajs-linker-used-concurrently-bug/js/target/scala-2.11/js-fastopt.js
java.lang.IllegalStateException: Linker used concurrently
	at org.scalajs.core.tools.linker.Linker.guard(Linker.scala:56)
	at org.scalajs.core.tools.linker.Linker.link(Linker.scala:47)
	at org.scalajs.core.tools.linker.ClearableLinker$$anonfun$link$1.apply(ClearableLinker.scala:51)
	at org.scalajs.core.tools.linker.ClearableLinker$$anonfun$link$1.apply(ClearableLinker.scala:51)
	at org.scalajs.core.tools.linker.ClearableLinker.linkerOp(ClearableLinker.scala:62)
	at org.scalajs.core.tools.linker.ClearableLinker.link(ClearableLinker.scala:51)
	at org.scalajs.sbtplugin.ScalaJSPluginInternal$$anonfun$org$scalajs$sbtplugin$ScalaJSPluginInternal$$scalaJSStageSettings$4$$anonfun$apply$6$$anonfun$apply$7.apply(ScalaJSPluginInternal.scala:241)
	at org.scalajs.sbtplugin.ScalaJSPluginInternal$$anonfun$org$scalajs$sbtplugin$ScalaJSPluginInternal$$scalaJSStageSettings$4$$anonfun$apply$6$$anonfun$apply$7.apply(ScalaJSPluginInternal.scala:229)
	at sbt.FileFunction$$anonfun$cached$1.apply(Tracked.scala:235)
	at sbt.FileFunction$$anonfun$cached$1.apply(Tracked.scala:235)
	at sbt.FileFunction$$anonfun$cached$2$$anonfun$apply$3$$anonfun$apply$4.apply(Tracked.scala:249)
	at sbt.FileFunction$$anonfun$cached$2$$anonfun$apply$3$$anonfun$apply$4.apply(Tracked.scala:245)
	at sbt.Difference.apply(Tracked.scala:224)
	at sbt.Difference.apply(Tracked.scala:206)
	at sbt.FileFunction$$anonfun$cached$2$$anonfun$apply$3.apply(Tracked.scala:245)
	at sbt.FileFunction$$anonfun$cached$2$$anonfun$apply$3.apply(Tracked.scala:244)
	at sbt.Difference.apply(Tracked.scala:224)
	at sbt.Difference.apply(Tracked.scala:200)
	at sbt.FileFunction$$anonfun$cached$2.apply(Tracked.scala:244)
	at sbt.FileFunction$$anonfun$cached$2.apply(Tracked.scala:242)
	at org.scalajs.sbtplugin.ScalaJSPluginInternal$$anonfun$org$scalajs$sbtplugin$ScalaJSPluginInternal$$scalaJSStageSettings$4$$anonfun$apply$6.apply(ScalaJSPluginInternal.scala:246)
	at org.scalajs.sbtplugin.ScalaJSPluginInternal$$anonfun$org$scalajs$sbtplugin$ScalaJSPluginInternal$$scalaJSStageSettings$4$$anonfun$apply$6.apply(ScalaJSPluginInternal.scala:227)
	at scala.Function1$$anonfun$compose$1.apply(Function1.scala:47)
	at sbt.$tilde$greater$$anonfun$$u2219$1.apply(TypeFunctions.scala:40)
	at sbt.std.Transform$$anon$4.work(System.scala:63)
	at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:228)
	at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:228)
	at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:17)
	at sbt.Execute.work(Execute.scala:237)
	at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:228)
	at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:228)
	at sbt.ConcurrentRestrictions$$anon$4$$anonfun$1.apply(ConcurrentRestrictions.scala:159)
	at sbt.CompletionService$$anon$2.call(CompletionService.scala:28)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
[error] (js/compile:fastOptJS) java.lang.IllegalStateException: Linker used concurrently
java.lang.IllegalStateException: Linker used concurrently
	at org.scalajs.core.tools.linker.Linker.guard(Linker.scala:56)
	at org.scalajs.core.tools.linker.Linker.link(Linker.scala:47)
	at org.scalajs.core.tools.linker.ClearableLinker$$anonfun$link$1.apply(ClearableLinker.scala:51)
	at org.scalajs.core.tools.linker.ClearableLinker$$anonfun$link$1.apply(ClearableLinker.scala:51)
	at org.scalajs.core.tools.linker.ClearableLinker.linkerOp(ClearableLinker.scala:62)
	at org.scalajs.core.tools.linker.ClearableLinker.link(ClearableLinker.scala:51)
	at org.scalajs.sbtplugin.ScalaJSPluginInternal$$anonfun$org$scalajs$sbtplugin$ScalaJSPluginInternal$$scalaJSStageSettings$4$$anonfun$apply$6$$anonfun$apply$7.apply(ScalaJSPluginInternal.scala:241)
	at org.scalajs.sbtplugin.ScalaJSPluginInternal$$anonfun$org$scalajs$sbtplugin$ScalaJSPluginInternal$$scalaJSStageSettings$4$$anonfun$apply$6$$anonfun$apply$7.apply(ScalaJSPluginInternal.scala:229)
	at sbt.FileFunction$$anonfun$cached$1.apply(Tracked.scala:235)
	at sbt.FileFunction$$anonfun$cached$1.apply(Tracked.scala:235)
	at sbt.FileFunction$$anonfun$cached$2$$anonfun$apply$3$$anonfun$apply$4.apply(Tracked.scala:249)
	at sbt.FileFunction$$anonfun$cached$2$$anonfun$apply$3$$anonfun$apply$4.apply(Tracked.scala:245)
	at sbt.Difference.apply(Tracked.scala:224)
	at sbt.Difference.apply(Tracked.scala:206)
	at sbt.FileFunction$$anonfun$cached$2$$anonfun$apply$3.apply(Tracked.scala:245)
	at sbt.FileFunction$$anonfun$cached$2$$anonfun$apply$3.apply(Tracked.scala:244)
	at sbt.Difference.apply(Tracked.scala:224)
	at sbt.Difference.apply(Tracked.scala:200)
	at sbt.FileFunction$$anonfun$cached$2.apply(Tracked.scala:244)
	at sbt.FileFunction$$anonfun$cached$2.apply(Tracked.scala:242)
	at org.scalajs.sbtplugin.ScalaJSPluginInternal$$anonfun$org$scalajs$sbtplugin$ScalaJSPluginInternal$$scalaJSStageSettings$4$$anonfun$apply$6.apply(ScalaJSPluginInternal.scala:246)
	at org.scalajs.sbtplugin.ScalaJSPluginInternal$$anonfun$org$scalajs$sbtplugin$ScalaJSPluginInternal$$scalaJSStageSettings$4$$anonfun$apply$6.apply(ScalaJSPluginInternal.scala:227)
	at scala.Function1$$anonfun$compose$1.apply(Function1.scala:47)
	at sbt.$tilde$greater$$anonfun$$u2219$1.apply(TypeFunctions.scala:40)
	at sbt.std.Transform$$anon$4.work(System.scala:63)
	at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:228)
	at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:228)
	at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:17)
	at sbt.Execute.work(Execute.scala:237)
	at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:228)
	at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:228)
	at sbt.ConcurrentRestrictions$$anon$4$$anonfun$1.apply(ConcurrentRestrictions.scala:159)
	at sbt.CompletionService$$anon$2.call(CompletionService.scala:28)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
[error] (js/compile:fastOptJS) java.lang.IllegalStateException: Linker used concurrently
[error] Total time: 10 s, completed Apr 27, 2016 2:56:14 PM
```

**Comment by sjrd** [comment]
Apparently, `sbt-buildinfo` does not correctly deduplicate concurrent accesses to a given task or setting. And it tries to "execute" `scalaJSLinkedFile` twice concurrently, which is not permitted.

You should not refer to `scalaJSLinkedFile` from your build info anyways. You should use the `artifactPath in fastOptJS` setting (and `artifactPath in packageJSDependencies`), which does trigger the actual compilation, and is therefore safe to use concurrently.

**Comment by gzm0** [comment]
Hmmm... this is not good at all :( We should probably file this as a bug against sbt.

**Comment by sjrd** [comment]
It's [`sbt-buildinfo`](https://github.com/sbt/sbt-buildinfo), not sbt itself, AFAICT.

**Comment by Atry** [comment]
Why shouldn't I use `scalaJSLinkedFile` ?

**Comment by sjrd** [comment]
Because it's a task that takes time to do what it does, and most importantly its results change from one run to the next. But for your build info you want something stable instead.

**Comment by Atry** [comment]
It seems that `js-fastopt.js` file does not generated if I change every `scalaJSLinkedFile` to `artifactPath in fastOptJS`, which did trigger the actual compilation on my machine.

**Comment by sjrd** [comment]
That's what `resourceGenerators` are for.

**Comment by sjrd** [comment]
@Atry Is this issue still relevant? Can we close it?

**Comment by dwijnand** [comment]
Btw the issue in sbt-buildinfo was fixed.
