### ISSUE TITLE
Named export def inherited from traits crash the compiler

### ISSUE THREAD

**Issue by sjrd** [scala-js/scala-js#2440]
I found this while trying to strengthen the tests while fixing #2437. It turns out this does not even work in 2.11:
```scala
  @Test def name_exports_inherited_from_traits(): Unit = {
    import js.Dynamic.{literal => lit}

    trait FooNamedTrait {
      @JSExportNamed("bar1")
      def bar(x: Int, y: Int): Int = x + y

      @JSExportNamed("bar2")
      @JSExport
      def bar(x: Int = 1)(y: Int = x)(z: Int = y): Int = x + y + z
    }

    class BarNamedFromTrait extends FooNamedTrait

    val bar = (new BarNamedFromTrait).asInstanceOf[js.Dynamic]

    assertEquals(3, bar.bar1(lit(x = 1, y = 2)))
    if (hasCompliantAsInstanceOfs)
      assertThrows(classOf[Exception], bar.bar1(lit(x = 1))) // missing arg
    assertEquals(3, bar.bar2(lit()))
    assertEquals(6, bar.bar2(lit(x = 2)))
    assertEquals(5, bar.bar2(lit(y = 2)))
    assertEquals(4, bar.bar2(lit(y = 2, z = 1)))
    assertEquals(6, bar.bar(2))
    assertEquals(8, bar.bar(2,3))
  }
```
The stack trace points to [this line](https://github.com/scala-js/scala-js/blob/c51ce4ca53f70e300d2f99d40654aefec2ef97af/compiler/src/main/scala/org/scalajs/core/compiler/GenJSExports.scala#L126):
```
scala.MatchError: org.scalajs.testsuite.jsinterop.ExportsTest$FooNamedTrait$1$class.$js$exported$meth|1(ExportsTest$BarNamedFromTrait$1.this, namedArgs) (of class scala.reflect.internal.Trees$Apply)
        at org.scalajs.core.compiler.GenJSExports$JSExportsPhase$class.genNamedExporterDef(GenJSExports.scala:126)
        at org.scalajs.core.compiler.GenJSCode$JSCodePhase.genNamedExporterDef(GenJSCode.scala:123)
        at org.scalajs.core.compiler.GenJSCode$JSCodePhase.org$scalajs$core$compiler$GenJSCode$JSCodePhase$$gen$1(GenJSCode.scala:390)
        at org.scalajs.core.compiler.GenJSCode$JSCodePhase$$anonfun$org$scalajs$core$compiler$GenJSCode$JSCodePhase$$gen$1$1.apply(GenJSCode.scala:377)
        at org.scalajs.core.compiler.GenJSCode$JSCodePhase$$anonfun$org$scalajs$core$compiler$GenJSCode$JSCodePhase$$gen$1$1.apply(GenJSCode.scala:377)
        at scala.collection.immutable.List.foreach(List.scala:381)
        at org.scalajs.core.compiler.GenJSCode$JSCodePhase.org$scalajs$core$compiler$GenJSCode$JSCodePhase$$gen$1(GenJSCode.scala:377)
        at org.scalajs.core.compiler.GenJSCode$JSCodePhase.genClass(GenJSCode.scala:404)
        ...
```

**Comment by sjrd** [comment]
Fixing this appears to be non-trivial, and since [we've deprecated `@JSExportNamed`](https://github.com/scala-js/scala-js/issues/2442), I'll close this as won't fix.
