### ISSUE TITLE
Native interface problem in FastOpt.

### ISSUE THREAD

**Issue by andreaTP** [scala-js/scala-js#2463]
I'm writing the interface to WeakMap and I have this code:
```scala
import scala.scalajs.js

object Main extends js.JSApp {

  def main() = {
    val wm = WeakMap[String, String]()
    wm.set("ciao", "1")

    println("GET: "+wm.get("ciao"))
    println("HAS: "+wm.has("ciao"))
  }
}

import js.annotation.JSBracketAccess

@js.native
sealed trait WeakMap[K <: AnyRef, V] extends js.Any {

  @JSBracketAccess
  def delete(key: K): Unit = js.native

  @JSBracketAccess
  def has(key: K): Boolean = js.native

  @JSBracketAccess
  def get(key: K): V = js.native

  @JSBracketAccess
  def set(key: K, value: V): Unit = js.native

}

object WeakMap {
  def empty[K <: AnyRef, V]: WeakMap[K, V] = (new Object).asInstanceOf[WeakMap[K, V]]

  def apply[K <: AnyRef, V](): WeakMap[K, V] = empty[K, V]
}
```

it happens that running this on node provide:
in FullOptJS, as expected:
```
GET: 1
HAS: true
```
in FastOptJS, it throw with:
```
GET: 1
Error
    at $c_sjsr_UndefinedBehaviorError.$c_jl_Throwable.fillInStackTrace__jl_Throwable (/home/andrea/workspace/hasBug/target/scala-2.11/hasbug-fastopt.js:1672:14)
    at $c_sjsr_UndefinedBehaviorError.fillInStackTrace__jl_Throwable (/home/andrea/workspace/hasBug/target/scala-2.11/hasbug-fastopt.js:2747:67)
    at $c_sjsr_UndefinedBehaviorError.$c_jl_Throwable.init___T__jl_Throwable (/home/andrea/workspace/hasBug/target/scala-2.11/hasbug-fastopt.js:1688:8)
    at $c_sjsr_UndefinedBehaviorError.init___T__jl_Throwable (/home/andrea/workspace/hasBug/target/scala-2.11/hasbug-fastopt.js:2754:52)
    at $c_sjsr_UndefinedBehaviorError.init___jl_Throwable (/home/andrea/workspace/hasBug/target/scala-2.11/hasbug-fastopt.js:2750:67)
    at $throwClassCastException (/home/andrea/workspace/hasBug/target/scala-2.11/hasbug-fastopt.js:196:46)
    at $asBoolean (/home/andrea/workspace/hasBug/target/scala-2.11/hasbug-fastopt.js:595:5)
    at $uZ (/home/andrea/workspace/hasBug/target/scala-2.11/hasbug-fastopt.js:638:12)
    at $c_LMain$.main__V (/home/andrea/workspace/hasBug/target/scala-2.11/hasbug-fastopt.js:1585:24)
    at $c_LMain$.$$js$exported$meth$main__O (/home/andrea/workspace/hasBug/target/scala-2.11/hasbug-fastopt.js:1591:8)
```

this behavior is the same on 0.6.9 and on .10 SNAPSHOT.

**Comment by sjrd** [comment]
`fastOptJS` holds the truth. You should not use `@JSBracketAccess` on all these methods. As documented [on this page](https://www.scala-js.org/doc/interoperability/facade-types.html), `@JSBracketAccess` is for methods that should be replaced by bracket access.

In other words, `wm.has("ciao")` means in JS `vm["ciao"]`, which is clearly not what you want.

**Comment by andreaTP** [comment]
still not convinced by the fact that the behavior is different in this case....

... probably my ignorance but if I remove ```@JSBracketAccess``` to the ```has``` method linker complain  with ```TypeError: wm.has is not a function```

**Comment by sjrd** [comment]
That's because `wm` doesn't have a `has` method. And that's because you're not *actually* creating a `WeakMap`. Your creating some empty object:
```scala
object WeakMap {
  def empty[K <: AnyRef, V]: WeakMap[K, V] = (new Object).asInstanceOf[WeakMap[K, V]]

  def apply[K <: AnyRef, V](): WeakMap[K, V] = empty[K, V]
}
```
So you're not facading `WeakMap` at all, here. You're somehow creating a JS object and you're trying to use it as if it were a `WeakMap`. Which it is not.

What is it you are trying to do, exactly? Use genuine `WeakMap`s, or polyfill them, or some combination thereof?

**Comment by andreaTP** [comment]
ok, thanks! this is my fault.
