### ISSUE TITLE
Method overriding leads to AssertionError in the compiler

### ISSUE THREAD

**Issue by glmars** [scala-js/scala-js#2547]
Base class has method witch has parameter with default value. I try override this method, but lost default value for parameter and, unfortunately, I receive very uninformative compiler error :(

Anybody can reproduce this with such test:
```scala
  @Test
  def overrideNativeMethod: Unit = {
    """
    @js.native
    class NativeBase extends js.Object {
		def add(option: js.Any = js.native): js.Any = js.native 
 	}
    @ScalaJSDefined
    class Derived extends NativeBase {
		override def add(option: js.Any): js.Any = super.add(option) 
    }
    """ succeeds
  }
```

Result:
```

java.lang.AssertionError: assertion failed: 
  
     while compiling: newSource1.scala
        during phase: jscode
     library version: version 2.11.8
    compiler version: version 2.11.8
  reconstructed args: -bootclasspath C:\Users\someuser\.m2\repository\org\scala-lang\scala-library\2.10.3\scala-library-2.10.3.jar -classpath C:\Users\some\.m2\repository\org\scala-js\scalajs-library_2.10\0.6.10\scalajs-library_2.10-0.6.10.jar -d C:\work\testprojects\scala-js\target

  last tree to typer: Ident(option)
       tree position: line 11 of newSource1.scala
            tree tpe: scala.scalajs.js.Any
              symbol: value option
   symbol definition: option: scala.scalajs.js.Any (a TermSymbol)
      symbol package: <empty>
       symbol owners: value option -> method add -> class Derived
           call site: class Derived in package <empty>

<Cannot read source file>

	at scala.tools.nsc.Global.assert(Global.scala:261)
	at scala.tools.nsc.Global.assert(Global.scala:264)
	at org.scalajs.core.compiler.GenJSExports$JSExportsPhase$$anonfun$genPrepareArgs$2.apply(GenJSExports.scala:670)
	at org.scalajs.core.compiler.GenJSExports$JSExportsPhase$$anonfun$genPrepareArgs$2.apply(GenJSExports.scala:630)
	at scala.collection.TraversableLike$WithFilter$$anonfun$map$2.apply(TraversableLike.scala:683)
	at scala.collection.immutable.List.foreach(List.scala:381)
	at scala.collection.TraversableLike$WithFilter.map(TraversableLike.scala:682)
	at org.scalajs.core.compiler.GenJSExports$JSExportsPhase$class.genPrepareArgs(GenJSExports.scala:630)
	at org.scalajs.core.compiler.GenJSExports$JSExportsPhase$class.genApplyForSymNonJSSuperCall(GenJSExports.scala:605)
	at org.scalajs.core.compiler.GenJSExports$JSExportsPhase$class.org$scalajs$core$compiler$GenJSExports$JSExportsPhase$$genApplyForSym(GenJSExports.scala:546)
	at org.scalajs.core.compiler.GenJSExports$JSExportsPhase$ExportedSymbol.genBody(GenJSExports.scala:730)
	at org.scalajs.core.compiler.GenJSExports$JSExportsPhase$class.org$scalajs$core$compiler$GenJSExports$JSExportsPhase$$genExportSameArgc(GenJSExports.scala:412)
...
```

**Comment by sjrd** [comment]
Thanks for the report. The compiler should indeed give a compile error, instead of crashing.
