### ISSUE TITLE
providedJS fails to load specific file. with name "bn.js"

### ISSUE THREAD

**Issue by mandar-k** [scala-js/scala-js#2581]
I am trying to load some js files into my  project for srp implementation there are several files which I was able to load with providedJS but when I do add bn.js
 jsDependencies ++= clientJSDeps.map(ProvidedJS / _)

val clientJSDeps = Seq(
    "prolog_parser.js",  "validator.js", " bn.js" , "srp-client.js",  "sjcl.js", "srp.js", "bitArray.js", 
    "codecHex.js", "codecString.js", "sha256.js", "sha512.js", "aes.js", "random.js"
  )
it results in error stack 

[trace] Stack trace suppressed: run last client/compile:resolvedJSDependencies for the full output.
[error] (client/compile:resolvedJSDependencies) org.scalajs.core.tools.jsdep.JSLibResolveException: Some references to JS libraries could not be resolved:
[error] - Missing JS library:  bn.js
[error]   originating from: client:compile
[trace] Stack trace suppressed: run last client/compile:resolvedJSDependencies for the full output.
[error] (client/compile:resolvedJSDependencies) org.scalajs.core.tools.jsdep.JSLibResolveException: Some references to JS libraries could not be resolved:
[error] - Missing JS library:  bn.js
[error]   originating from: client:compile
[error] application -

! @71addb76f - Internal server error, for (GET) [/] ->

play.sbt.PlayExceptions$UnexpectedException: Unexpected exception[JSLibResolveException: Some references to JS libraries could not be resolved:
- Missing JS library:  bn.js
  originating from: client:compile
]
        at play.sbt.run.PlayReload$$anonfun$taskFailureHandler$1.apply(PlayReload.scala:51)
        at play.sbt.run.PlayReload$$anonfun$taskFailureHandler$1.apply(PlayReload.scala:44)
        at scala.Option.map(Option.scala:145)
        at play.sbt.run.PlayReload$.taskFailureHandler(PlayReload.scala:44)
        at play.sbt.run.PlayReload$.compileFailure(PlayReload.scala:40)
        at play.sbt.run.PlayReload$$anonfun$compile$2$$anonfun$apply$3.apply(PlayReload.scala:20)
        at play.sbt.run.PlayReload$$anonfun$compile$2$$anonfun$apply$3.apply(PlayReload.scala:20)
        at scala.util.Either$LeftProjection.map(Either.scala:377)
        at play.sbt.run.PlayReload$$anonfun$compile$2.apply(PlayReload.scala:20)
        at play.sbt.run.PlayReload$$anonfun$compile$2.apply(PlayReload.scala:18)
Caused by: org.scalajs.core.tools.jsdep.JSLibResolveException: Some references to JS libraries could not be resolved:
- Missing JS library:  bn.js
  originating from: client:compile

        at org.scalajs.core.tools.jsdep.DependencyResolver$.resolveAllResourceNames(DependencyResolver.scala:84)
        at org.scalajs.core.tools.jsdep.DependencyResolver$.resolveDependencies(DependencyResolver.scala:25)
        at org.scalajs.sbtplugin.ScalaJSPluginInternal$$anonfun$42.apply(ScalaJSPluginInternal.scala:545)
        at org.scalajs.sbtplugin.ScalaJSPluginInternal$$anonfun$42.apply(ScalaJSPluginInternal.scala:513)
        at scala.Function1$$anonfun$compose$1.apply(Function1.scala:47)
        at sbt.$tilde$greater$$anonfun$$u2219$1.apply(TypeFunctions.scala:40)
        at sbt.std.Transform$$anon$4.work(System.scala:63)
        at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:228)
        at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:228)
        at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:17)

**Comment by gzm0** [comment]
There is a space in front of the `b`.
