### ISSUE TITLE
CommonJSModule + jsdom env crashes

### ISSUE THREAD

**Issue by sjrd** [scala-js/scala-js#2635]
```
> set scalaJSModuleKind in testingExample := ModuleKind.CommonJSModule
> testingExample/test
[info] Updating {file:/localhome/doeraene/projects/scalajs/}testingExample...
[info] Resolving org.eclipse.jetty#jetty-continuation;8.1.16.v20140903 ...
[info] Done updating.
[info] Compiling 1 Scala source to /localhome/doeraene/projects/scalajs/examples/testing/target/scala-2.11/classes...
[info] Compiling 4 Scala sources to /localhome/doeraene/projects/scalajs/examples/testing/target/scala-2.11/test-classes...
[info] Fast optimizing /localhome/doeraene/projects/scalajs/examples/testing/target/scala-2.11/testing-test-fastopt.js
[error] Error: Uncaught [ReferenceError: exports is not defined]
[error]     at reportException (/localhome/doeraene/projects/scalajs/node_modules/jsdom/lib/jsdom/living/helpers/runtime-script-errors.js:58:24)
[error]     at processJavaScript (/localhome/doeraene/projects/scalajs/node_modules/jsdom/lib/jsdom/living/nodes/HTMLScriptElement-impl.js:130:7)
[error]     at HTMLScriptElementImpl._eval (/localhome/doeraene/projects/scalajs/node_modules/jsdom/lib/jsdom/living/nodes/HTMLScriptElement-impl.js:65:7)
[error]     at /localhome/doeraene/projects/scalajs/node_modules/jsdom/lib/jsdom/browser/resource-loader.js:30:22
[error]     at Object.check (/localhome/doeraene/projects/scalajs/node_modules/jsdom/lib/jsdom/living/nodes/Document-impl.js:85:11)
[error]     at /localhome/doeraene/projects/scalajs/node_modules/jsdom/lib/jsdom/living/nodes/Document-impl.js:104:12
[error]     at wrappedEnqueued (/localhome/doeraene/projects/scalajs/node_modules/jsdom/lib/jsdom/browser/resource-loader.js:243:16)
[error]     at ReadStream.<anonymous> (/localhome/doeraene/projects/scalajs/node_modules/jsdom/lib/jsdom/browser/resource-loader.js:76:7)
[error]     at emitNone (events.js:72:20)
[error]     at ReadStream.emit (events.js:166:7) [ReferenceError: exports is not defined]
[error] Error: Uncaught [ReferenceError: exports is not defined]
[error]     at reportException (/localhome/doeraene/projects/scalajs/node_modules/jsdom/lib/jsdom/living/helpers/runtime-script-errors.js:58:24)
[error]     at processJavaScript (/localhome/doeraene/projects/scalajs/node_modules/jsdom/lib/jsdom/living/nodes/HTMLScriptElement-impl.js:130:7)
[error]     at HTMLScriptElementImpl._eval (/localhome/doeraene/projects/scalajs/node_modules/jsdom/lib/jsdom/living/nodes/HTMLScriptElement-impl.js:65:7)
[error]     at /localhome/doeraene/projects/scalajs/node_modules/jsdom/lib/jsdom/browser/resource-loader.js:30:22
[error]     at Object.check (/localhome/doeraene/projects/scalajs/node_modules/jsdom/lib/jsdom/living/nodes/Document-impl.js:85:11)
[error]     at /localhome/doeraene/projects/scalajs/node_modules/jsdom/lib/jsdom/living/nodes/Document-impl.js:104:12
[error]     at wrappedEnqueued (/localhome/doeraene/projects/scalajs/node_modules/jsdom/lib/jsdom/browser/resource-loader.js:243:16)
[error]     at ReadStream.<anonymous> (/localhome/doeraene/projects/scalajs/node_modules/jsdom/lib/jsdom/browser/resource-loader.js:76:7)
[error]     at emitNone (events.js:72:20)
[error]     at ReadStream.emit (events.js:166:7) [ReferenceError: exports is not defined]
[error] Error: Uncaught [ReferenceError: exports is not defined]
[error]     at reportException (/localhome/doeraene/projects/scalajs/node_modules/jsdom/lib/jsdom/living/helpers/runtime-script-errors.js:58:24)
[error]     at processJavaScript (/localhome/doeraene/projects/scalajs/node_modules/jsdom/lib/jsdom/living/nodes/HTMLScriptElement-impl.js:130:7)
[error]     at HTMLScriptElementImpl._eval (/localhome/doeraene/projects/scalajs/node_modules/jsdom/lib/jsdom/living/nodes/HTMLScriptElement-impl.js:65:7)
[error]     at /localhome/doeraene/projects/scalajs/node_modules/jsdom/lib/jsdom/browser/resource-loader.js:30:22
[error]     at Object.check (/localhome/doeraene/projects/scalajs/node_modules/jsdom/lib/jsdom/living/nodes/Document-impl.js:85:11)
[error]     at /localhome/doeraene/projects/scalajs/node_modules/jsdom/lib/jsdom/living/nodes/Document-impl.js:104:12
[error]     at wrappedEnqueued (/localhome/doeraene/projects/scalajs/node_modules/jsdom/lib/jsdom/browser/resource-loader.js:243:16)
[error]     at ReadStream.<anonymous> (/localhome/doeraene/projects/scalajs/node_modules/jsdom/lib/jsdom/browser/resource-loader.js:76:7)
[error]     at emitNone (events.js:72:20)
[error]     at ReadStream.emit (events.js:166:7) [ReferenceError: exports is not defined]
[error] Error: Uncaught [ReferenceError: exports is not defined]
[error]     at reportException (/localhome/doeraene/projects/scalajs/node_modules/jsdom/lib/jsdom/living/helpers/runtime-script-errors.js:58:24)
[error]     at processJavaScript (/localhome/doeraene/projects/scalajs/node_modules/jsdom/lib/jsdom/living/nodes/HTMLScriptElement-impl.js:130:7)
[error]     at HTMLScriptElementImpl._eval (/localhome/doeraene/projects/scalajs/node_modules/jsdom/lib/jsdom/living/nodes/HTMLScriptElement-impl.js:65:7)
[error]     at /localhome/doeraene/projects/scalajs/node_modules/jsdom/lib/jsdom/browser/resource-loader.js:30:22
[error]     at Object.check (/localhome/doeraene/projects/scalajs/node_modules/jsdom/lib/jsdom/living/nodes/Document-impl.js:85:11)
[error]     at /localhome/doeraene/projects/scalajs/node_modules/jsdom/lib/jsdom/living/nodes/Document-impl.js:104:12
[error]     at wrappedEnqueued (/localhome/doeraene/projects/scalajs/node_modules/jsdom/lib/jsdom/browser/resource-loader.js:243:16)
[error]     at ReadStream.<anonymous> (/localhome/doeraene/projects/scalajs/node_modules/jsdom/lib/jsdom/browser/resource-loader.js:76:7)
[error]     at emitNone (events.js:72:20)
[error]     at ReadStream.emit (events.js:166:7) [ReferenceError: exports is not defined]
[error] Error: Uncaught [ReferenceError: exports is not defined]
[error]     at reportException (/localhome/doeraene/projects/scalajs/node_modules/jsdom/lib/jsdom/living/helpers/runtime-script-errors.js:58:24)
[error]     at processJavaScript (/localhome/doeraene/projects/scalajs/node_modules/jsdom/lib/jsdom/living/nodes/HTMLScriptElement-impl.js:130:7)
[error]     at HTMLScriptElementImpl._eval (/localhome/doeraene/projects/scalajs/node_modules/jsdom/lib/jsdom/living/nodes/HTMLScriptElement-impl.js:65:7)
[error]     at /localhome/doeraene/projects/scalajs/node_modules/jsdom/lib/jsdom/browser/resource-loader.js:30:22
[error]     at Object.check (/localhome/doeraene/projects/scalajs/node_modules/jsdom/lib/jsdom/living/nodes/Document-impl.js:85:11)
[error] Error: Uncaught [ReferenceError: exports is not defined]
[error]     at reportException (/localhome/doeraene/projects/scalajs/node_modules/jsdom/lib/jsdom/living/helpers/runtime-script-errors.js:58:24)
[error]     at /localhome/doeraene/projects/scalajs/node_modules/jsdom/lib/jsdom/living/nodes/Document-impl.js:104:12
[error]     at processJavaScript (/localhome/doeraene/projects/scalajs/node_modules/jsdom/lib/jsdom/living/nodes/HTMLScriptElement-impl.js:130:7)
[error]     at wrappedEnqueued (/localhome/doeraene/projects/scalajs/node_modules/jsdom/lib/jsdom/browser/resource-loader.js:243:16)
[error]     at HTMLScriptElementImpl._eval (/localhome/doeraene/projects/scalajs/node_modules/jsdom/lib/jsdom/living/nodes/HTMLScriptElement-impl.js:65:7)
[error]     at ReadStream.<anonymous> (/localhome/doeraene/projects/scalajs/node_modules/jsdom/lib/jsdom/browser/resource-loader.js:76:7)
[error]     at emitNone (events.js:72:20)
[error]     at ReadStream.emit (events.js:166:7) [ReferenceError: exports is not defined]
[error]     at /localhome/doeraene/projects/scalajs/node_modules/jsdom/lib/jsdom/browser/resource-loader.js:30:22
[error]     at Object.check (/localhome/doeraene/projects/scalajs/node_modules/jsdom/lib/jsdom/living/nodes/Document-impl.js:85:11)
[error]     at /localhome/doeraene/projects/scalajs/node_modules/jsdom/lib/jsdom/living/nodes/Document-impl.js:104:12
[error]     at wrappedEnqueued (/localhome/doeraene/projects/scalajs/node_modules/jsdom/lib/jsdom/browser/resource-loader.js:243:16)
[error]     at ReadStream.<anonymous> (/localhome/doeraene/projects/scalajs/node_modules/jsdom/lib/jsdom/browser/resource-loader.js:76:7)
[error]     at emitNone (events.js:72:20)
[error]     at ReadStream.emit (events.js:166:7) [ReferenceError: exports is not defined]
[info] Passed: Total 7, Failed 0, Errors 0, Passed 7
[success] Total time: 7 s, completed Oct 18, 2016 11:24:20 AM
```

Note that, somehow, the tests _pass_. But the `ReferenceError`s in them middle are no good.

**Comment by sjrd** [comment]
Hum, in fact, I'm not completely sure this should be considered a bug. It's kind of a feature of Node.js+jsdom that it emulates a browser environment pretty well. And in a browser environment, scripts cannot be CommonJS modules.

**Comment by julienrf** [comment]
Exactly, scripts are loaded by jsdom exactly in the same way a Web browser would load them. But still, it would be interesting to have the ability to locally run tests for code that uses the DOM and CommonJSModule.

That’s probably something that should be done by scalajs-bundler then. In case scalajs-bundler detects that the DOM is required for the tests, it set up a custom test framework that would use the bundled tests instead of the CommonJS module. What is the correct way to check that the DOM is required for the tests?

**Comment by sjrd** [comment]
> What is the correct way to check that the DOM is required for the tests?

```scala
import org.scalajs.sbtplugin.ScalaJSPluginInternal.scalaJSRequestsDOM

(scalaJSRequestsDOM in Test).value
```

**Comment by cuzfrog** [comment]
When `extends js.JSApp` and using `test:run`, err message still goes out: (Though, it does not matter on the run.)

```
[error] Error: Uncaught [ReferenceError: exports is not defined]
[error]     at reportException (/home/cuzfrog/workspace/scala/glois/node_modules/jsdom/lib/jsdom/living/helpers/runtime-script-errors.js:58:24)
[error]     at processJavaScript (/home/cuzfrog/workspace/scala/glois/node_modules/jsdom/lib/jsdom/living/nodes/HTMLScriptElement-impl.js:130:7)
[error]     at HTMLScriptElementImpl._eval (/home/cuzfrog/workspace/scala/glois/node_modules/jsdom/lib/jsdom/living/nodes/HTMLScriptElement-impl.js:65:7)
[error]     at /home/cuzfrog/workspace/scala/glois/node_modules/jsdom/lib/jsdom/browser/resource-loader.js:31:22
[error]     at Object.check (/home/cuzfrog/workspace/scala/glois/node_modules/jsdom/lib/jsdom/living/nodes/Document-impl.js:89:11)
[error]     at /home/cuzfrog/workspace/scala/glois/node_modules/jsdom/lib/jsdom/living/nodes/Document-impl.js:108:12
[error]     at wrappedEnqueued (/home/cuzfrog/workspace/scala/glois/node_modules/jsdom/lib/jsdom/browser/resource-loader.js:255:16)
[error]     at ReadStream.readableStream.on (/home/cuzfrog/workspace/scala/glois/node_modules/jsdom/lib/jsdom/browser/resource-loader.js:76:7)
[error]     at emitNone (events.js:91:20)
[error]     at ReadStream.emit (events.js:185:7) ReferenceError: exports is not defined
[error]     at /home/cuzfrog/workspace/scala/glois/app/js/target/scala-2.11/scalajs-bundler/test/app-client-test-fastopt.js:27:10
[error]     at ContextifyScript.Script.runInContext (vm.js:37:29)
[error]     at Object.exports.runInContext (vm.js:69:17)
[error]     at processJavaScript (/home/cuzfrog/workspace/scala/glois/node_modules/jsdom/lib/jsdom/living/nodes/HTMLScriptElement-impl.js:128:10)
[error]     at HTMLScriptElementImpl._eval (/home/cuzfrog/workspace/scala/glois/node_modules/jsdom/lib/jsdom/living/nodes/HTMLScriptElement-impl.js:65:7)
[error]     at /home/cuzfrog/workspace/scala/glois/node_modules/jsdom/lib/jsdom/browser/resource-loader.js:31:22
[error]     at Object.check (/home/cuzfrog/workspace/scala/glois/node_modules/jsdom/lib/jsdom/living/nodes/Document-impl.js:89:11)
[error]     at /home/cuzfrog/workspace/scala/glois/node_modules/jsdom/lib/jsdom/living/nodes/Document-impl.js:108:12
[error]     at wrappedEnqueued (/home/cuzfrog/workspace/scala/glois/node_modules/jsdom/lib/jsdom/browser/resource-loader.js:255:16)
[error]     at ReadStream.readableStream.on (/home/cuzfrog/workspace/scala/glois/node_modules/jsdom/lib/jsdom/browser/resource-loader.js:76:7)
[success] Total time: 4 s, completed Apr 15, 2017 12:53:57 PM

```

**Comment by sjrd** [comment]
@cuzfrog That's also expected. If you use CommonJS modules, don't use `JSDOMNodeJSEnv`. That environment expects *scripts*, just like a browser.

**Comment by sjrd** [comment]
Rereading this, I'm now convinced this works as expected. Closing as "as-designed".
