### ISSUE TITLE
Inconsistent behavior in min method between JVM and JS

### ISSUE THREAD

**Issue by beppu** [scala-js/scala-js#2655]
# JVM

```scala
scala> val x = 1 to 10 by 1
x: scala.collection.immutable.Range = Range(1, 2, 3, 4, 5, 6, 7, 8, 9, 10)

scala> println(x.min)
1

scala> val y = 1.0 to 10.0 by 1.0
y: scala.collection.immutable.NumericRange[Double] = NumericRange(1.0, 2.0, 3.0, 4.0, 5.0, 6.0, 7.0, 8.0, 9.0, 10.0)

scala> println(y.min)
1.0
```

# JS

```scala
val x = 1 to 10 by 1
println(x.min) // 1

val y = 1.0 to 10.0 by 1.0
println(y.min) // error
```

https://gitter.im/scala-js/scala-js?at=582f309db563b5516c371ee4

**Comment by sjrd** [comment]
Confirmed.

**Comment by sjrd** [comment]
```
1
java.util.NoSuchElementException: key not found: scala.math.Numeric$DoubleAsIfIntegral$@6
    at $c_ju_NoSuchElementException.$c_jl_Throwable.fillInStackTrace__jl_Throwable (C:\Users\Sepi\Documents\Projets\scalajs\examples\helloworld\target\scala-2.11\file:\C:\Users\Sepi\Documents\Projets\scalajs\library\src\main\scala\scala\scalajs\runtime\StackTrace.scala:33:5)
    at $c_ju_NoSuchElementException.$c_jl_Throwable.init___T__jl_Throwable (C:\Users\Sepi\Documents\Projets\scalajs\examples\helloworld\target\scala-2.11\file:\C:\Users\Sepi\Documents\Projets\scalajs\javalanglib\src\main\scala\java\lang\Throwables.scala:12:19)
    at $c_ju_NoSuchElementException.init___T (C:\Users\Sepi\Documents\Projets\scalajs\examples\helloworld\target\scala-2.11\file:\C:\Users\Sepi\Documents\Projets\scalajs\javalib\src\main\scala\java\util\Throwables.scala:136:49)
    at $s_sc_MapLike$class__$default__sc_MapLike__O__O (C:\Users\Sepi\Documents\Projets\scalajs\examples\helloworld\target\scala-2.11\https:\raw.githubusercontent.com\scala\scala\v2.11.8\src\library\scala\collection\MapLike.scala:228:5)
    at $s_sc_MapLike$class__apply__sc_MapLike__O__O (C:\Users\Sepi\Documents\Projets\scalajs\examples\helloworld\target\scala-2.11\https:\raw.githubusercontent.com\scala\scala\v2.11.8\src\library\scala\collection\Map.scala:59:16)
    at $c_sci_HashMap$HashTrieMap.$c_sc_AbstractMap.apply__O__O (C:\Users\Sepi\Documents\Projets\scalajs\examples\helloworld\target\scala-2.11\https:\raw.githubusercontent.com\scala\scala\v2.11.8\src\library\scala\collection\Map.scala:59:16)
    at $c_sci_NumericRange$Inclusive.$c_sci_NumericRange.min__s_math_Ordering__O (C:\Users\Sepi\Documents\Projets\scalajs\examples\helloworld\target\scala-2.11\file:\C:\Users\Sepi\Documents\Projets\scalajs\scalalib\overrides-2.11\scala\collection\immutable\NumericRange.scala:117:5)
    at $c_Lhelloworld_HelloWorld$.main__V (C:\Users\Sepi\Documents\Projets\scalajs\examples\helloworld\target\scala-2.11\file:\C:\Users\Sepi\Documents\Projets\scalajs\examples\helloworld\HelloWorld.scala:12:14)
    at $c_Lhelloworld_HelloWorld$.$$js$exported$meth$main__O (C:\Users\Sepi\Documents\Projets\scalajs\examples\helloworld\target\scala-2.11\file:\C:\Users\Sepi\Documents\Projets\scalajs\library\src\main\scala\scala\scalajs\js\JSApp.scala:18:4)
    at $c_Lhelloworld_HelloWorld$.main (C:\Users\Sepi\Documents\Projets\scalajs\examples\helloworld\target\scala-2.11\file:\C:\Users\Sepi\Documents\Projets\scalajs\examples\helloworld\HelloWorld.scala:11:8)
```

**Comment by gzm0** [comment]
The problem here is that our override of `NumericRange` (that we did since `BigNumeric` / `BigDecimal` were not implemented) did not catch up with what is reachable now.

So the lookup map used for optimization of `min` is not up to date:

```diff
   private[collection] val defaultOrdering = Map[Numeric[_], Ordering[_]](
+    Numeric.BigIntIsIntegral -> Ordering.BigInt,
     Numeric.IntIsIntegral -> Ordering.Int,
     Numeric.ShortIsIntegral -> Ordering.Short,
     Numeric.ByteIsIntegral -> Ordering.Byte,
     Numeric.CharIsIntegral -> Ordering.Char,
-    Numeric.LongIsIntegral -> Ordering.Long
+    Numeric.LongIsIntegral -> Ordering.Long,
+    Numeric.FloatAsIfIntegral -> Ordering.Float,
+    Numeric.DoubleAsIfIntegral -> Ordering.Double,
+    Numeric.BigDecimalAsIfIntegral -> Ordering.BigDecimal
```

The lookup in this map fails. I'll investigate if the overrides are still necessary at all.

**Comment by sjrd** [comment]
The overrides are still necessary not to bring Big Integers in every single codebase that uses a `Range`

**Comment by gzm0** [comment]
This is actually a more fundamental problem in the standard library. `NumericRange` does not work with custom integral types, although it claims it should:

```scala
object Test {

  import scala.collection.immutable.NumericRange

  case class A(v: Int)

  implicit object aIsIntegral extends scala.math.Integral[A] {
    def compare(x: A, y: A): Int = x.v - y.v
    def fromInt(x: Int): A = A(x)
    def minus(x: A, y: A): A = A(x.v - y.v)
    def negate(x: A): A = A(-x.v)
    def plus(x: A, y: A): A = A(x.v + y.v)
    def times(x: A, y: A): A = A(x.v * x.v)
    def quot(x: A, y: A): A = A(x.v / y.v)
    def rem(x: A, y: A): A = A(x.v % y.v)
    def toDouble(x: A): Double = x.v.toDouble
    def toFloat(x: A): Float = x.v.toFloat
    def toInt(x: A): Int = x.v
    def toLong(x: A): Long = x.v.toLong
  }

  def main(args: Array[String]): Unit = {
    val r = NumericRange(A(1), A(10), A(1))

    println(r)
    // NumericRange(A(1), A(2), A(3), A(4), A(5), A(6), A(7), A(8), A(9))
    // As expected.

    println(r.max)
    // java.util.NoSuchElementException: key not found: Test$aIsIntegral$@1a0e35d3
    // 	at scala.collection.MapLike$class.default(MapLike.scala:228)
    // 	at scala.collection.AbstractMap.default(Map.scala:58)
    // 	at scala.collection.MapLike$class.apply(MapLike.scala:141)
    // 	at scala.collection.AbstractMap.apply(Map.scala:58)
    // 	at scala.collection.immutable.NumericRange.max(NumericRange.scala:137)
    // 	at Test$.main(Test.scala:26)
    // 	at Test.main(Test.scala)
    // 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    // 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    // 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    // 	at java.lang.reflect.Method.invoke(Method.java:498)
  }
}
```

**Comment by sjrd** [comment]
Ouch. So that's a bug for scala/scala?

**Comment by gzm0** [comment]
Yes. Essentially there is code to optimize `min` / `max` if it is a known `Integral[_]` with it's default ordering (so that `(1 to 10000000000000000000).max` is fast. For this, it looks for the default ordering in the map above. However, it does not handle missing values properly. So if the `Integral[_]` is not known, it blows up.

I'll go ahead and file this...

**Comment by gzm0** [comment]
Filed as [SI-10086](https://issues.scala-lang.org/browse/SI-10086). I will go ahead and fix this for Scala.js. I hope a non-bug compatible fix is OK here.

**Comment by gzm0** [comment]
Upstream PR is here: scala/scala#5575
