### ISSUE TITLE
java.math.BigDecimal.divide fails when used with a scale and rounding mode

### ISSUE THREAD

**Issue by liff** [scala-js/scala-js#2755]
Running this code:

```scala
import java.math.{BigDecimal, RoundingMode}

val a = new BigDecimal(2L)
val b = new BigDecimal(1L)

a.divide(b, 1, RoundingMode.UNNECESSARY)
```

results in this exception:

```
target/scala-2.12/bdbug-fastopt.js:5755
    var lo$2 = t.lo$2;
                ^
TypeError: Cannot read property 'lo$2' of undefined
    at $c_Ljava_math_BigDecimal.divide__Ljava_math_BigDecimal__I__Ljava_math_RoundingMode__Ljava_math_BigDecimal (target/scala-2.12/bdbug-fastopt.js:5755:17)
    at $c_LBug$.main__V (target/scala-2.12/bdbug-fastopt.js:3712:5)
    at $c_LBug$.$$js$exported$meth$main__O (target/scala-2.12/bdbug-fastopt.js:3715:8)
    at $c_LBug$.main (target/scala-2.12/bdbug-fastopt.js:3718:15)
    at [stdin]:40:65
    at ContextifyScript.Script.runInThisContext (vm.js:26:33)
    at Object.exports.runInThisContext (vm.js:79:17)
    at Object.<anonymous> ([stdin]-wrapper:6:22)
    at Module._compile (module.js:571:32)
    at Immediate.<anonymous> (bootstrap_node.js:383:29)
```

Looks like the reason may be that `diffScale` on [line 707](https://github.com/scala-js/scala-js/blob/master/javalib/src/main/scala/java/math/BigDecimal.scala#L707) gets a negative value and causes a lookup with negative index [into `LongTenPows`](https://github.com/scala-js/scala-js/blob/master/javalib/src/main/scala/java/math/BigDecimal.scala#L732).

**Comment by sjrd** [comment]
Confirmed. On master this indeed throws a `UndefinedBehaviorError` or an `ArrayIndexOutOfBoundsException`.
