### ISSUE TITLE
MatchError regarding an interop class aborts test instead of failing it

### ISSUE THREAD

**Issue by OndrejSpanel** [scala-js/scala-js#2770]
When a `MatchError` is encountered on a interop (js.native) class, the message processing handling the exception handling fails and the test is aborted.

Repro:

```
import org.scalatest.FunSuite

import scala.scalajs.js
import scala.scalajs.js.annotation.ScalaJSDefined

class Test extends FunSuite {
  @ScalaJSDefined
  class Foo extends js.Object

  @ScalaJSDefined
  class Bar extends Foo

  test("Intentional match error") {
    val foo = new Foo
    foo match {
      case _ : Bar =>
    }
  }

}

```

`build.sbt`:

```
name := "ScalaTestJSNative"

version := "1.0"

scalaVersion := "2.12.1"

enablePlugins(ScalaJSPlugin)

libraryDependencies += "org.scalatest" %%% "scalatest" % "3.0.1" % "test"
```

plugins.sbt:

```
addSbtPlugin("org.scala-js" % "sbt-scalajs" % "0.6.14")
```

Test output:

<pre>
GOT TO THIS RECOVER CALL
[info] Test:
[info] Test *** ABORTED ***
[info]   scala.scalajs.js.JavaScriptException: TypeError: Cannot read property 'getName__T' of null
[info]   at scala.MatchError.ofClass$1(W:\Test\ScalaTestJSNative\target\scala-2.12\scalatestjsnative-test-fastopt.js:29113:48)
[info]   at scala.MatchError.liftedTree1$1(W:\Test\ScalaTestJSNative\target\scala-2.12\scalatestjsnative-test-fastopt.js:29121:37)
[info]   at scala.MatchError.objString$lzycompute(W:\Test\ScalaTestJSNative\target\scala-2.12\scalatestjsnative-test-fastopt.js:29106:63)
[info]   at scala.MatchError.objString(W:\Test\ScalaTestJSNative\target\scala-2.12\scalatestjsnative-test-fastopt.js:29131:37)
[info]   at scala.MatchError.getMessage(W:\Test\ScalaTestJSNative\target\scala-2.12\scalatestjsnative-test-fastopt.js:29128:15)
[info]   at org.scalatest.Suite$.getMessageForException(W:\Test\ScalaTestJSNative\target\scala-2.12\scalatestjsnative-test-fastopt.js:20898:14)
[info]   at org.scalatest.Suite$.reportTestFailed(W:\Test\ScalaTestJSNative\target\scala-2.12\scalatestjsnative-test-fastopt.js:20512:22)
[info]   at org.scalatest.FunSuiteLike.runTest(W:\Test\ScalaTestJSNative\target\scala-2.12\scalatestjsnative-test-fastopt.js:46061:36)
[info]   at {anonymous}()(W:\Test\ScalaTestJSNative\target\scala-2.12\scalatestjsnative-test-fastopt.js:46100:14)
[info]   at scala.scalajs.runtime.AnonFunction2.apply(W:\Test\ScalaTestJSNative\target\scala-2.12\scalatestjsnative-test-fastopt.js:24348:23)
[info]   ...
[trace] Stack trace suppressed: run last test:test(name: Test, isModule: false) for the full output.
[info] Run completed in 505 milliseconds.
[info] Total number of tests run: 0
[info] Suites: completed 0, aborted 1
[info] Tests: succeeded 0, failed 0, canceled 0, ignored 0, pending 0
[info] *** 1 SUITE ABORTED ***
[error] Error during tests:
[error]         Test
[error] (test:test) sbt.TestsFailedException: Tests unsuccessful
[error] Total time: 7 s, completed 10.2.2017 16:06:38

</pre>

**Comment by OndrejSpanel** [comment]
Wrong repository.
