### ISSUE TITLE
run/Predef.readLine.scala is broken in --fullOpt

### ISSUE THREAD

**Issue by sjrd** [scala-js/scala-js#2815]
The change in partest to use a module initializer rather than export to call the launcher broke `run/Predef.readLine.scala` in `--fullOpt`. Somehow this simplified the program enough that Closure could see a bit more ... and break things because it's buggy.

How to reproduce:

    > partestSuite/testOnly -- --fullOpt run/Predef.readLine.scala

Source of the test: [`run/Predef.readLine.scala`](https://github.com/scala/scala/blob/2.12.x/test/files/run/Predef.readLine.scala)

Error:
```
[error] TypeError: Cannot read property 'eb' of null
[error]     at sf (...\java\io\BufferedReader.scala:71:15)
[error]     at Object.<anonymous> (...\helloworld-opt.js:3409:3)
[error]     at Object.<anonymous> (...\helloworld-opt.js:3470:4)
[error]     at Module._compile (module.js:541:32)
[error]     at Object.Module._extensions..js (module.js:550:10)
[error]     at Module.load (module.js:458:32)
[error]     at tryModuleLoad (module.js:417:12)
[error]     at Function.Module._load (module.js:409:3)
[error]     at Module.require (module.js:468:17)
[error]     at require (internal/module.js:20:19)
```
After some digging, I found that GCC removes the assignment of the `new BufferedReader` (created by [`Console.withIn`](https://github.com/scala-js/scala-js/blob/502bde1b1d6046ea531df95abba64b61265168ab/scalalib/overrides-2.11/scala/Console.scala#L112)) to the `value` field of the `DynamicVariable`. Hence, it stays the `null` [it was initialized with](https://github.com/scala-js/scala-js/blob/502bde1b1d6046ea531df95abba64b61265168ab/scalalib/overrides-2.11/scala/Console.scala#L25).

Later, the calls to `readLine()` eventually *reads* that field, calls a method on it, and kaboom!

This is clearly a bug in GCC. It looks similar to the one that led to #2749.

**Comment by sjrd** [comment]
For further debugging, it is possible to reproduce it in the helloworld with exactly this code:
```scala
import java.io.StringReader
import scala.io.StdIn.readLine

object PartestLauncher {
  def main(): Unit = {
    Console.withIn(new StringReader("")) {
      readLine()
      readLine("prompt\n")
      readLine("%s prompt\n", "fancy")
      readLine("%s %s prompt\n", "immensely", "fancy")
    }
  }
}
```
and
```scala
set mainClass in (helloworld, Compile) := Some("PartestLauncher")
```
