### ISSUE TITLE
Neg test JSExportsTest.noExportStaticLazyVal fails on 2.12.0

### ISSUE THREAD

**Issue by sjrd** [scala-js/scala-js#2816]
It succeeds on 2.12.1, which is why it was only discovered in the nightly build.

Error:
```
[error] Test org.scalajs.core.compiler.test.JSExportTest.noExportStaticLazyVal failed: snippet shouldn't compile
[error]     at org.scalajs.core.compiler.test.util.TestHelpers$CompileTests.$anonfun$hasErrors$1(TestHelpers.scala:30)
[error]     at org.scalajs.core.compiler.test.util.TestHelpers$CompileTests.repResult(TestHelpers.scala:74)
[error]     at org.scalajs.core.compiler.test.util.TestHelpers$CompileTests.hasErrors(TestHelpers.scala:30)
[error]     at org.scalajs.core.compiler.test.JSExportTest.noExportStaticLazyVal(JSExportTest.scala:1452)
[error]     ...
```
I haven't investigated yet.

**Comment by sjrd** [comment]
OK this one is [SI-10075](https://issues.scala-lang.org/browse/SI-10075), which is a 2.12.0 regression, fixed in https://github.com/scala/scala/pull/5570.

The only reasonable thing to do is to ignore this test on 2.12.0. I guess we can even call it an internal bug.
