### ISSUE TITLE
Could not fetch scala-library sources for version 2.11.11

### ISSUE THREAD

**Issue by mkotsbak** [scala-js/scala-js#2923]
```
> testSuite/test
[trace] Stack trace suppressed: run last scalalib/*:fetchScalaSource for the full output.
[error] (scalalib/*:fetchScalaSource) Could not fetch scala-library sources for version 2.11.11
[error] Total time: 0 s, completed 03.mai.2017 11:08:10
> last scalalib/*:fetchScalaSource
java.lang.RuntimeException: Could not fetch scala-library sources for version 2.11.11
        at scala.sys.package$.error(package.scala:27)
        at Build$$anonfun$scalalib$1$$anonfun$apply$83$$anonfun$55.apply(Build.scala:909)
        at Build$$anonfun$scalalib$1$$anonfun$apply$83$$anonfun$55.apply(Build.scala:909)
        at scala.Option.getOrElse(Option.scala:120)
        at Build$$anonfun$scalalib$1$$anonfun$apply$83.apply(Build.scala:908)
        at Build$$anonfun$scalalib$1$$anonfun$apply$83.apply(Build.scala:898)
        at scala.Function1$$anonfun$compose$1.apply(Function1.scala:47)
        at sbt.$tilde$greater$$anonfun$$u2219$1.apply(TypeFunctions.scala:40)
        at sbt.std.Transform$$anon$4.work(System.scala:63)
        at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:228)
        at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:228)
        at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:17)
        at sbt.Execute.work(Execute.scala:237)
        at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:228)
        at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:228)
        at sbt.ConcurrentRestrictions$$anon$4$$anonfun$1.apply(ConcurrentRestrictions.scala:159)
        at sbt.CompletionService$$anon$2.call(CompletionService.scala:28)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
[error] (scalalib/*:fetchScalaSource) Could not fetch scala-library sources for version 2.11.11
```

Same for 2.12.x and both master and 0.6.x branches.

**Comment by sjrd** [comment]
If someone who experiences this bug manages to amend the build to make it work, that'd be great. No one in the core team nor our CI can reproduce this bug, so it's basically impossible for us to work on it.

**Comment by gzm0** [comment]
@mkotsbak A good start do debugging this would be to `println` the report (or the selection on it):

https://github.com/scala-js/scala-js/blob/master/project/Build.scala#L897

In the past, we have seen this error if sbt was running with the Scala version that we tried to fetch the sources for (see #2649).

**Comment by mkotsbak** [comment]
Ok, I got a lot of output. The interesting part is probably this?:

```
        org.scala-lang:scala-library
                - 2.11.11
                        status: release
                        publicationDate: Thu Apr 13 21:50:31 CEST 2017
                        resolver: sbt-chain
                        artifactResolver: sbt-chain
                        evicted: false
                        homepage: http://www.scala-lang.org/
                        textraAttributes: Map(info.apiURL -> http://www.scala-lang.org/api/2.11.11/)
                        isDefault: false
                        configurations: default, compile, runtime(*), master(compile), runtime, optional, optional(default), compile(*), master
                        licenses: (BSD 3-Clause,Some(http://www.scala-lang.org/license.html))
                        callers: org.scala-lang:scala-reflect:2.11.11 (), org.scala-lang:scala-compiler:2.11.11, org.scala-lang.modules:scala-xml_2.11:1.0.5, org.scala-js:scala-library-for-scalajs_2.11:0.6.17-SNAPSHOT (), org.scala-lang.modules:scala-parser-combinators_2.11:1.0.4
```
I use the sbt wrapper that uses the correct version of sbt, but I had the same issue before.

**Comment by gzm0** [comment]
Well, that's the binary library jar (AFAICS), not the sources jar.

**Comment by mkotsbak** [comment]
I can't find much references to sources other than emptyness:
```
        sources:
        docs:
        pom:
        scala-tool:
        org.scala-lang:scala-compiler
                - 2.11.11
```

Do I need to add a resolver to find it?

**Comment by sjrd** [comment]
No you're not supposed to need a resolver for that. Source jars are on Maven.

```
                        resolver: sbt-chain
                        artifactResolver: sbt-chain
```
This part is worrisome. It reminds me of the same-version-as-sbt bug.

Crazy idea: are you using the new launcher of sbt 0.1.3.15 which supports offline installation?

**Comment by mkotsbak** [comment]
Not sure. I see the command line that is run is like this:
`java -Xms512m -Xmx1536m -Xss2m -jar /home/marius/.sbt/launchers/0.13.15/sbt-launch.jar shell`

**Comment by sjrd** [comment]
Could you try downgrading to the 0.13.13 launcher?

**Comment by mkotsbak** [comment]
Same issue with 0.13.13. (running `sbt -sbt-version 0.13.13`)

**Comment by sjrd** [comment]
> running sbt -sbt-version 0.13.13

I don't think that will force the usage of the 0.13.13 *launcher*. For that you really need to download sbt 0.13.13 and adapt your PATH to use its launcher.

**Comment by sjrd** [comment]
Note that I can't reproduce the issue even if I wipe all of `.ivy2/local`, `.ivy2/cache`, *and* `.sbt/` (except `.sbt/0.13/plugins/*.sbt`) and then use the 0.13.15 launcher. It apparently can resolve and download the sources jar.

**Comment by mkotsbak** [comment]
Ah, I started looking into cleaning my .sbt too, and it seems like it is something in the plugin directory that breaks this. It works without that :)

**Comment by sjrd** [comment]
Nice thanks for investigating!

**Comment by mkotsbak** [comment]
I narrowed it down to this plugin: `addSbtPlugin("org.ensime" % "ensime-sbt" % "0.4.0")`
