### ISSUE TITLE
Future.mapTo behaves differently on JS and JVM when casts to incompatible type

### ISSUE THREAD

**Issue by nartamonov** [scala-js/scala-js#3026]
When `mapTo` incompatible type, it is expected that failure will be propagated *inside* future, for example (see [demo repository](https://github.com/nartamonov/scalajs-mapto-case/blob/master/shared/src/test/scala/MapToTest.scala)):

```scala
class MapToTest extends FreeSpec with Matchers with ScalaFutures {
  "mapTo incompatible type should fail *inside* future" in {
    val f = Future.successful(10).mapTo[String]
    an[RuntimeException] should be thrownBy f.futureValue
  }
}
```

This test successfully passes in JVM, but in ScalaJS `mapTo` throws some weird exception:

```
> sharedJS/test
[info] Compiling 1 Scala source to C:\DATA\Dev\scalajs-mapto-case\shared\.js\target\scala-2.12\test-classes...
[info] Fast optimizing C:\DATA\Dev\scalajs-mapto-case\shared\.js\target\scala-2.12\shared-test-fastopt.js
[info] MapToTest:
[info] - mapTo incompatible type should fail *inside* future *** FAILED ***
[info]   java.lang.IllegalStateException: problem in scala.concurrent internal callback
[info]   at $c_jl_IllegalStateException.$c_jl_Throwable.fillInStackTrace__jl_Throwable(C:\DATA\Dev\scalajs-mapto-case\shared\.js\target\scala-2.12\shared-test-fastopt.js:19896:14)
[info]   at $c_jl_IllegalStateException.$c_jl_Throwable.init___T__jl_Throwable(C:\DATA\Dev\scalajs-mapto-case\shared\.js\target\scala-2.12\shared-test-fastopt.js:19918:8)
[info]   at java.lang.IllegalStateException.<init>(C:\DATA\Dev\scalajs-mapto-case\shared\.js\target\scala-2.12\shared-test-fastopt.js:30936:52)
[info]   at scala.concurrent.Future$InternalCallbackExecutor$.reportFailure(C:\DATA\Dev\scalajs-mapto-case\shared\.js\target\scala-2.12\shared-test-fastopt.js:28573:43)
[info]   at scala.concurrent.impl.CallbackRunnable.executeWithValue(C:\DATA\Dev\scalajs-mapto-case\shared\.js\target\scala-2.12\shared-test-fastopt.js:25503:27)
[info]   at scala.concurrent.impl.Promise$KeptPromise$Kept.onComplete(C:\DATA\Dev\scalajs-mapto-case\shared\.js\target\scala-2.12\shared-test-fastopt.js:28596:104)
[info]   at scala.concurrent.impl.Promise$KeptPromise$Successful.onComplete(C:\DATA\Dev\scalajs-mapto-case\shared\.js\target\scala-2.12\shared-test-fastopt.js:37598:3)
[info]   at scala.concurrent.impl.Promise.transform(C:\DATA\Dev\scalajs-mapto-case\shared\.js\target\scala-2.12\shared-test-fastopt.js:25584:9)
[info]   at scala.concurrent.Future.map(C:\DATA\Dev\scalajs-mapto-case\shared\.js\target\scala-2.12\shared-test-fastopt.js:12007:10)
[info]   at scala.concurrent.impl.Promise$KeptPromise$Successful.map(C:\DATA\Dev\scalajs-mapto-case\shared\.js\target\scala-2.12\shared-test-fastopt.js:37604:10)
[info]   ...
[info]   Cause: java.lang.IllegalArgumentException: requirement failed
[info]   at $c_jl_IllegalArgumentException.$c_jl_Throwable.fillInStackTrace__jl_Throwable(C:\DATA\Dev\scalajs-mapto-case\shared\.js\target\scala-2.12\shared-test-fastopt.js:19896:14)
[info]   at $c_jl_IllegalArgumentException.$c_jl_Throwable.init___T__jl_Throwable(C:\DATA\Dev\scalajs-mapto-case\shared\.js\target\scala-2.12\shared-test-fastopt.js:19918:8)
[info]   at java.lang.IllegalArgumentException.<init>(C:\DATA\Dev\scalajs-mapto-case\shared\.js\target\scala-2.12\shared-test-fastopt.js:30906:52)
[info]   at scala.Predef$.require(C:\DATA\Dev\scalajs-mapto-case\shared\.js\target\scala-2.12\shared-test-fastopt.js:25189:48)
[info]   at scala.concurrent.BatchingExecutor$Batch.run(C:\DATA\Dev\scalajs-mapto-case\shared\.js\target\scala-2.12\shared-test-fastopt.js:25424:18)
[info]   at scala.concurrent.BatchingExecutor$Batch.processBatch$1(C:\DATA\Dev\scalajs-mapto-case\shared\.js\target\scala-2.12\shared-test-fastopt.js:25409:15)
[info]   at scala.concurrent.BatchingExecutor$Batch.run(C:\DATA\Dev\scalajs-mapto-case\shared\.js\target\scala-2.12\shared-test-fastopt.js:25432:12)
[info]   at scala.concurrent.BatchingExecutor.execute(C:\DATA\Dev\scalajs-mapto-case\shared\.js\target\scala-2.12\shared-test-fastopt.js:11895:9)
[info]   at scala.concurrent.Future$InternalCallbackExecutor$.execute(C:\DATA\Dev\scalajs-mapto-case\shared\.js\target\scala-2.12\shared-test-fastopt.js:28576:3)
[info]   at scala.concurrent.impl.CallbackRunnable.executeWithValue(C:\DATA\Dev\scalajs-mapto-case\shared\.js\target\scala-2.12\shared-test-fastopt.js:25495:21)
[info]   ...
[info] Run completed in 460 milliseconds.
[info] Total number of tests run: 1
[info] Suites: completed 1, aborted 0
[info] Tests: succeeded 0, failed 1, canceled 0, ignored 0, pending 0
[info] *** 1 TEST FAILED ***
```

Same behaviour in browser (tried Chrome).

Test environment:

Scala.JS 0.6.17
Scala 2.12.1

**Comment by sjrd** [comment]
That's expected. When `mapTo` fails, it fails a *cast*. [Failing a cast is undefined behavior in Scala.js](https://www.scala-js.org/doc/semantics.html#undefined-behaviors), and undefined behavior, in fastOpt, are thrown under as `UndefinedBehaviorError`s instead of their "normal" exception type (i.e., `ClassCastException` in this case). An `UndefinedBehaviorError` is a *fatal* error, which is precisely designed *not* to stay in a `Future`, but fall outside so that it can be debugged right away.

In fullOpt, undefined behaviors are *unchecked*, and will behave *arbitrarily*. It could fail, it could continue and crash later, it could just stop the program without notice, or could send your personal information to my server.

So this is as-designed.
