### ISSUE TITLE
getting exception on sbt load after updating sbt plugin w/ sbt 0.13.15

### ISSUE THREAD

**Issue by yurique** [scala-js/scala-js#3132]
I just updated this:
```
addSbtPlugin("org.scala-js" % "sbt-scalajs" % "0.6.19")
```
to this:
```
addSbtPlugin("org.scala-js" % "sbt-scalajs" % "0.6.20")
```

and I started getting this when sbt loads:

```
java.lang.NoSuchMethodError: sbt.package$.Zero()Lsbt/Global$;
	at org.scalajs.sbtplugin.ScalaJSPluginInternal$.org$scalajs$sbtplugin$ScalaJSPluginInternal$$scalaJSStageSettings(ScalaJSPluginInternal.scala:254)
	at org.scalajs.sbtplugin.ScalaJSPluginInternal$$anonfun$22.apply(ScalaJSPluginInternal.scala:446)
	at org.scalajs.sbtplugin.ScalaJSPluginInternal$$anonfun$22.apply(ScalaJSPluginInternal.scala:446)
	at scala.Function2$$anonfun$tupled$1.apply(Function2.scala:54)
	at scala.Function2$$anonfun$tupled$1.apply(Function2.scala:53)
	at scala.collection.TraversableLike$$anonfun$flatMap$1.apply(TraversableLike.scala:251)
	at scala.collection.TraversableLike$$anonfun$flatMap$1.apply(TraversableLike.scala:251)
	at scala.collection.immutable.Map$Map2.foreach(Map.scala:130)
	at scala.collection.TraversableLike$class.flatMap(TraversableLike.scala:251)
	at scala.collection.AbstractTraversable.flatMap(Traversable.scala:105)
	at org.scalajs.sbtplugin.ScalaJSPluginInternal$.<init>(ScalaJSPluginInternal.scala:446)
	at org.scalajs.sbtplugin.ScalaJSPluginInternal$.<clinit>(ScalaJSPluginInternal.scala)
	at org.scalajs.sbtplugin.ScalaJSPlugin$.projectSettings(ScalaJSPlugin.scala:544)
	at sbt.Load$$anonfun$resolveProject$1$$anonfun$autoPluginSettings$1$1$$anonfun$apply$34.apply(Load.scala:721)
	at sbt.Load$$anonfun$resolveProject$1$$anonfun$autoPluginSettings$1$1$$anonfun$apply$34.apply(Load.scala:721)
	at scala.collection.TraversableLike$$anonfun$flatMap$1.apply(TraversableLike.scala:251)
	at scala.collection.TraversableLike$$anonfun$flatMap$1.apply(TraversableLike.scala:251)
	at scala.collection.immutable.List.foreach(List.scala:318)
	at scala.collection.TraversableLike$class.flatMap(TraversableLike.scala:251)
	at scala.collection.AbstractTraversable.flatMap(Traversable.scala:105)
	at sbt.Load$$anonfun$resolveProject$1$$anonfun$autoPluginSettings$1$1.apply(Load.scala:721)
	at sbt.Load$$anonfun$resolveProject$1$$anonfun$autoPluginSettings$1$1.apply(Load.scala:721)
	at sbt.Load$.timed(Load.scala:1025)
	at sbt.Load$$anonfun$resolveProject$1.autoPluginSettings$1(Load.scala:720)
	at sbt.Load$$anonfun$resolveProject$1.sbt$Load$$anonfun$$expandSettings$1(Load.scala:739)
	at sbt.Load$$anonfun$resolveProject$1$$anonfun$sbt$Load$$anonfun$$expandSettings$1$2.apply(Load.scala:740)
	at sbt.Load$$anonfun$resolveProject$1$$anonfun$sbt$Load$$anonfun$$expandSettings$1$2.apply(Load.scala:740)
	at scala.collection.IndexedSeqOptimized$class.foldl(IndexedSeqOptimized.scala:51)
	at scala.collection.IndexedSeqOptimized$class.foldLeft(IndexedSeqOptimized.scala:60)
	at scala.collection.mutable.WrappedArray.foldLeft(WrappedArray.scala:34)
	at scala.collection.TraversableOnce$class.$div$colon(TraversableOnce.scala:138)
	at scala.collection.AbstractTraversable.$div$colon(Traversable.scala:105)
	at sbt.Load$$anonfun$resolveProject$1.sbt$Load$$anonfun$$expandSettings$1(Load.scala:740)
	at sbt.Load$$anonfun$resolveProject$1$$anonfun$56.apply(Load.scala:743)
	at sbt.Load$$anonfun$resolveProject$1$$anonfun$56.apply(Load.scala:743)
	at sbt.Load$.timed(Load.scala:1025)
	at sbt.Load$$anonfun$resolveProject$1.apply(Load.scala:742)
	at sbt.Load$$anonfun$resolveProject$1.apply(Load.scala:703)
	at sbt.Load$.timed(Load.scala:1025)
	at sbt.Load$.resolveProject(Load.scala:703)
	at sbt.Load$.sbt$Load$$finalizeProject$1(Load.scala:603)
	at sbt.Load$.discoverAndLoad$1(Load.scala:620)
	at sbt.Load$.sbt$Load$$loadTransitive(Load.scala:629)
	at sbt.Load$.sbt$Load$$loadTransitive(Load.scala:644)
	at sbt.Load$$anonfun$loadUnit$1.sbt$Load$$anonfun$$loadProjects$1(Load.scala:482)
	at sbt.Load$$anonfun$loadUnit$1$$anonfun$40.apply(Load.scala:485)
	at sbt.Load$$anonfun$loadUnit$1$$anonfun$40.apply(Load.scala:485)
	at sbt.Load$.timed(Load.scala:1025)
	at sbt.Load$$anonfun$loadUnit$1.apply(Load.scala:485)
	at sbt.Load$$anonfun$loadUnit$1.apply(Load.scala:459)
	at sbt.Load$.timed(Load.scala:1025)
	at sbt.Load$.loadUnit(Load.scala:459)
	at sbt.Load$$anonfun$25$$anonfun$apply$14.apply(Load.scala:311)
	at sbt.Load$$anonfun$25$$anonfun$apply$14.apply(Load.scala:310)
	at sbt.BuildLoader$$anonfun$componentLoader$1$$anonfun$apply$4$$anonfun$apply$5$$anonfun$apply$6.apply(BuildLoader.scala:91)
	at sbt.BuildLoader$$anonfun$componentLoader$1$$anonfun$apply$4$$anonfun$apply$5$$anonfun$apply$6.apply(BuildLoader.scala:90)
	at sbt.BuildLoader.apply(BuildLoader.scala:140)
	at sbt.Load$.loadAll(Load.scala:365)
	at sbt.Load$.loadURI(Load.scala:320)
	at sbt.Load$.load(Load.scala:316)
	at sbt.Load$.load(Load.scala:305)
	at sbt.Load$$anonfun$4.apply(Load.scala:146)
	at sbt.Load$$anonfun$4.apply(Load.scala:146)
	at sbt.Load$.timed(Load.scala:1025)
	at sbt.Load$.apply(Load.scala:146)
	at sbt.Load$.defaultLoad(Load.scala:39)
	at sbt.BuiltinCommands$.liftedTree1$1(Main.scala:548)
	at sbt.BuiltinCommands$.doLoadProject(Main.scala:548)
	at sbt.BuiltinCommands$$anonfun$loadProjectImpl$2.apply(Main.scala:540)
	at sbt.BuiltinCommands$$anonfun$loadProjectImpl$2.apply(Main.scala:540)
	at sbt.Command$$anonfun$applyEffect$1$$anonfun$apply$2.apply(Command.scala:59)
	at sbt.Command$$anonfun$applyEffect$1$$anonfun$apply$2.apply(Command.scala:59)
	at sbt.Command$$anonfun$applyEffect$2$$anonfun$apply$3.apply(Command.scala:61)
	at sbt.Command$$anonfun$applyEffect$2$$anonfun$apply$3.apply(Command.scala:61)
	at sbt.Command$.process(Command.scala:93)
	at sbt.MainLoop$$anonfun$1$$anonfun$apply$1.apply(MainLoop.scala:96)
	at sbt.MainLoop$$anonfun$1$$anonfun$apply$1.apply(MainLoop.scala:96)
	at sbt.State$$anon$1.doX$1(State.scala:183)
	at sbt.State$$anon$1.process(State.scala:190)
	at sbt.MainLoop$$anonfun$1.apply(MainLoop.scala:96)
	at sbt.MainLoop$$anonfun$1.apply(MainLoop.scala:96)
	at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:17)
	at sbt.MainLoop$.next(MainLoop.scala:96)
	at sbt.MainLoop$.run(MainLoop.scala:89)
	at sbt.MainLoop$$anonfun$runWithNewLog$1.apply(MainLoop.scala:68)
	at sbt.MainLoop$$anonfun$runWithNewLog$1.apply(MainLoop.scala:63)
	at sbt.Using.apply(Using.scala:24)
	at sbt.MainLoop$.runWithNewLog(MainLoop.scala:63)
	at sbt.MainLoop$.runAndClearLast(MainLoop.scala:46)
	at sbt.MainLoop$.runLoggedLoop(MainLoop.scala:30)
	at sbt.MainLoop$.runLogged(MainLoop.scala:22)
	at sbt.StandardMain$.runManaged(Main.scala:109)
	at sbt.xMain.run(Main.scala:38)
	at xsbt.boot.Launch$$anonfun$run$1.apply(Launch.scala:109)
	at xsbt.boot.Launch$.withContextLoader(Launch.scala:128)
	at xsbt.boot.Launch$.run(Launch.scala:109)
	at xsbt.boot.Launch$$anonfun$apply$1.apply(Launch.scala:35)
	at xsbt.boot.Launch$.launch(Launch.scala:117)
	at xsbt.boot.Launch$.apply(Launch.scala:18)
	at xsbt.boot.Boot$.runImpl(Boot.scala:41)
	at xsbt.boot.Boot$.main(Boot.scala:17)
	at xsbt.boot.Boot.main(Boot.scala)
```

It turned out the project was using sbt `0.13.15`. Updating sbt to `0.13.16` fixes this (reverting plugin back to `0.6.19` does as well.)

So this is a pretty straight-forward fix, but probably some one else experiences this too.

**Comment by sjrd** [comment]
From [the release notes of 0.6.20](https://www.scala-js.org/news/2017/09/01/announcing-scalajs-0.6.20/):

> **sbt 0.13.16 or above is required (or sbt 1.x)**
>
> The sbt plugin of Scala.js 0.6.20 starts using features of sbt 0.13.16. If you are using an older version of sbt 0.13.x, you will have to upgrade to 0.13.16 or later.
>
> Since 0.6.19, Scala.js also supports sbt 1.0.0+.

**Comment by yurique** [comment]
Ouch, my bad. Didn't take a look there for some reason. Sorry for wasting your time :)
