### ISSUE TITLE
Our test suite does not pass on Node.js 8

### ISSUE THREAD

**Issue by sjrd** [scala-js/scala-js#3148]
The following tests fail:
```
> testSuite/testOnly org.scalajs.testsuite.junit.JUnitAssertionsTest org.scalajs.testsuite.javalib.util.ThrowablesTest
[warn] javaOptions will be ignored, fork is set to false
[info] Test run started
[info] Test org.scalajs.testsuite.javalib.util.ThrowablesTest.shouldDefineAllJavaUtilErrorsAndExceptions started
[error] Test org.scalajs.testsuite.javalib.util.ThrowablesTest.shouldDefineAllJavaUtilErrorsAndExceptions failed: scala.scalajs.js.JavaScriptException: TypeError: Cannot read property 'getName__T' of null, took 3.224 sec
[error]     at <jscode>.$c_ju_IllegalFormatConversionException.$c_O.toString(/localhome/doeraene/projects/scalajs/test-suite/js/target/scala-2.11/scalajs-test-suite-test-fastopt.js:15885)
[error]     at <jscode>.Function.prepareStackTrace(/localhome/doeraene/projects/scalajs/node_modules/source-map-support/source-map-support.js:377)
[error]     at <jscode>.Function.captureStackTrace@<anonymous>(Unknown Source)
[error]     at <jscode>.$c_ju_IllegalFormatConversionException.$c_jl_Throwable.fillInStackTrace__jl_Throwable(/localhome/doeraene/projects/scalajs/test-suite/js/target/scala-2.11/file:/localhome/doeraene/projects/scalajs/library/src/main/scala/scala/scalajs/runtime/StackTrace.scala:43)
[error]     at <jscode>.$c_ju_IllegalFormatConversionException.$c_jl_Throwable.init___T__jl_Throwable(/localhome/doeraene/projects/scalajs/test-suite/js/target/scala-2.11/file:/localhome/doeraene/projects/scalajs/javalanglib/src/main/scala/java/lang/Throwables.scala:12)
[error]     at java.util.IllegalFormatConversionException.this(/localhome/doeraene/projects/scalajs/test-suite/js/target/scala-2.11/file:/localhome/doeraene/projects/scalajs/javalanglib/src/main/scala/java/lang/Throwables.scala:267)
[error]     at java.util.IllegalFormatConversionException.this(/localhome/doeraene/projects/scalajs/test-suite/js/target/scala-2.11/file:/localhome/doeraene/projects/scalajs/javalib/src/main/scala/java/util/Throwables.scala:48)
[error]     at org.scalajs.testsuite.javalib.util.ThrowablesTest.shouldDefineAllJavaUtilErrorsAndExceptions(/localhome/doeraene/projects/scalajs/test-suite/js/target/scala-2.11/file:/localhome/doeraene/projects/scalajs/test-suite/shared/src/test/scala/org/scalajs/testsuite/javalib/util/ThrowablesTest.scala:23)
[info] Test run finished: 1 failed, 0 ignored, 1 total, 3.232s
[info] Test run started
[info] Test org.scalajs.testsuite.junit.JUnitAssertionsTest.testAssertArrayEquals started
[error] Test org.scalajs.testsuite.junit.JUnitAssertionsTest.testAssertArrayEquals failed: scala.scalajs.js.JavaScriptException: TypeError: Cannot read property 'head__O' of null, took 3.249000192 sec
[error]     at <jscode>.$c_Lorg_junit_internal_ArrayComparisonFailure.$c_O.toString(/localhome/doeraene/projects/scalajs/test-suite/js/target/scala-2.11/scalajs-test-suite-test-fastopt.js:15885)
[error]     at <jscode>.Function.prepareStackTrace(/localhome/doeraene/projects/scalajs/node_modules/source-map-support/source-map-support.js:377)
[error]     at <jscode>.Function.captureStackTrace@<anonymous>(Unknown Source)
[error]     at <jscode>.$c_Lorg_junit_internal_ArrayComparisonFailure.$c_jl_Throwable.fillInStackTrace__jl_Throwable(/localhome/doeraene/projects/scalajs/test-suite/js/target/scala-2.11/file:/localhome/doeraene/projects/scalajs/library/src/main/scala/scala/scalajs/runtime/StackTrace.scala:43)
[error]     at <jscode>.$c_Lorg_junit_internal_ArrayComparisonFailure.$c_jl_Throwable.init___T__jl_Throwable(/localhome/doeraene/projects/scalajs/test-suite/js/target/scala-2.11/file:/localhome/doeraene/projects/scalajs/javalanglib/src/main/scala/java/lang/Throwables.scala:12)
[error]     ...
[info] Test org.scalajs.testsuite.junit.JUnitAssertionsTest.testAssertArrayEqualsDouble started
[error] Test org.scalajs.testsuite.junit.JUnitAssertionsTest.testAssertArrayEqualsDouble failed: scala.scalajs.js.JavaScriptException: TypeError: Cannot read property 'head__O' of null, took 0.002000128 sec
[error]     at <jscode>.$c_Lorg_junit_internal_ArrayComparisonFailure.$c_O.toString(/localhome/doeraene/projects/scalajs/test-suite/js/target/scala-2.11/scalajs-test-suite-test-fastopt.js:15885)
[error]     at <jscode>.Function.prepareStackTrace(/localhome/doeraene/projects/scalajs/node_modules/source-map-support/source-map-support.js:377)
[error]     at <jscode>.Function.captureStackTrace@<anonymous>(Unknown Source)
[error]     at <jscode>.$c_Lorg_junit_internal_ArrayComparisonFailure.$c_jl_Throwable.fillInStackTrace__jl_Throwable(/localhome/doeraene/projects/scalajs/test-suite/js/target/scala-2.11/file:/localhome/doeraene/projects/scalajs/library/src/main/scala/scala/scalajs/runtime/StackTrace.scala:43)
[error]     at <jscode>.$c_Lorg_junit_internal_ArrayComparisonFailure.$c_jl_Throwable.init___T__jl_Throwable(/localhome/doeraene/projects/scalajs/test-suite/js/target/scala-2.11/file:/localhome/doeraene/projects/scalajs/javalanglib/src/main/scala/java/lang/Throwables.scala:12)
[error]     ...
[info] Test org.scalajs.testsuite.junit.JUnitAssertionsTest.testAssertArrayEqualsFloats started
[error] Test org.scalajs.testsuite.junit.JUnitAssertionsTest.testAssertArrayEqualsFloats failed: scala.scalajs.js.JavaScriptException: TypeError: Cannot read property 'head__O' of null, took 0.002000128 sec
[error]     at <jscode>.$c_Lorg_junit_internal_ArrayComparisonFailure.$c_O.toString(/localhome/doeraene/projects/scalajs/test-suite/js/target/scala-2.11/scalajs-test-suite-test-fastopt.js:15885)
[error]     at <jscode>.Function.prepareStackTrace(/localhome/doeraene/projects/scalajs/node_modules/source-map-support/source-map-support.js:377)
[error]     at <jscode>.Function.captureStackTrace@<anonymous>(Unknown Source)
[error]     at <jscode>.$c_Lorg_junit_internal_ArrayComparisonFailure.$c_jl_Throwable.fillInStackTrace__jl_Throwable(/localhome/doeraene/projects/scalajs/test-suite/js/target/scala-2.11/file:/localhome/doeraene/projects/scalajs/library/src/main/scala/scala/scalajs/runtime/StackTrace.scala:43)
[error]     at <jscode>.$c_Lorg_junit_internal_ArrayComparisonFailure.$c_jl_Throwable.init___T__jl_Throwable(/localhome/doeraene/projects/scalajs/test-suite/js/target/scala-2.11/file:/localhome/doeraene/projects/scalajs/javalanglib/src/main/scala/java/lang/Throwables.scala:12)
[error]     ...
[info] Test org.scalajs.testsuite.junit.JUnitAssertionsTest.testAssertEquals started
[info] Test org.scalajs.testsuite.junit.JUnitAssertionsTest.testAssertEqualsByte started
[info] Test org.scalajs.testsuite.junit.JUnitAssertionsTest.testAssertEqualsChar started
[info] Test org.scalajs.testsuite.junit.JUnitAssertionsTest.testAssertEqualsDouble started
[info] Test org.scalajs.testsuite.junit.JUnitAssertionsTest.testAssertEqualsFloat started
[info] Test org.scalajs.testsuite.junit.JUnitAssertionsTest.testAssertEqualsInt started
[info] Test org.scalajs.testsuite.junit.JUnitAssertionsTest.testAssertEqualsLong started
[info] Test org.scalajs.testsuite.junit.JUnitAssertionsTest.testAssertEqualsShort started
[info] Test org.scalajs.testsuite.junit.JUnitAssertionsTest.testAssertNull started
[info] Test org.scalajs.testsuite.junit.JUnitAssertionsTest.testAssertSame started
[info] Test org.scalajs.testsuite.junit.JUnitAssertionsTest.testAssertThat started
[info] Test org.scalajs.testsuite.junit.JUnitAssertionsTest.testAssertThrows started
[info] Test org.scalajs.testsuite.junit.JUnitAssertionsTest.testAssertTrueFalse started
[info] Test org.scalajs.testsuite.junit.JUnitAssertionsTest.testExpectThrows started
[info] Test org.scalajs.testsuite.junit.JUnitAssertionsTest.testIfAssertsTest_issue_2252 started
[info] Test run finished: 3 failed, 0 ignored, 18 total, 3.344s
[error] Failed: Total 19, Failed 4, Errors 0, Passed 15
[error] Failed tests:
[error]         org.scalajs.testsuite.junit.JUnitAssertionsTest
[error]         org.scalajs.testsuite.javalib.util.ThrowablesTest
[error] (testSuite/test:testOnly) sbt.TestsFailedException: Tests unsuccessful
[error] Total time: 17 s, completed Oct 6, 2017 12:54:10 PM
```
They pass if we deactivate `source-map-support`. It happens because, somehow, with source-map-support on Node.js 8, the `toString()` of exceptions can be called before their constructor has finished executing, which causes things like `NullPointerException`s due to `val`s not yet being initialized.

**Comment by sjrd** [comment]
Fixed in 4b42ad7d538fc8703126aec4abe82afe06a0970f.
