### ISSUE TITLE
CLI should release threads properly

### ISSUE THREAD

**Issue by Andrei-Pozolotin** [scala-js/scala-js#3169]
when invoked with `exec-maven-plugin:1.6.0:java` 
scala js `cli` invocation produces spurious errors
due to non-release of threads upon `main()` termination

```
					<plugin>
						<groupId>org.codehaus.mojo</groupId>
						<artifactId>exec-maven-plugin</artifactId>
						<dependencies>
							<dependency>
								<groupId>org.scala-js</groupId>
								<artifactId>scalajs-cli_${projectScalaVersion}</artifactId>
								<version>${projectScalaJsVersion}</version>
							</dependency>
						</dependencies>
						<executions>
							<execution>
								<id>make-js</id>
								<phase>${sjs.phase}</phase>
								<goals>
									<goal>java</goal>
								</goals>
								<configuration>
									<cleanupDaemonThreads>true</cleanupDaemonThreads>
									<daemonThreadJoinTimeout>100</daemonThreadJoinTimeout>
									<includePluginDependencies>true</includePluginDependencies>
									<includeProjectDependencies>false</includeProjectDependencies>
									<mainClass>org.scalajs.cli.Scalajsld</mainClass>
									<commandlineArgs>${sjs.arguments}</commandlineArgs>
								</configuration>
							</execution>
						</executions>
					</plugin>
```

```
INFO] Executed tasks
[INFO] 
[INFO] --- exec-maven-plugin:1.6.0:java (make-js) @ sjs_scalajs-vue ---
Linker: Compute reachability: 238903 us
Linker: Assemble LinkedClasses: 297333 us
Basic Linking: 568929 us
Inc. optimizer: Batch mode: true
Inc. optimizer: Incremental part: 203418 us
Inc. optimizer: Optimizing 2036 methods.
Inc. optimizer: Optimizer part: 319942 us
Inc. optimizer: 536382 us
Refiner: Compute reachability: 41367 us
Refiner: Assemble LinkedClasses: 10015 us
Refiner: 53381 us
Emitter: Class tree cache stats: reused: 239 -- invalidated: 249
Emitter: Method tree cache stats: resued: 0 -- invalidated: 940
Emitter (write output): 426581 us
[WARNING] thread Thread[scala-execution-context-global-29,5,org.scalajs.cli.Scalajsld] was interrupted but is still alive after waiting at least 100msecs
[WARNING] thread Thread[scala-execution-context-global-29,5,org.scalajs.cli.Scalajsld] will linger despite being asked to die via interruption
[WARNING] thread Thread[scala-execution-context-global-30,5,org.scalajs.cli.Scalajsld] will linger despite being asked to die via interruption
[WARNING] thread Thread[scala-execution-context-global-31,5,org.scalajs.cli.Scalajsld] will linger despite being asked to die via interruption
[WARNING] thread Thread[scala-execution-context-global-32,5,org.scalajs.cli.Scalajsld] will linger despite being asked to die via interruption
[WARNING] thread Thread[scala-execution-context-global-33,5,org.scalajs.cli.Scalajsld] will linger despite being asked to die via interruption
[WARNING] thread Thread[scala-execution-context-global-34,5,org.scalajs.cli.Scalajsld] will linger despite being asked to die via interruption
[WARNING] thread Thread[scala-execution-context-global-35,5,org.scalajs.cli.Scalajsld] will linger despite being asked to die via interruption
[WARNING] thread Thread[scala-execution-context-global-36,5,org.scalajs.cli.Scalajsld] will linger despite being asked to die via interruption
[WARNING] thread Thread[scala-execution-context-global-37,5,org.scalajs.cli.Scalajsld] will linger despite being asked to die via interruption
[WARNING] thread Thread[scala-execution-context-global-38,5,org.scalajs.cli.Scalajsld] will linger despite being asked to die via interruption
[WARNING] thread Thread[scala-execution-context-global-39,5,org.scalajs.cli.Scalajsld] will linger despite being asked to die via interruption
[WARNING] thread Thread[scala-execution-context-global-40,5,org.scalajs.cli.Scalajsld] will linger despite being asked to die via interruption
[WARNING] thread Thread[scala-execution-context-global-41,5,org.scalajs.cli.Scalajsld] will linger despite being asked to die via interruption
[WARNING] thread Thread[scala-execution-context-global-42,5,org.scalajs.cli.Scalajsld] will linger despite being asked to die via interruption
[WARNING] thread Thread[scala-execution-context-global-43,5,org.scalajs.cli.Scalajsld] will linger despite being asked to die via interruption
[WARNING] thread Thread[scala-execution-context-global-44,5,org.scalajs.cli.Scalajsld] will linger despite being asked to die via interruption
[WARNING] thread Thread[scala-execution-context-global-45,5,org.scalajs.cli.Scalajsld] will linger despite being asked to die via interruption
[WARNING] thread Thread[scala-execution-context-global-46,5,org.scalajs.cli.Scalajsld] will linger despite being asked to die via interruption
[WARNING] thread Thread[scala-execution-context-global-47,5,org.scalajs.cli.Scalajsld] will linger despite being asked to die via interruption
[WARNING] thread Thread[scala-execution-context-global-48,5,org.scalajs.cli.Scalajsld] will linger despite being asked to die via interruption
[WARNING] thread Thread[scala-execution-context-global-49,5,org.scalajs.cli.Scalajsld] will linger despite being asked to die via interruption
[WARNING] thread Thread[scala-execution-context-global-51,5,org.scalajs.cli.Scalajsld] will linger despite being asked to die via interruption
[WARNING] thread Thread[scala-execution-context-global-50,5,org.scalajs.cli.Scalajsld] will linger despite being asked to die via interruption
[WARNING] thread Thread[scala-execution-context-global-52,5,org.scalajs.cli.Scalajsld] will linger despite being asked to die via interruption
[WARNING] thread Thread[scala-execution-context-global-53,5,org.scalajs.cli.Scalajsld] will linger despite being asked to die via interruption
[WARNING] thread Thread[scala-execution-context-global-54,5,org.scalajs.cli.Scalajsld] will linger despite being asked to die via interruption
[WARNING] thread Thread[scala-execution-context-global-55,5,org.scalajs.cli.Scalajsld] will linger despite being asked to die via interruption
[WARNING] thread Thread[scala-execution-context-global-56,5,org.scalajs.cli.Scalajsld] will linger despite being asked to die via interruption
[WARNING] thread Thread[scala-execution-context-global-57,5,org.scalajs.cli.Scalajsld] will linger despite being asked to die via interruption
[WARNING] thread Thread[scala-execution-context-global-58,5,org.scalajs.cli.Scalajsld] will linger despite being asked to die via interruption
[WARNING] thread Thread[scala-execution-context-global-59,5,org.scalajs.cli.Scalajsld] will linger despite being asked to die via interruption
[WARNING] thread Thread[scala-execution-context-global-60,5,org.scalajs.cli.Scalajsld] will linger despite being asked to die via interruption
[WARNING] NOTE: 32 thread(s) did not finish despite being asked to  via interruption. This is not a problem with exec:java, it is a problem with the running code. Although not serious, it should be remedied.
[WARNING] Couldn't destroy threadgroup org.codehaus.mojo.exec.ExecJavaMojo$IsolatedThreadGroup[name=org.scalajs.cli.Scalajsld,maxpri=10]
java.lang.IllegalThreadStateException
	at java.lang.ThreadGroup.destroy(ThreadGroup.java:778)
	at org.codehaus.mojo.exec.ExecJavaMojo.execute(ExecJavaMojo.java:321)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:207)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:307)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:193)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:106)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:863)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:288)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:199)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
[INFO] 
```

**Comment by sjrd** [comment]
Looks like those are from the global `ExecutionContext` of Scala. I think this should be reported upstream to https://github.com/scala/bug

**Comment by Andrei-Pozolotin** [comment]
cli could use custom `ExecutionContext`, right?

**Comment by sjrd** [comment]
Yes but what would we do that when the original one could be fixed instead, improving the lives of everyone else using Futures in Scala?

**Comment by Andrei-Pozolotin** [comment]
we've seen this bug for few years now;
given 2K+ bugs in scala (possible indefinite fix time),
can you pretty please improve lives for scala-js, for now? 
![image](https://user-images.githubusercontent.com/1622151/32421012-2e0c9454-c259-11e7-8df3-d0f43838732c.png)

**Comment by Andrei-Pozolotin** [comment]
can this help:
https://github.com/scala/bug/issues/10587#issuecomment-342003796
>> It's possible to get a normal global by passing null to the factory method, supplying a reporter which detects the interruption.

**Comment by som-snytt** [comment]
It's not obvious to me that the `cleanupDaemonThreads` option is well-conceived.

**Comment by sjrd** [comment]
It looks like https://github.com/scala/bug/issues/10587 will be fixed upstream, so I'll close this here.
