### ISSUE TITLE
Node Exited with .toString Failed when run tests

### ISSUE THREAD

**Issue by cheeseng** [scala-js/scala-js#3230]
Hi all, 

We encountered the following node-js error when trying to run our tests: 

```
[info] Fast optimizing /home/cheeseng/git/scalatest/scalatest-test.js/target/scala-2.11/scalatesttestjs-test-fastopt.js
[error] buffer.js:385
[error]     throw new Error('toString failed');
[error]     ^
[error] 
[error] Error: toString failed
[error]     at Buffer.toString (buffer.js:385:11)
[error]     at Object.fs.readFileSync (fs.js:461:33)
[error]     at Object.Module._extensions..js (module.js:416:20)
[error]     at Module.load (module.js:344:32)
[error]     at Function.Module._load (module.js:301:12)
[error]     at Module.require (module.js:354:17)
[error]     at require (internal/module.js:12:17)
[error]     at [stdin]:38:1
[error]     at Object.exports.runInThisContext (vm.js:54:17)
[error]     at Object.<anonymous> ([stdin]-wrapper:6:22)
org.scalajs.jsenv.ExternalJSEnv$NonZeroExitException: Node.js exited with code 1
	at org.scalajs.jsenv.ExternalJSEnv$AbstractExtRunner.waitForVM(ExternalJSEnv.scala:119)
	at org.scalajs.jsenv.ExternalJSEnv$ExtRunner.run(ExternalJSEnv.scala:168)
	at org.scalajs.sbtplugin.FrameworkDetector.detect(FrameworkDetector.scala:71)
	at org.scalajs.sbtplugin.ScalaJSPluginInternal$$anonfun$79.apply(ScalaJSPluginInternal.scala:1004)
	at org.scalajs.sbtplugin.ScalaJSPluginInternal$$anonfun$79.apply(ScalaJSPluginInternal.scala:981)
	at scala.Function1$$anonfun$compose$1.apply(Function1.scala:47)
	at sbt.$tilde$greater$$anonfun$$u2219$1.apply(TypeFunctions.scala:40)
	at sbt.std.Transform$$anon$4.work(System.scala:63)
	at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:228)
	at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:228)
	at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:17)
	at sbt.Execute.work(Execute.scala:237)
	at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:228)
	at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:228)
	at sbt.ConcurrentRestrictions$$anon$4$$anonfun$1.apply(ConcurrentRestrictions.scala:159)
	at sbt.CompletionService$$anon$2.call(CompletionService.scala:28)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
[error] (scalatestTestJS/test:loadedTestFrameworks) org.scalajs.jsenv.ExternalJSEnv$NonZeroExitException: Node.js exited with code 1
[error] Total time: 83 s, completed Dec 19, 2017 3:40:02 PM
```

The problem can be reproduce by checking out this branch: 

```
https://github.com/cheeseng/scalatest/tree/node-js-debug
```

by doing: 

```
> sbt ++2.11.12 scalatestAppJS/clean
> sbt ++2.11.12 scalatestTestJS/test:compile
> sbt ++2.11.12 scalatestTestJS/test
```

We only encountered this error under scala 2.11, scala 2.12 works fine.

Thanks.

**Comment by sjrd** [comment]
This seems to be a Node.js/V8 limitation. The `-fastopt.js` module produced by `scalatestTestJS/test:fastOptJS` in 2.11.12 weighs **266.4 MB**. According to [this issue](https://github.com/nodejs/node/issues/3175), the string length limit in V8 is 256 MB. And when loading the module, it first loads it into a `Buffer` then calls `toString()` on it before parsing it, etc. This call to `toString()` fails because the resulting string to be bigger than 256 MB.

The very first thing I'd try to do is put `@noinline` on all the methods that look like
```scala
def test(...)(body: => T): U
```
so that when they're called as
```scala
test("should not blow up the code size") {
  assert(1 == 1)
}
```
the optimizer does not try to inline `test`. It is usually a good idea to inline higher-order methods, but for `test` that's just silly. The optimizer doesn't know, though, so telling it with `@noinline` would most likely improve the code size, *and* the time spent optimizing, *and* the amount of required RAM.

**Comment by cheeseng** [comment]
@sjrd adding ```@noinline``` does not seem to help with reducing the output file size, but after reading: 

https://monorail-prod.appspot.com/p/v8/issues/detail?id=6148

It seems that the limit was increased in version V8 6.2.10, I had 4.x node so I updated node to the latest node 9.3.0 and tests start running again!

I think we're fine at the moment, though in future it will be nice to break our tests in smaller partition so we can enjoy the reduced time and required RAM benefit that you mentioned.

Thanks again for your great help!
