### ISSUE TITLE
Add support names with dashes (which are valid JS identifiers) in commonJSName in sbt-scalajs plugin

### ISSUE THREAD

**Issue by dborisenko** [scala-js/scala-js#3254]
When I'm trying to add the following dependency:
```
"org.webjars.npm" % "storm-react-diagrams" % "3.2.0"  / "main.js" dependsOn "react-dom.js" commonJSName "storm-react-diagrams"
```
my sbt fails with the follwoing error message:
```
[error] java.lang.IllegalArgumentException: requirement failed: commonJSName must be a valid JavaScript identifier
[error] 	at scala.Predef$.require(Predef.scala:277)
[error] 	at org.scalajs.core.tools.jsdep.JSDependency.<init>(JSDependency.scala:33)
[error] 	at org.scalajs.core.tools.jsdep.JSDependency.copy(JSDependency.scala:48)
[error] 	at org.scalajs.core.tools.jsdep.JSDependency.commonJSName(JSDependency.scala:38)
[error] 	at org.scalajs.sbtplugin.JSModuleID.commonJSName(AbstractJSDeps.scala:33)
[error] 	at org.scalajs.sbtplugin.JSModuleID.commonJSName$(AbstractJSDeps.scala:32)
[error] 	at org.scalajs.sbtplugin.JarJSModuleID.commonJSName(AbstractJSDeps.scala:43)
[error] 	at $370d99c2a23361f9fc14$.$anonfun$plan$minusbuilder$minusclient$4(build.sbt:82)
[error] 	at sbt.internal.util.EvaluateSettings$MixedNode.evaluate0(INode.scala:214)
[error] 	at sbt.internal.util.EvaluateSettings$INode.evaluate(INode.scala:159)
[error] 	at sbt.internal.util.EvaluateSettings.$anonfun$submitEvaluate$1(INode.scala:82)
[error] 	at sbt.internal.util.EvaluateSettings.sbt$internal$util$EvaluateSettings$$run0(INode.scala:93)
[error] 	at sbt.internal.util.EvaluateSettings$$anon$3.run(INode.scala:89)
[error] 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
[error] 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
[error] 	at java.base/java.lang.Thread.run(Thread.java:844)
[error] java.lang.IllegalArgumentException: requirement failed: commonJSName must be a valid JavaScript identifier
[error] Use 'last' for the full log.
```

So, my question is, why dashes are not supported in commonJSName? Keys with dashes are valid JavaScript identifiers (you can access them by `$g["storm-react-diagrams"]`).

**Comment by sjrd** [comment]
Because `commonJSName` is used to define a `var`, not a property on `$g`, and therefore dashes would not work.

Note that if you're doing anything serious with `jsDependencies`, you should really consider [scalajs-bundler](https://scalacenter.github.io/scalajs-bundler/) instead.

**Comment by dborisenko** [comment]
Ah, now I see. I will check scalajs-bundler then. Thank you @sjrd for your response.
