### ISSUE TITLE
circeGenericInstanceFor::$2 is not a valid identifier when using Circe + Tuples

### ISSUE THREAD

**Issue by baank** [scala-js/scala-js#3256]
When trying to use Circe SemiAuto serialisation with Tuples the following error occurs when compiling:

````
[error] java.lang.IllegalArgumentException: requirement failed: circeGenericInstanceFor::$2 is not a valid identifier
[error]     at scala.Predef$.require(Predef.scala:277)
[error]     at org.scalajs.core.ir.Trees$.requireValidIdent(Trees.scala:63)
[error]     at org.scalajs.core.ir.Trees$Ident.<init>(Trees.scala:46)
[error]     at org.scalajs.core.compiler.JSEncoding.encodeFieldSym(JSEncoding.scala:136)
[error]     at org.scalajs.core.compiler.JSEncoding.encodeFieldSym$(JSEncoding.scala:89)
````

When run with -Ymacro-debug-lite the following identifiers are produced by Circe:
````
private[this] val circeGenericInstanceFor_2 = circe.this.Decoder.decodeInt;
````

**Comment by sjrd** [comment]
Could you please provide a reproduction?

**Comment by baank** [comment]
It's due to issue: https://github.com/circe/circe/issues/819

Maybe ScalaJS follow the JVM and allow any identifier but then rewrite it to be acceptable to JS internally.

**Comment by sjrd** [comment]
The issue was closed in circe.
