### ISSUE TITLE
NPE on fold of erroneous or inaccessible type

### ISSUE THREAD

**Issue by andreaTP** [scala-js/scala-js#3262]
The compiler is throwing a NPE in the condition you have:

 - `erroneous or inaccessible type [error]   val node: raw.Node = ul().render`
 - an operation like 'fold' that uses it

adding as library:
`com.lihaoyi" %%% "scalatags" % "0.6.3"`
with scala 2.12.4

a minimal repro is:
```scala
import scala.scalajs.js._
import org.scalajs.dom
import org.scalajs.dom.ext.Ajax

import scalatags.JsDom._
import scalatags.JsDom.all._

object Main extends App {

  val node: raw.Node = ul().render

  Seq().fold(node)(_ => _)

  dom.document.body.appendChild(node)
}
```

The stacktrace of the error is:
```
[error] java.lang.NullPointerException
[error] 	at org.scalajs.core.compiler.PrepJSInterop$JSInteropTransformer.transform(PrepJSInterop.scala:254)
[error] 	at org.scalajs.core.compiler.PrepJSInterop$JSInteropTransformer.transform(PrepJSInterop.scala:83)
[error] 	at scala.reflect.api.Trees$Transformer.$anonfun$transformTrees$1(Trees.scala:2559)
[error] 	at scala.reflect.api.Trees$Transformer.transformTrees(Trees.scala:2559)
[error] 	at scala.reflect.internal.Trees.itransform(Trees.scala:1359)
[error] 	at scala.reflect.internal.Trees.itransform$(Trees.scala:1348)
[error] 	at scala.reflect.internal.SymbolTable.itransform(SymbolTable.scala:16)
[error] 	at scala.reflect.internal.SymbolTable.itransform(SymbolTable.scala:16)
[error] 	at scala.reflect.api.Trees$Transformer.transform(Trees.scala:2555)
[error] 	at org.scalajs.core.compiler.PrepJSInterop$JSInteropTransformer.transform(PrepJSInterop.scala:372)
[error] 	at org.scalajs.core.compiler.PrepJSInterop$JSInteropTransformer.transform(PrepJSInterop.scala:83)
[error] 	at scala.reflect.api.Trees$Transformer.$anonfun$transformStats$2(Trees.scala:2588)
[error] 	at scala.reflect.api.Trees$Transformer.atOwner(Trees.scala:2600)
[error] 	at scala.reflect.api.Trees$Transformer.$anonfun$transformStats$1(Trees.scala:2588)
[error] 	at scala.reflect.api.Trees$Transformer.transformStats(Trees.scala:2587)
[error] 	at scala.reflect.internal.Trees.itransform(Trees.scala:1416)
[error] 	at scala.reflect.internal.Trees.itransform$(Trees.scala:1348)
[error] 	at scala.reflect.internal.SymbolTable.itransform(SymbolTable.scala:16)
[error] 	at scala.reflect.internal.SymbolTable.itransform(SymbolTable.scala:16)
[error] 	at scala.reflect.api.Trees$Transformer.transform(Trees.scala:2555)
[error] 	at org.scalajs.core.compiler.PrepJSInterop$JSInteropTransformer.transform(PrepJSInterop.scala:372)
[error] 	at org.scalajs.core.compiler.PrepJSInterop$JSInteropTransformer.transform(PrepJSInterop.scala:83)
[error] 	at scala.reflect.api.Trees$Transformer.transformTemplate(Trees.scala:2563)
[error] 	at scala.reflect.internal.Trees.$anonfun$itransform$5(Trees.scala:1425)
[error] 	at scala.reflect.api.Trees$Transformer.atOwner(Trees.scala:2600)
[error] 	at scala.reflect.internal.Trees.itransform(Trees.scala:1424)
[error] 	at scala.reflect.internal.Trees.itransform$(Trees.scala:1348)
[error] 	at scala.reflect.internal.SymbolTable.itransform(SymbolTable.scala:16)
[error] 	at scala.reflect.internal.SymbolTable.itransform(SymbolTable.scala:16)
[error] 	at scala.reflect.api.Trees$Transformer.transform(Trees.scala:2555)
[error] 	at org.scalajs.core.compiler.PrepJSInterop$JSInteropTransformer.super$transform(PrepJSInterop.scala:178)
[error] 	at org.scalajs.core.compiler.PrepJSInterop$JSInteropTransformer.$anonfun$transform$6(PrepJSInterop.scala:219)
[error] 	at org.scalajs.core.compiler.PrepJSInterop$JSInteropTransformer.enterOwner(PrepJSInterop.scala:113)
[error] 	at org.scalajs.core.compiler.PrepJSInterop$JSInteropTransformer.transform(PrepJSInterop.scala:219)
[error] 	at org.scalajs.core.compiler.PrepJSInterop$JSInteropTransformer.transform(PrepJSInterop.scala:83)
[error] 	at scala.reflect.api.Trees$Transformer.$anonfun$transformStats$1(Trees.scala:2589)
[error] 	at scala.reflect.api.Trees$Transformer.transformStats(Trees.scala:2587)
[error] 	at scala.reflect.internal.Trees.$anonfun$itransform$7(Trees.scala:1438)
[error] 	at scala.reflect.api.Trees$Transformer.atOwner(Trees.scala:2600)
[error] 	at scala.reflect.internal.Trees.itransform(Trees.scala:1438)
[error] 	at scala.reflect.internal.Trees.itransform$(Trees.scala:1348)
[error] 	at scala.reflect.internal.SymbolTable.itransform(SymbolTable.scala:16)
[error] 	at scala.reflect.internal.SymbolTable.itransform(SymbolTable.scala:16)
[error] 	at scala.reflect.api.Trees$Transformer.transform(Trees.scala:2555)
[error] 	at org.scalajs.core.compiler.PrepJSInterop$JSInteropTransformer.transform(PrepJSInterop.scala:372)
[error] 	at org.scalajs.core.compiler.PrepJSInterop$JSInteropTransformer.transform(PrepJSInterop.scala:83)
[error] 	at scala.tools.nsc.ast.Trees$Transformer.transformUnit(Trees.scala:140)
[error] 	at scala.tools.nsc.transform.Transform$Phase.apply(Transform.scala:30)
[error] 	at scala.tools.nsc.Global$GlobalPhase.$anonfun$applyPhase$1(Global.scala:436)
[error] 	at scala.tools.nsc.Global$GlobalPhase.applyPhase(Global.scala:429)
[error] 	at scala.tools.nsc.Global$GlobalPhase.$anonfun$run$1(Global.scala:400)
[error] 	at scala.tools.nsc.Global$GlobalPhase.$anonfun$run$1$adapted(Global.scala:400)
[error] 	at scala.collection.Iterator.foreach(Iterator.scala:929)
[error] 	at scala.collection.Iterator.foreach$(Iterator.scala:929)
[error] 	at scala.collection.AbstractIterator.foreach(Iterator.scala:1417)
[error] 	at scala.tools.nsc.Global$GlobalPhase.run(Global.scala:400)
[error] 	at org.scalajs.core.compiler.PrepJSInterop$JSInteropPhase.run(PrepJSInterop.scala:58)
[error] 	at scala.tools.nsc.Global$Run.compileUnitsInternal(Global.scala:1452)
[error] 	at scala.tools.nsc.Global$Run.compileUnits(Global.scala:1436)
[error] 	at scala.tools.nsc.Global$Run.compileSources(Global.scala:1429)
[error] 	at scala.tools.nsc.Global$Run.compile(Global.scala:1545)
[error] 	at xsbt.CachedCompiler0.run(CompilerInterface.scala:130)
[error] 	at xsbt.CachedCompiler0.run(CompilerInterface.scala:105)
[error] 	at xsbt.CompilerInterface.run(CompilerInterface.scala:31)
[error] 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[error] 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[error] 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[error] 	at java.lang.reflect.Method.invoke(Method.java:498)
[error] 	at sbt.internal.inc.AnalyzingCompiler.call(AnalyzingCompiler.scala:237)
[error] 	at sbt.internal.inc.AnalyzingCompiler.compile(AnalyzingCompiler.scala:111)
[error] 	at sbt.internal.inc.AnalyzingCompiler.compile(AnalyzingCompiler.scala:90)
[error] 	at sbt.internal.inc.MixedAnalyzingCompiler.$anonfun$compile$3(MixedAnalyzingCompiler.scala:83)
[error] 	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:12)
[error] 	at sbt.internal.inc.MixedAnalyzingCompiler.timed(MixedAnalyzingCompiler.scala:134)
[error] 	at sbt.internal.inc.MixedAnalyzingCompiler.compileScala$1(MixedAnalyzingCompiler.scala:74)
[error] 	at sbt.internal.inc.MixedAnalyzingCompiler.compile(MixedAnalyzingCompiler.scala:117)
[error] 	at sbt.internal.inc.IncrementalCompilerImpl.$anonfun$compileInternal$1(IncrementalCompilerImpl.scala:305)
[error] 	at sbt.internal.inc.IncrementalCompilerImpl.$anonfun$compileInternal$1$adapted(IncrementalCompilerImpl.scala:305)
[error] 	at sbt.internal.inc.Incremental$.doCompile(Incremental.scala:101)
[error] 	at sbt.internal.inc.Incremental$.$anonfun$compile$4(Incremental.scala:82)
[error] 	at sbt.internal.inc.IncrementalCommon.recompileClasses(IncrementalCommon.scala:110)
[error] 	at sbt.internal.inc.IncrementalCommon.cycle(IncrementalCommon.scala:57)
[error] 	at sbt.internal.inc.Incremental$.$anonfun$compile$3(Incremental.scala:84)
[error] 	at sbt.internal.inc.Incremental$.manageClassfiles(Incremental.scala:129)
[error] 	at sbt.internal.inc.Incremental$.compile(Incremental.scala:75)
[error] 	at sbt.internal.inc.IncrementalCompile$.apply(Compile.scala:61)
[error] 	at sbt.internal.inc.IncrementalCompilerImpl.compileInternal(IncrementalCompilerImpl.scala:309)
[error] 	at sbt.internal.inc.IncrementalCompilerImpl.$anonfun$compileIncrementally$1(IncrementalCompilerImpl.scala:267)
[error] 	at sbt.internal.inc.IncrementalCompilerImpl.handleCompilationError(IncrementalCompilerImpl.scala:158)
[error] 	at sbt.internal.inc.IncrementalCompilerImpl.compileIncrementally(IncrementalCompilerImpl.scala:237)
[error] 	at sbt.internal.inc.IncrementalCompilerImpl.compile(IncrementalCompilerImpl.scala:68)
[error] 	at sbt.Defaults$.compileIncrementalTaskImpl(Defaults.scala:1427)
[error] 	at sbt.Defaults$.$anonfun$compileIncrementalTask$1(Defaults.scala:1401)
[error] 	at scala.Function1.$anonfun$compose$1(Function1.scala:44)
[error] 	at sbt.internal.util.$tilde$greater.$anonfun$$u2219$1(TypeFunctions.scala:39)
[error] 	at sbt.std.Transform$$anon$4.work(System.scala:66)
[error] 	at sbt.Execute.$anonfun$submit$2(Execute.scala:262)
[error] 	at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:16)
[error] 	at sbt.Execute.work(Execute.scala:271)
[error] 	at sbt.Execute.$anonfun$submit$1(Execute.scala:262)
[error] 	at sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:174)
[error] 	at sbt.CompletionService$$anon$2.call(CompletionService.scala:36)
[error] 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error] 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[error] 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
[error] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
[error] 	at java.lang.Thread.run(Thread.java:745)
[error] (Compile / compileIncremental) java.lang.NullPointerException
```

**Comment by sjrd** [comment]
Are Scalatags and scalajs-dom really necessary to reproduce the crash?

**Comment by andreaTP** [comment]
not sure actually, probably it can be narrowed down better

**Comment by sjrd** [comment]
Thanks for the minimization.

It also crashes with a stock 2.12.4 Scala/JVM compiler, so it's not Scala.js' fault. It doesn't crash with 2.12.3, neither with Scala/JVM nor Scala.js. You should report this bug to https://github.com/scala/bug instead, assuming there isn't already a ticket about it.

**Comment by andreaTP** [comment]
sounds good.
thanks sorry for the noise
