### ISSUE TITLE
–Xdisable-assertions Not working

### ISSUE THREAD

**Issue by sumnulu** [scala-js/scala-js#3313]
rep: https://github.com/sumnulu/scalajs-assertion-dis-bug1
`scalacOptions += "–Xdisable-assertions"` Should remove assertion code. 

```
sbt:Assertion Bug 1> run
[info] Compiling 1 Scala source to /Users/sumnulu/Projects/scalajsBug1/target/scala-2.12/classes ...
[info] Done compiling.
[info] Fast optimizing /Users/sumnulu/Projects/scalajsBug1/target/scala-2.12/assertion-bug-1-fastopt.js
[info] Running bug.TutorialApp
Hello world!
/Users/sumnulu/Projects/scalajsBug1/target/scala-2.12/assertion-bug-1-fastopt.js:1947
  throw new $c_jl_AssertionError().init___O("assertion failed: 11aabb")
  ^

Error
    at $c_jl_AssertionError.$c_jl_Throwable.fillInStackTrace__jl_Throwable (/Users/sumnulu/Projects/scalajsBug1/target/scala-2.12/assertion-bug-1-fastopt.js:1751:14)
    at $c_jl_AssertionError.$c_jl_Throwable.init___T__jl_Throwable (/Users/sumnulu/Projects/scalajsBug1/target/scala-2.12/assertion-bug-1-fastopt.js:1767:8)
    at $c_jl_AssertionError.init___O (/Users/sumnulu/Projects/scalajsBug1/target/scala-2.12/assertion-bug-1-fastopt.js:2540:52)
    at $c_Lbug_TutorialApp$.delayedEndpoint$bug$TutorialApp$1__V (/Users/sumnulu/Projects/scalajsBug1/target/scala-2.12/assertion-bug-1-fastopt.js:1947:36)
    at $c_Lbug_TutorialApp$delayedInit$body.apply__O (/Users/sumnulu/Projects/scalajsBug1/target/scala-2.12/assertion-bug-1-fastopt.js:1986:18)
    at $f_s_App__main__AT__V (/Users/sumnulu/Projects/scalajsBug1/target/scala-2.12/assertion-bug-1-fastopt.js:1272:10)
    at $c_Lbug_TutorialApp$.main__AT__V (/Users/sumnulu/Projects/scalajsBug1/target/scala-2.12/assertion-bug-1-fastopt.js:1941:3)
    at Object.<anonymous> (/Users/sumnulu/Projects/scalajsBug1/target/scala-2.12/assertion-bug-1-fastopt.js:4061:24)
    at Object.<anonymous> (/Users/sumnulu/Projects/scalajsBug1/target/scala-2.12/assertion-bug-1-fastopt.js:4062:4)
    at Module._compile (module.js:643:30)
```

**Comment by sjrd** [comment]
This behaves the same as on the JVM. Comment out the `enablePlugins(ScalaJSPlugin)` to verify it. So this is not a Scala.js bug. If any, it is a Scala/JVM bug to be reported at https://github.com/scala/bug

Perhaps you wanted to use
```scala
scalacOptions ++= Seq("-Xelide-below", "5000")
```
instead? (which works both on Scala/JVM and Scala.js)

**Comment by sumnulu** [comment]
Ok will do thanks!
