### ISSUE TITLE
Sporadic test failures in org.scalajs.testcommon.RPCCore (NullPointerException)

### ISSUE THREAD

**Issue by tpolecat** [scala-js/scala-js#3408]
We're finding that our CI build fails about 10% of the time with a `ClosedException` caused by an NPE down in the guts. Has anyone run into this before? Any clues?

/cc @cquiroz 

```
Scala.js Com failed: Error: read ECONNRESET
  | [error] org.scalajs.testcommon.RPCCore$ClosedException
  | [error] 	at org.scalajs.testcommon.RPCCore.helpClose(RPCCore.scala:193)
  | [error] 	at org.scalajs.testcommon.RPCCore.call(RPCCore.scala:134)
  | [error] 	at org.scalajs.testcommon.RunMuxRPC.call(RunMuxRPC.scala:33)
  | [error] 	at org.scalajs.testadapter.RunnerAdapter.$anonfun$done$1(RunnerAdapter.scala:55)
  | [error] 	at scala.collection.immutable.List.map(List.scala:283)
  | [error] 	at org.scalajs.testadapter.RunnerAdapter.done(RunnerAdapter.scala:55)
  | [error] 	at sbt.Defaults$.$anonfun$allTestGroupsTask$6(Defaults.scala:936)
  | [error] 	at scala.collection.TraversableLike.$anonfun$map$1(TraversableLike.scala:234)
  | [error] 	at scala.collection.immutable.Map$Map2.foreach(Map.scala:146)
  | [error] 	at scala.collection.TraversableLike.map(TraversableLike.scala:234)
  | [error] 	at scala.collection.TraversableLike.map$(TraversableLike.scala:227)
  | [error] 	at scala.collection.AbstractTraversable.map(Traversable.scala:104)
  | [error] 	at sbt.Defaults$.$anonfun$allTestGroupsTask$5(Defaults.scala:934)
  | [error] 	at scala.Function1.$anonfun$compose$1(Function1.scala:44)
  | [error] 	at sbt.internal.util.$tilde$greater.$anonfun$$u2219$1(TypeFunctions.scala:39)
  | [error] 	at sbt.std.Transform$$anon$4.work(System.scala:66)
  | [error] 	at sbt.Execute.$anonfun$submit$2(Execute.scala:262)
  | [error] 	at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:16)
  | [error] 	at sbt.Execute.work(Execute.scala:271)
  | [error] 	at sbt.Execute.$anonfun$submit$1(Execute.scala:262)
  | [error] 	at sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:174)
  | [error] 	at sbt.CompletionService$$anon$2.call(CompletionService.scala:36)
  | [error] 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
  | [error] 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
  | [error] 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
  | [error] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
  | [error] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
  | [error] 	at java.lang.Thread.run(Thread.java:748)
  | [error] Caused by: java.lang.NullPointerException
  | [error] 	at org.scalajs.jsenv.nodejs.AbstractNodeJSEnv$NodeComJSRunner.receive(AbstractNodeJSEnv.scala:257)
  | [error] 	at org.scalajs.jsenv.nodejs.AbstractNodeJSEnv$NodeComJSRunner.receive$(AbstractNodeJSEnv.scala:253)
  | [error] 	at org.scalajs.jsenv.nodejs.NodeJSEnv$ComNodeRunner.receive(NodeJSEnv.scala:70)
  | [error] 	at org.scalajs.jsenv.ComJSRunner.receive(ComJSRunner.scala:15)
  | [error] 	at org.scalajs.jsenv.ComJSRunner.receive$(ComJSRunner.scala:15)
  | [error] 	at org.scalajs.jsenv.nodejs.NodeJSEnv$ComNodeRunner.receive(NodeJSEnv.scala:70)
  | [error] 	at org.scalajs.testadapter.ComJSEnvRPC$$anon$1.run(ComJSEnvRPC.scala:31)
  | [error] java.lang.NullPointerException
  | [error] 	at org.scalajs.jsenv.nodejs.AbstractNodeJSEnv$NodeComJSRunner.send(AbstractNodeJSEnv.scala:247)
  | [error] 	at org.scalajs.jsenv.nodejs.AbstractNodeJSEnv$NodeComJSRunner.send$(AbstractNodeJSEnv.scala:245)
  | [error] 	at org.scalajs.jsenv.nodejs.NodeJSEnv$ComNodeRunner.send(NodeJSEnv.scala:70)
  | [error] 	at org.scalajs.testadapter.ComJSEnvRPC.send(ComJSEnvRPC.scala:67)
  | [error] 	at org.scalajs.testcommon.RPCCore.call(RPCCore.scala:137)
  | [error] 	at org.scalajs.testadapter.TestAdapter.loadFrameworks(TestAdapter.scala:53)
  | [error] 	at org.scalajs.sbtplugin.ScalaJSPluginInternal$.$anonfun$scalaJSTestFrameworkSettings$1(ScalaJSPluginInternal.scala:1012)
  | [error] 	at scala.Function1.$anonfun$compose$1(Function1.scala:44)
  | [error] 	at sbt.internal.util.$tilde$greater.$anonfun$$u2219$1(TypeFunctions.scala:39)
  | [error] 	at sbt.std.Transform$$anon$4.work(System.scala:66)
  | [error] 	at sbt.Execute.$anonfun$submit$2(Execute.scala:262)
  | [error] 	at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:16)
  | [error] 	at sbt.Execute.work(Execute.scala:271)
  | [error] 	at sbt.Execute.$anonfun$submit$1(Execute.scala:262)
  | [error] 	at sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:174)
  | [error] 	at sbt.CompletionService$$anon$2.call(CompletionService.scala:36)
  | [error] 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
  | [error] 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
  | [error] 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
  | [error] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
  | [error] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
  | [error] 	at java.lang.Thread.run(Thread.java:748)
 ```

**Comment by tpolecat** [comment]
We're testing in parallel on a 4-CPU machine, if this is relevant. That's for having a look.

**Comment by tpolecat** [comment]
Ah, correction. We turned that off. They are not running in parallel.

**Comment by gzm0** [comment]
@sjrd both things seem plausible indeed and we should protect against them.

**Comment by sjrd** [comment]
Fixed in ecd52f4dd5c1aeee7fe766605659397dbc30b3a9.

**Comment by BardurArantsson** [comment]
@sjrd Any idea when a 0.6.25 release is expected? This bug is really killing us where I work... we're seeing something like 30% of builds failing due to this :/

**Comment by sjrd** [comment]
Not before end of August, I'm afraid. We barely made a release, and I'm on vacation until August 15.

As a workaround, not trivial but probably worth it if your situation is as dire as you say, you can copy-paste the fixed implementation of `AbstractNodeJSEnv` as well as its subclass `NodeJSEnv` into your build (inside `project/`), change the class name, and then use `jsEnv := new MyOwnJSEnv()` in your settings.

**Comment by BardurArantsson** [comment]
@sjrd Thanks for the workaround suggestion -- we'll try that!

Enjoy your vacation! :smile:
