### ISSUE TITLE
scalajs's testinterface throws JavaScriptException if the test class name is encoded

### ISSUE THREAD

**Issue by Atry** [scala-js/scala-js#3423]
# Reproduction

### project/build.properties
```
sbt.version=1.2.0
```

### project/plugins.sbt
``` sbt
addSbtPlugin("org.portable-scala" % "sbt-scalajs-crossproject" % "0.5.0")
addSbtPlugin("org.scala-js" % "sbt-scalajs" % "0.6.24")
```

### build.sbt

``` sbt
// shadow sbt-scalajs' crossProject(JSPlatform, JVMPlatform) and CrossType from Scala.js 0.6.x
import sbtcrossproject.CrossPlugin.autoImport.{crossProject, CrossType}

lazy val share = crossProject(JSPlatform, JVMPlatform)
  .crossType(CrossType.Pure)
  .settings(libraryDependencies += "org.scalatest" %%% "scalatest" % "3.0.5" % Test)

lazy val shareJS = share.js
lazy val shareJVM = share.jvm
```

### share/src/test/scala/mypackage/My$minusTest.scala

``` scala
package mypackage
import org.scalatest._
class My$minusTest extends FreeSpec with Matchers {
  "outer" - {
    "inner" in {
      succeed
    }
  }
}
```

## Run the following command

```
sbt test
```

## Expected output

No error.

## Actual output

```
[info] Loading global plugins from /Users/twer/.sbt/1.0/plugins
[info] Loading settings for project scalatest-js-crash-build from plugins.sbt ...
[info] Loading project definition from /private/tmp/scalatest-js-crash/project
[info] Loading settings for project scalatest-js-crash from build.sbt ...
[info] Set current project to scalatest-js-crash (in build file:/private/tmp/scalatest-js-crash/)
[info] Updating ...
[info] Updating shareJS...
[info] Updating shareJVM...
[info] Done updating.
[info] Done updating.
[info] Done updating.
[info] Compiling 1 Scala source to /private/tmp/scalatest-js-crash/share/.js/target/scala-2.12/test-classes ...
[info] Compiling 1 Scala source to /private/tmp/scalatest-js-crash/share/.jvm/target/scala-2.12/test-classes ...
[info] Done compiling.
[info] Done compiling.
[info] My$minusTest:
[info] outer
[info] - inner
[info] Run completed in 826 milliseconds.
[info] Total number of tests run: 1
[info] Suites: completed 1, aborted 0
[info] Tests: succeeded 1, failed 0, canceled 0, ignored 0, pending 0
[info] All tests passed.
[info] Fast optimizing /private/tmp/scalatest-js-crash/share/.js/target/scala-2.12/share-test-fastopt.js
[error] org.scalajs.testcommon.RPCCore$RPCException
[error] 	at org.scalajs.testcommon.RPCCore.$anonfun$handleMessage$4(RPCCore.scala:69)
[error] 	at scala.Option.foreach(Option.scala:257)
[error] 	at org.scalajs.testcommon.RPCCore.$anonfun$handleMessage$1(RPCCore.scala:67)
[error] 	at org.scalajs.testcommon.RPCCore.$anonfun$handleMessage$1$adapted(RPCCore.scala:47)
[error] 	at org.scalajs.testcommon.Serializer$.withInputStream(Serializer.scala:48)
[error] 	at org.scalajs.testcommon.RPCCore.handleMessage(RPCCore.scala:47)
[error] 	at org.scalajs.testadapter.ComJSEnvRPC$$anon$1.run(ComJSEnvRPC.scala:31)
[error] Caused by: scala.scalajs.js.JavaScriptException: TypeError: Cannot read property 'prototype' of undefined
[error] 	at <jscode>.$newJSObjectWithVarargs(/private/tmp/scalatest-js-crash/share/.js/target/scala-2.12/share-test-fastopt.js:478)
[error] 	at org.scalajs.testinterface.TestUtils$.newInstance(/private/tmp/scalatest-js-crash/share/.js/target/scala-2.12/share-test-fastopt.js:5322)
[error] 	at org.scalatest.tools.TaskRunner.executionFuture(/private/tmp/scalatest-js-crash/share/.js/target/scala-2.12/share-test-fastopt.js:21321)
[error] 	at org.scalatest.tools.TaskRunner.execute(/private/tmp/scalatest-js-crash/share/.js/target/scala-2.12/share-test-fastopt.js:21283)
[error] 	at <jscode>.{anonymous}()(/private/tmp/scalatest-js-crash/share/.js/target/scala-2.12/share-test-fastopt.js:5488)
[error] 	at scala.scalajs.runtime.AnonFunction1.apply(/private/tmp/scalatest-js-crash/share/.js/target/scala-2.12/share-test-fastopt.js:28570)
[error] 	at <jscode>.{anonymous}()(/private/tmp/scalatest-js-crash/share/.js/target/scala-2.12/share-test-fastopt.js:4131)
[error] 	at scala.scalajs.runtime.AnonFunction1.apply(/private/tmp/scalatest-js-crash/share/.js/target/scala-2.12/share-test-fastopt.js:28570)
[error] 	at <jscode>.{anonymous}()(/private/tmp/scalatest-js-crash/share/.js/target/scala-2.12/share-test-fastopt.js:13610)
[error] 	at scala.scalajs.runtime.AnonFunction1.apply(/private/tmp/scalatest-js-crash/share/.js/target/scala-2.12/share-test-fastopt.js:28570)
[error] Could not run test mypackage.My$minusTest: org.scalajs.testcommon.RPCCore$RPCException
[info] EndTestGroupErrorEvent(mypackage.My$minusTest, null
[info] org.scalajs.testcommon.RPCCore.$anonfun$handleMessage$4(RPCCore.scala:69)
[info] scala.Option.foreach(Option.scala:257)
[info] org.scalajs.testcommon.RPCCore.$anonfun$handleMessage$1(RPCCore.scala:67)
[info] org.scalajs.testcommon.RPCCore.$anonfun$handleMessage$1$adapted(RPCCore.scala:47)
[info] org.scalajs.testcommon.Serializer$.withInputStream(Serializer.scala:48)
[info] org.scalajs.testcommon.RPCCore.handleMessage(RPCCore.scala:47)
[info] org.scalajs.testadapter.ComJSEnvRPC$$anon$1.run(ComJSEnvRPC.scala:31))
[error] java.lang.NullPointerException
[error] 	at sbt.JUnitXmlTestsListener$TestSuite.$anonfun$stop$2(JUnitXmlTestsListener.scala:114)
[error] 	at scala.collection.TraversableLike.$anonfun$map$1(TraversableLike.scala:234)
[error] 	at scala.collection.immutable.List.foreach(List.scala:389)
[error] 	at scala.collection.generic.TraversableForwarder.foreach(TraversableForwarder.scala:35)
[error] 	at scala.collection.generic.TraversableForwarder.foreach$(TraversableForwarder.scala:35)
[error] 	at scala.collection.mutable.ListBuffer.foreach(ListBuffer.scala:44)
[error] 	at scala.collection.TraversableLike.map(TraversableLike.scala:234)
[error] 	at scala.collection.TraversableLike.map$(TraversableLike.scala:227)
[error] 	at scala.collection.AbstractTraversable.map(Traversable.scala:104)
[error] 	at sbt.JUnitXmlTestsListener$TestSuite.stop(JUnitXmlTestsListener.scala:110)
[error] 	at sbt.JUnitXmlTestsListener.$anonfun$writeSuite$2(JUnitXmlTestsListener.scala:232)
[error] 	at scala.Option.map(Option.scala:146)
[error] 	at sbt.JUnitXmlTestsListener.withTestSuite(JUnitXmlTestsListener.scala:153)
[error] 	at sbt.JUnitXmlTestsListener.writeSuite(JUnitXmlTestsListener.scala:232)
[error] 	at sbt.JUnitXmlTestsListener.endGroup(JUnitXmlTestsListener.scala:207)
[error] 	at sbt.TestRunner.$anonfun$run$8(TestFramework.scala:129)
[error] 	at sbt.TestRunner.$anonfun$run$8$adapted(TestFramework.scala:129)
[error] 	at sbt.TestFramework$.$anonfun$safeForeach$1(TestFramework.scala:150)
[error] 	at sbt.TestFramework$.$anonfun$safeForeach$1$adapted(TestFramework.scala:149)
[error] 	at scala.collection.Iterator.foreach(Iterator.scala:944)
[error] 	at scala.collection.Iterator.foreach$(Iterator.scala:944)
[error] 	at scala.collection.AbstractIterator.foreach(Iterator.scala:1432)
[error] 	at scala.collection.IterableLike.foreach(IterableLike.scala:71)
[error] 	at scala.collection.IterableLike.foreach$(IterableLike.scala:70)
[error] 	at scala.collection.AbstractIterable.foreach(Iterable.scala:54)
[error] 	at sbt.TestFramework$.safeForeach(TestFramework.scala:149)
[error] 	at sbt.TestRunner.safeListenersCall(TestFramework.scala:135)
[error] 	at sbt.TestRunner.run(TestFramework.scala:129)
[error] 	at sbt.TestFramework$$anon$2$$anonfun$$lessinit$greater$1.$anonfun$apply$1(TestFramework.scala:282)
[error] 	at sbt.TestFramework$.sbt$TestFramework$$withContextLoader(TestFramework.scala:246)
[error] 	at sbt.TestFramework$$anon$2$$anonfun$$lessinit$greater$1.apply(TestFramework.scala:282)
[error] 	at sbt.TestFramework$$anon$2$$anonfun$$lessinit$greater$1.apply(TestFramework.scala:282)
[error] 	at sbt.TestFunction.apply(TestFramework.scala:294)
[error] 	at sbt.Tests$.$anonfun$toTask$1(Tests.scala:309)
[error] 	at sbt.std.Transform$$anon$3.$anonfun$apply$2(System.scala:46)
[error] 	at sbt.std.Transform$$anon$4.work(System.scala:67)
[error] 	at sbt.Execute.$anonfun$submit$2(Execute.scala:269)
[error] 	at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:16)
[error] 	at sbt.Execute.work(Execute.scala:278)
[error] 	at sbt.Execute.$anonfun$submit$1(Execute.scala:269)
[error] 	at sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:178)
[error] 	at sbt.CompletionService$$anon$2.call(CompletionService.scala:37)
[error] 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error] 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[error] 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[error] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[error] 	at java.lang.Thread.run(Thread.java:748)
[error] java.lang.NullPointerException
[info] Run completed in 329 milliseconds.
[info] Total number of tests run: 0
[info] Suites: completed 0, aborted 0
[info] Tests: succeeded 0, failed 0, canceled 0, ignored 0, pending 0
[info] No tests were executed.
[error] Error during tests:
[error] 	mypackage.My-Test
[error] (shareJS / Test / test) sbt.TestsFailedException: Tests unsuccessful
[error] Total time: 19 s, completed Aug 7, 2018 2:56:58 PM
```

**Comment by sjrd** [comment]
Thanks for the report.

Can it be reproduced with Scala.js' JUnit? If not, it is probably a bug in ScalaTest, not in Scala.js.

**Comment by sjrd** [comment]
I cannot reproduce with JUnit, so I'll blame this on ScalaTest until proven otherwise.
### build.sbt

``` sbt
// shadow sbt-scalajs' crossProject(JSPlatform, JVMPlatform) and CrossType from Scala.js 0.6.x
import sbtcrossproject.CrossPlugin.autoImport.{crossProject, CrossType}

lazy val share = crossProject(JSPlatform, JVMPlatform)
  .crossType(CrossType.Pure)
  .jvmSettings(libraryDependencies += "com.novocode" % "junit-interface" % "0.11" % "test")
  .jsConfigure(_.enablePlugins(ScalaJSJUnitPlugin))

lazy val shareJS = share.js
lazy val shareJVM = share.jvm
```

### share/src/test/scala/mypackage/My$minusTest.scala

``` scala
package mypackage

import org.junit.Assert._
import org.junit.Test

class My$minusTest {
  @Test
  def theTest(): Unit = {
    assertTrue(true)
  }
}
```
`shareJVM/test` and `shareJS/test` print exactly the same thing:
```
[debug] Test run started
[debug] Test mypackage.My$minusTest.theTest started
[debug] Test mypackage.My$minusTest.theTest finished, took 0 sec
[debug] Test run finished: 0 failed, 0 ignored, 1 total, 0.009999872s
[info] Passed: Total 1, Failed 0, Errors 0, Passed 1
```
