### ISSUE TITLE
LinkingException: scala-js 0.6.25, Scala 2.13.0-M4

### ISSUE THREAD

**Issue by xuwei-k** [scala-js/scala-js#3445]
### Main.scala 

```scala
package example

object Main {
  def main(args: Array[String]): Unit = {
    val Array(x, xs @ _*) = args
  }
}
```

### build.sbt 

```scala
scalaVersion := "2.13.0-M4"

enablePlugins(ScalaJSPlugin)
```

### project/build.properties 

```
sbt.version=1.2.1
```

### project/plugins.sbt 

```scala
addSbtPlugin("org.scala-js" % "sbt-scalajs" % "0.6.25")
```

### execute `sbt fastOptJS`

```
[error] Referring to non-existent method scala.Array$.unapplySeq(java.lang.Object)scala.Option
[error]   called from example.Main$.main([java.lang.String)scala.Unit
[error]   called from core module module initializers
[error] involving instantiated classes:
[error]   example.Main$
[error] org.scalajs.core.tools.linker.LinkingException: There were linking errors
[error] 	at org.scalajs.core.tools.linker.frontend.BaseLinker.linkInternal(BaseLinker.scala:160)
[error] 	at org.scalajs.core.tools.linker.frontend.BaseLinker.linkInternal(BaseLinker.scala:108)
[error] 	at org.scalajs.core.tools.linker.frontend.LinkerFrontend.$anonfun$link$3(LinkerFrontend.scala:63)
[error] 	at org.scalajs.core.tools.logging.Logger.time(Logger.scala:28)
[error] 	at org.scalajs.core.tools.logging.Logger.time$(Logger.scala:26)
[error] 	at org.scalajs.sbtplugin.Loggers$SbtLoggerWrapper.time(Loggers.scala:7)
[error] 	at org.scalajs.core.tools.linker.frontend.LinkerFrontend.link(LinkerFrontend.scala:62)
[error] 	at org.scalajs.core.tools.linker.Linker.$anonfun$link$1(Linker.scala:52)
[error] 	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:12)
[error] 	at org.scalajs.core.tools.linker.Linker.guard(Linker.scala:69)
[error] 	at org.scalajs.core.tools.linker.Linker.link(Linker.scala:50)
[error] 	at org.scalajs.core.tools.linker.ClearableLinker.$anonfun$link$1(ClearableLinker.scala:52)
[error] 	at org.scalajs.core.tools.linker.ClearableLinker.$anonfun$link$1$adapted(ClearableLinker.scala:52)
[error] 	at org.scalajs.core.tools.linker.ClearableLinker.linkerOp(ClearableLinker.scala:63)
[error] 	at org.scalajs.core.tools.linker.ClearableLinker.link(ClearableLinker.scala:52)
[error] 	at org.scalajs.sbtplugin.ScalaJSPluginInternal$.$anonfun$scalaJSStageSettings$11(ScalaJSPluginInternal.scala:315)
[error] 	at sbt.util.FileFunction$.$anonfun$cached$1(FileFunction.scala:73)
[error] 	at sbt.util.FileFunction$.$anonfun$cached$4(FileFunction.scala:147)
[error] 	at sbt.util.Difference.apply(Tracked.scala:313)
[error] 	at sbt.util.Difference.apply(Tracked.scala:293)
[error] 	at sbt.util.FileFunction$.$anonfun$cached$3(FileFunction.scala:143)
[error] 	at sbt.util.Difference.apply(Tracked.scala:313)
[error] 	at sbt.util.Difference.apply(Tracked.scala:288)
[error] 	at sbt.util.FileFunction$.$anonfun$cached$2(FileFunction.scala:142)
[error] 	at org.scalajs.sbtplugin.ScalaJSPluginInternal$.$anonfun$scalaJSStageSettings$10(ScalaJSPluginInternal.scala:320)
[error] 	at sbt.std.Transform$$anon$3.$anonfun$apply$2(System.scala:46)
[error] 	at sbt.std.Transform$$anon$4.work(System.scala:67)
[error] 	at sbt.Execute.$anonfun$submit$2(Execute.scala:269)
[error] 	at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:16)
[error] 	at sbt.Execute.work(Execute.scala:278)
[error] 	at sbt.Execute.$anonfun$submit$1(Execute.scala:269)
[error] 	at sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:178)
[error] 	at sbt.CompletionService$$anon$2.call(CompletionService.scala:37)
[error] 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error] 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[error] 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[error] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[error] 	at java.lang.Thread.run(Thread.java:748)
[error] (Compile / fastOptJS) org.scalajs.core.tools.linker.LinkingException: There were linking errors
```

**Comment by sjrd** [comment]
Ouch. So I made a mistake in 1a7f013641edd77dd427e05a50f9d38462fbd154. I did not realize that [the changes to `unapplySeq`](https://github.com/scala-js/scala-js/commit/1a7f013641edd77dd427e05a50f9d38462fbd154#diff-e8890a4d66697e5e689507e1c4674a54L499) were binary-incompatible. I should have preserved a snapshot of the old overrides for 2.13.0-M4.

We can fix it, but the fix will probably never see the light of a release, because I don't intend to keep supporting 2.13.0-M4 in future versions of Scala.js. The only reason 0.6.25 has it was to provide an upgrade path (SJS 0.6.24 w/ M4 -> SJS 0.6.25 w/ M4 -> SJS 0.6.25 w/ M5).

**Comment by sjrd** [comment]
Fixed in f1593883bf9b5da0d2c6d3c1170539b3216dd516.

**Comment by djspiewak** [comment]
@sjrd I don't mean to nag but… nagging. :-)

Can we get a release which contains this fix? Right now, things are quite awkward because 0.6.24 is the most recent usable version of scala.js for anyone hitting this issue (which is a lot of projects), but 0.6.24 doesn't have a cross-build published for 2.12.7, and I'm assuming it's not going to have one for 2.13.0-M5 or higher. This in turn has a bit of a cascading effect on the ecosystem, particularly because of the high-level (dependency-wise) projects which are affected.

Would it be better for those of us who are affected to upgrade to a 1.0 milestone?

**Comment by sjrd** [comment]
We should indeed make a release. We are actually behind schedule, as we typically try to release the 0.6.x branch every 2 months (the last release was on September 3rd).

> Would it be better for those of us who are affected to upgrade to a 1.0 milestone?

That decision should be done independently of such a factor. It will have other major consequences, especially if you are talking about a library. That will have an impact on your downstream users. Ideally, as a library, you should build and publish *both* for 0.6.x and the latest 1.0 milestones.

**Comment by djspiewak** [comment]
> you should build and publish both for 0.6.x and the latest 1.0 milestones.

Is there tooling for this? I just shuddered involuntarily, because it sounds like you're adding an axis of cross-building. :-P

**Comment by djspiewak** [comment]
@sjrd Thank you so much!!
