### ISSUE TITLE
Regression in 0.6.25 (from 0.6.24) in ScalaCheck Linking on Scala 2.13

### ISSUE THREAD

**Issue by djspiewak** [scala-js/scala-js#3453]
I wish I could be more specific, I'm sorry. Here's the error:

<details>
<summary>SBT output</summary>

```
[info] Fast optimizing /Users/daniel/Development/Scala/shims/core/.js/target/scala-2.13.0-M4/shims-test-fastopt.js
[error] Referring to non-existent method scala.Array$.unapplySeq(java.lang.Object)scala.Option
[error]   called from org.scalacheck.ScalaCheckFramework$$anon$4.receiveMessage(java.lang.String)scala.Option
[error]   called from org.scalajs.testinterface.internal.Bridge$.$$anonfun$msgMasterFun$1(scala.Int,sbt.testing.Runner,org.scalajs.testcommon.FrameworkMessage)scala.Unit
[error]   called from org.scalajs.testinterface.internal.Bridge$.msgMasterFun(scala.Int,sbt.testing.Runner)scala.Function1
[error]   called from org.scalajs.testinterface.internal.Bridge$.$$anonfun$createRunnerFun$1(scala.Boolean,org.scalajs.testcommon.RunnerArgs)scala.Unit
[error]   called from org.scalajs.testinterface.internal.Bridge$.createRunnerFun(scala.Boolean)scala.Function1
[error]   called from org.scalajs.testinterface.internal.Bridge$.start()scala.Unit
[error]   called from org.scalajs.testinterface.internal.Bridge$.__exportedInits
[error]   exported to JavaScript with @JSExport
[error] involving instantiated classes:
[error]   org.scalacheck.ScalaCheckFramework$$anon$4
[error]   org.scalajs.testinterface.internal.Bridge$
[error] org.scalajs.core.tools.linker.LinkingException: There were linking errors
[error]   at org.scalajs.core.tools.linker.frontend.BaseLinker.linkInternal(BaseLinker.scala:160)
[error]   at org.scalajs.core.tools.linker.frontend.BaseLinker.linkInternal(BaseLinker.scala:108)
[error]   at org.scalajs.core.tools.linker.frontend.LinkerFrontend.$anonfun$link$3(LinkerFrontend.scala:63)
[error]   at org.scalajs.core.tools.logging.Logger.time(Logger.scala:28)
[error]   at org.scalajs.core.tools.logging.Logger.time$(Logger.scala:26)
[error]   at org.scalajs.sbtplugin.Loggers$SbtLoggerWrapper.time(Loggers.scala:7)
[error]   at org.scalajs.core.tools.linker.frontend.LinkerFrontend.link(LinkerFrontend.scala:62)
[error]   at org.scalajs.core.tools.linker.Linker.$anonfun$link$1(Linker.scala:52)
[error]   at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:12)
[error]   at org.scalajs.core.tools.linker.Linker.guard(Linker.scala:69)
[error]   at org.scalajs.core.tools.linker.Linker.link(Linker.scala:50)
[error]   at org.scalajs.core.tools.linker.ClearableLinker.$anonfun$link$1(ClearableLinker.scala:52)
[error]   at org.scalajs.core.tools.linker.ClearableLinker.$anonfun$link$1$adapted(ClearableLinker.scala:52)
[error]   at org.scalajs.core.tools.linker.ClearableLinker.linkerOp(ClearableLinker.scala:63)
[error]   at org.scalajs.core.tools.linker.ClearableLinker.link(ClearableLinker.scala:52)
[error]   at org.scalajs.sbtplugin.ScalaJSPluginInternal$.$anonfun$scalaJSStageSettings$11(ScalaJSPluginInternal.scala:315)
[error]   at sbt.util.FileFunction$.$anonfun$cached$1(FileFunction.scala:73)
[error]   at sbt.util.FileFunction$.$anonfun$cached$4(FileFunction.scala:147)
[error]   at sbt.util.Difference.apply(Tracked.scala:313)
[error]   at sbt.util.Difference.apply(Tracked.scala:293)
[error]   at sbt.util.FileFunction$.$anonfun$cached$3(FileFunction.scala:143)
[error]   at sbt.util.Difference.apply(Tracked.scala:313)
[error]   at sbt.util.Difference.apply(Tracked.scala:288)
[error]   at sbt.util.FileFunction$.$anonfun$cached$2(FileFunction.scala:142)
[error]   at org.scalajs.sbtplugin.ScalaJSPluginInternal$.$anonfun$scalaJSStageSettings$10(ScalaJSPluginInternal.scala:320)
[error]   at sbt.std.Transform$$anon$3.$anonfun$apply$2(System.scala:46)
[error]   at sbt.std.Transform$$anon$4.work(System.scala:67)
[error]   at sbt.Execute.$anonfun$submit$2(Execute.scala:269)
[error]   at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:16)
[error]   at sbt.Execute.work(Execute.scala:278)
[error]   at sbt.Execute.$anonfun$submit$1(Execute.scala:269)
[error]   at sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:178)
[error]   at sbt.CompletionService$$anon$2.call(CompletionService.scala:37)
[error]   at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error]   at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[error]   at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error]   at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[error]   at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[error]   at java.lang.Thread.run(Thread.java:748)
[error] (Test / fastOptJS) org.scalajs.core.tools.linker.LinkingException: There were linking errors
```
</details>

The base commit can be found as [djspiewak/shims:abcbe3](https://github.com/djspiewak/shims/commit/abcb3e0e0eac50a626e309504a42e9497fde4e5f). Swap the ScalaJS version in `plugins.sbt` from 0.6.24 to 0.6.25 and do a `; clean; coreJS/test`.

I'm not entirely sure what's going on. Obviously `Array$.unapplySeq` does exist in 2.13, and the class files in question link just fine on 0.6.24. I apologize for not having a more minimal example.

**Comment by sjrd** [comment]
This is a duplicate of #3445, unless I'm mistaken.

**Comment by djspiewak** [comment]
It is. Once again, @xuwei-k beats me to the punch!
