### ISSUE TITLE
Try cannot catch an exception thrown by string.split(sep)(index)

### ISSUE THREAD

**Issue by exoego** [scala-js/scala-js#3754]
# how to reproduce
```scala
object Main {
  def main(args: Array[String]): Unit = {
    println(Try("".split(".")(1)))
  }
}
```

then `sbt run`

* scala-js: 0.6.28
* Scala: 2.12.8

# Expected

As same as in JVM, `Try` should catch `ArrayIndexOutOfBoundsException` then ` Failure(java.lang.ArrayIndexOutOfBoundsException ...)` is printed.

# Actual

```
/home/vagrant/IdeaProjects/scala-steward-test-project/projects/scalajs/target/scala-2.12/scalajs-fastopt.js:1165
        throw $m_sjsr_package$().unwrapJavaScriptException__jl_Throwable__O(e$2)
        ^
/home/vagrant/IdeaProjects/scala-steward-test-project/projects/scalajs/target/scala-2.12/scalajs-fastopt.js:1165
        throw $m_sjsr_package$().unwrapJavaScriptException__jl_Throwable__O(e$2)
        ^

Error
    at $c_sjsr_UndefinedBehaviorError.$c_jl_Throwable.fillInStackTrace__jl_Throwable (/home/vagrant/IdeaProjects/scala-steward-test-project/projects/scalajs/target/scala-2.12/scalajs-fastopt.js:1884:14)
    at $c_sjsr_UndefinedBehaviorError.fillInStackTrace__jl_Throwable (/home/vagrant/IdeaProjects/scala-steward-test-project/projects/scalajs/target/scala-2.12/scalajs-fastopt.js:4271:67)
    at $c_sjsr_UndefinedBehaviorError.$c_jl_Throwable.init___T__jl_Throwable__Z__Z (/home/vagrant/IdeaProjects/scala-steward-test-project/projects/scalajs/target/scala-2.12/scalajs-fastopt.js:1903:10)
    at $c_sjsr_UndefinedBehaviorError.init___T__jl_Throwable (/home/vagrant/IdeaProjects/scala-steward-test-project/projects/scalajs/target/scala-2.12/scalajs-fastopt.js:4278:58)
    at $c_sjsr_UndefinedBehaviorError.init___jl_Throwable (/home/vagrant/IdeaProjects/scala-steward-test-project/projects/scalajs/target/scala-2.12/scalajs-fastopt.js:4274:67)
    at $throwArrayIndexOutOfBoundsException (/home/vagrant/IdeaProjects/scala-steward-test-project/projects/scalajs/target/scala-2.12/scalajs-fastopt.js:236:46)
    at ArrayClass.get (/home/vagrant/IdeaProjects/scala-steward-test-project/projects/scalajs/target/scala-2.12/scalajs-fastopt.js:871:7)
    at $c_Ljp_hoge_Main$.main__AT__V (/home/vagrant/IdeaProjects/scala-steward-test-project/projects/scalajs/target/scala-2.12/scalajs-fastopt.js:1153:102)
    at Object.<anonymous> (/home/vagrant/IdeaProjects/scala-steward-test-project/projects/scalajs/target/scala-2.12/scalajs-fastopt.js:4887:21)
    at Object.<anonymous> (/home/vagrant/IdeaProjects/scala-steward-test-project/projects/scalajs/target/scala-2.12/scalajs-fastopt.js:4888:4)
```

# Note

The below also fail to catch `IndexOutOfBoundsException`.

```scala
try {
  "".split(".")(1)
} catch {
  case e: IndexOutOfBoundsException=> println("fail")
}
```

**Comment by sjrd** [comment]
This is by design. `StringIndexOutOfBoundsException` is listed at https://www.scala-js.org/doc/semantics.html as *undefined behavior*. It is a programming error to try and catch it (with `catch` or with `Try`).
