### ISSUE TITLE
GC overhead limit when performing fastOptJS with 2gb

### ISSUE THREAD

**Issue by matthughes** [scala-js/scala-js#3767]
Using ScalaJS 0.6.28 / Scala 2.12.9 / JDK11 / SBT 1.2.7

Get the following stack trace blow up quite regularly when running ;clean;test at the root of my multi-module project.  Pretty standard setup of commonJVM/commonJS/client/server.

```
[info] Fast optimizing client/target/scala-2.12/scalajs-bundler/test/client-test-fastopt.js
[debug] Forcing garbage collection...
[error] java.util.concurrent.ExecutionException: java.lang.OutOfMemoryError: GC overhead limit exceeded
[error] 	at java.base/java.util.concurrent.FutureTask.report(FutureTask.java:122)
[error] 	at java.base/java.util.concurrent.FutureTask.get(FutureTask.java:191)
[error] 	at sbt.ConcurrentRestrictions$$anon$4.take(ConcurrentRestrictions.scala:213)
[error] 	at sbt.Execute.next$1(Execute.scala:110)
[error] 	at sbt.Execute.processAll(Execute.scala:113)
[error] 	at sbt.Execute.runKeep(Execute.scala:90)
[error] 	at sbt.EvaluateTask$.liftedTree1$1(EvaluateTask.scala:420)
[error] 	at sbt.EvaluateTask$.run$1(EvaluateTask.scala:419)
[error] 	at sbt.EvaluateTask$.runTask(EvaluateTask.scala:438)
[error] 	at sbt.internal.Aggregation$.$anonfun$timedRun$4(Aggregation.scala:99)
[error] 	at sbt.EvaluateTask$.withStreams(EvaluateTask.scala:355)
[error] 	at sbt.internal.Aggregation$.timedRun(Aggregation.scala:97)
[error] 	at sbt.internal.Aggregation$.runTasks(Aggregation.scala:111)
[error] 	at sbt.internal.Aggregation$.$anonfun$applyTasks$1(Aggregation.scala:67)
[error] 	at sbt.Command$.$anonfun$applyEffect$2(Command.scala:137)
[error] 	at sbt.internal.Aggregation$.$anonfun$evaluatingParser$11(Aggregation.scala:212)
[error] 	at sbt.internal.Act$.$anonfun$actParser0$3(Act.scala:435)
[error] 	at sbt.Command$.process(Command.scala:181)
[error] 	at sbt.MainLoop$.processCommand(MainLoop.scala:151)
[error] 	at sbt.MainLoop$.$anonfun$next$2(MainLoop.scala:139)
[error] 	at sbt.State$$anon$1.runCmd$1(State.scala:246)
[error] 	at sbt.State$$anon$1.process(State.scala:250)
[error] 	at sbt.MainLoop$.$anonfun$next$1(MainLoop.scala:139)
[error] 	at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:16)
[error] 	at sbt.MainLoop$.next(MainLoop.scala:139)
[error] 	at sbt.MainLoop$.run(MainLoop.scala:132)
[error] 	at sbt.MainLoop$.$anonfun$runWithNewLog$1(MainLoop.scala:110)
[error] 	at sbt.io.Using.apply(Using.scala:22)
[error] 	at sbt.MainLoop$.runWithNewLog(MainLoop.scala:104)
[error] 	at sbt.MainLoop$.runAndClearLast(MainLoop.scala:59)
[error] 	at sbt.MainLoop$.runLoggedLoop(MainLoop.scala:44)
[error] 	at sbt.MainLoop$.runLogged(MainLoop.scala:35)
[error] 	at sbt.StandardMain$.runManaged(Main.scala:138)
[error] 	at sbt.xMain.run(Main.scala:89)
[error] 	at xsbt.boot.Launch$$anonfun$run$1.apply(Launch.scala:111)
[error] 	at xsbt.boot.Launch$.withContextLoader(Launch.scala:130)
[error] 	at xsbt.boot.Launch$.run(Launch.scala:111)
[error] 	at xsbt.boot.Launch$$anonfun$apply$1.apply(Launch.scala:37)
[error] 	at xsbt.boot.Launch$.launch(Launch.scala:119)
[error] 	at xsbt.boot.Launch$.apply(Launch.scala:20)
[error] 	at xsbt.boot.Boot$.runImpl(Boot.scala:56)
[error] 	at xsbt.boot.Boot$.main(Boot.scala:18)
[error] 	at xsbt.boot.Boot.main(Boot.scala)
[error] Caused by: java.lang.OutOfMemoryError: GC overhead limit exceeded
[error] 	at java.base/java.io.DataInputStream.readUTF(DataInputStream.java:666)
[error] 	at java.base/java.io.DataInputStream.readUTF(DataInputStream.java:569)
[error] 	at org.scalajs.core.ir.InfoSerializers$Deserializer.$anonfun$readStrings$1(InfoSerializers.scala:103)
[error] 	at org.scalajs.core.ir.InfoSerializers$Deserializer$$Lambda$28170/0x00000008046d9040.apply(Unknown Source)
[error] 	at scala.collection.generic.GenTraversableFactory.fill(GenTraversableFactory.scala:89)
[error] 	at org.scalajs.core.ir.InfoSerializers$Deserializer.readList(InfoSerializers.scala:100)
[error] 	at org.scalajs.core.ir.InfoSerializers$Deserializer.readStrings(InfoSerializers.scala:103)
[error] 	at org.scalajs.core.ir.InfoSerializers$Deserializer.$anonfun$deserialize$2(InfoSerializers.scala:124)
[error] 	at org.scalajs.core.ir.InfoSerializers$Deserializer$$Lambda$28169/0x00000008046de040.apply(Unknown Source)
[error] 	at scala.collection.generic.GenTraversableFactory.fill(GenTraversableFactory.scala:89)
[error] 	at org.scalajs.core.ir.InfoSerializers$Deserializer.readList(InfoSerializers.scala:100)
[error] 	at org.scalajs.core.ir.InfoSerializers$Deserializer.readPerClassStrings$1(InfoSerializers.scala:124)
[error] 	at org.scalajs.core.ir.InfoSerializers$Deserializer.readMethod$1(InfoSerializers.scala:136)
[error] 	at org.scalajs.core.ir.InfoSerializers$Deserializer.$anonfun$deserialize$3(InfoSerializers.scala:150)
[error] 	at org.scalajs.core.ir.InfoSerializers$Deserializer$$Lambda$28168/0x00000008046df840.apply(Unknown Source)
[error] 	at scala.collection.generic.GenTraversableFactory.fill(GenTraversableFactory.scala:89)
[error] 	at org.scalajs.core.ir.InfoSerializers$Deserializer.readList(InfoSerializers.scala:100)
[error] 	at org.scalajs.core.ir.InfoSerializers$Deserializer.deserialize(InfoSerializers.scala:150)
[error] 	at org.scalajs.core.ir.InfoSerializers$.deserializeWithVersion(InfoSerializers.scala:38)
[error] 	at org.scalajs.core.tools.io.VirtualSerializedScalaJSIRFile.infoAndTree(VirtualFiles.scala:178)
[error] 	at org.scalajs.core.tools.io.VirtualSerializedScalaJSIRFile.infoAndTree$(VirtualFiles.scala:175)
[error] 	at org.scalajs.core.tools.io.MemVirtualSerializedScalaJSIRFile.infoAndTree(MemFiles.scala:107)
[error] 	at org.scalajs.core.tools.io.VirtualScalaJSIRFile.tree(VirtualFiles.scala:146)
[error] 	at org.scalajs.core.tools.io.VirtualScalaJSIRFile.tree$(VirtualFiles.scala:145)
[error] 	at org.scalajs.core.tools.io.MemVirtualSerializedScalaJSIRFile.tree(MemFiles.scala:107)
[error] 	at org.scalajs.core.tools.io.IRFileCache$PersistentIRFile.$anonfun$loadTree$1(IRFileCache.scala:271)
[error] 	at org.scalajs.core.tools.io.IRFileCache$PersistentIRFile$$Lambda$28431/0x0000000804cdd840.apply$mcV$sp(Unknown Source)
[error] 	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:12)
[error] 	at org.scalajs.core.tools.io.IRFileCache.org$scalajs$core$tools$io$IRFileCache$$clearOnThrow(IRFileCache.scala:283)
[error] 	at org.scalajs.core.tools.io.IRFileCache$PersistentIRFile.loadTree(IRFileCache.scala:269)
[error] 	at org.scalajs.core.tools.io.IRFileCache$PersistentIRFile.tree(IRFileCache.scala:258)
[error] 	at org.scalajs.core.tools.linker.frontend.BaseLinker.$anonfun$linkInternal$2(BaseLinker.scala:107)
[error] java.util.concurrent.ExecutionException: java.lang.OutOfMemoryError: GC overhead limit exceeded
[error] Use 'last' for the full log.
```

I wouldn't really know where to begin in trying to minimize this.  I don't know SJS internals well enough and it may be a red herring but it seems like decoding the SJS IR files is causing the heap to blow.  If it helps, the top ten sjsir files for this project range in size from 220K-624K (using `find . -name "*.sjsir" -size +100k | xargs ls -lhsSr | grep -v bloop | tail -n 10` on my project).

**Comment by sjrd** [comment]
Do you have a very large string constant somewhere in your codebase?

**Comment by sjrd** [comment]
Does the following sbt setting help?
```scala
concurrentRestrictions in Global += Tags.limit(ScalaJSTags.Link, 1)
```

**Comment by matthughes** [comment]
Seems to have died at a different spot now:

```
[error] GC overhead limit exceeded
[error] scala.reflect.internal.Symbols$Symbol.createValueParameterSymbol(Symbols.scala:1370)
[error] scala.reflect.internal.Symbols$Symbol.newTermSymbol(Symbols.scala:1384)
[error] scala.reflect.internal.Symbols$TermSymbol.cloneSymbolImpl(Symbols.scala:2889)
[error] scala.reflect.internal.Symbols$TermSymbol.cloneSymbolImpl(Symbols.scala:2815)
[error] scala.reflect.internal.Symbols$Symbol.cloneSymbol(Symbols.scala:2016)
[error] scala.reflect.internal.Symbols$Symbol.cloneSymbol(Symbols.scala:2014)
[error] scala.reflect.internal.Symbols$Symbol.cloneSymbol(Symbols.scala:2012)
[error] scala.reflect.internal.Symbols$Symbol.cloneSymbol(Symbols.scala:2008)
[error] scala.reflect.internal.Symbols.$anonfun$cloneSymbols$1(Symbols.scala:3692)
[error] scala.reflect.internal.Symbols$$Lambda$9543/0x000000080271e840.apply(Unknown Source)
[error] scala.reflect.internal.Symbols.deriveSymbols(Symbols.scala:3627)
[error] scala.reflect.internal.Symbols.deriveSymbols$(Symbols.scala:3624)
[error] scala.reflect.internal.SymbolTable.deriveSymbols(SymbolTable.scala:28)
[error] scala.reflect.internal.Symbols.cloneSymbols(Symbols.scala:3692)
[error] scala.reflect.internal.Symbols.cloneSymbols$(Symbols.scala:3691)
[error] scala.reflect.internal.SymbolTable.cloneSymbols(SymbolTable.scala:28)
[error] scala.reflect.internal.tpe.TypeMaps$TypeMap.mapOver(TypeMaps.scala:264)
[error] scala.reflect.internal.tpe.TypeMaps$TypeMap.$anonfun$mapOver$1(TypeMaps.scala:137)
[error] scala.reflect.internal.tpe.TypeMaps$TypeMap.mapOver(TypeMaps.scala:216)
[error] scala.reflect.internal.transform.UnCurry$$anon$1.apply(UnCurry.scala:65)
[error] scala.reflect.internal.tpe.TypeMaps$TypeMap.mapOver(TypeMaps.scala:143)
[error] scala.reflect.internal.transform.UnCurry$$anon$1.apply(UnCurry.scala:65)
[error] scala.tools.nsc.transform.UnCurry$UnCurryTransformer.mainTransform(UnCurry.scala:534)
[error] scala.tools.nsc.transform.UnCurry$UnCurryTransformer.transform(UnCurry.scala:119)
[error] scala.tools.nsc.transform.UnCurry$UnCurryTransformer.transform(UnCurry.scala:79)
[error] scala.reflect.internal.Trees.itransform(Trees.scala:1410)
[error] scala.reflect.internal.Trees.itransform$(Trees.scala:1374)
[error] scala.reflect.internal.SymbolTable.itransform(SymbolTable.scala:28)
[error] scala.reflect.internal.SymbolTable.itransform(SymbolTable.scala:28)
[error] scala.reflect.api.Trees$Transformer.transform(Trees.scala:2563)
[error] scala.tools.nsc.transform.TypingTransformers$TypingTransformer.transform(TypingTransformers.scala:51)
[error] scala.tools.nsc.transform.UnCurry$UnCurryTransformer.mainTransform(UnCurry.scala:523)
[error]
[error] java.util.concurrent.ExecutionException: java.lang.OutOfMemoryError: GC overhead limit exceeded
[error] 	at java.base/java.util.concurrent.FutureTask.report(FutureTask.java:122)
[error] 	at java.base/java.util.concurrent.FutureTask.get(FutureTask.java:191)
[error] 	at sbt.ConcurrentRestrictions$$anon$4.take(ConcurrentRestrictions.scala:213)
[error] 	at sbt.Execute.next$1(Execute.scala:110)
[error] 	at sbt.Execute.processAll(Execute.scala:113)
[error] 	at sbt.Execute.runKeep(Execute.scala:90)
[error] 	at sbt.EvaluateTask$.liftedTree1$1(EvaluateTask.scala:420)
[error] 	at sbt.EvaluateTask$.run$1(EvaluateTask.scala:419)
[error] 	at sbt.EvaluateTask$.runTask(EvaluateTask.scala:438)
[error] 	at sbt.internal.Aggregation$.$anonfun$timedRun$4(Aggregation.scala:99)
[error] 	at sbt.EvaluateTask$.withStreams(EvaluateTask.scala:355)
[error] 	at sbt.internal.Aggregation$.timedRun(Aggregation.scala:97)
[error] 	at sbt.internal.Aggregation$.runTasks(Aggregation.scala:111)
[error] 	at sbt.internal.Aggregation$.$anonfun$applyTasks$1(Aggregation.scala:67)
[error] 	at sbt.Command$.$anonfun$applyEffect$2(Command.scala:137)
[error] 	at sbt.internal.Aggregation$.$anonfun$evaluatingParser$11(Aggregation.scala:212)
[error] 	at sbt.internal.Act$.$anonfun$actParser0$3(Act.scala:435)
[error] 	at sbt.Command$.process(Command.scala:181)
[error] 	at sbt.MainLoop$.processCommand(MainLoop.scala:151)
[error] 	at sbt.MainLoop$.$anonfun$next$2(MainLoop.scala:139)
[error] 	at sbt.State$$anon$1.runCmd$1(State.scala:246)
[error] 	at sbt.State$$anon$1.process(State.scala:250)
[error] 	at sbt.MainLoop$.$anonfun$next$1(MainLoop.scala:139)
[error] 	at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:16)
[error] 	at sbt.MainLoop$.next(MainLoop.scala:139)
[error] 	at sbt.MainLoop$.run(MainLoop.scala:132)
[error] 	at sbt.MainLoop$.$anonfun$runWithNewLog$1(MainLoop.scala:110)
[error] 	at sbt.io.Using.apply(Using.scala:22)
[error] 	at sbt.MainLoop$.runWithNewLog(MainLoop.scala:104)
[error] 	at sbt.MainLoop$.runAndClearLast(MainLoop.scala:59)
[error] 	at sbt.MainLoop$.runLoggedLoop(MainLoop.scala:44)
[error] 	at sbt.MainLoop$.runLogged(MainLoop.scala:35)
[error] 	at sbt.StandardMain$.runManaged(Main.scala:138)
[error] 	at sbt.xMain.run(Main.scala:89)
[error] 	at xsbt.boot.Launch$$anonfun$run$1.apply(Launch.scala:111)
[error] 	at xsbt.boot.Launch$.withContextLoader(Launch.scala:130)
[error] 	at xsbt.boot.Launch$.run(Launch.scala:111)
[error] 	at xsbt.boot.Launch$$anonfun$apply$1.apply(Launch.scala:37)
[error] 	at xsbt.boot.Launch$.launch(Launch.scala:119)
[error] 	at xsbt.boot.Launch$.apply(Launch.scala:20)
[error] 	at xsbt.boot.Boot$.runImpl(Boot.scala:56)
[error] 	at xsbt.boot.Boot$.main(Boot.scala:18)
[error] 	at xsbt.boot.Boot.main(Boot.scala)
[error] Caused by: java.lang.OutOfMemoryError: GC overhead limit exceeded
[error] 	at scala.reflect.internal.Symbols$Symbol.createValueParameterSymbol(Symbols.scala:1370)
[error] 	at scala.reflect.internal.Symbols$Symbol.newTermSymbol(Symbols.scala:1384)
[error] 	at scala.reflect.internal.Symbols$TermSymbol.cloneSymbolImpl(Symbols.scala:2889)
[error] 	at scala.reflect.internal.Symbols$TermSymbol.cloneSymbolImpl(Symbols.scala:2815)
[error] 	at scala.reflect.internal.Symbols$Symbol.cloneSymbol(Symbols.scala:2016)
[error] 	at scala.reflect.internal.Symbols$Symbol.cloneSymbol(Symbols.scala:2014)
[error] 	at scala.reflect.internal.Symbols$Symbol.cloneSymbol(Symbols.scala:2012)
[error] 	at scala.reflect.internal.Symbols$Symbol.cloneSymbol(Symbols.scala:2008)
[error] 	at scala.reflect.internal.Symbols.$anonfun$cloneSymbols$1(Symbols.scala:3692)
[error] 	at scala.reflect.internal.Symbols$$Lambda$9543/0x000000080271e840.apply(Unknown Source)
[error] 	at scala.reflect.internal.Symbols.deriveSymbols(Symbols.scala:3627)
[error] 	at scala.reflect.internal.Symbols.deriveSymbols$(Symbols.scala:3624)
[error] 	at scala.reflect.internal.SymbolTable.deriveSymbols(SymbolTable.scala:28)
[error] 	at scala.reflect.internal.Symbols.cloneSymbols(Symbols.scala:3692)
[error] 	at scala.reflect.internal.Symbols.cloneSymbols$(Symbols.scala:3691)
[error] 	at scala.reflect.internal.SymbolTable.cloneSymbols(SymbolTable.scala:28)
[error] 	at scala.reflect.internal.tpe.TypeMaps$TypeMap.mapOver(TypeMaps.scala:264)
[error] 	at scala.reflect.internal.tpe.TypeMaps$TypeMap.$anonfun$mapOver$1(TypeMaps.scala:137)
[error] 	at scala.reflect.internal.tpe.TypeMaps$TypeMap.mapOver(TypeMaps.scala:216)
[error] 	at scala.reflect.internal.transform.UnCurry$$anon$1.apply(UnCurry.scala:65)
[error] 	at scala.reflect.internal.tpe.TypeMaps$TypeMap.mapOver(TypeMaps.scala:143)
[error] 	at scala.reflect.internal.transform.UnCurry$$anon$1.apply(UnCurry.scala:65)
[error] 	at scala.tools.nsc.transform.UnCurry$UnCurryTransformer.mainTransform(UnCurry.scala:534)
[error] 	at scala.tools.nsc.transform.UnCurry$UnCurryTransformer.transform(UnCurry.scala:119)
[error] 	at scala.tools.nsc.transform.UnCurry$UnCurryTransformer.transform(UnCurry.scala:79)
[error] 	at scala.reflect.internal.Trees.itransform(Trees.scala:1410)
[error] 	at scala.reflect.internal.Trees.itransform$(Trees.scala:1374)
[error] 	at scala.reflect.internal.SymbolTable.itransform(SymbolTable.scala:28)
[error] 	at scala.reflect.internal.SymbolTable.itransform(SymbolTable.scala:28)
[error] 	at scala.reflect.api.Trees$Transformer.transform(Trees.scala:2563)
[error] 	at scala.tools.nsc.transform.TypingTransformers$TypingTransformer.transform(TypingTransformers.scala:51)
[error] 	at scala.tools.nsc.transform.UnCurry$UnCurryTransformer.mainTransform(UnCurry.scala:523)
[error] java.util.concurrent.ExecutionException: java.lang.OutOfMemoryError: GC overhead limit exceeded
```

**Comment by sjrd** [comment]
Try running the test tasks sequentially rather than using the parallel aggregate: `;commonJS/test;commonJVM/test;client/test;server/test`.

**Comment by matthughes** [comment]
It got to client/test and failed with GC OOM though this time it was abrupt and didn't provide stack.  

I double-checked and I'm actually running with 2GB, not 4GB.  I'll update the issue title.

Bumping to 4GB does let it complete FWIW.

**Comment by sjrd** [comment]
Oh, 2GB is definitely not enough for Scala.js to work given a medium codebase. 4GB is recommended. This is unlikely to change, so I'm going to close this issue.

**Comment by kubukoz** [comment]
4GB is no longer enough in 2023 when you get 10+ cores on a machine and sbt gives you this many concurrent builds 😅 

going to try to limit the concurrency with the workaround above, but it seems strange that this step really requires this much memory.

@sjrd do you see an inherent issue in reducing the memory usage of the linking process, or is there another reason why it's unlikely to change?

**Comment by sjrd** [comment]
There's an important trade-off between memory consumption and speed of incremental building. Many more people want fast incremental builds, so that's what we optimize for. If we can reduce memory without increasing build times, then sure, it would be better to do it.

**Comment by gzm0** [comment]
IMO there are likely a couple of low-hanging fruits in terms of linker memory consumption. Last time I checked, a large portion of memory was taken by `::` (List's cons). It would not surprise me if we could reduce memory consumption significantly by using array backed collections.

I'll file this as a follow-up and take a stab.
