### ISSUE TITLE
PrepJSInterop crash for object annotated with `@GlobalScope` and with nested object

### ISSUE THREAD

**Issue by oyvindberg** [scala-js/scala-js#3839]
The following is allowed in 0.6.29, but fails in 1.0.0-M8 and in current master.

Add the following test to `JSInteropTest`:
```scala
  @Test
  def dontCrash: Unit = {
    """
    @JSGlobalScope
    @js.native
    object A extends js.Object {
      @js.native
      object B extends js.Object
    }

    """.succeeds
  }


```

Fails with the following stack trace
```
[error] Test org.scalajs.nscplugin.test.JSInteropTest.dontCrash failed: key not found: object A
[error]     at scala.collection.MapLike.default(MapLike.scala:235)
[error]     at scala.collection.MapLike.default$(MapLike.scala:234)
[error]     at scala.collection.AbstractMap.default(Map.scala:63)
[error]     at scala.collection.mutable.HashMap.apply(HashMap.scala:69)
[error]     at org.scalajs.nscplugin.JSGlobalAddons$jsInterop$.jsNativeLoadSpecOf(JSGlobalAddons.scala:280)
[error]     at org.scalajs.nscplugin.PrepJSInterop$JSInteropTransformer.checkAndComputeJSNativeLoadSpecOf(PrepJSInterop.scala:706)
[error]     at org.scalajs.nscplugin.PrepJSInterop$JSInteropTransformer.transformJSAny(PrepJSInterop.scala:596)
[error]     at org.scalajs.nscplugin.PrepJSInterop$JSInteropTransformer.transform(PrepJSInterop.scala:154)
[error]     at org.scalajs.nscplugin.PrepJSInterop$JSInteropTransformer.transform(PrepJSInterop.scala:84)
[error]     at scala.reflect.api.Trees$Transformer.$anonfun$transformStats$1(Trees.scala:2597)
[error]     at scala.reflect.api.Trees$Transformer.transformStats(Trees.scala:2595)
[error]     at scala.reflect.internal.Trees.itransform(Trees.scala:1440)
[error]     at scala.reflect.internal.Trees.itransform$(Trees.scala:1372)
[error]     at scala.reflect.internal.SymbolTable.itransform(SymbolTable.scala:27)
[error]     at scala.reflect.internal.SymbolTable.itransform(SymbolTable.scala:27)
[error]     at scala.reflect.api.Trees$Transformer.transform(Trees.scala:2563)
[error]     at org.scalajs.nscplugin.PrepJSInterop$JSInteropTransformer.transform(PrepJSInterop.scala:393)
[error]     at org.scalajs.nscplugin.PrepJSInterop$JSInteropTransformer.transform(PrepJSInterop.scala:84)
[error]     at scala.reflect.api.Trees$Transformer.transformTemplate(Trees.scala:2571)
[error]     at scala.reflect.internal.Trees.$anonfun$itransform$5(Trees.scala:1449)
[error]     at scala.reflect.api.Trees$Transformer.atOwner(Trees.scala:2608)
[error]     at scala.reflect.internal.Trees.itransform(Trees.scala:1448)
[error]     at scala.reflect.internal.Trees.itransform$(Trees.scala:1372)
[error]     at scala.reflect.internal.SymbolTable.itransform(SymbolTable.scala:27)
[error]     at scala.reflect.internal.SymbolTable.itransform(SymbolTable.scala:27)
[error]     at scala.reflect.api.Trees$Transformer.transform(Trees.scala:2563)
[error]     at org.scalajs.nscplugin.PrepJSInterop$JSInteropTransformer.super$transform(PrepJSInterop.scala:171)
[error]     at org.scalajs.nscplugin.PrepJSInterop$JSInteropTransformer.$anonfun$transformJSAny$9(PrepJSInterop.scala:673)
[error]     at org.scalajs.nscplugin.PrepJSInterop$JSInteropTransformer.enterOwner(PrepJSInterop.scala:114)
[error]     at org.scalajs.nscplugin.PrepJSInterop$JSInteropTransformer.transformJSAny(PrepJSInterop.scala:673)
[error]     at org.scalajs.nscplugin.PrepJSInterop$JSInteropTransformer.transform(PrepJSInterop.scala:154)
[error]     at org.scalajs.nscplugin.PrepJSInterop$JSInteropTransformer.transform(PrepJSInterop.scala:84)
[error]     at scala.reflect.api.Trees$Transformer.$anonfun$transformStats$1(Trees.scala:2597)
[error]     at scala.reflect.api.Trees$Transformer.transformStats(Trees.scala:2595)
[error]     at scala.reflect.internal.Trees.$anonfun$itransform$7(Trees.scala:1462)
[error]     at scala.reflect.api.Trees$Transformer.atOwner(Trees.scala:2608)
[error]     at scala.reflect.internal.Trees.itransform(Trees.scala:1462)
[error]     at scala.reflect.internal.Trees.itransform$(Trees.scala:1372)
[error]     at scala.reflect.internal.SymbolTable.itransform(SymbolTable.scala:27)
[error]     at scala.reflect.internal.SymbolTable.itransform(SymbolTable.scala:27)
[error]     at scala.reflect.api.Trees$Transformer.transform(Trees.scala:2563)
[error]     at org.scalajs.nscplugin.PrepJSInterop$JSInteropTransformer.transform(PrepJSInterop.scala:393)
[error]     at org.scalajs.nscplugin.PrepJSInterop$JSInteropTransformer.transform(PrepJSInterop.scala:84)
[error]     at scala.tools.nsc.ast.Trees$Transformer.transformUnit(Trees.scala:147)
[error]     at scala.tools.nsc.transform.Transform$Phase.apply(Transform.scala:37)
[error]     at scala.tools.nsc.Global$GlobalPhase.applyPhase(Global.scala:448)
[error]     at scala.tools.nsc.Global$GlobalPhase.run(Global.scala:398)
[error]     at org.scalajs.nscplugin.PrepJSInterop$JSInteropPhase.run(PrepJSInterop.scala:67)
[error]     at scala.tools.nsc.Global$Run.compileUnitsInternal(Global.scala:1498)
[error]     at scala.tools.nsc.Global$Run.compileUnits(Global.scala:1482)
[error]     at scala.tools.nsc.Global$Run.compileSources(Global.scala:1475)
[error]     at org.scalajs.nscplugin.test.util.DirectTest.$anonfun$compileSources$1(DirectTest.scala:88)
[error]     at org.scalajs.nscplugin.test.util.DirectTest.$anonfun$compileSources$1$adapted(DirectTest.scala:88)
[error]     at org.scalajs.nscplugin.test.util.DirectTest.withRun(DirectTest.scala:84)
[error]     at org.scalajs.nscplugin.test.util.DirectTest.compileSources(DirectTest.scala:88)
[error]     at org.scalajs.nscplugin.test.util.DirectTest.compileString(DirectTest.scala:93)
[error]     at org.scalajs.nscplugin.test.util.DirectTest.compileString(DirectTest.scala:96)
[error]     at org.scalajs.nscplugin.test.util.TestHelpers$CompileTests.succeeds(TestHelpers.scala:80)
[error]     at org.scalajs.nscplugin.test.JSInteropTest.dontCrash(JSInteropTest.scala:3014)
```

**Comment by sjrd** [comment]
Thanks for the report. It looks like a bug, indeed.
