### ISSUE TITLE
Scala.js 1.0 fails to read transitive jsDependency

### ISSUE THREAD

**Issue by japgolly** [scala-js/scala-js#4031]
I've got a [PR for scalajs-react to cross-compile to SJS 1.0](https://github.com/japgolly/scalajs-react/pull/696). The SJS 0.6.32 tests pass fine but for SJS 1.0 I'm getting this error:

https://travis-ci.org/github/japgolly/scalajs-react/jobs/682482544#L543-L567

```
[error] java.nio.file.FileSystemLoopException: /META-INF/resources/webjars/prop-types/15.7.2
[error] 	at java.nio.file.FileTreeWalker.visit(FileTreeWalker.java:294)
[error] 	at java.nio.file.FileTreeWalker.next(FileTreeWalker.java:372)
[error] 	at java.nio.file.Files.walkFileTree(Files.java:2706)
[error] 	at org.scalajs.linker.PathIRContainer$.org$scalajs$linker$PathIRContainer$$walkIR(PathIRContainer.scala:95)
[error] 	at org.scalajs.linker.PathIRContainer$JarIRContainer.$anonfun$sjsirFiles$2(PathIRContainer.scala:67)
[error] 	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
[error] 	at scala.concurrent.impl.ExecutionContextImpl$DefaultThreadFactory$$anon$1$$anon$2.block(ExecutionContextImpl.scala:75)
[error] 	at java.util.concurrent.ForkJoinPool.managedBlock(ForkJoinPool.java:3313)
[error] 	at scala.concurrent.impl.ExecutionContextImpl$DefaultThreadFactory$$anon$1.blockOn(ExecutionContextImpl.scala:87)
[error] 	at scala.concurrent.package$.blocking(package.scala:146)
[error] 	at org.scalajs.linker.PathIRContainer$JarIRContainer.$anonfun$sjsirFiles$1(PathIRContainer.scala:59)
[error] 	at scala.concurrent.Future$.$anonfun$apply$1(Future.scala:659)
[error] 	at scala.util.Success.$anonfun$map$1(Try.scala:255)
[error] 	at scala.util.Success.map(Try.scala:213)
[error] 	at scala.concurrent.Future.$anonfun$map$1(Future.scala:292)
[error] 	at scala.concurrent.impl.Promise.liftedTree1$1(Promise.scala:33)
[error] 	at scala.concurrent.impl.Promise.$anonfun$transform$1(Promise.scala:33)
[error] 	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:64)
[error] 	at java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1402)
[error] 	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
[error] 	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
[error] 	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
[error] 	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
[error] (test / Test / scalaJSIR) java.nio.file.FileSystemLoopException: /META-INF/resources/webjars/prop-types/15.7.2
```

I don't directly specify `prop-types` in my build, it's a transitive dependency of one of the react `jsDependencies`.

**Comment by nafg** [comment]
How is there a cycle inside a jar file?

**Comment by sjrd** [comment]
There's something seriously wrong with that jar. If you [download prop-types-15.7.2.jar](https://search.maven.org/remotecontent?filepath=org/webjars/npm/prop-types/15.7.2/prop-types-15.7.2.jar) and examine its content, under `/META-INF/resources/webjars/prop-types/15.7.2/` (the path in the exception), there is a *very* weird entry that shows up.

On Windows it appears as a nameless entry whose type is a "local disk" (a hard drive, basically). On Linux, `unzip -l` lists it as a nameless directory, it seems:
```
$ unzip -l ~/.coursier/cache/v1/https/repo1.maven.org/maven2/org/webjars/npm/prop-types/15.7.2/prop-types-15.7.2.jar
Archive:  .../org/webjars/npm/prop-types/15.7.2/prop-types-15.7.2.jar
  Length      Date    Time    Name
---------  ---------- -----   ----
        0  2019-02-15 08:19   META-INF/
        0  2019-02-15 08:19   META-INF/maven/
        0  2019-02-15 08:19   META-INF/maven/org.webjars.npm/
        0  2019-02-15 08:19   META-INF/maven/org.webjars.npm/prop-types/
     2059  2019-02-15 08:19   META-INF/maven/org.webjars.npm/prop-types/pom.xml
       95  2019-02-15 08:19   META-INF/maven/org.webjars.npm/prop-types/pom.properties
        0  2019-02-15 08:19   META-INF/
        0  2019-02-15 08:19   META-INF/resources/
        0  2019-02-15 08:19   META-INF/resources/webjars/
        0  2019-02-15 08:19   META-INF/resources/webjars/prop-types/
        0  2019-02-15 08:19   META-INF/resources/webjars/prop-types/15.7.2/
        0  2019-02-15 08:19   META-INF/resources/webjars/prop-types/15.7.2// # <-- This one
     5562  2019-02-15 08:19   META-INF/resources/webjars/prop-types/15.7.2/CHANGELOG.md
     1080  2019-02-15 08:19   META-INF/resources/webjars/prop-types/15.7.2/LICENSE
    11199  2019-02-15 08:19   META-INF/resources/webjars/prop-types/15.7.2/README.md
     3781  2019-02-15 08:19   META-INF/resources/webjars/prop-types/15.7.2/checkPropTypes.js
      768  2019-02-15 08:19   META-INF/resources/webjars/prop-types/15.7.2/factory.js
     1621  2019-02-15 08:19   META-INF/resources/webjars/prop-types/15.7.2/factoryWithThrowingShims.js
    21563  2019-02-15 08:19   META-INF/resources/webjars/prop-types/15.7.2/factoryWithTypeCheckers.js
      710  2019-02-15 08:19   META-INF/resources/webjars/prop-types/15.7.2/index.js
        0  2019-02-15 08:19   META-INF/resources/webjars/prop-types/15.7.2/lib/
     1586  2019-02-15 08:19   META-INF/resources/webjars/prop-types/15.7.2/package.json
    47744  2019-02-15 08:19   META-INF/resources/webjars/prop-types/15.7.2/prop-types.js
     1763  2019-02-15 08:19   META-INF/resources/webjars/prop-types/15.7.2/prop-types.min.js
      314  2019-02-15 08:19   META-INF/resources/webjars/prop-types/15.7.2/lib/ReactPropTypesSecret.js
---------                     -------
    99845                     25 files
```
I think this .jar file is just plain corrupted. I don't think it's Scala.js' fault, and I don't see what we could do about it.

You could report the issue to https://www.webjars.org/, or create a new archive and upload it (if that's possible).

**Comment by sjrd** [comment]
And, if it's not corrupted, and nameless directories are actually supposed to be valid in .zip files, then it's a bug in the JDK implementation [`java.nio.file.Files.walkFileTree`](https://docs.oracle.com/javase/8/docs/api/java/nio/file/Files.html#walkFileTree-java.nio.file.Path-java.util.Set-int-java.nio.file.FileVisitor-). In that case, feel free to report the bug to the JDK bug database.

In either case, this is clearly outside of Scala.js, so I'm going to close this issue.

**Comment by japgolly** [comment]
Did some more digging. Of SJS {0.6, 1.0} x JDK {8, 11} this only occurs with SJS 1.0 & JDK 8. Why does it occur with SJS 0.6 & JDK 8?

**Comment by sjrd** [comment]
In 0.6.x we used `ZipInputStream` to open jar files. In 1.x we use `java.nio.file` APIs. From what you say it seems `walkFileTree` had a bug in JDK 8 that was fixed in 11.

Regardless, I think this jar is borderline. One shouldn't put nameless directories in a jar.
