### ISSUE TITLE
"NoSuchElementException: key not found: LabelName<matchAlts1>" with dotty 0.27.0-RC1

### ISSUE THREAD

**Issue by xuwei-k** [scala-js/scala-js#4171]
### build.sbt

```scala
scalaVersion := "0.27.0-RC1"

enablePlugins(ScalaJSPlugin)

scalaJSUseMainModuleInitializer := true
```

###  project/plugins.sbt

```scala
addSbtPlugin("org.scala-js" % "sbt-scalajs" % "1.1.1")
addSbtPlugin("ch.epfl.lamp" % "sbt-dotty" % "0.4.2")
```

### project/build.properties

```
sbt.version=1.3.13
```

### A.scala

```scala
package example

object A {
  def main(args: Array[String]): Unit = {
    (null: Any) match {
      case (_: Int) | (_: String) =>
    }
  }
}
```

execute `sbt fastOptJS`

## log

```
[error] java.util.NoSuchElementException: key not found: LabelName<matchAlts1>
[error] 	at scala.collection.immutable.Map$Map2.apply(Map.scala:138)
[error] 	at org.scalajs.linker.backend.emitter.FunctionEmitter$Env.lhsForLabeledExpr(FunctionEmitter.scala:2836)
[error] 	at org.scalajs.linker.backend.emitter.FunctionEmitter$JSDesugar.doReturnToLabel$1(FunctionEmitter.scala:1375)
[error] 	at org.scalajs.linker.backend.emitter.FunctionEmitter$JSDesugar.pushLhsInto(FunctionEmitter.scala:1437)
[error] 	at org.scalajs.linker.backend.emitter.FunctionEmitter$JSDesugar.pushLhsInto(FunctionEmitter.scala:1485)
[error] 	at org.scalajs.linker.backend.emitter.FunctionEmitter$JSDesugar.redo$1(FunctionEmitter.scala:1352)
[error] 	at org.scalajs.linker.backend.emitter.FunctionEmitter$JSDesugar.pushLhsInto(FunctionEmitter.scala:1420)
[error] 	at org.scalajs.linker.backend.emitter.FunctionEmitter$JSDesugar.$anonfun$pushLhsInto$3(FunctionEmitter.scala:1477)
[error] 	at org.scalajs.linker.backend.emitter.FunctionEmitter$JSDesugar.extractLet$1(FunctionEmitter.scala:1367)
[error] 	at org.scalajs.linker.backend.emitter.FunctionEmitter$JSDesugar.pushLhsInto(FunctionEmitter.scala:1474)
[error] 	at org.scalajs.linker.backend.emitter.FunctionEmitter$JSDesugar.transformStat(FunctionEmitter.scala:853)
[error] 	at org.scalajs.linker.backend.emitter.FunctionEmitter$JSDesugar.transformLoop$1(FunctionEmitter.scala:871)
[error] 	at org.scalajs.linker.backend.emitter.FunctionEmitter$JSDesugar.transformBlockStats(FunctionEmitter.scala:877)
[error] 	at org.scalajs.linker.backend.emitter.FunctionEmitter$JSDesugar.pushLhsInto(FunctionEmitter.scala:1419)
[error] 	at org.scalajs.linker.backend.emitter.FunctionEmitter$JSDesugar.transformStat(FunctionEmitter.scala:853)
[error] 	at org.scalajs.linker.backend.emitter.FunctionEmitter$JSDesugar.desugarToFunctionInternal(FunctionEmitter.scala:495)
[error] 	at org.scalajs.linker.backend.emitter.FunctionEmitter$JSDesugar.$anonfun$desugarToFunction$1(FunctionEmitter.scala:467)
[error] 	at org.scalajs.linker.backend.emitter.FunctionEmitter$JSDesugar.performOptimisticThenPessimisticRuns(FunctionEmitter.scala:377)
[error] 	at org.scalajs.linker.backend.emitter.FunctionEmitter$JSDesugar.desugarToFunction(FunctionEmitter.scala:467)
[error] 	at org.scalajs.linker.backend.emitter.FunctionEmitter.desugarToFunction(FunctionEmitter.scala:259)
[error] 	at org.scalajs.linker.backend.emitter.ClassEmitter.genMethod(ClassEmitter.scala:489)
[error] 	at org.scalajs.linker.backend.emitter.Emitter.$anonfun$genClass$20(Emitter.scala:456)
[error] 	at org.scalajs.linker.backend.emitter.Emitter$MethodCache.getOrElseUpdate(Emitter.scala:648)
[error] 	at org.scalajs.linker.backend.emitter.Emitter.$anonfun$genClass$19(Emitter.scala:456)
[error] 	at scala.collection.TraversableLike$WithFilter.$anonfun$map$2(TraversableLike.scala:827)
[error] 	at scala.collection.immutable.List.foreach(List.scala:392)
[error] 	at scala.collection.TraversableLike$WithFilter.map(TraversableLike.scala:826)
[error] 	at org.scalajs.linker.backend.emitter.Emitter.genClass(Emitter.scala:449)
[error] 	at org.scalajs.linker.backend.emitter.Emitter.$anonfun$emitOnce$3(Emitter.scala:174)
[error] 	at scala.collection.immutable.List.map(List.scala:290)
[error] 	at org.scalajs.linker.backend.emitter.Emitter.$anonfun$emitOnce$2(Emitter.scala:174)
[error] 	at org.scalajs.logging.Logger.time(Logger.scala:42)
[error] 	at org.scalajs.logging.Logger.time$(Logger.scala:40)
[error] 	at org.scalajs.sbtplugin.Loggers$SbtLoggerWrapper.time(Loggers.scala:19)
[error] 	at org.scalajs.linker.backend.emitter.Emitter.emitOnce(Emitter.scala:174)
[error] 	at org.scalajs.linker.backend.emitter.Emitter.emitAvoidGlobalClash(Emitter.scala:148)
[error] 	at org.scalajs.linker.backend.emitter.Emitter.emitInternal(Emitter.scala:124)
[error] 	at org.scalajs.linker.backend.emitter.Emitter.emit(Emitter.scala:78)
[error] 	at org.scalajs.linker.backend.BasicLinkerBackend.$anonfun$emit$1(BasicLinkerBackend.scala:57)
[error] 	at org.scalajs.logging.Logger.time(Logger.scala:42)
[error] 	at org.scalajs.logging.Logger.time$(Logger.scala:40)
[error] 	at org.scalajs.sbtplugin.Loggers$SbtLoggerWrapper.time(Loggers.scala:19)
[error] 	at org.scalajs.linker.backend.BasicLinkerBackend.emit(BasicLinkerBackend.scala:57)
[error] 	at org.scalajs.linker.standard.StandardLinkerImpl.$anonfun$link$2(StandardLinkerImpl.scala:47)
[error] 	at scala.concurrent.Future.$anonfun$flatMap$1(Future.scala:307)
[error] 	at scala.concurrent.impl.Promise.$anonfun$transformWith$1(Promise.scala:41)
[error] 	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:64)
[error] 	at java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1402)
[error] 	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
[error] 	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
[error] 	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
[error] 	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
[error] (Compile / fastOptJS) java.util.NoSuchElementException: key not found: LabelName<matchAlts1>
```

original report↓

<details>

## step with scalaz

```shell
git clone git@github.com:scalaz/scalaz.git
cd scalaz
git checkout 82e3ae344582ba2e569a1ab5bc78ea8f26b9282e
sbt '++ 0.27.0-RC1!' rootJS/test:fastOptJS
```

## log

https://travis-ci.com/github/scalaz/scalaz/jobs/379348358#L11125

```
[error] java.util.NoSuchElementException: key not found: LabelName<matchAlts1>
[error] 	at scala.collection.immutable.Map$Map2.apply(Map.scala:138)
[error] 	at org.scalajs.linker.backend.emitter.FunctionEmitter$Env.lhsForLabeledExpr(FunctionEmitter.scala:2836)
[error] 	at org.scalajs.linker.backend.emitter.FunctionEmitter$JSDesugar.doReturnToLabel$1(FunctionEmitter.scala:1375)
[error] 	at org.scalajs.linker.backend.emitter.FunctionEmitter$JSDesugar.pushLhsInto(FunctionEmitter.scala:1437)
[error] 	at org.scalajs.linker.backend.emitter.FunctionEmitter$JSDesugar.pushLhsInto(FunctionEmitter.scala:1485)
[error] 	at org.scalajs.linker.backend.emitter.FunctionEmitter$JSDesugar.redo$1(FunctionEmitter.scala:1352)
[error] 	at org.scalajs.linker.backend.emitter.FunctionEmitter$JSDesugar.pushLhsInto(FunctionEmitter.scala:1420)
[error] 	at org.scalajs.linker.backend.emitter.FunctionEmitter$JSDesugar.$anonfun$pushLhsInto$3(FunctionEmitter.scala:1477)
[error] 	at org.scalajs.linker.backend.emitter.FunctionEmitter$JSDesugar.extractLet$1(FunctionEmitter.scala:1367)
[error] 	at org.scalajs.linker.backend.emitter.FunctionEmitter$JSDesugar.pushLhsInto(FunctionEmitter.scala:1474)
[error] 	at org.scalajs.linker.backend.emitter.FunctionEmitter$JSDesugar.transformStat(FunctionEmitter.scala:853)
[error] 	at org.scalajs.linker.backend.emitter.FunctionEmitter$JSDesugar.transformLoop$1(FunctionEmitter.scala:871)
[error] 	at org.scalajs.linker.backend.emitter.FunctionEmitter$JSDesugar.transformBlockStats(FunctionEmitter.scala:877)
[error] 	at org.scalajs.linker.backend.emitter.FunctionEmitter$JSDesugar.pushLhsInto(FunctionEmitter.scala:1419)
[error] 	at org.scalajs.linker.backend.emitter.FunctionEmitter$JSDesugar.pushLhsInto(FunctionEmitter.scala:1404)
[error] 	at org.scalajs.linker.backend.emitter.FunctionEmitter$JSDesugar.$anonfun$pushLhsInto$3(FunctionEmitter.scala:1477)
[error] 	at org.scalajs.linker.backend.emitter.FunctionEmitter$JSDesugar.extractLet$1(FunctionEmitter.scala:1367)
[error] 	at org.scalajs.linker.backend.emitter.FunctionEmitter$JSDesugar.pushLhsInto(FunctionEmitter.scala:1474)
[error] 	at org.scalajs.linker.backend.emitter.FunctionEmitter$JSDesugar.desugarToFunctionInternal(FunctionEmitter.scala:500)
[error] 	at org.scalajs.linker.backend.emitter.FunctionEmitter$JSDesugar.$anonfun$desugarToFunctionWithExplicitThis$1(FunctionEmitter.scala:455)
[error] 	at org.scalajs.linker.backend.emitter.FunctionEmitter$JSDesugar.performOptimisticThenPessimisticRuns(FunctionEmitter.scala:377)
[error] 	at org.scalajs.linker.backend.emitter.FunctionEmitter$JSDesugar.desugarToFunctionWithExplicitThis(FunctionEmitter.scala:451)
[error] 	at org.scalajs.linker.backend.emitter.FunctionEmitter.desugarToFunctionWithExplicitThis(FunctionEmitter.scala:271)
[error] 	at org.scalajs.linker.backend.emitter.ClassEmitter.genMethod(ClassEmitter.scala:491)
[error] 	at org.scalajs.linker.backend.emitter.Emitter.$anonfun$genClass$5(Emitter.scala:387)
[error] 	at org.scalajs.linker.backend.emitter.Emitter$MethodCache.getOrElseUpdate(Emitter.scala:648)
[error] 	at org.scalajs.linker.backend.emitter.Emitter.$anonfun$genClass$4(Emitter.scala:387)
[error] 	at org.scalajs.linker.backend.emitter.Emitter.$anonfun$genClass$4$adapted(Emitter.scala:378)
[error] 	at scala.collection.immutable.List.foreach(List.scala:392)
[error] 	at org.scalajs.linker.backend.emitter.Emitter.genClass(Emitter.scala:378)
[error] 	at org.scalajs.linker.backend.emitter.Emitter.$anonfun$emitOnce$3(Emitter.scala:174)
[error] 	at scala.collection.immutable.List.map(List.scala:290)
[error] 	at org.scalajs.linker.backend.emitter.Emitter.$anonfun$emitOnce$2(Emitter.scala:174)
[error] 	at org.scalajs.logging.Logger.time(Logger.scala:42)
[error] 	at org.scalajs.logging.Logger.time$(Logger.scala:40)
[error] 	at org.scalajs.sbtplugin.Loggers$SbtLoggerWrapper.time(Loggers.scala:19)
[error] 	at org.scalajs.linker.backend.emitter.Emitter.emitOnce(Emitter.scala:174)
[error] 	at org.scalajs.linker.backend.emitter.Emitter.emitAvoidGlobalClash(Emitter.scala:148)
[error] 	at org.scalajs.linker.backend.emitter.Emitter.emitInternal(Emitter.scala:124)
[error] 	at org.scalajs.linker.backend.emitter.Emitter.emit(Emitter.scala:78)
[error] 	at org.scalajs.linker.backend.BasicLinkerBackend.$anonfun$emit$1(BasicLinkerBackend.scala:57)
[error] 	at org.scalajs.logging.Logger.time(Logger.scala:42)
[error] 	at org.scalajs.logging.Logger.time$(Logger.scala:40)
[error] 	at org.scalajs.sbtplugin.Loggers$SbtLoggerWrapper.time(Loggers.scala:19)
[error] 	at org.scalajs.linker.backend.BasicLinkerBackend.emit(BasicLinkerBackend.scala:57)
[error] 	at org.scalajs.linker.standard.StandardLinkerImpl.$anonfun$link$2(StandardLinkerImpl.scala:47)
[error] 	at scala.concurrent.Future.$anonfun$flatMap$1(Future.scala:307)
[error] 	at scala.concurrent.impl.Promise.$anonfun$transformWith$1(Promise.scala:41)
[error] 	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:64)
[error] 	at java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1402)
[error] 	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
[error] 	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
[error] 	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
[error] 	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
[error] (testsJS / Test / fastOptJS) java.util.NoSuchElementException: key not found: LabelName<matchAlts1>
```

</details>

**Comment by xuwei-k** [comment]
- https://github.com/lampepfl/dotty/blob/4c99388e77be12ee6cc6cb3b503bc1093bc4a5e6/compiler/src/dotty/tools/dotc/core/NameKinds.scala#L317
- https://github.com/lampepfl/dotty/blob/4c99388e77be12ee6cc6cb3b503bc1093bc4a5e6/compiler/src/dotty/tools/dotc/transform/PatternMatcher.scala#L109-L114
- https://github.com/lampepfl/dotty/blob/4c99388e77be12ee6cc6cb3b503bc1093bc4a5e6/compiler/src/dotty/tools/dotc/transform/PatternMatcher.scala#L405-L406
- https://github.com/lampepfl/dotty/blob/4c99388e77be12ee6cc6cb3b503bc1093bc4a5e6/compiler/src/dotty/tools/dotc/ast/Trees.scala#L718-L719

**Comment by gzm0** [comment]
Thanks for the report.

What happens if you enable the IR checker (`scalaJSLinkerConfig ~= (_.withCheckIR(true))`)?

Also, what's the output of `sbt> scalajsp example.A`?

**Comment by sjrd** [comment]
`scalajsp` shows
```scala
  def main;[Ljava.lang.String;V(args: java.lang.String[]) {
    matchResult1: {
      val x1: any = null;
      matchAlts1: {
        matchAlts2: {
          if (x1.isInstanceOf[java.lang.Integer]) {
            return@matchAlts2 (void 0)
          };
          if (x1.isInstanceOf[java.lang.String]) {
            return@matchAlts2 (void 0)
          };
          return@matchAlts1 (void 0)
        };
        return@matchResult1 (void 0)
      };
      throw new scala.MatchError().<init>;Ljava.lang.Object;V(x1)
    }
  }
```
which seems correct. The IR checker lets it through.

Deactivating the optimizer with `withOptimizer(false)` works around the problem. So this is likely an issue in the optimizer.

**Comment by sjrd** [comment]
The following test for `LinkerTest` reproduces the crash:
```scala
  @Test
  def optimizerDoesNotEliminateRequiredLabeledBlockEmittedByDotty_issue4171(): AsyncResult = await {
    /*
    matchResult1: {
      val x1: any = null;
      matchAlts1: {
        matchAlts2: {
          if (x1.isInstanceOf[java.lang.Integer]) {
            return@matchAlts2 (void 0)
          };
          if (x1.isInstanceOf[java.lang.String]) {
            return@matchAlts2 (void 0)
          };
          return@matchAlts1 (void 0)
        };
        return@matchResult1 (void 0)
      };
      throw new scala.MatchError().<init>;Ljava.lang.Object;V(x1)
    }*/

    val matchResult1 = LabelIdent(LabelName("matchResult1"))
    val x1 = LocalIdent("x1")
    val matchAlts1 = LabelIdent(LabelName("matchAlts1"))
    val matchAlts2 = LabelIdent(LabelName("matchAlts2"))

    val classDefs = Seq(
        mainTestClassDef(Block(
          Labeled(matchResult1, NoType, Block(
            VarDef(x1, NON, AnyType, mutable = false, Null()),
            Labeled(matchAlts1, NoType, Block(
              Labeled(matchAlts2, NoType, Block(
                If(IsInstanceOf(VarRef(x1)(AnyType), ClassType(BoxedIntegerClass)), {
                  Return(Undefined(), matchAlts2)
                }, Skip())(NoType),
                If(IsInstanceOf(VarRef(x1)(AnyType), ClassType(BoxedStringClass)), {
                  Return(Undefined(), matchAlts2)
                }, Skip())(NoType),
                Return(Undefined(), matchAlts1)
              )),
              Return(Undefined(), matchResult1)
            )),
            Throw(New("java.lang.Exception", NoArgConstructorName, Nil))
          ))
        ))
    )

    testLink(classDefs, MainTestModuleInitializers)
  }
```
