### ISSUE TITLE
regex.Matcher.lookingAt() and matches() incorrect in 1.3.0

### ISSUE THREAD

**Issue by thesamet** [scala-js/scala-js#4252]
This is a regression in regex matcher() compared to 1.2.0:

```
val p = java.util.regex.Pattern.compile("a+")
val m = p.matcher("abaa").region(2,4);
println(m.lookingAt())
println(m.group())
```

In 1.2.0, the code would correctly print:
```
true
aa
```

In 1.3.0:
```
false
/tmp/sjs/target/scala-2.13/scala-js-tutorial-fastopt/main.js:1128
    throw new $c_jl_IllegalStateException("No match available")
    ^

java.lang.IllegalStateException: No match available
    at $p_ju_regex_Matcher__ensureLastMatch__sjs_js_RegExp$ExecResult (/tmp/sjs/target/scala-2.13/scala-js-tutorial-fastopt/main.js:1128:11)
    at $c_ju_regex_Matcher.group__T (/tmp/sjs/target/scala-2.13/scala-js-tutorial-fastopt/main.js:1201:19)
    at $c_Ltutorial_webapp_TutorialApp$.main__AT__V (/tmp/sjs/target/scala-2.13/scala-js-tutorial-fastopt/main.js:1030:19)
    at $s_Ltutorial_webapp_TutorialApp__main__AT__V (/tmp/sjs/target/scala-2.13/scala-js-tutorial-fastopt/main.js:1013:38)
    at /tmp/sjs/target/scala-2.13/scala-js-tutorial-fastopt/main.js:3244:1
    at /tmp/sjs/target/scala-2.13/scala-js-tutorial-fastopt/main.js:3245:4
    at Script.runInThisContext (vm.js:122:20)
    at Object.runInThisContext (vm.js:329:38)
    at [stdin]:8:25
    at Script.runInThisContext (vm.js:122:20)
```

This blocks upgrading ScalaPB to Scala.js 1.3.x.

**Comment by sjrd** [comment]
Thanks for the report. This was most likely broken in 537558013fb4ec30580e05a67d167c877afc6ffb.

**Comment by sjrd** [comment]
Judging by other uses of `start()` to implement other methods, I guess `matches()` is broken as well.

**Comment by gzm0** [comment]
:( eventually we'll have enough tests for this...
