### ISSUE TITLE
Refiner Info caching does not call `cleanAfterRun` on LinkedJSMethodPropDefInfoCache

### ISSUE THREAD

**Issue by gzm0** [scala-js/scala-js#4335]
Start with (post #4334)

```scala
package helloworld

import scala.scalajs.js
import js.annotation._

trait A extends js.Any {
  def foo(x: js.UndefOr[Int] = js.undefined): Int
}

object Impl extends js.Object with A {
  def foo(x: js.UndefOr[Int]): Int = x.getOrElse(5)
}

object HelloWorld {
  def main(args: Array[String]): Unit = {
    println(Impl.foo())
  }
}
```

Prepare the following diff:

```diff
 }
 
 object Impl extends js.Object with A {
-  def foo(x: js.UndefOr[Int]): Int = x.getOrElse(5)
+  def foo(x: js.UndefOr[Int] = 6): Int = x.getOrElse(5)
 }
 
 object HelloWorld {
```

Run:

```sh
$  sbt
sbt:Scala.js> helloworld2_12/run
[info] Running helloworld.HelloWorld. Hit any key to interrupt.
5
// Apply change
sbt:Scala.js> helloworld2_12/run
[info] Compiling 1 Scala source to scala-js/examples/helloworld/.2.12/target/scala-2.12/classes ...
[info] Done compiling.
[info] Fast optimizing scala-js/examples/helloworld/.2.12/target/scala-2.12/helloworld-fastopt
[info] Running helloworld.HelloWorld. Hit any key to interrupt.
scala-js/examples/helloworld/.2.12/target/scala-2.12/helloworld-fastopt/main.js:1260
        var prep0 = ((rest[0] === (void 0)) ? $s_Lhelloworld_Impl$__foo$default$1__Lhelloworld_Impl$__sjs_js_$bar(this) : rest[0]);
                              ^

ReferenceError: $s_Lhelloworld_Impl$__foo$default$1__Lhelloworld_Impl$__sjs_js_$bar is not defined
    at $b_Lhelloworld_Impl$.foo (scala-js/examples/helloworld/src/main/scala/helloworld/HelloWorld.scala:16:7)
    at $c_Lhelloworld_HelloWorld$.main__AT__V (scala-js/examples/helloworld/src/main/scala/helloworld/HelloWorld.scala:21:21)
    at $s_Lhelloworld_HelloWorld__main__AT__V (scala-js/examples/helloworld/src/main/scala/helloworld/HelloWorld.scala:19:8)
    at scala-js/examples/helloworld/.2.12/target/scala-2.12/helloworld-fastopt/main.js:1827:1
    at scala-js/examples/helloworld/.2.12/target/scala-2.12/helloworld-fastopt/main.js:1828:4
    at Script.runInThisContext (vm.js:132:18)
    at Object.runInThisContext (vm.js:315:38)
    at [stdin]:8:25
    at Script.runInThisContext (vm.js:132:18)
    at Object.runInThisContext (vm.js:315:38)
```

Restarting `sbt` and deleting only the produced JS (no code is recompiled) produces the expected:

```sh
 $ sbt
sbt:Scala.js> helloworld2_12/run
[info] Fast optimizing scala-js/examples/helloworld/.2.12/target/scala-2.12/helloworld-fastopt
[info] Running helloworld.HelloWorld. Hit any key to interrupt.
6
[success] Total time: 6 s, completed Dec 16, 2020, 4:44:25 PM
```

**Comment by gzm0** [comment]
Disabling the optimizer makes the issue go away.

**Comment by gzm0** [comment]
I am starting to write a testbed for this. The problem only seems to occur if the static method is called from a JS method. I suspect that the optimizer wrongly removes a method if it doesn't see a call to it (because it doesn't optimizer JS methods).

**Comment by gzm0** [comment]
The problem appears to be in the `Info` caching in the `Refiner`: If I replace `caches(i).getInfo(member)` in the following snippet with an uncached version, the problem vanishes.

https://github.com/scala-js/scala-js/blob/a27c22bc0bf15a84b14745231815ea0a4a12c90f/linker/shared/src/main/scala/org/scalajs/linker/frontend/Refiner.scala#L254-L270
