### ISSUE TITLE
Incremental fastLinkJS throws "key not found: ClassName<scala.package$>"

### ISSUE THREAD

**Issue by adpi2** [scala-js/scala-js#4344]
The reproduction steps are:

1. Create an sbt project with `sbt-scalajs`
```scala
// project/plugins.sbt
addSbtPlugin("org.scala-js" % "sbt-scalajs" % "1.3.1")
```
```scala
// build.sbt
lazy val root = project.in(file("."))
  .settings(
    scalaVersion := "2.13.4",
    scalaJSUseMainModuleInitializer := true,
  )
  .enablePlugins(ScalaJSPlugin, ScalaJSBundlerPlugin)
```
2. Add a single source file
```scala
// src/main/scala/foo/App.scala
package foo

import scala.scalajs.js

object App {
  def main(args: Array[String]): Unit =
    println(Scene)
}

object Scene extends js.Object {
  val title = ""
}
```
3. In the sbt shell run `fastLinkJS`
4. Change `val title = ""` to `val title = Seq()`
5. Run `fastLinkJS` again
It should return the following error
```shell
[error] stack trace is suppressed; run last Compile / fastLinkJS for the full output
[error] (Compile / fastLinkJS) java.util.NoSuchElementException: key not found: ClassName<scala.package$>
[error] Total time: 0 s, completed Dec 22, 2020, 2:47:38 PM
```
But if you run `fastLinkJS` again, it should succeed.

The full stack trace is

```shell
[debug] Linker: Compute reachability: 35227 us
[debug] Linker: Assemble LinkedClasses: 5119 us
[debug] Linker: 54984 us
[debug] Optimizer: Batch mode: false
[debug] Optimizer: Incremental part: 8939 us
[debug] Optimizer: Optimizing 1621 methods.
[debug] Optimizer: Optimizer part: 30292 us
[debug] Optimizer: 41272 us
[debug] Refiner: Compute reachability: 3562 us
[debug] Refiner: Assemble LinkedClasses: 363 us
[debug] Refiner: 4459 us
[debug] Module Splitter: Calculate Dependency Info: 52 us
[debug] Module Splitter: Analyze Modules: 2 us
[debug] Module Splitter: Assemble Modules: 139 us
[debug] Module Splitter: 232 us
[debug] Emitter: Class tree cache stats: reused: 20 -- invalidated: 8
[debug] Emitter: Method tree cache stats: reused: 30 -- invalidated: 10
[error] java.util.NoSuchElementException: key not found: ClassName<scala.package$>
[error]         at scala.collection.MapLike.default(MapLike.scala:235)
[error]         at scala.collection.MapLike.default$(MapLike.scala:234)
[error]         at scala.collection.AbstractMap.default(Map.scala:65)
[error]         at scala.collection.mutable.HashMap.apply(HashMap.scala:69)
[error]         at org.scalajs.linker.backend.emitter.KnowledgeGuardian$KnowledgeAccessor.getModule(KnowledgeGuardian.scala:211)
[error]         at org.scalajs.linker.backend.emitter.VarGen.foldSameModule(VarGen.scala:145)
[error]         at org.scalajs.linker.backend.emitter.VarGen.globalVar(VarGen.scala:49)
[error]         at org.scalajs.linker.backend.emitter.SJSGen.genLoadModule(SJSGen.scala:273)
[error]         at org.scalajs.linker.backend.emitter.FunctionEmitter$JSDesugar.transformExpr(FunctionEmitter.scala:2020)
[error]         at org.scalajs.linker.backend.emitter.FunctionEmitter$JSDesugar.transformExprNoChar(FunctionEmitter.scala:1953)
[error]         at org.scalajs.linker.backend.emitter.FunctionEmitter$JSDesugar.transformExpr(FunctionEmitter.scala:2036)
[error]         at org.scalajs.linker.backend.emitter.FunctionEmitter$JSDesugar.transformExprNoChar(FunctionEmitter.scala:1953)
[error]         at org.scalajs.linker.backend.emitter.FunctionEmitter$JSDesugar.transformExpr(FunctionEmitter.scala:2036)
[error]         at org.scalajs.linker.backend.emitter.FunctionEmitter$JSDesugar.transformExprNoChar(FunctionEmitter.scala:1953)
[error]         at org.scalajs.linker.backend.emitter.FunctionEmitter$JSDesugar.transformExpr(FunctionEmitter.scala:2467)
[error]         at org.scalajs.linker.backend.emitter.FunctionEmitter$JSDesugar.transformExprNoChar(FunctionEmitter.scala:1953)
[error]         at org.scalajs.linker.backend.emitter.FunctionEmitter$JSDesugar.$anonfun$transformStat$4(FunctionEmitter.scala:624)
[error]         at org.scalajs.linker.backend.emitter.FunctionEmitter$JSDesugar.$anonfun$unnest$8(FunctionEmitter.scala:1094)
[error]         at org.scalajs.linker.backend.emitter.FunctionEmitter$JSDesugar.unnest(FunctionEmitter.scala:936)
[error]         at org.scalajs.linker.backend.emitter.FunctionEmitter$JSDesugar.unnest(FunctionEmitter.scala:1092)
[error]         at org.scalajs.linker.backend.emitter.FunctionEmitter$JSDesugar.transformStat(FunctionEmitter.scala:618)
[error]         at org.scalajs.linker.backend.emitter.FunctionEmitter$JSDesugar.transformLoop$1(FunctionEmitter.scala:888)
[error]         at org.scalajs.linker.backend.emitter.FunctionEmitter$JSDesugar.transformBlockStats(FunctionEmitter.scala:894)
[error]         at org.scalajs.linker.backend.emitter.FunctionEmitter$JSDesugar.pushLhsInto(FunctionEmitter.scala:1458)
[error]         at org.scalajs.linker.backend.emitter.FunctionEmitter$JSDesugar.desugarToFunctionInternal(FunctionEmitter.scala:504)
[error]         at org.scalajs.linker.backend.emitter.FunctionEmitter$JSDesugar.$anonfun$desugarToFunction$1(FunctionEmitter.scala:471)
[error]         at org.scalajs.linker.backend.emitter.FunctionEmitter$JSDesugar.performOptimisticThenPessimisticRuns(FunctionEmitter.scala:381)
[error]         at org.scalajs.linker.backend.emitter.FunctionEmitter$JSDesugar.desugarToFunction(FunctionEmitter.scala:471)
[error]         at org.scalajs.linker.backend.emitter.FunctionEmitter.desugarToFunction(FunctionEmitter.scala:260)
[error]         at org.scalajs.linker.backend.emitter.ClassEmitter$$anonfun$genConstructorFunForJSClass$2.applyOrElse(ClassEmitter.scala:388)
[error]         at org.scalajs.linker.backend.emitter.ClassEmitter$$anonfun$genConstructorFunForJSClass$2.applyOrElse(ClassEmitter.scala:385)
[error]         at scala.collection.TraversableOnce.collectFirst(TraversableOnce.scala:172)
[error]         at scala.collection.TraversableOnce.collectFirst$(TraversableOnce.scala:159)
[error]         at scala.collection.AbstractTraversable.collectFirst(Traversable.scala:108)
[error]         at org.scalajs.linker.backend.emitter.ClassEmitter.genConstructorFunForJSClass(ClassEmitter.scala:385)
[error]         at org.scalajs.linker.backend.emitter.ClassEmitter.genES6Constructor(ClassEmitter.scala:270)
[error]         at org.scalajs.linker.backend.emitter.ClassEmitter.genConstructor(ClassEmitter.scala:184)
[error]         at org.scalajs.linker.backend.emitter.Emitter.$anonfun$genClass$10(Emitter.scala:420)
[error]         at org.scalajs.linker.backend.emitter.Emitter$MethodCache.getOrElseUpdate(Emitter.scala:655)
[error]         at org.scalajs.linker.backend.emitter.Emitter.genClass(Emitter.scala:420)
[error]         at org.scalajs.linker.backend.emitter.Emitter.$anonfun$emitOnce$4(Emitter.scala:180)
[error]         at scala.collection.immutable.List.map(List.scala:297)
[error]         at org.scalajs.linker.backend.emitter.Emitter.$anonfun$emitOnce$2(Emitter.scala:180)
[error]         at scala.collection.immutable.List.map(List.scala:293)
[error]         at org.scalajs.linker.backend.emitter.Emitter.$anonfun$emitOnce$1(Emitter.scala:177)
[error]         at org.scalajs.logging.Logger.time(Logger.scala:42)
[error]         at org.scalajs.logging.Logger.time$(Logger.scala:40)
[error]         at org.scalajs.sbtplugin.Loggers$SbtLoggerWrapper.time(Loggers.scala:19)
[error]         at org.scalajs.linker.backend.emitter.Emitter.emitOnce(Emitter.scala:181)
[error]         at org.scalajs.linker.backend.emitter.Emitter.emitAvoidGlobalClash(Emitter.scala:151)
[error]         at org.scalajs.linker.backend.emitter.Emitter.emitInternal(Emitter.scala:127)
[error]         at org.scalajs.linker.backend.emitter.Emitter.emit(Emitter.scala:79)
[error]         at org.scalajs.linker.backend.BasicLinkerBackend.$anonfun$emit$1(BasicLinkerBackend.scala:57)
[error]         at org.scalajs.logging.Logger.time(Logger.scala:42)
[error]         at org.scalajs.logging.Logger.time$(Logger.scala:40)
[error]         at org.scalajs.sbtplugin.Loggers$SbtLoggerWrapper.time(Loggers.scala:19)
[error]         at org.scalajs.linker.backend.BasicLinkerBackend.emit(BasicLinkerBackend.scala:57)
[error]         at scalajsbundler.bundlerlinker.EntryPointAnalyzerBackend.emit(EntryPointAnalyzerBackend.scala:26)
[error]         at org.scalajs.linker.standard.StandardLinkerImpl.$anonfun$link$2(StandardLinkerImpl.scala:47)
[error]         at scala.concurrent.Future.$anonfun$flatMap$1(Future.scala:307)
[error]         at scala.concurrent.impl.Promise.$anonfun$transformWith$1(Promise.scala:41)
[error]         at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:64)
[error]         at java.base/java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1426)
[error]         at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
[error]         at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
[error]         at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
[error]         at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
[error]         at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:177)
[error] (Compile / fastLinkJS) java.util.NoSuchElementException: key not found: ClassName<scala.package$>
```

**Comment by gzm0** [comment]
Thank you for filing this with full reproduction. Very much looks like a bug in the incremental pipeline.

**Comment by sjrd** [comment]
I can reproduce this in the hello world on `master`, but not on top of #4341. So I believe #4341 is fixing this issue as well.

**Comment by gzm0** [comment]
Ah yes. That makes sense: It is a `js.Object` so it's the same invalidation issue.

**Comment by adpi2** [comment]
Wow! That is being efficient!
