### ISSUE TITLE
Upgrade to use scala 2.12.13 to resolve scala map concatenation bug

### ISSUE THREAD

**Issue by dsw2127** [scala-js/scala-js#4459]
Scala bug https://github.com/scala/bug/issues/12140 introduced in scala 2.12.11 is hit when using scala-js 0.6.x versions greater than 0.6.32 or 1.x versions greater than 1.1.0. Upgrading scala-js to scala 2.12.13 for both of these branches would resolve these issues.

Example repro (`HashMapConcatNpe` taken from https://github.com/scala/bug/issues/12140):

**build.sbt**
```
enablePlugins(ScalaJSPlugin)

scalaVersion := "2.12.10"

scalaJSUseMainModuleInitializer := true

scalacOptions ++= Seq(
  "-deprecation",
  "-feature",
  "-encoding",
  "utf-8",
)
```
**HashMapConcatNpe.scala**
```
import scala.collection.immutable.HashMap

object HashMapConcatNpe {
  trait DataType              extends Product with Serializable
  case class Foo(arg: String) extends DataType
  case class Bar(arg: String) extends DataType

  def main(args: Array[String]): Unit = {
    // Create a HashMap consisting of a single HashMapCollision1.
    val collision = HashMap(Foo("toxic") -> 0, Bar("toxic") -> 0)
    val singleton = (new HashMap[DataType, Int]).updated(Foo("toxic"), 0)

    collision ++ singleton
  }
}
```

**Failure on scala-js 0.6.33:**
```
dwalker24-mac:test_proj dwalker$ cat project/plugins.sbt
addSbtPlugin("org.scala-js" % "sbt-scalajs" % "0.6.33")
dwalker24-mac:test_proj dwalker$ ../sbt/bin/sbt
[info] welcome to sbt 1.4.9 (Azul Systems, Inc. Java 15.0.2)
[info] loading settings for project test_proj-build from plugins.sbt ...
[info] loading project definition from /Users/dwalker/Documents/no_scan/code/scala_testing/test_proj/project
[info] loading settings for project test_proj from build.sbt ...
[info] set current project to test_proj (in build file:/Users/dwalker/Documents/no_scan/code/scala_testing/test_proj/)
[info] sbt server started at local:///Users/dwalker/.sbt/1.0/server/2655f7ee41497186cdbf/sock
[info] started sbt server
sbt:test_proj> clean
[success] Total time: 0 s, completed Apr 1, 2021, 1:48:34 PM
sbt:test_proj> run
[info] compiling 1 Scala source to /Users/dwalker/Documents/no_scan/code/scala_testing/test_proj/target/scala-2.12/classes ...
[info] Fast optimizing /Users/dwalker/Documents/no_scan/code/scala_testing/test_proj/target/scala-2.12/test_proj-fastopt.js
[info] Running HashMapConcatNpe
/Users/dwalker/Documents/no_scan/code/scala_testing/test_proj/target/scala-2.12/test_proj-fastopt.js:9027
  var k = kv.$$und1$f;
             ^

TypeError: Cannot read property '$$und1$f' of null
    at $c_sci_ListMap$Node.$$plus__T2__sci_ListMap (/Users/dwalker/Documents/no_scan/code/scala_testing/test_proj/target/scala-2.12/test_proj-fastopt.js:9027:14)
    at $c_sci_HashMap$HashMapCollision1.updated0__O__I__I__O__T2__sci_HashMap$Merger__sci_HashMap (/Users/dwalker/Documents/no_scan/code/scala_testing/test_proj/target/scala-2.12/test_proj-fastopt.js:9442:270)
    at $c_sci_HashMap$HashMap1.merge0__sci_HashMap__I__sci_HashMap$Merger__sci_HashMap (/Users/dwalker/Documents/no_scan/code/scala_testing/test_proj/target/scala-2.12/test_proj-fastopt.js:9360:17)
    at $c_sci_HashMap$HashMap1.$c_sci_HashMap.merged__sci_HashMap__F2__sci_HashMap (/Users/dwalker/Documents/no_scan/code/scala_testing/test_proj/target/scala-2.12/test_proj-fastopt.js:8649:15)
    at $c_sci_HashMap$HashMapCollision1.$c_sci_HashMap.$$plus$plus__sc_GenTraversableOnce__scg_CanBuildFrom__O (/Users/dwalker/Documents/no_scan/code/scala_testing/test_proj/target/scala-2.12/test_proj-fastopt.js:8689:17)
    at $c_LHashMapConcatNpe$.main__AT__V (/Users/dwalker/Documents/no_scan/code/scala_testing/test_proj/target/scala-2.12/test_proj-fastopt.js:1163:25)
    at Object.<anonymous> (/Users/dwalker/Documents/no_scan/code/scala_testing/test_proj/target/scala-2.12/test_proj-fastopt.js:10256:25)
    at Object.<anonymous> (/Users/dwalker/Documents/no_scan/code/scala_testing/test_proj/target/scala-2.12/test_proj-fastopt.js:10257:4)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
[error] org.scalajs.jsenv.ExternalJSEnv$NonZeroExitException: Node.js exited with code 1
[error] 	at org.scalajs.jsenv.ExternalJSEnv$AbstractExtRunner.waitForVM(ExternalJSEnv.scala:133)
[error] 	at org.scalajs.jsenv.ExternalJSEnv$ExtRunner.run(ExternalJSEnv.scala:183)
[error] 	at org.scalajs.sbtplugin.ScalaJSPluginInternal$.jsRun(ScalaJSPluginInternal.scala:819)
[error] 	at org.scalajs.sbtplugin.ScalaJSPluginInternal$.$anonfun$scalaJSRunSettings$22(ScalaJSPluginInternal.scala:983)
[error] 	at org.scalajs.sbtplugin.ScalaJSPluginInternal$.$anonfun$scalaJSRunSettings$22$adapted(ScalaJSPluginInternal.scala:976)
[error] 	at scala.Function1.$anonfun$compose$1(Function1.scala:49)
[error] stack trace is suppressed; run last Compile / run for the full output
[error] (Compile / run) org.scalajs.jsenv.ExternalJSEnv$NonZeroExitException: Node.js exited with code 1
[error] Total time: 4 s, completed Apr 1, 2021, 1:48:39 PM
```

**As opposed to success on 0.6.32:**
```
dwalker24-mac:test_proj dwalker$ cat project/plugins.sbt
addSbtPlugin("org.scala-js" % "sbt-scalajs" % "0.6.32")
dwalker24-mac:test_proj dwalker$ ../sbt/bin/sbt
[info] welcome to sbt 1.4.9 (Azul Systems, Inc. Java 15.0.2)
[info] loading settings for project test_proj-build from plugins.sbt ...
[info] loading project definition from /Users/dwalker/Documents/no_scan/code/scala_testing/test_proj/project
[info] loading settings for project test_proj from build.sbt ...
[info] set current project to test_proj (in build file:/Users/dwalker/Documents/no_scan/code/scala_testing/test_proj/)
[info] sbt server started at local:///Users/dwalker/.sbt/1.0/server/2655f7ee41497186cdbf/sock
[info] started sbt server
sbt:test_proj> clean
[success] Total time: 0 s, completed Apr 1, 2021, 1:47:12 PM
sbt:test_proj> run
[info] compiling 1 Scala source to /Users/dwalker/Documents/no_scan/code/scala_testing/test_proj/target/scala-2.12/classes ...
[info] Fast optimizing /Users/dwalker/Documents/no_scan/code/scala_testing/test_proj/target/scala-2.12/test_proj-fastopt.js
[info] Running HashMapConcatNpe
[success] Total time: 5 s, completed Apr 1, 2021, 1:47:18 PM
```

Similar results for scala-js >=1.1.0 (failure) vs 1.0.1 (success).

**Comment by sjrd** [comment]
We should indeed upgrade to Scala 2.12.13 and 2.13.5.

Note that the 0.6.x series is EOL, so we won't publish any new 0.6.x release.

**Comment by blakehawkins** [comment]
Note: I have this issue in 2.12.13 but the issue has gone away in 2.12.16
