### ISSUE TITLE
compileIncremental fails

### ISSUE THREAD

**Issue by catap** [scala-js/scala-js#4481]
After migrating a code base to scala.js 1.5.1  and scala3 `compileIncremental` phase fails with error:
```
error] java.lang.IllegalArgumentException: Invalid name: [-3, 3]$2
[error] 	at org.scalajs.ir.Names$.org$scalajs$ir$Names$$$throwInvalidEncodedName(Names.scala:536)
[error] 	at org.scalajs.ir.Names$.org$scalajs$ir$Names$$$validateSimpleEncodedName(Names.scala:550)
[error] 	at org.scalajs.ir.Names$.org$scalajs$ir$Names$$$validateSimpleEncodedName(Names.scala:539)
[error] 	at org.scalajs.ir.Names$LocalName$.apply(Names.scala:106)
[error] 	at org.scalajs.ir.Names$LocalName$.apply(Names.scala:109)
[error] 	at dotty.tools.backend.sjs.JSEncoding$LocalNameGenerator.freshLocalIdent(JSEncoding.scala:109)
[error] 	at dotty.tools.backend.sjs.JSCodeGen.freshLocalIdent(JSCodeGen.scala:132)
[error] 	at dotty.tools.backend.sjs.JSCodeGen.$anonfun$29(JSCodeGen.scala:3044)
[error] 	at scala.collection.immutable.List.map(List.scala:250)
[error] 	at dotty.tools.backend.sjs.JSCodeGen.genClosure(JSCodeGen.scala:3051)
[error] 	at dotty.tools.backend.sjs.JSCodeGen.genStatOrExpr(JSCodeGen.scala:1532)
[error] 	at dotty.tools.backend.sjs.JSCodeGen.genStatOrExpr(JSCodeGen.scala:1469)
[error] 	at dotty.tools.backend.sjs.JSCodeGen.genExpr(JSCodeGen.scala:1263)
[error] 	at dotty.tools.backend.sjs.JSCodeGen.genActualArgs$$anonfun$1(JSCodeGen.scala:3679)
[error] 	at scala.collection.immutable.List.map(List.scala:250)
[error] 	at dotty.tools.backend.sjs.JSCodeGen.genActualArgs(JSCodeGen.scala:3679)
[error] 	at dotty.tools.backend.sjs.JSCodeGen.genNormalApply(JSCodeGen.scala:2635)
[error] 	at dotty.tools.backend.sjs.JSCodeGen.genApply(JSCodeGen.scala:1722)
[error] 	at dotty.tools.backend.sjs.JSCodeGen.genStatOrExpr(JSCodeGen.scala:1390)
[error] 	at dotty.tools.backend.sjs.JSCodeGen.genStatOrExpr(JSCodeGen.scala:1469)
[error] 	at dotty.tools.backend.sjs.JSCodeGen.genStatOrExpr(JSCodeGen.scala:1469)
[error] 	at dotty.tools.backend.sjs.JSCodeGen.genStatOrExpr(JSCodeGen.scala:1469)
[error] 	at dotty.tools.backend.sjs.JSCodeGen.genStatOrExpr(JSCodeGen.scala:1469)
[error] 	at dotty.tools.backend.sjs.JSCodeGen.genStat(JSCodeGen.scala:1241)
[error] 	at dotty.tools.backend.sjs.JSCodeGen.genStatOrExpr$$anonfun$5(JSCodeGen.scala:1469)
[error] 	at scala.collection.immutable.List.map(List.scala:246)
[error] 	at dotty.tools.backend.sjs.JSCodeGen.genStatOrExpr(JSCodeGen.scala:1469)
[error] 	at dotty.tools.backend.sjs.JSCodeGen.genStat(JSCodeGen.scala:1241)
[error] 	at dotty.tools.backend.sjs.JSCodeGen.genBody$1(JSCodeGen.scala:1145)
[error] 	at dotty.tools.backend.sjs.JSCodeGen.genMethodDef(JSCodeGen.scala:1151)
[error] 	at dotty.tools.backend.sjs.JSCodeGen.genMethodWithCurrentLocalNameScope$$anonfun$1(JSCodeGen.scala:1118)
[error] 	at dotty.tools.backend.sjs.ScopedVar$.withScopedVars(ScopedVar.scala:35)
[error] 	at dotty.tools.backend.sjs.JSCodeGen.genMethodWithCurrentLocalNameScope(JSCodeGen.scala:1124)
[error] 	at dotty.tools.backend.sjs.JSCodeGen.genMethod$$anonfun$1(JSCodeGen.scala:1022)
[error] 	at dotty.tools.backend.sjs.ScopedVar$.withScopedVars(ScopedVar.scala:35)
[error] 	at dotty.tools.backend.sjs.JSCodeGen.genMethod(JSCodeGen.scala:1023)
[error] 	at dotty.tools.backend.sjs.JSCodeGen.genScalaClass$$anonfun$2(JSCodeGen.scala:341)
[error] 	at scala.collection.immutable.List.foreach(List.scala:333)
[error] 	at dotty.tools.backend.sjs.JSCodeGen.genScalaClass(JSCodeGen.scala:346)
[error] 	at dotty.tools.backend.sjs.JSCodeGen.genCompilationUnit$$anonfun$6$$anonfun$1(JSCodeGen.scala:217)
[error] 	at dotty.tools.backend.sjs.ScopedVar$.withScopedVars(ScopedVar.scala:35)
[error] 	at dotty.tools.backend.sjs.JSCodeGen.genCompilationUnit$$anonfun$2(JSCodeGen.scala:221)
[error] 	at scala.runtime.function.JProcedure1.apply(JProcedure1.java:15)
[error] 	at scala.runtime.function.JProcedure1.apply(JProcedure1.java:10)
[error] 	at scala.collection.immutable.List.foreach(List.scala:333)
[error] 	at dotty.tools.backend.sjs.JSCodeGen.genCompilationUnit(JSCodeGen.scala:223)
[error] 	at dotty.tools.backend.sjs.JSCodeGen.run(JSCodeGen.scala:152)
[error] 	at dotty.tools.backend.sjs.GenSJSIR.run(GenSJSIR.scala:15)
[error] 	at dotty.tools.dotc.core.Phases$Phase.runOn$$anonfun$1(Phases.scala:303)
[error] 	at scala.collection.immutable.List.map(List.scala:250)
[error] 	at dotty.tools.dotc.core.Phases$Phase.runOn(Phases.scala:304)
[error] 	at dotty.tools.dotc.Run.runPhases$4$$anonfun$4(Run.scala:205)
[error] 	at scala.runtime.function.JProcedure1.apply(JProcedure1.java:15)
[error] 	at scala.runtime.function.JProcedure1.apply(JProcedure1.java:10)
[error] 	at scala.collection.ArrayOps$.foreach$extension(ArrayOps.scala:1323)
[error] 	at dotty.tools.dotc.Run.runPhases$5(Run.scala:215)
[error] 	at dotty.tools.dotc.Run.compileUnits$$anonfun$1(Run.scala:223)
[error] 	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.scala:18)
[error] 	at dotty.tools.dotc.util.Stats$.maybeMonitored(Stats.scala:67)
[error] 	at dotty.tools.dotc.Run.compileUnits(Run.scala:230)
[error] 	at dotty.tools.dotc.Run.compileSources(Run.scala:166)
[error] 	at dotty.tools.dotc.Run.compile(Run.scala:150)
[error] 	at dotty.tools.dotc.Driver.doCompile(Driver.scala:39)
[error] 	at dotty.tools.xsbt.CompilerBridgeDriver.run(CompilerBridgeDriver.java:88)
[error] 	at dotty.tools.xsbt.CompilerBridge.run(CompilerBridge.java:22)
[error] 	at sbt.internal.inc.AnalyzingCompiler.compile(AnalyzingCompiler.scala:91)
[error] 	at sbt.internal.inc.MixedAnalyzingCompiler.$anonfun$compile$7(MixedAnalyzingCompiler.scala:186)
[error] 	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
[error] 	at sbt.internal.inc.MixedAnalyzingCompiler.timed(MixedAnalyzingCompiler.scala:241)
[error] 	at sbt.internal.inc.MixedAnalyzingCompiler.$anonfun$compile$4(MixedAnalyzingCompiler.scala:176)
[error] 	at sbt.internal.inc.MixedAnalyzingCompiler.$anonfun$compile$4$adapted(MixedAnalyzingCompiler.scala:157)
[error] 	at sbt.internal.inc.JarUtils$.withPreviousJar(JarUtils.scala:239)
[error] 	at sbt.internal.inc.MixedAnalyzingCompiler.compileScala$1(MixedAnalyzingCompiler.scala:157)
[error] 	at sbt.internal.inc.MixedAnalyzingCompiler.compile(MixedAnalyzingCompiler.scala:204)
[error] 	at sbt.internal.inc.IncrementalCompilerImpl.$anonfun$compileInternal$1(IncrementalCompilerImpl.scala:528)
[error] 	at sbt.internal.inc.IncrementalCompilerImpl.$anonfun$compileInternal$1$adapted(IncrementalCompilerImpl.scala:528)
[error] 	at sbt.internal.inc.Incremental$.$anonfun$apply$5(Incremental.scala:174)
[error] 	at sbt.internal.inc.Incremental$.$anonfun$apply$5$adapted(Incremental.scala:172)
[error] 	at sbt.internal.inc.Incremental$$anon$2.run(Incremental.scala:457)
[error] 	at sbt.internal.inc.IncrementalCommon$CycleState.next(IncrementalCommon.scala:116)
[error] 	at sbt.internal.inc.IncrementalCommon$$anon$1.next(IncrementalCommon.scala:56)
[error] 	at sbt.internal.inc.IncrementalCommon$$anon$1.next(IncrementalCommon.scala:52)
[error] 	at sbt.internal.inc.IncrementalCommon.cycle(IncrementalCommon.scala:261)
[error] 	at sbt.internal.inc.Incremental$.$anonfun$incrementalCompile$8(Incremental.scala:412)
[error] 	at sbt.internal.inc.Incremental$.withClassfileManager(Incremental.scala:499)
[error] 	at sbt.internal.inc.Incremental$.incrementalCompile(Incremental.scala:399)
[error] 	at sbt.internal.inc.Incremental$.apply(Incremental.scala:166)
[error] 	at sbt.internal.inc.IncrementalCompilerImpl.compileInternal(IncrementalCompilerImpl.scala:528)
[error] 	at sbt.internal.inc.IncrementalCompilerImpl.$anonfun$compileIncrementally$1(IncrementalCompilerImpl.scala:482)
[error] 	at sbt.internal.inc.IncrementalCompilerImpl.handleCompilationError(IncrementalCompilerImpl.scala:332)
[error] 	at sbt.internal.inc.IncrementalCompilerImpl.compileIncrementally(IncrementalCompilerImpl.scala:420)
[error] 	at sbt.internal.inc.IncrementalCompilerImpl.compile(IncrementalCompilerImpl.scala:137)
[error] 	at sbt.Defaults$.compileIncrementalTaskImpl(Defaults.scala:2346)
[error] 	at sbt.Defaults$.$anonfun$compileIncrementalTask$2(Defaults.scala:2303)
[error] 	at sbt.internal.io.Retry$.apply(Retry.scala:46)
[error] 	at sbt.internal.io.Retry$.apply(Retry.scala:28)
[error] 	at sbt.internal.io.Retry$.apply(Retry.scala:23)
[error] 	at sbt.internal.server.BspCompileTask$.compute(BspCompileTask.scala:31)
[error] 	at sbt.Defaults$.$anonfun$compileIncrementalTask$1(Defaults.scala:2299)
[error] 	at scala.Function1.$anonfun$compose$1(Function1.scala:49)
[error] 	at sbt.internal.util.$tilde$greater.$anonfun$$u2219$1(TypeFunctions.scala:62)
[error] 	at sbt.std.Transform$$anon$4.work(Transform.scala:68)
[error] 	at sbt.Execute.$anonfun$submit$2(Execute.scala:282)
[error] 	at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:23)
[error] 	at sbt.Execute.work(Execute.scala:291)
[error] 	at sbt.Execute.$anonfun$submit$1(Execute.scala:282)
[error] 	at sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:265)
[error] 	at sbt.CompletionService$$anon$2.call(CompletionService.scala:64)
[error] 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error] 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[error] 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[error] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[error] 	at java.lang.Thread.run(Thread.java:748)
```

**Comment by sjrd** [comment]
Crashes in the Scala 3 compiler should be reported on the dotty repo, not here, even if they involve Scala.js. Please reopen over there.

**Comment by catap** [comment]
Reopened it here: https://github.com/lampepfl/dotty/issues/12507
