### ISSUE TITLE
Many dynamicImports with FewestModules causes the Linker to GC itself to death

### ISSUE THREAD

**Issue by dispalt** [scala-js/scala-js#4542]
So this is a perplexing one.

I have a fairly big application that uses dynamic imports, and with that I use FewestModules for the production builds.  However I added a new module recently and the linker started dieing basically from GC pressure.

I looked in jvisualvm and in the memory sample the number one object was a RedBlackTree in terms of total size.  Unfortunately the code is private but I think it has something to do maybe the internal-id generation?  And without seeing the code, the only difference from when the linker didn't die and when it did, is that I added 2 `dynamicImports`.  I do have sourceMaps on as well.  And of course, the GCC is disabled.

Upping memory from 3g -> 4g didn't make a difference.

Here's the list of modules the commit before it started bombing (I removed the sourceMaps from the listing):

```
internal-0.js
internal-10608.js
internal-10938.js
internal-10.js
internal-12238.js
internal-12378.js
internal-1251730.js
internal-12.js
internal-1330878.js
internal-1338.js
internal-1345814.js
internal-1352956.js
internal-1388.js
internal-147062.js
internal-14.js
internal-1575752.js
internal-16.js
internal-1821838.js
internal-18.js
internal-2006.js
internal-2054544.js
internal-2085364.js
internal-2094766.js
internal-2097148.js
internal-2097149.js
internal-20.js
internal-2106.js
internal-212310.js
internal-215270.js
internal-22.js
internal-2368.js
internal-24.js
internal-252.js
internal-2662.js
internal-2676.js
internal-2678.js
internal-26.js
internal-28.js
internal-29240.js
internal-29260.js
internal-298.js
internal-2.js
internal-30.js
internal-310.js
internal-32.js
internal-333470.js
internal-34650.js
internal-34.js
internal-36.js
internal-370.js
internal-372.js
internal-38.js
internal-390.js
internal-394.js
internal-396.js
internal-398.js
internal-40142.js
internal-416.js
internal-418.js
internal-43178.js
internal-474788.js
internal-4.js
internal-52496.js
internal-603194.js
internal-66.js
internal-6946.js
internal-6.js
internal-740.js
internal-74.js
internal-758.js
internal-8726.js
internal-8.js
internal-93428.js
internal-951372.js
internal-951442.js
internal-996600.js
main.js
```

**Comment by sjrd** [comment]
Thanks for the report.

Is it possible to get a stack trace of the linker at the time of dying?

**Comment by dispalt** [comment]
Would like a threaddump work? It basically GC's itself to death so there's no real "error" per se.  I can also do a screenshot of jvisualvm if that would be helpful.

**Comment by sjrd** [comment]
A thread dump would be useful, yes.

**Comment by gzm0** [comment]
Better even a heap dump. VisualVM should let you export that. (It might expose some stuff about your code, so if you're concerned, you might wanna send it privately).

**Comment by dispalt** [comment]
While I figure out a way to give you a heapdump, here's a thread from the linker that looks interesting.

```
"scala-execution-context-global-404" daemon prio=5 tid=404 RUNNABLE
    at scala.collection.immutable.NewRedBlackTree$.upd(RedBlackTree.scala:422)
       local variable: scala.collection.immutable.NewRedBlackTree$#1
       local variable: scala.collection.immutable.NewRedBlackTree$Tree#9361007
       local variable: org.scalajs.ir.Names$ClassName#46392
       local variable: scala.runtime.BoxedUnit#1
       local variable: scala.math.LowPriorityOrderingImplicits$$anon$2#2
    at scala.collection.immutable.NewRedBlackTree$.upd(RedBlackTree.scala:426)
    at scala.collection.immutable.NewRedBlackTree$.upd(RedBlackTree.scala:426)
    at scala.collection.immutable.NewRedBlackTree$.upd(RedBlackTree.scala:426)
    at scala.collection.immutable.NewRedBlackTree$.upd(RedBlackTree.scala:426)
    at scala.collection.immutable.NewRedBlackTree$.update(RedBlackTree.scala:182)
    at scala.collection.immutable.TreeSet.$plus(TreeSet.scala:217)
    at scala.collection.immutable.TreeSet.$plus(TreeSet.scala:134)
    at scala.collection.mutable.SetBuilder.$plus$eq(SetBuilder.scala:28)
    at scala.collection.mutable.SetBuilder.$plus$eq(SetBuilder.scala:24)
    at scala.collection.SetLike$SubsetsItr.$anonfun$next$1(SetLike.scala:272)
    at scala.collection.SetLike$SubsetsItr.$anonfun$next$1$adapted(SetLike.scala:272)
    at scala.collection.SetLike$SubsetsItr.next(SetLike.scala:272)
       local variable: scala.collection.SetLike$SubsetsItr#1
    at scala.collection.SetLike$SubsetsItr.next(SetLike.scala:262)
    at scala.collection.SetLike$$anon$1.next(SetLike.scala:251)
    at scala.collection.SetLike$$anon$1.next(SetLike.scala:236)
    at scala.collection.Iterator$$anon$11.nextCur(Iterator.scala:486)
    at scala.collection.Iterator$$anon$11.hasNext(Iterator.scala:492)
       local variable: scala.collection.Iterator$$anon$11#1
    at scala.collection.Iterator.foreach(Iterator.scala:943)
       local variable: scala.collection.Iterator$$anon$11#1
       local variable: scala.collection.generic.Growable$$Lambda$111#1
    at scala.collection.Iterator.foreach$(Iterator.scala:943)
    at scala.collection.AbstractIterator.foreach(Iterator.scala:1431)
       local variable: scala.collection.Iterator$$anon$11#1
       local variable: scala.collection.generic.Growable$$Lambda$111#1
    at scala.collection.generic.Growable.$plus$plus$eq(Growable.scala:62)
       local variable: scala.collection.immutable.Map$MapBuilderImpl#1
    at scala.collection.generic.Growable.$plus$plus$eq$(Growable.scala:53)
    at scala.collection.immutable.Map$MapBuilderImpl.$plus$plus$eq(Map.scala:648)
       local variable: scala.collection.immutable.Map$MapBuilderImpl#1
       local variable: scala.collection.Iterator$$anon$11#1
    at scala.collection.immutable.Map$MapBuilderImpl.$plus$plus$eq(Map.scala:595)
    at scala.collection.TraversableOnce.toMap(TraversableOnce.scala:372)
       local variable: scala.collection.immutable.Map$MapBuilderImpl#1
    at scala.collection.TraversableOnce.toMap$(TraversableOnce.scala:370)
    at scala.collection.AbstractIterator.toMap(Iterator.scala:1431)
       local variable: scala.collection.Iterator$$anon$11#1
       local variable: scala.Predef$$anon$2#1
    at org.scalajs.linker.frontend.modulesplitter.MaxModuleAnalyzer.buildModuleIDs(MaxModuleAnalyzer.scala:92)
       local variable: org.scalajs.linker.frontend.modulesplitter.MaxModuleAnalyzer#1
       local variable: scala.collection.immutable.MapLike$ImmutableDefaultKeySet#1
       local variable: scala.collection.mutable.ArrayBuffer#5807
       local variable: scala.collection.immutable.TreeSet#2666232
       local variable: scala.collection.immutable.TreeSet#2666233
       local variable: scala.collection.Iterator$$anon$12#1
       local variable: scala.collection.Iterator$$anon$11#1
    at org.scalajs.linker.frontend.modulesplitter.MaxModuleAnalyzer.analyze(MaxModuleAnalyzer.scala:43)
       local variable: org.scalajs.linker.frontend.modulesplitter.MaxModuleAnalyzer#1
       local variable: org.scalajs.linker.frontend.modulesplitter.ModuleAnalyzer$DependencyInfo#1
       local variable: scala.collection.mutable.HashMap#44519
    at org.scalajs.linker.frontend.modulesplitter.ModuleSplitter.$anonfun$split$3(ModuleSplitter.scala:51)
       local variable: org.scalajs.linker.frontend.modulesplitter.ModuleSplitter#1
       local variable: org.scalajs.linker.frontend.modulesplitter.ModuleAnalyzer$DependencyInfo#1
    at org.scalajs.linker.frontend.modulesplitter.ModuleSplitter$$Lambda$15780.apply(<unknown string>)
       local variable: org.scalajs.linker.frontend.modulesplitter.ModuleSplitter$$Lambda$15780#1
    at org.scalajs.logging.Logger.time(Logger.scala:42)
       local variable: org.scalajs.sbtplugin.Loggers$SbtLoggerWrapper#1
       local variable: java.lang.String#2700456
       local variable: org.scalajs.linker.frontend.modulesplitter.ModuleSplitter$$Lambda$15780#1
    at org.scalajs.logging.Logger.time$(Logger.scala:40)
       local variable: org.scalajs.sbtplugin.Loggers$SbtLoggerWrapper#1
       local variable: java.lang.String#2700456
       local variable: org.scalajs.linker.frontend.modulesplitter.ModuleSplitter$$Lambda$15780#1
    at org.scalajs.sbtplugin.Loggers$SbtLoggerWrapper.time(Loggers.scala:19)
       local variable: org.scalajs.sbtplugin.Loggers$SbtLoggerWrapper#1
       local variable: java.lang.String#2700456
       local variable: org.scalajs.linker.frontend.modulesplitter.ModuleSplitter$$Lambda$15780#1
    at org.scalajs.linker.frontend.modulesplitter.ModuleSplitter.split(ModuleSplitter.scala:51)
       local variable: org.scalajs.linker.frontend.modulesplitter.ModuleSplitter#1
       local variable: org.scalajs.linker.frontend.LinkingUnit#1
       local variable: org.scalajs.sbtplugin.Loggers$SbtLoggerWrapper#1
       local variable: org.scalajs.linker.frontend.modulesplitter.ModuleAnalyzer$DependencyInfo#1
    at org.scalajs.linker.frontend.LinkerFrontendImpl.$anonfun$link$8(LinkerFrontendImpl.scala:76)
       local variable: org.scalajs.linker.frontend.LinkerFrontendImpl#1
       local variable: org.scalajs.linker.frontend.LinkingUnit#1
       local variable: org.scalajs.sbtplugin.Loggers$SbtLoggerWrapper#1
    at org.scalajs.linker.frontend.LinkerFrontendImpl$$Lambda$15772.apply(<unknown string>)
       local variable: org.scalajs.linker.frontend.LinkerFrontendImpl$$Lambda$15772#1
    at org.scalajs.logging.Logger.time(Logger.scala:42)
       local variable: org.scalajs.sbtplugin.Loggers$SbtLoggerWrapper#1
       local variable: java.lang.String#2700457
       local variable: org.scalajs.linker.frontend.LinkerFrontendImpl$$Lambda$15772#1
    at org.scalajs.logging.Logger.time$(Logger.scala:40)
       local variable: org.scalajs.sbtplugin.Loggers$SbtLoggerWrapper#1
       local variable: java.lang.String#2700457
       local variable: org.scalajs.linker.frontend.LinkerFrontendImpl$$Lambda$15772#1
    at org.scalajs.sbtplugin.Loggers$SbtLoggerWrapper.time(Loggers.scala:19)
       local variable: org.scalajs.sbtplugin.Loggers$SbtLoggerWrapper#1
       local variable: java.lang.String#2700457
       local variable: org.scalajs.linker.frontend.LinkerFrontendImpl$$Lambda$15772#1
    at org.scalajs.linker.frontend.LinkerFrontendImpl.$anonfun$link$7(LinkerFrontendImpl.scala:76)
       local variable: org.scalajs.linker.frontend.LinkerFrontendImpl#1
       local variable: org.scalajs.sbtplugin.Loggers$SbtLoggerWrapper#1
       local variable: org.scalajs.linker.frontend.LinkingUnit#1
    at org.scalajs.linker.frontend.LinkerFrontendImpl$$Lambda$14058.apply(<unknown string>)
       local variable: org.scalajs.linker.frontend.LinkerFrontendImpl$$Lambda$14058#1
       local variable: org.scalajs.linker.frontend.LinkingUnit#1
    at scala.util.Success.$anonfun$map$1(Try.scala:255)
    at scala.util.Success.map(Try.scala:213)
    at scala.concurrent.Future.$anonfun$map$1(Future.scala:292)
    at scala.concurrent.Future$$Lambda$6546.apply(<unknown string>)
       local variable: scala.concurrent.Future$$Lambda$6546#1
       local variable: scala.util.Success#57865
    at scala.concurrent.impl.Promise.liftedTree1$1(Promise.scala:33)
    at scala.concurrent.impl.Promise.$anonfun$transform$1(Promise.scala:33)
    at scala.concurrent.impl.Promise$$Lambda$6547.apply(<unknown string>)
    at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:64)
       local variable: scala.concurrent.impl.CallbackRunnable#4
    at java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1402)
    at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
       local variable: java.util.concurrent.ForkJoinTask$RunnableExecuteAction#1
    at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
       local variable: java.util.concurrent.ForkJoinPool$WorkQueue#46
    at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
       local variable: java.util.concurrent.ForkJoinPool#1
       local variable: java.util.concurrent.ForkJoinPool$WorkQueue#46
    at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:175)
       local variable: scala.concurrent.impl.ExecutionContextImpl$DefaultThreadFactory$$anon$1#27
```

**Comment by gzm0** [comment]
Just real quick to avoid unnecessary work: I understand what the problem is, no need for the heap dump.

**Comment by gzm0** [comment]
More details: The problem here is that the module ID generation is `O(2^(n +m))` where `n` is the number of public modules and `m` is the number of dynamic modules.

Now for `n` this is OK, because likely:
- The number of public modules is low.
- The connection graph is likely dense, so we'll end up with all the combinations anyways.

However, for dynamic modules, the story is very different: A normal (i.e. reasonable) dynamic loading graph will likely look more like a tree with maybe some additional edges in between. Hence, it is sparse, so the ID generation will totally over-generate.

As a workaround, try to switch to `SmallestModules`; that should not suffer from this problem.

As how to fix it: We'll need to find a way to generate module IDs in a somewhat stable manner. Because they are numbers, we might be able to use the same approach, but without actually calculating them. (i.e. dynamic module number `k` sets bit `k` in the module ID).

**Comment by dispalt** [comment]
Yep smallest fixed the problem, I can't believe I left out that detail.
