### ISSUE TITLE
Error while emitting, head of empty list

### ISSUE THREAD

**Issue by japgolly** [scala-js/scala-js#4583]
This compiles with 1.7.0 but doesn't in 1.7.1.

```scala
object X {
  case class Blah(blah: XY)

  case class XY(x: Int, y: Int)

  case class Dsl(x: Int) extends AnyVal {
    def apply(y: Int = 0) = XY(x, y)
  }

  val dsl = Dsl(1)
  val x = Blah(dsl(1))
  x.blah
}
```

Error:

```
[error] Error while emitting bug.scala
[error] head of empty list
```

**Comment by japgolly** [comment]
It's Scala 2.13.6.

**Comment by gzm0** [comment]
```
	at org.scalajs.nscplugin.GenJSCode$DefaultParamInfo.attachedMethod(GenJSCode.scala:6855)
	at org.scalajs.nscplugin.GenJSCode$JSCodePhase.isJSDefaultParam$1(GenJSCode.scala:3008)
	at org.scalajs.nscplugin.GenJSCode$JSCodePhase.genApply(GenJSCode.scala:3018)
	at org.scalajs.nscplugin.GenJSCode$JSCodePhase.genStatOrExpr(GenJSCode.scala:2456)
	at org.scalajs.nscplugin.GenJSCode$JSCodePhase.genExpr(GenJSCode.scala:2305)
	at org.scalajs.nscplugin.GenJSCode$JSCodePhase.genBodyWithinReturnableScope$1(GenJSCode.scala:2206)
	at org.scalajs.nscplugin.GenJSCode$JSCodePhase.$anonfun$genMethodDef$4(GenJSCode.scala:2211)
	at org.scalajs.nscplugin.JSEncoding.$anonfun$withNewReturnableScope$1(JSEncoding.scala:89)
```

**Comment by gzm0** [comment]
Ah, I think I understand the problem. Default method accessors for value classes are owned by their companion. That's not unreasonable.
