### ISSUE TITLE
Random "Could not create directory <xxx>-fastopt" prevents compilation

### ISSUE THREAD

**Issue by pmeheut** [scala-js/scala-js#4609]
I'm trying to compile this scala3 full stack project: https://github.com/adpi2/scala3-full-stack-example.

SBT 1.5.5
Scala 3.0.2
JDK 11.0.12
Windows Server 2019

After a while, from a few minutes to one hour or so of working, without changing anything into the 'webpage scala.js" subproject as I'm working the backend only, when running `compile` in sbt I get the message:

```
webserver/runMain io.softhedge.webreport.timebase.ReadVwap
[info] Fast optimizing <dir>\webpage\target\scala-3.0.2\webpage-fastopt
[error] stack trace is suppressed; run 'last webpage / Compile / fastLinkJS' for the full output
[error] (webpage / Compile / fastLinkJS) java.io.IOException: Could not create directory <dir>\webpage\target\scala-3.0.2\webpage-fastopt: java.nio.file.AccessDeniedException: <dir>\webpage\target\scala-3.0.2\webpage-fastopt
```
where <dir> is my base directory, irrelevant to the problem.

When this happens, there is nothing I can do: the operating system does not allow me to delete the webpage-fastopt directory and not even to read it whatever I do with administrative rights.
The only solution is to quit sbt and relaunch it.

The full stack is:
```
last webpage / Compile / fastLinkJS
[info] Fast optimizing <dir>\webpage\target\scala-3.0.2\webpage-fastopt
[error] java.io.IOException: Could not create directory <dir>\webpage\target\scala-3.0.2\webpage-fastopt: java.nio.file.AccessDeniedException: <dir>\webpage\target\scala-3.0.2\webpage-fastopt
[error]         at sbt.io.IO$.createDirectory(IO.scala:337)
[error]         at org.scalajs.sbtplugin.ScalaJSPluginInternal$.$anonfun$scalaJSStageSettings$19(ScalaJSPluginInternal.scala:250)
[error]         at sbt.util.FileFunction$.$anonfun$cached$1(FileFunction.scala:80)
[error]         at sbt.util.FileFunction$.$anonfun$cached$4(FileFunction.scala:153)
[error]         at sbt.util.Difference.apply(Tracked.scala:414)
[error]         at sbt.util.Difference.apply(Tracked.scala:394)
[error]         at sbt.util.FileFunction$.$anonfun$cached$3(FileFunction.scala:149)
[error]         at sbt.util.Difference.apply(Tracked.scala:414)
[error]         at sbt.util.Difference.apply(Tracked.scala:389)
[error]         at sbt.util.FileFunction$.$anonfun$cached$2(FileFunction.scala:148)
[error]         at org.scalajs.sbtplugin.ScalaJSPluginInternal$.$anonfun$scalaJSStageSettings$18(ScalaJSPluginInternal.scala:267)
[error]         at sbt.std.Transform$$anon$3.$anonfun$apply$2(Transform.scala:46)
[error]         at sbt.std.Transform$$anon$4.work(Transform.scala:68)
[error]         at sbt.Execute.$anonfun$submit$2(Execute.scala:282)
[error]         at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:23)
[error]         at sbt.Execute.work(Execute.scala:291)
[error]         at sbt.Execute.$anonfun$submit$1(Execute.scala:282)
[error]         at sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:265)
[error]         at sbt.CompletionService$$anon$2.call(CompletionService.scala:64)
[error]         at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[error]         at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
[error]         at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[error]         at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
[error]         at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
[error]         at java.base/java.lang.Thread.run(Thread.java:834)
[error] Caused by: java.nio.file.AccessDeniedException: <dir>\webpage\target\scala-3.0.2\webpage-fastopt
[error]         at java.base/sun.nio.fs.WindowsException.translateToIOException(WindowsException.java:89)
[error]         at java.base/sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:103)
[error]         at java.base/sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:108)
[error]         at java.base/sun.nio.fs.WindowsFileSystemProvider.createDirectory(WindowsFileSystemProvider.java:509)
[error]         at java.base/java.nio.file.Files.createDirectory(Files.java:690)
[error]         at java.base/java.nio.file.Files.createAndCheckIsDirectory(Files.java:797)
[error]         at java.base/java.nio.file.Files.createDirectories(Files.java:783)
[error]         at sbt.io.IO$.$anonfun$createDirectory$1(IO.scala:333)
[error]         at sbt.internal.io.Retry$.apply(Retry.scala:46)
[error]         at sbt.internal.io.Retry$.apply(Retry.scala:28)
[error]         at sbt.internal.io.Retry$.apply(Retry.scala:23)
[error]         at sbt.io.IO$.createDirectory(IO.scala:335)
[error]         at org.scalajs.sbtplugin.ScalaJSPluginInternal$.$anonfun$scalaJSStageSettings$19(ScalaJSPluginInternal.scala:250)
[error]         at sbt.util.FileFunction$.$anonfun$cached$1(FileFunction.scala:80)
[error]         at sbt.util.FileFunction$.$anonfun$cached$4(FileFunction.scala:153)
[error]         at sbt.util.Difference.apply(Tracked.scala:414)
[error]         at sbt.util.Difference.apply(Tracked.scala:394)
[error]         at sbt.util.FileFunction$.$anonfun$cached$3(FileFunction.scala:149)
[error]         at sbt.util.Difference.apply(Tracked.scala:414)
[error]         at sbt.util.Difference.apply(Tracked.scala:389)
[error]         at sbt.util.FileFunction$.$anonfun$cached$2(FileFunction.scala:148)
[error]         at org.scalajs.sbtplugin.ScalaJSPluginInternal$.$anonfun$scalaJSStageSettings$18(ScalaJSPluginInternal.scala:267)
[error]         at sbt.std.Transform$$anon$3.$anonfun$apply$2(Transform.scala:46)
[error]         at sbt.std.Transform$$anon$4.work(Transform.scala:68)
[error]         at sbt.Execute.$anonfun$submit$2(Execute.scala:282)
[error]         at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:23)
[error]         at sbt.Execute.work(Execute.scala:291)
[error]         at sbt.Execute.$anonfun$submit$1(Execute.scala:282)
[error]         at sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:265)
[error]         at sbt.CompletionService$$anon$2.call(CompletionService.scala:64)
[error]         at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[error]         at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
[error]         at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[error]         at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
[error]         at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
[error]         at java.base/java.lang.Thread.run(Thread.java:834)
[error] (webpage / Compile / fastLinkJS) java.io.IOException: Could not create directory <dir>\webpage\target\scala-3.0.2\webpage-fastopt: java.nio.file.AccessDeniedException: <dir>\webpage\target\scala-3.0.2\webpage-fastopt
```

**Comment by sjrd** [comment]
Thanks for the report.

This seems annoying. I regularly work on Windows and have never seen this issue. It is probably going to be a pain de reproduce. :(

**Comment by pmeheut** [comment]
Is there a way I can investigate when it happens?

**Comment by sjrd** [comment]
I don't know. You could try using a custom build of Scala.js with some `println`s in relevant places, but I'm not sure what to diagnose.

To create a custom build, follow https://github.com/scala-js/scala-js/blob/main/DEVELOPING.md#publish-locally

The failing `createDirectory` is at
https://github.com/scala-js/scala-js/blob/81ef662d9d02656fe7c11fa490bf37af2bb1a38c/sbt-plugin/src/main/scala/org/scalajs/sbtplugin/ScalaJSPluginInternal.scala#L251

Perhaps, just testing whether it exists before creating it would help? I don't know.

The implementation of `IO.createDirectory` is in sbt at
https://github.com/sbt/io/blob/162521a265b7e0ee764fb75eb5e552ec4b5f3f6c/io/src/main/scala/sbt/io/IO.scala#L327-L339
in case that helps.

**Comment by pmeheut** [comment]
Thanks. I'll try that as soon as possible because this is still a low priority problem.

**Comment by sjrd** [comment]
Closing for lack of activity and reproduction. Feel free to reopen with a reproduction.
