### ISSUE TITLE
$classData for Throwable is not generated

### ISSUE THREAD

**Issue by keynmol** [scala-js/scala-js#4629]
NB: this problem manifested itself in a scenario with more moving parts involved, and let to a NPE on JavaScript side, trying to call `name` on an Error in failed Future. It is minimised to what should be reproducible on its own.

Assume these contents of an SBT project

```scala
// ./project/build.properties
sbt.version=1.6.1

// ./project/plugins.sbt
addSbtPlugin("org.scala-js" % "sbt-scalajs" % "1.8.0")


// ./repro.scala
package app

import scala.scalajs.js.JSConverters.*
import concurrent.ExecutionContext.Implicits.global
import scala.concurrent.Future
import scala.scalajs.js
import scala.scalajs.js.annotation.JSExportTopLevel

@JSExportTopLevel(name = "onRequest", moduleID = "test_failure")
def testFailure() =
  Future
    .failed(js.JavaScriptException("what"))
    .toJSPromise

// ./build.sbt
enablePlugins(ScalaJSPlugin)

scalaVersion := "3.1.0"

scalaJSLinkerConfig ~= { conf =>
  conf.withModuleKind(ModuleKind.ESModule).withSourceMap(true)
}

```

## steps to reproduce

1. Run `sbt clean fullLinkJS`.
2. Try to find the place in the generated JS file where `$classData` property of `Throwable` is being set:

```js
❯ grep "Throwable.prototype" target/scala-3.1.0/scala-js-bug-opt/*.js
    return $c_jl_Throwable.prototype.fillInStackTrace__jl_Throwable.call($thiz)
```

**It's not there**

As opposed to Exception and its subclasses:

```
❯ grep "Exception.prototype" target/scala-3.1.0/scala-js-bug-opt/*.js
$c_jl_Exception.prototype.$classData = $d_jl_Exception;
$c_jl_RuntimeException.prototype.$classData = $d_jl_RuntimeException;
$c_ju_concurrent_ExecutionException.prototype.$classData = $d_ju_concurrent_ExecutionException;
```

The way this manifested originally is some middleware (cloudflare pages), was trying to render the error from a failed promise, but the class data was null:

```
[pages:err] POST /test_failure: TypeError: Cannot read properties of null (reading 'getName__T')
    at $objectClassName (/var/folders/my/drt5584s2w59ncgxgxpq7v040000gn/T/functionsWorker.js:142:21)
    at Error.$js$exported$prop$name__O (/var/folders/my/drt5584s2w59ncgxgxpq7v040000gn/T/functionsWorker.js:4537:12)
    at Error.get name [as name] (/var/folders/my/drt5584s2w59ncgxgxpq7v040000gn/T/functionsWorker.js:4553:17)
```

As it fell through in the $objectClassName method to this block:

```javascript
    default: {
      if ((arg0 === null)) {
        return arg0.getClass__jl_Class()
      } else if ((arg0 instanceof $c_RTLong)) {
        return "java.lang.Long"
      } else if ((arg0 instanceof $Char)) {
        return "java.lang.Character"
      } else if ((!(!(arg0 && arg0.$classData)))) {
        return arg0.$classData.name
      } else {
        return null.getName__T()
      }
    }
  }

```

**Comment by sjrd** [comment]
Thanks for the report!

**Comment by sjrd** [comment]
Hum, this might have been minimized a bit too much. In this case, it's fine that `Throwable` doesn't have a `$classData` field, because it is never directly instantiated.

Could you expand the reproduction so that it produces an actual failure? One that displays the `TypeError: Cannot read properties of null (reading 'getName__T')` error message?

**Comment by keynmol** [comment]
I was afraid you'd say that :) 

Will try to expand it - direct copy of the code didn't produce the failure in isolation - I will take a look at how the worker API extracts the promise's failure to replicate it.

**Comment by armanbilge** [comment]
I may be experiencing a similar problem to this in https://github.com/gemini-hlsw/lucuma-react/pull/2, after switching a build to Scala 3.

```
==> X react.common.ReactPropsForwardRefWithChildrenSuite.propsWithChildren.withRef 0.02s scala.scalajs.js.JavaScriptException: TypeError: Cannot read properties of null (reading 'ctor__Ljapgolly_scalajs_react_CtorType')

==> X react.common.ReactPropsForwardRefWithChildrenSuite.propsWithChildren.withRef.withKey 0.00s scala.scalajs.js.JavaScriptException: TypeError: Cannot read properties of null (reading 'ctor__Ljapgolly_scalajs_react_CtorType')
```
