### ISSUE TITLE
Optimized (non-compliant) semantics + strict-floats is broken

### ISSUE THREAD

**Issue by sjrd** [scala-js/scala-js#4632]
The following fails:
```
> partestSuite2_12/testOnly -- --fullOpt run/issue192.scala
```
Same with 2.11 and 2.13.

The log contains:
```
JSC_UNDEFINED_VARIABLE. variable $fround is undeclared at javalanglib/src/main/scala/java/lang/FloatingPointBits.scala line 119 : 18
Closure: 1 error(s), 0 warning(s)
Exception in thread "main" org.scalajs.linker.interface.LinkingException: There were errors when applying the Google Closure Compiler
	at org.scalajs.linker.backend.closure.ClosureLinkerBackend.compile(ClosureLinkerBackend.scala:149)
	at org.scalajs.linker.backend.closure.ClosureLinkerBackend.$anonfun$emit$5(ClosureLinkerBackend.scala:120)
	at org.scalajs.logging.Logger.time(Logger.scala:42)
	at org.scalajs.logging.Logger.time$(Logger.scala:40)
	at org.scalajs.logging.ScalaConsoleLogger.time(ScalaConsoleLogger.scala:15)
	at org.scalajs.linker.backend.closure.ClosureLinkerBackend.$anonfun$emit$3(ClosureLinkerBackend.scala:109)
	at scala.Option.map(Option.scala:230)
	at org.scalajs.linker.backend.closure.ClosureLinkerBackend.emit(ClosureLinkerBackend.scala:103)
	at org.scalajs.linker.standard.StandardLinkerImpl.$anonfun$link$2(StandardLinkerImpl.scala:47)
	at scala.concurrent.Future.$anonfun$flatMap$1(Future.scala:307)
	at scala.concurrent.impl.Promise.$anonfun$transformWith$1(Promise.scala:41)
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:64)
	at java.base/java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1426)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)
```
This was caught by the nightly build.

---

It turns out that the same problem exists in the test suite:
```
> set testSuite.v2_12/scalaJSLinkerConfig ~= { _.withSemantics(_.withStrictFloats(true)) }
...
> set Global/scalaJSStage := FullOptStage
...
> testSuite2_12/test
...
[info] Full optimizing test-suite\js\.2.12\target\scala-2.12\scalajs-test-suite-test-opt
[error] JSC_UNDEFINED_VARIABLE. variable $fround is undeclared at javalanglib/src/main/scala/java/lang/FloatingPointBits.scala line 119 : 18
[error] Closure: 1 error(s), 0 warning(s)
[error] There were errors when applying the Google Closure Compiler
[error] (testSuite2_12 / Test / fullLinkJS) There were errors when applying the Google Closure Compiler
```
This was not caught by the regular CI, because it has no entry when we *only* enable strict-floats. Strict floats are always added as part of `makeCompliant`, which enables all compliant semantics. And in that case, the test suite passes, for some reason.

**Comment by sjrd** [comment]
This is also reproducible in fastOpt with optimized semantics:
```
> set testSuite.v2_12/scalaJSLinkerConfig ~= { _.withSemantics(_.withStrictFloats(true).optimized) }
> testSuite2_12/test
```
causes lots of (run-time) errors.

---

The culprit is probably here:
https://github.com/scala-js/scala-js/blob/5e5880af2f61751a3f02584dc42fffd57e521e0e/linker/shared/src/main/scala/org/scalajs/linker/backend/emitter/SJSGen.scala#L287-L289
