### ISSUE TITLE
Linking fails when a `jsDependencies` library references `TextEncoder`

### ISSUE THREAD

**Issue by japgolly** [scala-js/scala-js#4674]
I'm trying to use React 18.0.0 however my tests are failing to link with this error:

```
ReferenceError: TextEncoder is not defined
ReferenceError: TextEncoder is not defined
    at file:///tmp/tmp-316588705405132660react-dom-server.browser.development.js:142:21
    at file:///tmp/tmp-316588705405132660react-dom-server.browser.development.js:13:29
    at file:///tmp/tmp-316588705405132660react-dom-server.browser.development.js:14:2
    at Script.runInContext (node:vm:139:12)
    at Object.runInContext (node:vm:289:6)
    at processJavaScript (/home/golly/.npm/lib/node_modules/jsdom/lib/jsdom/living/nodes/HTMLScriptElement-impl.js:241:10)
    at HTMLScriptElementImpl._innerEval (/home/golly/.npm/lib/node_modules/jsdom/lib/jsdom/living/nodes/HTMLScriptElement-impl.js:176:5)
    at onLoadExternalScript (/home/golly/.npm/lib/node_modules/jsdom/lib/jsdom/living/nodes/HTMLScriptElement-impl.js:98:12)
    at onLoadWrapped (/home/golly/.npm/lib/node_modules/jsdom/lib/jsdom/browser/resources/per-document-resource-loader.js:53:33)
    at Object.check (/home/golly/.npm/lib/node_modules/jsdom/lib/jsdom/browser/resources/resource-queue.js:76:23)
```

The part of `/tmp/tmp-316588705405132660react-dom-server.browser.development.js` that's causing the linking error looks like this:

```js
  var textEncoder = new TextEncoder();
  function stringToChunk(content) {
    return textEncoder.encode(content);
  }
  function stringToPrecomputedChunk(content) {
    return textEncoder.encode(content);
  }
```

which seems to be coming from React ([source](https://github.com/facebook/react/blob/v18.0.0/packages/react-server/src/ReactServerStreamConfigBrowser.js#L107-L115)):

```ts
const textEncoder = new TextEncoder();

export function stringToChunk(content: string): Chunk {
  return textEncoder.encode(content);
}

export function stringToPrecomputedChunk(content: string): PrecomputedChunk {
  return textEncoder.encode(content);
}
```

## Attempted Workaround

I tried adding a facade to the source of the module that's failing to link, but it didn't make a difference:

```scala
import scala.scalajs.js
import scala.scalajs.js.typedarray.Uint8Array
import scala.scalajs.js.annotation.JSGlobal
import scala.annotation.nowarn

@js.native
@JSGlobal
@nowarn("cat=unused")
class TextEncoder() extends js.Object {
  def encode(input: String = js.native): Uint8Array = js.native
  def encodeInto(source: String, destination: Uint8Array): TextEncoderEncodeIntoResult = js.native
}

@js.native
trait TextEncoderEncodeIntoResult extends js.Object {
  var read: Double = js.native
  var written: Double = js.native
}
```

## Config

```scala
addSbtPlugin("org.scala-js"   % "sbt-jsdependencies" % "1.0.2")
addSbtPlugin("org.scala-js"   % "sbt-scalajs"        % "1.10.0")

    jsDependencies ++= Seq(

      "org.webjars.npm" % "react" % "18.0.0"
        /        "umd/react.development.js"
        minified "umd/react.production.min.js"
        commonJSName "React",

      "org.webjars.npm" % "react-dom" % "18.0.0"
        /         "umd/react-dom.development.js"
        minified  "umd/react-dom.production.min.js"
        dependsOn "umd/react.development.js"
        commonJSName "ReactDOM",

      "org.webjars.npm" % "react-dom" % "18.0.0"
        /         "umd/react-dom-server.browser.development.js"
        minified  "umd/react-dom-server.browser.production.min.js"
        dependsOn "umd/react-dom.development.js"
        commonJSName "ReactDOMServer",
    ),

    dependencyOverrides += "org.webjars.npm" % "scheduler" % "0.22.0", // Required for React 18.0.0
```

**Comment by japgolly** [comment]
I forgot to mention: `TextEncoder` is part of global DOM. MDN here: https://developer.mozilla.org/en-US/docs/Web/API/TextEncoder

**Comment by sjrd** [comment]
Are you running into https://github.com/jsdom/jsdom/issues/2524 ?

Anyway, it doesn't seem related to this repo. If it's a DOM thing that cannot be accessed globally although it should, it's probably more related to the JavaScript env being used than to Scala.js core. What JS env are you using?

**Comment by japgolly** [comment]
Oh my bad. I was fighting linking errors just before I got to this and didn't realise it was a runtime error. In that case it seems that jsDependencies are evaluated before user-land which would explain why the ad-hoc facade didn't work. I'll close this now and investigate further. Thanks for new perspective!
