### ISSUE TITLE
`IllegalArgumentException: A constructor or static initializer must have a void result type`

### ISSUE THREAD

**Issue by armanbilge** [scala-js/scala-js#4865]
Sorry, not maximally minimized, but minimizing into a test framework proved challenging 🤔 

```scala
//> using scala "2.13.10"
//> using platform "js"
//> using jsVersion "1.13.1"
//> using dep "org.scalameta::munit::1.0.0-M7"

import scala.collection.concurrent.TrieMap

class Test extends munit.FunSuite {
  TrieMap.mapFactory[String, String]
}
```

```
scala-cli test test.scala
```

```
Exception in thread "main" java.lang.IllegalArgumentException: A constructor or static initializer must have a void result type
        at org.scalajs.ir.Names$MethodName$.apply(Names.scala:405)
        at org.scalajs.ir.Names$MethodName$.reflectiveProxy(Names.scala:436)
        at org.scalajs.linker.analyzer.Analyzer$ClassInfo.proxyCandidates$lzycompute(Analyzer.scala:831)
        at org.scalajs.linker.analyzer.Analyzer$ClassInfo.proxyCandidates(Analyzer.scala:821)
        at org.scalajs.linker.analyzer.Analyzer$ClassInfo.findProxyCandidates(Analyzer.scala:819)
        at org.scalajs.linker.analyzer.Analyzer$ClassInfo.findFirstNonEmptyCandidates$1(Analyzer.scala:772)
        at org.scalajs.linker.analyzer.Analyzer$ClassInfo.findReflectiveTarget(Analyzer.scala:782)
        at org.scalajs.linker.analyzer.Analyzer$ClassInfo.$anonfun$tryLookupReflProxyMethod$1(Analyzer.scala:746)
        at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.scala:18)
        at scala.Option.fold(Option.scala:263)
        at org.scalajs.linker.analyzer.Analyzer$ClassInfo.tryLookupReflProxyMethod(Analyzer.scala:747)
        at org.scalajs.linker.analyzer.Analyzer$ClassInfo.callMethodResolved(Analyzer.scala:1122)
        at org.scalajs.linker.analyzer.Analyzer$ClassInfo.$anonfun$instantiated$4(Analyzer.scala:1020)
        at org.scalajs.linker.analyzer.Analyzer$ClassInfo.$anonfun$instantiated$4$adapted(Analyzer.scala:1017)
        at scala.collection.immutable.List.foreach(List.scala:333)
        at org.scalajs.linker.analyzer.Analyzer$ClassInfo.$anonfun$instantiated$3(Analyzer.scala:1017)
        at org.scalajs.linker.analyzer.Analyzer$ClassInfo.$anonfun$instantiated$3$adapted(Analyzer.scala:1016)
        at scala.collection.IterableOnceOps.foreach(IterableOnce.scala:575)
        at scala.collection.IterableOnceOps.foreach$(IterableOnce.scala:573)
        at scala.collection.AbstractIterable.foreach(Iterable.scala:933)
        at scala.collection.IterableOps$WithFilter.foreach(Iterable.scala:903)
        at org.scalajs.linker.analyzer.Analyzer$ClassInfo.instantiated(Analyzer.scala:1016)
        at org.scalajs.linker.analyzer.Analyzer.$anonfun$followReachabilityInfo$3(Analyzer.scala:1331)
        at org.scalajs.linker.analyzer.Analyzer.$anonfun$followReachabilityInfo$3$adapted(Analyzer.scala:1320)
        at org.scalajs.linker.analyzer.Analyzer.$anonfun$lookupClass$1(Analyzer.scala:311)
        at org.scalajs.linker.analyzer.Analyzer.$anonfun$lookupClass$1$adapted(Analyzer.scala:307)
        at org.scalajs.linker.analyzer.Analyzer$WorkQueue.$anonfun$enqueue$2(Analyzer.scala:1509)
        at org.scalajs.linker.analyzer.Analyzer$WorkQueue.tryDoWork(Analyzer.scala:1528)
        at org.scalajs.linker.analyzer.Analyzer$WorkQueue.$anonfun$enqueue$1(Analyzer.scala:1510)
        at scala.concurrent.impl.Promise$Transformation.run(Promise.scala:484)
        at java.base@17.0.6/java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1395)
        at java.base@17.0.6/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
        at java.base@17.0.6/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
        at java.base@17.0.6/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
        at java.base@17.0.6/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
        at java.base@17.0.6/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)
        at org.graalvm.nativeimage.builder/com.oracle.svm.core.thread.PlatformThreads.threadStartRoutine(PlatformThreads.java:775)
        at org.graalvm.nativeimage.builder/com.oracle.svm.core.posix.thread.PosixPlatformThreads.pthreadStartRoutine(PosixPlatformThreads.java:203)
```

**Comment by sjrd** [comment]
I cannot reproduce. The suggested command yields user-level linking errors, not a crash with the above stack trace:
```
Compiling project (Scala 2.13.10, Scala.js)
Compiled project (Scala 2.13.10, Scala.js)
Referring to non-existent class java.util.concurrent.atomic.AtomicReferenceFieldUpdater
  called from constructor scala.collection.concurrent.TrieMap$.<init>()void
  called from constructor Test.<init>()void
  called from static constructor Test.<stinit>()void
  called from core module analyzer
Referring to non-existent class java.util.concurrent.atomic.AtomicReferenceFieldUpdater
  called from constructor scala.collection.concurrent.TrieMap$.<init>()void
  called from constructor Test.<init>()void
  called from static constructor Test.<stinit>()void
  called from core module analyzer
Referring to non-existent method static java.util.concurrent.atomic.AtomicReferenceFieldUpdater.newUpdater(java.lang.Class,java.lang.Class,java.lang.String)java.util.concurrent.atomic.AtomicReferenceFieldUpdater
...
Not showing 182 more linking errors
Exception in thread "main" org.scalajs.linker.interface.LinkingException: There were linking errors
...
[error]  Error linking Scala.js
```

**Comment by keynmol** [comment]
FWIW I can reproduce it in a clean folder (MacOS, arm64):

```bash
/v/f/r/t/T/tmp.vTokSyFb > tree -a
.
└── testbla.scala

/v/f/r/t/T/tmp.vTokSyFb > cat testbla.scala
//> using scala "2.13.10"
//> using platform "js"
//> using jsVersion "1.13.1"
//> using dep "org.scalameta::munit::1.0.0-M7"

import scala.collection.concurrent.TrieMap

class Test extends munit.FunSuite {
  TrieMap.mapFactory[String, String]
}

# Scala CLI built from 842ea6c368b9b12b1f2cfab407da85d0bffa8e2e
/v/f/r/t/T/tmp.vTokSyFb > scli version
Scala CLI version: 1.0.1-SNAPSHOT
Scala version (default): 3.2.2

/v/f/r/t/T/tmp.vTokSyFb > scli test testbla.scala
Compiling project (Scala 2.13.10, Scala.js)
Compiled project (Scala 2.13.10, Scala.js)
Exception in thread "main" java.lang.IllegalArgumentException: A constructor or static initializer must have a void result type
        at org.scalajs.ir.Names$MethodName$.apply(Names.scala:405)
        at org.scalajs.ir.Names$MethodName$.reflectiveProxy(Names.scala:436)
        at org.scalajs.linker.analyzer.Analyzer$ClassInfo.proxyCandidates$lzycompute(Analyzer.scala:831)
        at org.scalajs.linker.analyzer.Analyzer$ClassInfo.proxyCandidates(Analyzer.scala:821)
```

**Comment by armanbilge** [comment]
I can still reproduce it today, in a clean cloud instance.
```
$ scala-cli version
Scala CLI version: 1.0.0-RC2
Scala version (default): 3.2.2
```

I added `//> using jsCheckIr true` but I get the same error.

**Comment by keynmol** [comment]
And here's a docker repro (run with `docker build -t scala-js-repro .`, can even add `--platform linux/amd64`, same effect):

```dockerfile
FROM eclipse-temurin:17

RUN curl -sSLf https://virtuslab.github.io/scala-cli-packages/scala-setup.sh | sh

RUN echo  "\
//> using scala "2.13.10"\n \
//> using platform "js"\n \
//> using jsVersion "1.13.1"\n \
//> using dep "org.scalameta::munit::1.0.0-M7"\n \
\n\
import scala.collection.concurrent.TrieMap\n \
\n\
class Test extends munit.FunSuite {\n \
  TrieMap.mapFactory[String, String]\n \
\n} \
" > test.scala && cat test.scala

RUN /root/.cache/scalacli/local-repo/bin/scala-cli/scala-cli test test.scala

```

**Comment by sjrd** [comment]
So ... I had scala-cli 1.0.0-RC1. I updated it to 1.0.0-RC2 and now I can reproduce! I don't whose fault it is.
