### ISSUE TITLE
1.16.0 does not work `sbt run` with Scala 2.13.12 or lower versions due to SIP-51 

### ISSUE THREAD

**Issue by xuwei-k** [scala-js/scala-js#4995]
### build.sbt

```scala
scalaVersion := "2.13.12"

enablePlugins(ScalaJSPlugin)

scalaJSUseMainModuleInitializer := true
```

### `project/build.properties`

```properties
sbt.version = 1.10.0
```

### `project/plugins.sbt`

```scala
addSbtPlugin("org.scala-js" % "sbt-scalajs" % "1.16.0")
```

### `src/main/scala/Main.scala`

```scala
object Main {
  def main(args: Array[String]): Unit =
    println("Hello, world!")
}
```

### `sbt run`

```
[error] java.lang.RuntimeException: expected `scala-js-example/scalaVersion` to be "2.13.13" or later,
[error] but found "2.13.12"; upgrade scalaVersion to fix the build.
[error] 
[error] to support backwards-only binary compatibility (SIP-51),
[error] the Scala 2.13 compiler cannot be older than scala-library on the
[error] dependency classpath.
[error] see `scala-js-example/evicted` to know why scala-library 2.13.13 is getting pulled in.
[error] 
[error] 	at scala.sys.package$.error(package.scala:30)
[error] 	at sbt.Defaults$.$anonfun$scalaInstanceFromUpdate$14(Defaults.scala:1195)
[error] 	at sbt.Defaults$.$anonfun$scalaInstanceFromUpdate$14$adapted(Defaults.scala:1184)
[error] 	at scala.Option.foreach(Option.scala:407)
[error] 	at sbt.Defaults$.$anonfun$scalaInstanceFromUpdate$12(Defaults.scala:1184)
[error] 	at sbt.Defaults$.$anonfun$scalaInstanceFromUpdate$12$adapted(Defaults.scala:1182)
[error] 	at scala.collection.Iterator.foreach(Iterator.scala:943)
[error] 	at scala.collection.Iterator.foreach$(Iterator.scala:943)
[error] 	at scala.collection.AbstractIterator.foreach(Iterator.scala:1431)
[error] 	at scala.collection.IterableLike.foreach(IterableLike.scala:74)
[error] 	at scala.collection.IterableLike.foreach$(IterableLike.scala:73)
[error] 	at scala.collection.AbstractIterable.foreach(Iterable.scala:56)
[error] 	at sbt.Defaults$.$anonfun$scalaInstanceFromUpdate$11(Defaults.scala:1182)
[error] 	at sbt.Defaults$.$anonfun$scalaInstanceFromUpdate$11$adapted(Defaults.scala:1181)
[error] 	at scala.Option.foreach(Option.scala:407)
[error] 	at sbt.Defaults$.$anonfun$scalaInstanceFromUpdate$1(Defaults.scala:1181)
[error] 	at scala.Function1.$anonfun$compose$1(Function1.scala:49)
[error] 	at sbt.internal.util.$tilde$greater.$anonfun$$u2219$1(TypeFunctions.scala:63)
[error] 	at sbt.std.Transform$$anon$4.work(Transform.scala:69)
[error] 	at sbt.Execute.$anonfun$submit$2(Execute.scala:283)
[error] 	at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:24)
[error] 	at sbt.Execute.work(Execute.scala:292)
[error] 	at sbt.Execute.$anonfun$submit$1(Execute.scala:283)
[error] 	at sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:265)
[error] 	at sbt.CompletionService$$anon$2.call(CompletionService.scala:65)
[error] 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[error] 	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
[error] 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[error] 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
[error] 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
[error] 	at java.base/java.lang.Thread.run(Thread.java:840)
[error] (scalaInstance) expected `scala-js-example/scalaVersion` to be "2.13.13" or later,
[error] but found "2.13.12"; upgrade scalaVersion to fix the build.
[error] 
[error] to support backwards-only binary compatibility (SIP-51),
[error] the Scala 2.13 compiler cannot be older than scala-library on the
[error] dependency classpath.
[error] see `scala-js-example/evicted` to know why scala-library 2.13.13 is getting pulled in.
[error] Total time: 0 s, completed Jun 4, 2024, 3:46:36 AM
```

### note

- https://github.com/sbt/sbt/pull/7480
- https://github.com/scala-native/scala-native/issues/3943
- https://docs.scala-lang.org/sips/drop-stdlib-forwards-bin-compat.html

`scalajs-library_2.13-1.16.0` depends on scala-library 2.13.13

https://repo1.maven.org/maven2/org/scala-js/scalajs-library_2.13/1.16.0/scalajs-library_2.13-1.16.0.pom

```xml
<dependency>
<groupId>org.scala-lang</groupId>
<artifactId>scala-library</artifactId>
<version>2.13.13</version>
</dependency>
```

**Comment by WojciechMazur** [comment]
We've already dropped support for versions older than 2.13.8 (published ~2 years ago), but we should be able to publish artefacts using the oldest 2.13 versions instead of the latest one. This should allow for big enough variety of Scala versions used by the end users.

**Comment by sjrd** [comment]
I had not anticipated that. In order to address that, it seems we'll need to downgrade our dependency on `scala-library.jar` in the published `scalajs-library` (and our other artifacts). In theory we should downgrade all the way to 2.12.2 and 2.13.0, which are the earliest versions we still support. That's going to complicate our build process, because we want to use the most recent versions of the compiler to build `scalajs-library`, since they produce better code.

Unless we use this opportunity to cut ties with old (> 1 year old) Scala patch versions? I'm not sure what is best here.

@gzm0 Opinions?

**Comment by gzm0** [comment]
> to support backwards-only binary compatibility (SIP-51),
[error] the Scala 2.13 compiler cannot be older than scala-library on the
[error] dependency classpath.

I do not quite understand this part: If the library is backwards compatible, then why do we need a newer compiler? Shouldn't it be the other way around? A newer Scala compiler requires a newer library (I guess because it relies on symbols in it).

At least this is how I understood it initially, am I completely off?

**Comment by sjrd** [comment]
That was the original plan. It was a late change to enforce compiler version = library version. The issue is that the compiler is compiled with full optimizations that allow it to inline from the library. If there is a newer library, the compiler can break. Moreover, the existence of macros and scala-reflect, also compiled with full inlining, means that the classpath of the compiler and of the compiled application must have the same reflect and library versions.

**Comment by gzm0** [comment]
> That was the original plan. It was a late change to enforce compiler version = library version

I see :-/ And I assume impact on the downstream ecosystem wasn't fully re-assesed :(

> The issue is that the compiler is compiled with full optimizations that allow it to inline from the library. If there is a newer library, the compiler can break.

This I do not quite understand: If an older compiler inclined from an older library, how does providing a newer, backwards compatible library break anything?

> Moreover, the existence of macros and scala-reflect, also compiled with full inlining, means that the classpath of the compiler and of the compiled application must have the same reflect and library versions.

Similar thing here: I do not understand how I lining changes the picture :-/

Also: What in these constraints makes it that they do not apply to Scala.js compilation? Because otherwise we'd have to ship all Scala library version for all SJS versions which we deemed unacceptable IIRC.

**Comment by gzm0** [comment]
I'm doing some digging on 
- https://github.com/sbt/sbt/pull/7480
And found this (partial) on the commit that introduced this check

> When expanding a macro compiled against a new Scala library, the
runtime classpath of the compiler should not contain an older library.
Otherwise a NoSuchMethodException can occur

https://github.com/sbt/sbt/pull/7480/commits/4c74358707477d105bf8d4d4452e2b7971b73ba7

It feels like the comment / commit message is arguing for the other direction of the inequality sign: the scalalib must not be older 🤔

**Comment by sjrd** [comment]
> This I do not quite understand: If an older compiler inclined from an older library, how does providing a newer, backwards compatible library break anything?

Because the *public* ABI is backward compatible, but inlining across the artifact boundary means that we also rely on the *private* ABI. The latter is not checked for backward compatibility.

**Comment by lrytz** [comment]
The same issue affects authors of compiler plugins. A compiler plugin for 2.13.N needs to be built with 2.13.N, as it was always the case. But if the plugin has a dependency on some library that depends on a newer 2.13.(N+M) scala-library, dependency resolution will pull in that newer scala-library jar and sbt will fail the build.

So compiler plugin authors cannot just upgrade their dependencies, if they want to release a new version of a plugin for an older Scala version. They need to make sure none of their dependencies pulls in a newer scala-library. https://github.com/sbt/sbt/pull/7480#issuecomment-2162448612

> It feels like the comment / commit message is arguing for the other direction of the inequality sign: the scalalib must not be older 🤔

The scala lib of the project cannot be older than what any of the dependencies needs; that's the same as with other libraries. The difference is that we cannot upgrade the scala-library transparently, like the build tool does for other libraries. The reason is inlining: a 2.13.13 scala-compiler requires exactly the 2.13.13 scala-library on the runtime classpath.

We were considering upgrading the scala-library transparently only on the compile time classpath (assume the compiler is running as `java -cp <runtime classpath> scala.tools.nsc.Main -cp <compile time classpath>`), but that doesn't work due to macros.

A macro compiled with 2.13.14 can reference a new method added to scala-library.jar in that release. When using the macro on 2.13.13, it is loaded dynamically into the jvm running the 2.13.13 compiler, with the 2.13.13 standard library on the runtime classpath. So the method is not there when the macro is invoked.

-----

We considered transparently upgrading the `scalaVersion` altogehter, but then decided that it's better if the user does so manually. It's not ideal if the user writes `scalaVersion = 2.13.13` but then the project actually uses a newer compiler.

So I guess the question is this: how important is it for new library / compiler plugin / Scala.js releases to support older 2.13 versions? Can all the library / plugin authors assume that forcing users to the latest 2.13 is OK?

On Discord it was also suggested that `scalaVersion := 2.13` or something like that should be allowed so that the build tool can automatically pick the latest compiler according to the dependency graph. https://discord.com/channels/632150470000902164/632628489719382036/1246367750054740029

**Comment by gzm0** [comment]
TY for the explanation @lrytz. This is very helpful.

> A macro compiled with 2.13.14 can reference a new method added to scala-library.jar in that release. When using the macro on 2.13.13, it is loaded dynamically into the jvm running the 2.13.13 compiler, with the 2.13.13 standard library on the runtime classpath. So the method is not there when the macro is invoked.

It feels to me that this is the core of the issue: Macro libraries should be on the runtime classpath, not the compile time classpath. Have you considered resolving them differently?

After all, macros are really just a form of compiler plugins :ducks:

>So I guess the question is this: how important is it for new library / compiler plugin / Scala.js releases to support older 2.13 versions? Can all the library / plugin authors assume that forcing users to the latest 2.13 is OK?

@sjrd can answer this question better than me. But so far we have even back published newer Scala versions for older Scala.js versions (to some extent). Tying the Scala version to the Scala.js version would be a significant departure from our current versioning scheme.

My understanding of the discussion on SIP-51 was that it is not a change the Scala community is willing to do.

**Comment by sjrd** [comment]
Indeed, we do backpublish newer Scala versions for older Scala.js versions. Usually several versions back. For the latest 2.13.14, I had only proactively backpublished the latest Scala.js version, and there was an explicit request to publish older ones.

The demand definitely exists. Now is it a demand that belongs to the "old system", and that we should nudge people away from? I don't know.

**Comment by lrytz** [comment]
> > A macro compiled with 2.13.14 can reference a new method added to scala-library.jar in that release. When using the macro on 2.13.13, it is loaded dynamically into the jvm running the 2.13.13 compiler, with the 2.13.13 standard library on the runtime classpath. So the method is not there when the macro is invoked.
> 
> It feels to me that this is the core of the issue: Macro libraries should be on the runtime classpath, not the compile time classpath. Have you considered resolving them differently?

I don't really follow... A difference between macros and compiler plugins is that macros are binary compatible (unless they do funky stuff like casting to `nsc.Global` to access internal API). So a library with macros built on 2.13.10 can be used on a 2.13.13 compiler.

The compiled macro is bytecode executed at compile time, the macro code is loaded and executed within the compiler. It runs with the scala-library that the compiler has on its runtime classpath.

So a macro compiled against 2.13.14 referencing some new API will fail to expand in a 2.13.13 compiler.



> The demand definitely exists. Now is it a demand that belongs to the "old system", and that we should nudge people away from?

At the end, Scala.js is not different from a library. After SIP-51, updating a dependency to new version built with 2.13.14 requires the project's `scalaVersion` to be updated to at least 2.13.14. While working on SIP-51 we realized that upgrading only scala-library but keeping the compiler doesn't work, and the we (the SIP commitee) agreed that it's fine requiring the Scala version upgrade.

The question is, what's the use case for people to update a dependency but remain on an older Scala compiler?

Maybe there's a stronger use case for Scala.js (or compiler plugins in general) than any other library, to be able to push a new plugin version for older compilers? For example, for Metals, it seems supporting older Scala versions in new releases is important. After all, the plugin is injected into the build when a user loads the project in the IDE, so the user doesn't make a choice to update some dependency.

**Comment by lefou** [comment]
> The question is, what's the use case for people to update a dependency but remain on an older Scala compiler?

The main use case is to use a compiler plugin, which isn't released for a newer Scala version. Since most projects prefer to support newer Scala versions only by version bumps instead of re-publishing old tags/releases for newer Scala versions. Most tool chains aren't ready for selective republishing.

Combined with the fact, that most libraries frequently update their Scala library version (for no reason other than providing a newer transitive version), you quickly end up with hard challenges to pick the correct version.

As a rule of thumb: Libraries should always depend on the lowest possible version, applications should always pick the newest supported version.

**Comment by gzm0** [comment]
> A macro compiled with 2.13.14 can reference a new method added to scala-library.jar in that release. When using the macro on 2.13.13, it is loaded dynamically into the jvm running the 2.13.13 compiler, with the 2.13.13 standard library on the runtime classpath. So the method is not there when the macro is invoked.
> 
> It feels to me that this is the core of the issue: Macro libraries should be on the runtime classpath, not the compile time classpath. Have you considered resolving them differently?
> 
> I don't really follow... A difference between macros and compiler plugins is that macros are binary compatible (unless they do funky stuff like casting to nsc.Global to access internal API). So a library with macros built on 2.13.10 can be used on a 2.13.13 compiler.
> 
> The compiled macro is bytecode executed at compile time, the macro code is loaded and executed within the compiler. It runs with the scala-library that the compiler has on its runtime classpath.
> 
> So a macro compiled against 2.13.14 referencing some new API will fail to expand in a 2.13.13 compiler.

Coming back to this. I'll try to clarify: IIUC the reason we need strict alignment of the Scala version is for code executed during the compilation phase: Compiler plugins and macros.

For compiler plugins (including the Scala.js plugin), this is nothing new. For macros, the non-forward compatibility & the inlining has implications.

What I was trying to ask is whether we have considered applying the exact version restriction to macro libraries only (this would imply resolving them differently of course).

**Comment by lrytz** [comment]
> What I was trying to ask is whether we have considered applying the exact version restriction to macro libraries only (this would imply resolving them differently of course).

Right, every library with a macro would need to be fully cross-versioned (`_2.13.14` instead of just `_2.13`). This would be a really big ask from the community, I think we should avoid that if possible. It would trickle down to all users of such libraries, they would have to use `cross CrossVersion.full` in their builds.

**Comment by lefou** [comment]
IIUC, one major issue with the new SIP-51 approach is, that you can't profit from a newer compiler if you need to target an older Scala version. As a consequence, no library can use a newer compiler than the targeted library version. This looks like a misconception. The Scala ecosystem is primarily based to released binary artifact. The people and the projects, not necessarily the tools, aren't prepared for this. Especially not, when such a change is rolled out with a new minor version. Until before SIP-51, it was perfectly ok and probably the right thing, to always use the latest Scala library version available.

Since SIP-51 seems to be already in effect, you can come in huge trouble if you use third-party libraries _and_ compiler plugins. The moment one of these dependencies start to bump the Scala version, it _can_ become impossible to find a version matching all requirements of your setup. 

In a source code first world (Linux, BSD, and in general everything which has a binary distributor in between), this isn't a problem, since you can provide newer artifacts from the same sources/versions. In the Scala world, and more generally in the JVM world, where a release is just a binary artifact (and maybe some VCS tag), you don't have that flexibility. You can easily find yourself in a situation in which you are stuck with your libraries, as a single bump forces a version bump which you can't do because of a used compiler plugin. Many projects don't have the discipline regarding dependencies to keep that idea working. Mostly because each little OSS project is doing their binary releases themselves and can't oversee the whole impact of a little bump.

**Comment by gzm0** [comment]
@lrytz , no that's not what I meant. I meant applying the compiler version == scalalib version restriction to macro libraries only. A macro library compiled with an older Scala Version can still be used with a newer Scala version (but a Scala upgrade in the macro library would force the upgrade downstream).

**Comment by lrytz** [comment]
@lefou I understand what you're saying. Should we open a thread on https://contributors.scala-lang.org?

We were aware of the fact that users will sometimes be forced onto newer Scala versions, we thought this is an OK compromise because 2.13 releases are relatively small these days. When upgrading a dependency, it doesn't seem too much of a problem to also update the Scala version at the same time.

Note that Scala 3 shares the same constraint. If a library author moves to Scala 3.5, all of its users have to move to 3.5 as well. That's why Scala 3 introduced LTS.

**Comment by lrytz** [comment]
@gzm0 do you mean allowing a newer std lib on the classpath of an older compiler, unless there are libraries with macros on the classpath? It seems doable, but maybe not worth the effort?

Also, there's the problem of running the repl through the `console` command. There a library mismatch can trigger a NoSuchMethodError (repl line compiled against a new Scala library because that's on the compilation classpath, but then run against an old library because that's on the REPL's runtime classpath).

**Comment by gzm0** [comment]
> do you mean allowing a newer std lib on the classpath of an older compiler, unless there are libraries with macros on the classpath?

No. I mean to perform dependency resolution separately for the compiler runtime classpath (including macro libraries) and the compiler compilation classpath.

@sjrd to answer your question:

Making the Scala.js library depend on the oldest Scala library would fix the issue, yes. But it would make us unable to add support/integration for newer Scala library features (or use them).

**Comment by gzm0** [comment]
**Definitions**

`c`: Scala compiler version.
`sl_cr`: Scalalib version on the compiler runtime classpath: the version the Scala compiler is executed with
`sl_cc`: Scalalib version on the compilation classpath: the version the Scala compiler "looks at" to compile code
`sl_r`: Scalalib version on the runtime / link time classpath: the version the compiled code is executed (JVM) / linked (Scala.js / Scala-native) with.
`sjs_c`: Scala.js (compiler) verison
`sjsl_cc`: Scala.js library version on the compilation classpath.
`sjsl_r`:  Scala.js library version on the linking classpath.
`sjsl_sl_supp`: Function from Scala.js library version to minimum Scala library version.

**Constraints**

1. `c == sl_cr`: due to inlining in the compiler
2. `c <= sl_cc`: otherwise the compiler cannot rely on the Scalalib for runtime support (this is what @lefou is challenging).
3. `sl_cc <= sl_r`: otherwise symbols during compilation might not be available at runtime.
4. `sjsl_cc <= sjsl_r`: otherwise symbols during compilation might not be available at runtime.
5. `sl_cc == sl_cr`: currently enforced by build tools (this is what @gzm0 is challenging).
6. `sjs_c <= sjsl_cc`: otherwise the compiler cannot rely on the lib for runtime support (@lefou might also challenge this one?)
7. `sjsl_cc <= sjsl_r`: otherwise symbols during compilation might not be available at runtime.
8. `sjsl_sl_supp(sjsl_cc) <= sl_cc`: otherwise compiling a Scala.js library feature that uses a newer Scala library type might not work.
9. `sjsl_sl_supp(sjsl_r) <= sl_r`: otherwise the Scala.js library might not work.

**Implications**

With all these constraints, we have

```
sjsl_sl_supp(sjsl_cc) <= sl_cc == sl_cr == c
==>
sjsl_sl_supp(sjsl_cc) <= c
```

this is the symptom in this issue: upgrading Scala.js forces an upgrade of the Scala compiler version
if that Scala.js version has been compiled with a newer Scala version.

**Options**

- adjust `sjsl_sl_supp` (@sjrd's proposal)
- remove `sl_cc == sl_cr` (@gzm0's proposal, `c <= sl_cc` remains)
- split the Scala.js library (unclear if feasible)
  - core that doesn't depend on Scalalib
  - "porcelain" that depends on Scalalib, potentially versioned separately

**Notes**
- `c <= sl_cc` seems to not contribute to the issue.

**Comment by lrytz** [comment]
> No. I mean to perform dependency resolution separately for the compiler runtime classpath (including macro libraries) and the compiler compilation classpath.

Macros are loaded dynamically from the compilation classpath, so I don't see how that could work. We'd have to somehow find an older version of the macro library that was built with the current compiler version?

**Comment by gzm0** [comment]
> Macros are loaded dynamically from the compilation classpath, so I don't see how that could work. We'd have to somehow find an older version of the macro library that was built with the current compiler version?

No, I meant the build tool should do this not the compiler. (just like the build tool is ensuring resolution to the correct scalalib, etc.)

**Comment by lrytz** [comment]
libraries with macros are not (don't need to be) fully cross-versioned. there's no simple way to tell what compiler version a library was built with, no easy way to find a library built with a specific compiler version, and it might not exist at all.
